In [1]:
import pandas as pd
import numpy as np


import datetime

from azure.storage.blob import BlobServiceClient
from azure.storage.blob import BlobClient

import gzip

import io
from io import BytesIO


import tensorflow as tf
import tensorflow_addons as tfa
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l1, l2, l1_l2
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import LearningRateScheduler, ReduceLROnPlateau
from tensorflow.keras.initializers import HeNormal, GlorotUniform

from sklearn.ensemble import IsolationForest
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.utils.class_weight import compute_class_weight


import pickle
import json
from collections import Counter
import itertools
import shap

from azure.storage.blob import ContainerClient
from io import StringIO
import re
import os

import joblib
import sys

C:\Users\Rob\anaconda3\lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject

In [2]:
# Add the folder containing the module to sys.path
# module_path = "E:\\"
module_path = "C:/Users/Rob/Desktop/"

if module_path not in sys.path:
    sys.path.append(module_path)

# Now import the module
import database_functions as dbf

In [3]:
def remove_high_null_features(df, features_to_check, threshold):
    
    for col in features_to_check:
        null_counts = (df[col].isnull().sum() / len(df))
        if null_counts > 0:
            print('Column  %s with nulls %s'%(col, round(null_counts*100,1)))

            if null_counts > threshold:
                print('Dropping column')
                print('')
                df.drop(col, axis = 1, inplace = True)
                features_to_check.remove(col)
            
    return df, features_to_check

In [4]:
def impute_missing_values(df, features_to_impute):
    
    for feature in features_to_impute:
        
        if feature in df.columns:

            if df[feature].isnull().sum() > 0:

                feature_type = df[feature].dtype

                if feature_type == 'object':
                    print('Replacing %s with mode: %s'%(feature, df[feature].mode()[0]))
                    df[feature] = df[feature].fillna(df[feature].mode()[0])
                else:
                    print('Replacing %s with median: %s'%(feature, df[feature].median()))
                    df[feature] = df[feature].fillna(df[feature].median())
        else:
            print('Cant impute as this feature has already been removed: %s'%(feature))
            
    return df

In [5]:
def remove_low_varAndcorr_features(df, var_thresh, corr_thresh):

    variances = df.var()
    threshold = 0.01 # adjust as needed
    low_variance_cols = variances[variances < var_thresh].index

    corr_matrix = df.corr()
    corr_with_response = corr_matrix[response_variable_name]

    low_corr_cols = corr_with_response[abs(corr_with_response) < corr_thresh].index

    cols_to_remove = set(low_variance_cols).union(set(low_corr_cols))

    df = df.drop(cols_to_remove, axis=1)
    
    return df

In [6]:
def drop_categorical_vars_with_too_many_categories(df, threshold_perc):

    cat_cols = df.select_dtypes(include=['object']).columns.tolist()
    unique_perc = (df[cat_cols].nunique() / df[cat_cols].count()) * 100

    cols_to_drop = unique_perc[unique_perc > threshold_perc].index.tolist()
    df.drop(cols_to_drop, axis=1, inplace=True)

    cat_cols = df.select_dtypes(include=['object']).columns.tolist()
    unique_perc = (df[cat_cols].nunique() / df[cat_cols].count()) * 100
    cols_to_drop = unique_perc[unique_perc == 100].index.tolist()
    df.drop(cols_to_drop, axis=1, inplace=True)

    return df

In [7]:
def combine_categories(df, col_name1, col_name2, new_column):
    
    df[new_column] = df[col_name1] + ' ' + df[col_name2]
    
    return df

In [8]:
def one_hot_encode_categorical_variables(df):

    # Select columns of data type 'object'
    cat_cols = df.select_dtypes(['object']).columns

    for col in cat_cols:
        
        # perform one-hot encoding using Pandas' get_dummies function
        one_hot_df = pd.get_dummies(df[col])
        
        if (len(one_hot_df.columns) / len(df)) >= 0.05:
            print( str(col) + ' would add an additional ' + str(len(one_hot_df.columns)) + ' columns and therefore has been dropped')

        else:
            # concatenate the one-hot encoded DataFrame with the original DataFrame
            df = pd.concat([df, one_hot_df], axis=1)

        # drop the original categorical variable column
        df.drop(col, axis=1, inplace=True)

    return df

In [9]:
def add_event_deltas(all_features_df):

    # Get event deltas
    url = "https://bbpowerbiblob.blob.core.windows.net/standardfiles/event_deltas.csv?sp=r&st=2023-03-15T10:27:09Z&se=2023-04-01T17:27:09Z&spr=https&sv=2021-12-02&sr=b&sig=A308eSTCniCp2QVLjIYtlL2xe3iyPI6KoQDaxIyC2%2BQ%3D"
    event_deltas = pd.read_csv(url)

    for col in event_deltas:

        if col.find('post') > 0:
            event_deltas.drop(col, axis = 1, inplace = True)

        if (col != 'event_id') & (col in all_features_df.columns):
            event_deltas.drop(col, axis = 1, inplace = True)

    all_features_df = all_features_df.merge(event_deltas, how = 'left', left_on = 'internal_id', right_on = 'event_id')
    
    return all_features_df

In [10]:
def reduce_to_teams_with_10orMore_fixtures(all_features_df, fix_min):

    home_fix = all_features_df[['internal_id', 'home_team_id', 'start_time']].rename(columns = {'home_team_id':'team_id'})
    away_fix = all_features_df[['internal_id', 'away_team_id', 'start_time']].rename(columns = {'away_team_id':'team_id'})
    all_fix = pd.concat([home_fix,away_fix])
    all_fix['fix_num'] = all_fix.groupby('team_id')['start_time'].rank('min')

    all_features_df = all_features_df.merge(all_fix[['internal_id', 'team_id', 'fix_num']].rename(columns = {'team_id':'home_team_id', 'fix_num':'home_team_fix_num'}), how = 'left', left_on = ['internal_id', 'home_team_id'], right_on = ['internal_id', 'home_team_id'])
    all_features_df = all_features_df.merge(all_fix[['internal_id', 'team_id', 'fix_num']].rename(columns = {'team_id':'away_team_id', 'fix_num':'away_team_fix_num'}), how = 'left', left_on = ['internal_id', 'away_team_id'], right_on = ['internal_id', 'away_team_id'])

    all_features_df = all_features_df[ (all_features_df['home_team_fix_num'] >= fix_min) & (all_features_df['away_team_fix_num'] >= fix_min)]
    
    return all_features_df

In [11]:
def connect_to_blob():
    
    blob_account_name = "bbblob" # fill in your blob account name
    blob_account_key = "qKoaGz7crK5QMI5jGh1CbxMM7/LZYpPVyKGrEjeMKeCmtLXKQA8PkRpJbWnPO/ub1fLFNZ5SGZxW0GzhkBpb7g=="  # fill in your blob account key
    account_url = 'https://bbblob.blob.core.windows.net/'

    blob_service_client = BlobServiceClient(account_url=account_url, account_name=blob_account_name, account_key=blob_account_key)
    
#     sas_url = "https://bbpowerbiblob.blob.core.windows.net/standardfiles?sp=racwdli&st=2022-11-08T16:40:40Z&se=2030-11-09T00:40:40Z&spr=https&sv=2021-06-08&sr=c&sig=CSczfckr1VF8sTNM6til3iGNBQRKElInRyZu3fJhppk%3D"
#     container = ContainerClient.from_container_url(sas_url)
    
    return blob_service_client

In [12]:
def retrieve_files_to_dataframe(container_name, prefix, strings_to_filter=[], dtypes = {}):
    
    blob_service_client = connect_to_blob()
    container_client = blob_service_client.get_container_client(container_name)
    blobs = container_client.list_blobs(name_starts_with=prefix)
    
    if len(strings_to_filter) > 0:
        filtered_blobs = []
        for blob in blobs:
            blob_name = blob.name
            if any(string in blob_name for string in strings_to_filter):
                filtered_blobs.append(blob)

        blobs = filtered_blobs
        
    file_data = []
    for blob in blobs:
        blob_client = container_client.get_blob_client(blob)
        blob_data = blob_client.download_blob().readall()
        file_name = blob.name.split('/')[-1]  # Extract filename from blob's name
        file_data.append((file_name, BytesIO(blob_data)))  # Store filename with file data

    # Convert the list of tuples (filename, file data) into a list of DataFrames
    dfs = [pd.read_csv(file[1], dtype=dtypes) for file in file_data]

    # Add filename column to each DataFrame
    for i, df in enumerate(dfs):
        df['filename'] = file_data[i][0]

    # Concatenate all DataFrames into a single DataFrame
    concatenated_df = pd.concat(dfs, ignore_index=True)
    
    return concatenated_df

In [13]:
def connect_to_blob():
    
    sas_url = "https://bbpowerbiblob.blob.core.windows.net/standardfiles?sp=racwdli&st=2022-11-08T16:40:40Z&se=2030-11-09T00:40:40Z&spr=https&sv=2021-06-08&sr=c&sig=CSczfckr1VF8sTNM6til3iGNBQRKElInRyZu3fJhppk%3D"
    container = ContainerClient.from_container_url(sas_url)
    
    return container

In [14]:
def get_blob(blob_name):
    
    local_start_time = datetime.datetime.now()
    print('Getting blob')
    
    downloaded_blob = container.download_blob(blob_name)
    downloaded_file = pd.read_csv(StringIO(downloaded_blob.content_as_text()))
    
    local_end_time = datetime.datetime.now()
    print('Get complete: ' + str(local_end_time - local_start_time))

    return downloaded_file

In [15]:
POSTGRESQL_PARAMS = {
  'username': "HPzg5vzqsmye9PvIygPtXf2SVZrk16oi",
  'pass': "8GCacTSXObYR6nUllbx9SdF1KyT3psJX",
  'host': "bbdb-prod-master.postgres.database.azure.com",
  'DB': "bbc"
}

# Start

In [16]:
# Set the name of this model/data
model_name = 'deltaerror_global_transformed'

# # Set response variable
response_variable_name = 'delta_error'
# response_variable_name = 'home_away_win'


# Set the model type
# model_type = 'binary_classification'
model_type = 'regression'

validation_range_column = 'start_time'
train_start_range = '2010-01-01'
validation_start_range = '2020-01-01'
validation_end_range = '2023-01-01'

validation_dict = dict()
validation_dict['validation_range_column'] = validation_range_column
validation_dict['train_start_range'] = train_start_range
validation_dict['validation_start_range'] = validation_start_range
validation_dict['validation_end_range'] = validation_end_range
validation_dict['validation_comparison_column'] = 'delta_error_abs'
validation_dict['validation_success_column'] = 'prediction_error_abs'
validation_dict['validation_agg_type'] = 'median'
validation_dict['model_success_direction_asc'] = True

In [17]:
# transform_target = None
# transform_target = 'tan'
transform_target = 'sqrt'
# transform_target = 'power_34'

In [18]:
# Use these for regression
# model_ass_val = 'avg_sign_accuracy'
# model_ass_val_direction = False # Set true if we want ascending, false if we want descending
# model_ass_val = 'median_absolute_error_residuals_cv'
# model_ass_val_direction = True # Set true if we want ascending, false if we want descending

# Use these for classification
model_ass_val = ['validation_train_test_geometric_mean', 'validation_avg_train_test_improvement']
model_ass_val_direction = [False, False] # Set true if we want ascending, false if we want descending

In [19]:
sql_statement = 'select * from event_deltas;'
event_deltas = dbf.postgres_Retreive_Insert(sql_statement,POSTGRESQL_PARAMS, True)
event_deltas['pre_delta_diff'] = event_deltas['pre_delta_diff'].astype('float')

In [20]:
# Checking out main feature to see what rows it is missing
event_deltas[ pd.isna(event_deltas['pre_delta_diff'])].sort_values('start_time')

Empty DataFrame
Columns: [event_id, home_team_internal_id, away_team_internal_id, competition_internal_id, start_time, home_score, away_score, updated_at, created_at, home_pre_delta, home_post_delta, away_pre_delta, away_post_delta, home_team_buffer, pre_delta_diff, venue_internal_id, home_delta_change_trend_5, away_delta_change_trend_5, home_error_trend_5, away_error_trend_5, home_delta_change_trend_10, away_delta_change_trend_10, home_error_trend_10, away_error_trend_10, home_delta_change_trend_20, away_delta_change_trend_20, home_error_trend_20, away_error_trend_20, home_pre_delta_halftime, home_post_delta_halftime, away_pre_delta_halftime, away_post_delta_halftime, pre_delta_diff_halftime, home_team_buffer_halftime, home_pre_delta_secondhalf, home_post_delta_secondhalf, away_pre_delta_secondhalf, away_post_delta_secondhalf, pre_delta_diff_secondhalf, home_team_buffer_secondhalf, home_delta_change_halftime_trend_5, home_delta_change_halftime_trend_10, home_delta_change_halftime_trend_20, away_delta_change_halftime_trend_5, away_delta_change_halftime_trend_10, away_delta_change_halftime_trend_20, home_error_halftime_trend_5, home_error_halftime_trend_10, home_error_halftime_trend_20, away_error_halftime_trend_5, away_error_halftime_trend_10, away_error_halftime_trend_20, home_delta_change_secondhalf_trend_5, home_delta_change_secondhalf_trend_10, home_delta_change_secondhalf_trend_20, away_delta_change_secondhalf_trend_5, away_delta_change_secondhalf_trend_10, away_delta_change_secondhalf_trend_20, home_error_secondhalf_trend_5, home_error_secondhalf_trend_10, home_error_secondhalf_trend_20, away_error_secondhalf_trend_5, away_error_secondhalf_trend_10, away_error_secondhalf_trend_20, pre_delta_adjustment, home_attack_pre, home_defence_pre, home_home_attack_pre, home_home_defence_pre, away_attack_pre, away_defence_pre, away_away_attack_pre, away_away_defence_pre, home_attack_post, home_defence_post, home_home_attack_post, home_home_defence_post, away_attack_post, away_defence_post, away_away_attack_post, away_away_defence_post, pre_delta_adjustment_secondhalf, pre_delta_adjustment_halftime, pred_home_score_all, pred_home_score_ha, pred_away_score_all, pred_away_score_ha, pred_total_points_all, pred_total_points_ha, pred_total_points_all_adjusted, pred_total_points_ha_adjusted, pre_delta_diff_halftime_adjusted, pre_delta_diff_secondhalf_adjusted, pre_delta_diff_adjusted, home_team_player_delta, away_team_player_delta, player_delta_diff, home_triesscored_pre, home_triesconceded_pre, home_home_triesscored_pre, ...]
Index: []

[0 rows x 483 columns]

In [21]:
list(event_deltas.columns)

['event_id',
 'home_team_internal_id',
 'away_team_internal_id',
 'competition_internal_id',
 'start_time',
 'home_score',
 'away_score',
 'updated_at',
 'created_at',
 'home_pre_delta',
 'home_post_delta',
 'away_pre_delta',
 'away_post_delta',
 'home_team_buffer',
 'pre_delta_diff',
 'venue_internal_id',
 'home_delta_change_trend_5',
 'away_delta_change_trend_5',
 'home_error_trend_5',
 'away_error_trend_5',
 'home_delta_change_trend_10',
 'away_delta_change_trend_10',
 'home_error_trend_10',
 'away_error_trend_10',
 'home_delta_change_trend_20',
 'away_delta_change_trend_20',
 'home_error_trend_20',
 'away_error_trend_20',
 'home_pre_delta_halftime',
 'home_post_delta_halftime',
 'away_pre_delta_halftime',
 'away_post_delta_halftime',
 'pre_delta_diff_halftime',
 'home_team_buffer_halftime',
 'home_pre_delta_secondhalf',
 'home_post_delta_secondhalf',
 'away_pre_delta_secondhalf',
 'away_post_delta_secondhalf',
 'pre_delta_diff_secondhalf',
 'home_team_buffer_secondhalf',
 'home_delta_change_halftime_trend_5',
 'home_delta_change_halftime_trend_10',
 'home_delta_change_halftime_trend_20',
 'away_delta_change_halftime_trend_5',
 'away_delta_change_halftime_trend_10',
 'away_delta_change_halftime_trend_20',
 'home_error_halftime_trend_5',
 'home_error_halftime_trend_10',
 'home_error_halftime_trend_20',
 'away_error_halftime_trend_5',
 'away_error_halftime_trend_10',
 'away_error_halftime_trend_20',
 'home_delta_change_secondhalf_trend_5',
 'home_delta_change_secondhalf_trend_10',
 'home_delta_change_secondhalf_trend_20',
 'away_delta_change_secondhalf_trend_5',
 'away_delta_change_secondhalf_trend_10',
 'away_delta_change_secondhalf_trend_20',
 'home_error_secondhalf_trend_5',
 'home_error_secondhalf_trend_10',
 'home_error_secondhalf_trend_20',
 'away_error_secondhalf_trend_5',
 'away_error_secondhalf_trend_10',
 'away_error_secondhalf_trend_20',
 'pre_delta_adjustment',
 'home_attack_pre',
 'home_defence_pre',
 'home_home_attack_pre',
 'home_home_defence_pre',
 'away_attack_pre',
 'away_defence_pre',
 'away_away_attack_pre',
 'away_away_defence_pre',
 'home_attack_post',
 'home_defence_post',
 'home_home_attack_post',
 'home_home_defence_post',
 'away_attack_post',
 'away_defence_post',
 'away_away_attack_post',
 'away_away_defence_post',
 'pre_delta_adjustment_secondhalf',
 'pre_delta_adjustment_halftime',
 'pred_home_score_all',
 'pred_home_score_ha',
 'pred_away_score_all',
 'pred_away_score_ha',
 'pred_total_points_all',
 'pred_total_points_ha',
 'pred_total_points_all_adjusted',
 'pred_total_points_ha_adjusted',
 'pre_delta_diff_halftime_adjusted',
 'pre_delta_diff_secondhalf_adjusted',
 'pre_delta_diff_adjusted',
 'home_team_player_delta',
 'away_team_player_delta',
 'player_delta_diff',
 'home_triesscored_pre',
 'home_triesconceded_pre',
 'home_home_triesscored_pre',
 'home_home_triesconceded_pre',
 'away_triesscored_pre',
 'away_triesconceded_pre',
 'away_away_triesscored_pre',
 'away_away_triesconceded_pre',
 'home_triesscored_post',
 'home_triesconceded_post',
 'home_home_triesscored_post',
 'home_home_triesconceded_post',
 'away_triesscored_post',
 'away_triesconceded_post',
 'away_away_triesscored_post',
 'away_away_triesconceded_post',
 'pred_home_tries_all',
 'pred_home_tries_ha',
 'pred_away_tries_all',
 'pred_away_tries_ha',
 'pred_total_tries_all',
 'pred_total_tries_ha',
 'home_venue',
 'home_delta_change',
 'away_delta_change',
 'home_error',
 'away_error',
 'home_delta_change_stdev_5',
 'home_comp_delta_change_trend_5',
 'home_comp_delta_change_stdev_5',
 'away_delta_change_stdev_5',
 'away_comp_delta_change_trend_5',
 'away_comp_delta_change_stdev_5',
 'home_error_stdev_5',
 'home_comp_error_trend_5',
 'home_comp_error_stdev_5',
 'away_error_stdev_5',
 'away_comp_error_trend_5',
 'away_comp_error_stdev_5',
 'home_delta_change_stdev_10',
 'home_comp_delta_change_trend_10',
 'home_comp_delta_change_stdev_10',
 'away_delta_change_stdev_10',
 'away_comp_delta_change_trend_10',
 'away_comp_delta_change_stdev_10',
 'home_error_stdev_10',
 'home_comp_error_trend_10',
 'home_comp_error_stdev_10',
 'away_error_stdev_10',
 'away_comp_error_trend_10',
 'away_comp_error_stdev_10',
 'home_delta_change_stdev_20',
 'home_comp_delta_change_trend_20',
 'home_comp_delta_change_stdev_20',
 'away_delta_change_stdev_20',
 'away_comp_delta_change_trend_20',
 'away_comp_delta_change_stdev_20',
 'home_error_stdev_20',
 'home_comp_error_trend_20',
 'home_comp_error_stdev_20',
 'away_error_stdev_20',
 'away_comp_error_trend_20',
 'away_comp_error_stdev_20',
 'pre_delta_diff_first_plus_second',
 'pre_delta_diff_vs_first_plus_second',
 'home_team_first_vs_second_half_points',
 'away_team_first_vs_second_half_points',
 'team_first_vs_second_half_diff',
 'predicted_change_of_result_at_halftime',
 'pre_delta_diff - error_5 - std_devs_away - home',
 'pre_delta_diff - error_10 - std_devs_away - home',
 'pre_delta_diff - error_20 - std_devs_away - home',
 'pre_delta_diff - error_5 - std_devs_away - away',
 'pre_delta_diff - error_10 - std_devs_away - away',
 'pre_delta_diff - error_20 - std_devs_away - away',
 'pre_delta_diff - deltachange_5 - std_devs_away - away',
 'pre_delta_diff - deltachange_10 - std_devs_away - away',
 'pre_delta_diff - deltachange_20 - std_devs_away - away',
 'pre_delta_diff - deltachange_5 - std_devs_away - home',
 'pre_delta_diff - deltachange_10 - std_devs_away - home',
 'pre_delta_diff - deltachange_20 - std_devs_away - home',
 'home_ha_delta_change_trend_5',
 'home_ha_delta_change_stdev_5',
 'away_ha_delta_change_trend_5',
 'away_ha_delta_change_stdev_5',
 'home_ha_error_trend_5',
 'home_ha_error_stdev_5',
 'away_ha_error_trend_5',
 'away_ha_error_stdev_5',
 'home_ha_delta_change_trend_10',
 'home_ha_delta_change_stdev_10',
 'away_ha_delta_change_trend_10',
 'away_ha_delta_change_stdev_10',
 'home_ha_error_trend_10',
 'home_ha_error_stdev_10',
 'away_ha_error_trend_10',
 'away_ha_error_stdev_10',
 'home_ha_delta_change_trend_20',
 'home_ha_delta_change_stdev_20',
 'away_ha_delta_change_trend_20',
 'away_ha_delta_change_stdev_20',
 'home_ha_error_trend_20',
 'home_ha_error_stdev_20',
 'away_ha_error_trend_20',
 'away_ha_error_stdev_20',
 'pre_delta_diff - comp_error_5 - std_devs_away - home',
 'pre_delta_diff - comp_error_10 - std_devs_away - home',
 'pre_delta_diff - comp_error_20 - std_devs_away - home',
 'pre_delta_diff - comp_error_5 - std_devs_away - away',
 'pre_delta_diff - comp_error_10 - std_devs_away - away',
 'pre_delta_diff - comp_error_20 - std_devs_away - away',
 'pre_delta_diff - ha_error_5 - std_devs_away - home',
 'pre_delta_diff - ha_error_10 - std_devs_away - home',
 'pre_delta_diff - ha_error_20 - std_devs_away - home',
 'pre_delta_diff - ha_error_5 - std_devs_away - away',
 'pre_delta_diff - ha_error_10 - std_devs_away - away',
 'pre_delta_diff - ha_error_20 - std_devs_away - away',
 'pre_delta_diff - error_5 - std_devs_away - diff',
 'pre_delta_diff - error_10 - std_devs_away - diff',
 'pre_delta_diff - error_20 - std_devs_away - diff',
 'pre_delta_diff - comp_error_5 - std_devs_away - diff',
 'pre_delta_diff - comp_error_10 - std_devs_away - diff',
 'pre_delta_diff - comp_error_20 - std_devs_away - diff',
 'pre_delta_diff - ha_error_5 - std_devs_away - diff',
 'pre_delta_diff - ha_error_10 - std_devs_away - diff',
 'pre_delta_diff - ha_error_20 - std_devs_away - diff',
 'home_team_total_fixture_number',
 'away_team_total_fixture_number',
 'home_team_home_fixture_number',
 'away_team_away_fixture_number',
 'home_team_comp_fixture_number',
 'away_team_comp_fixture_number',
 'pre_delta_diff_vs_total_points_ratio',
 'pre_delta_diff_vs_total_points_ratio_abs',
 'key_competition_name',
 'cross_competition_category',
 'weighted_form_diff',
 'home_weighted_form',
 'away_weighted_form',
 'home_weighted_form_ha',
 'home_weighted_form_comp',
 'away_weighted_form_ha',
 'away_weighted_form_comp',
 'weighted_form_ha_diff',
 'weighted_form_comp_diff',
 'pre_delta_diff_vs_total_points_ratio_ha',
 'pre_delta_diff_vs_total_points_ratio_ha_abs',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - away',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - away',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - away',
 'pre_delta_diff - deltachange_5 - std_devs_away - diff',
 'pre_delta_diff - deltachange_10 - std_devs_away - diff',
 'pre_delta_diff - deltachange_20 - std_devs_away - diff',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - diff',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - diff',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - diff',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - diff',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - diff',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - diff',
 'delta_change_diff_5',
 'delta_change_diff_10',
 'delta_change_diff_20',
 'error_trend_diff_5',
 'error_trend_diff_10',
 'error_trend_diff_20',
 'pred_score_all',
 'pred_score_ha',
 'tries_diff_all',
 'tries_diff_ha',
 'triesdiff_vs_total_tries_ratio',
 'triesdiff_vs_total_tries_ratio_abs',
 'triesdiff_vs_total_tries_ha_ratio',
 'triesdiff_vs_total_tries_ha_ratio_abs',
 'home_delta_change_halftime_stdev_5',
 'home_comp_delta_change_halftime_trend_5',
 'home_comp_delta_change_halftime_stdev_5',
 'home_ha_delta_change_halftime_trend_5',
 'home_ha_delta_change_halftime_stdev_5',
 'away_delta_change_halftime_stdev_5',
 'away_comp_delta_change_halftime_trend_5',
 'away_comp_delta_change_halftime_stdev_5',
 'away_ha_delta_change_halftime_trend_5',
 'away_ha_delta_change_halftime_stdev_5',
 'home_error_halftime_stdev_5',
 'home_comp_error_halftime_trend_5',
 'home_comp_error_halftime_stdev_5',
 'home_ha_error_halftime_trend_5',
 'home_ha_error_halftime_stdev_5',
 'away_error_halftime_stdev_5',
 'away_comp_error_halftime_trend_5',
 'away_comp_error_halftime_stdev_5',
 'away_ha_error_halftime_trend_5',
 'away_ha_error_halftime_stdev_5',
 'home_delta_change_halftime_stdev_10',
 'home_comp_delta_change_halftime_trend_10',
 'home_comp_delta_change_halftime_stdev_10',
 'home_ha_delta_change_halftime_trend_10',
 'home_ha_delta_change_halftime_stdev_10',
 'away_delta_change_halftime_stdev_10',
 'away_comp_delta_change_halftime_trend_10',
 'away_comp_delta_change_halftime_stdev_10',
 'away_ha_delta_change_halftime_trend_10',
 'away_ha_delta_change_halftime_stdev_10',
 'home_error_halftime_stdev_10',
 'home_comp_error_halftime_trend_10',
 'home_comp_error_halftime_stdev_10',
 'home_ha_error_halftime_trend_10',
 'home_ha_error_halftime_stdev_10',
 'away_error_halftime_stdev_10',
 'away_comp_error_halftime_trend_10',
 'away_comp_error_halftime_stdev_10',
 'away_ha_error_halftime_trend_10',
 'away_ha_error_halftime_stdev_10',
 'home_delta_change_halftime_stdev_20',
 'home_comp_delta_change_halftime_trend_20',
 'home_comp_delta_change_halftime_stdev_20',
 'home_ha_delta_change_halftime_trend_20',
 'home_ha_delta_change_halftime_stdev_20',
 'away_delta_change_halftime_stdev_20',
 'away_comp_delta_change_halftime_trend_20',
 'away_comp_delta_change_halftime_stdev_20',
 'away_ha_delta_change_halftime_trend_20',
 'away_ha_delta_change_halftime_stdev_20',
 'home_error_halftime_stdev_20',
 'home_comp_error_halftime_trend_20',
 'home_comp_error_halftime_stdev_20',
 'home_ha_error_halftime_trend_20',
 'home_ha_error_halftime_stdev_20',
 'away_error_halftime_stdev_20',
 'away_comp_error_halftime_trend_20',
 'away_comp_error_halftime_stdev_20',
 'away_ha_error_halftime_trend_20',
 'away_ha_error_halftime_stdev_20',
 'second_half_win_margin',
 'home_delta_change_secondhalf_stdev_5',
 'home_comp_delta_change_secondhalf_trend_5',
 'home_comp_delta_change_secondhalf_stdev_5',
 'home_ha_delta_change_secondhalf_trend_5',
 'home_ha_delta_change_secondhalf_stdev_5',
 'away_delta_change_secondhalf_stdev_5',
 'away_comp_delta_change_secondhalf_trend_5',
 'away_comp_delta_change_secondhalf_stdev_5',
 'away_ha_delta_change_secondhalf_trend_5',
 'away_ha_delta_change_secondhalf_stdev_5',
 'home_error_secondhalf_stdev_5',
 'home_comp_error_secondhalf_trend_5',
 'home_comp_error_secondhalf_stdev_5',
 'home_ha_error_secondhalf_trend_5',
 'home_ha_error_secondhalf_stdev_5',
 'away_error_secondhalf_stdev_5',
 'away_comp_error_secondhalf_trend_5',
 'away_comp_error_secondhalf_stdev_5',
 'away_ha_error_secondhalf_trend_5',
 'away_ha_error_secondhalf_stdev_5',
 'home_delta_change_secondhalf_stdev_10',
 'home_comp_delta_change_secondhalf_trend_10',
 'home_comp_delta_change_secondhalf_stdev_10',
 'home_ha_delta_change_secondhalf_trend_10',
 'home_ha_delta_change_secondhalf_stdev_10',
 'away_delta_change_secondhalf_stdev_10',
 'away_comp_delta_change_secondhalf_trend_10',
 'away_comp_delta_change_secondhalf_stdev_10',
 'away_ha_delta_change_secondhalf_trend_10',
 'away_ha_delta_change_secondhalf_stdev_10',
 'home_error_secondhalf_stdev_10',
 'home_comp_error_secondhalf_trend_10',
 'home_comp_error_secondhalf_stdev_10',
 'home_ha_error_secondhalf_trend_10',
 'home_ha_error_secondhalf_stdev_10',
 'away_error_secondhalf_stdev_10',
 'away_comp_error_secondhalf_trend_10',
 'away_comp_error_secondhalf_stdev_10',
 'away_ha_error_secondhalf_trend_10',
 'away_ha_error_secondhalf_stdev_10',
 'home_delta_change_secondhalf_stdev_20',
 'home_comp_delta_change_secondhalf_trend_20',
 'home_comp_delta_change_secondhalf_stdev_20',
 'home_ha_delta_change_secondhalf_trend_20',
 'home_ha_delta_change_secondhalf_stdev_20',
 'away_delta_change_secondhalf_stdev_20',
 'away_comp_delta_change_secondhalf_trend_20',
 'away_comp_delta_change_secondhalf_stdev_20',
 'away_ha_delta_change_secondhalf_trend_20',
 'away_ha_delta_change_secondhalf_stdev_20',
 'home_error_secondhalf_stdev_20',
 'home_comp_error_secondhalf_trend_20',
 'home_comp_error_secondhalf_stdev_20',
 'home_ha_error_secondhalf_trend_20',
 'home_ha_error_secondhalf_stdev_20',
 'away_error_secondhalf_stdev_20',
 'away_comp_error_secondhalf_trend_20',
 'away_comp_error_secondhalf_stdev_20',
 'away_ha_error_secondhalf_trend_20',
 'away_ha_error_secondhalf_stdev_20',
 'p1_model_global_win_margin',
 'p1_model_compspecific_homeawaywin_probability',
 'p1_model_compspecific_winmarginerror',
 'last_game_distance_category',
 'away_last_game_distance_category',
 'home_last_game_distance_category',
 'last_game_distance_value',
 'home_last_game_distance_value',
 'away_last_game_distance_value',
 'p1_model_global_win_margin_outlier_flag',
 'p1_model_compspecific_homeawaywin_probability_outlier_flag',
 'p1_model_compspecific_winmarginerror_outlier_flag',
 'home_weighted_form_vsopp',
 'away_weighted_form_vsopp',
 'weighted_form_vsopp_diff',
 'home_pos_error_streak',
 'home_neg_error_streak',
 'away_pos_error_streak',
 'away_neg_error_streak',
 'home_pos_deltachange_streak',
 'home_neg_deltachange_streak',
 'away_pos_deltachange_streak',
 'away_neg_deltachange_streak',
 'home_team_pre_delta_mean_last_10',
 'home_team_pre_delta_stdev_last_10',
 'home_upper_band_2std_last_10',
 'home_lower_band_2std_last_10',
 'home_upper_band_1_5std_last_10',
 'home_lower_band_1_5std_last_10',
 'home_above_upper_band_2std_last_10',
 'home_below_lower_band_2std_last_10',
 'home_above_upper_band_1_5std_last_10',
 'home_below_lower_band_1_5std_last_10',
 'home_std_deviation_away_last_10',
 'home_team_pre_delta_mean_last_20',
 'home_team_pre_delta_stdev_last_20',
 'home_upper_band_2std_last_20',
 'home_lower_band_2std_last_20',
 'home_upper_band_1_5std_last_20',
 'home_lower_band_1_5std_last_20',
 'home_above_upper_band_2std_last_20',
 'home_below_lower_band_2std_last_20',
 'home_above_upper_band_1_5std_last_20',
 'home_below_lower_band_1_5std_last_20',
 'home_std_deviation_away_last_20',
 'away_team_pre_delta_mean_last_10',
 'away_team_pre_delta_stdev_last_10',
 'away_upper_band_2std_last_10',
 'away_lower_band_2std_last_10',
 'away_upper_band_1_5std_last_10',
 'away_lower_band_1_5std_last_10',
 'away_above_upper_band_2std_last_10',
 'away_below_lower_band_2std_last_10',
 'away_above_upper_band_1_5std_last_10',
 'away_below_lower_band_1_5std_last_10',
 'away_std_deviation_away_last_10',
 'away_team_pre_delta_mean_last_20',
 'away_team_pre_delta_stdev_last_20',
 'away_upper_band_2std_last_20',
 'away_lower_band_2std_last_20',
 'away_upper_band_1_5std_last_20',
 'away_lower_band_1_5std_last_20',
 'away_above_upper_band_2std_last_20',
 'away_below_lower_band_2std_last_20',
 'away_above_upper_band_1_5std_last_20',
 'away_below_lower_band_1_5std_last_20',
 'away_std_deviation_away_last_20',
 'diff_std_deviation_away_last_10',
 'diff_std_deviation_away_last_20',
 'diff_pre_delta_mean_last_10',
 'diff_pre_delta_mean_last_20',
 'bookmakers_handicap_value',
 'bookmakers_totalpoints_value',
 'p1_model_global_delta_error',
 'p1_model_global_delta_error_outlier_flag',
 'p1_model_bookmakers_handicap_error',
 'bookmakers_home_1x2_odds',
 'bookmakers_away_1x2_odds',
 'p1_model_global_predeltadiff_adjusted',
 'features_z_score_cluster',
 'general_features_cluster',
 'p1_model_compspecific_deltaerror',
 'p1_model_compspecific_predeltadiff_adjusted']

In [22]:
all_features_df = event_deltas.copy()

# Add competition and team details

In [23]:
dtypes = {'level':str}
all_competitions = pd.read_csv('all_competitions.csv', dtype = dtypes)
all_competitions = all_competitions[['id', 'level', 'type', 'hemisphere',
       'home_competition_group', 'competition_group', 'cross_border_comp', 'key_competition_name']].rename(columns = {'id':'competition_internal_id'})

for col in ['id', 'level', 'type', 'hemisphere',
       'home_competition_group', 'competition_group', 'cross_border_comp', 'key_competition_name']:
    if col in all_features_df.columns:
        all_features_df.drop(col, axis = 1, inplace = True)
all_features_df = all_features_df.merge(all_competitions, how = 'left', left_on = 'competition_internal_id', right_on = 'competition_internal_id')

all_teams = pd.read_csv('all_teams.csv')
all_teams = all_teams[['id', 'gender', 'type', 'level']].rename(columns = {'id':'internal_id'})
home_teams = all_teams.copy()
away_teams = all_teams.copy()
del all_teams

for col in home_teams:
    home_teams.rename(columns = {col:'home_team_'+col}, inplace = True)
for col in away_teams:
    away_teams.rename(columns = {col:'away_team_'+col}, inplace = True)

all_features_df = all_features_df.merge(home_teams, how = 'left', left_on = 'home_team_internal_id', right_on = 'home_team_internal_id')
all_features_df = all_features_df.merge(away_teams, how = 'left', left_on = 'away_team_internal_id', right_on = 'away_team_internal_id')

del home_teams
del away_teams

# Create metrics and categories

In [24]:
# For this model we only want to predict events where pre_delta_diff is actually there
all_features_df = all_features_df[ pd.notna(all_features_df['pre_delta_diff'])].copy()

In [25]:
all_features_df['win_margin'] = all_features_df[['home_score', 'away_score']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else x[0] - x[1], axis = 1)
all_features_df['win_margin_sign'] = all_features_df['win_margin'].apply(lambda x: -1 if x < 0 else 1)

all_features_df['home_win_not_win'] = all_features_df[['home_score', 'away_score']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else 1 if x[0] > x[1] else 0, axis = 1)
all_features_df['home_away_win'] = all_features_df[['home_score', 'away_score']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else 1 if x[0] > x[1] else 0 if x[0] < x[1] else None, axis = 1)

all_features_df['delta_error'] = all_features_df[['pre_delta_diff', 'win_margin']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else x[0] - x[1], axis = 1)
all_features_df['delta_error_abs'] = abs(all_features_df['delta_error'])

all_features_df['delta_success'] = all_features_df[['pre_delta_diff', 'win_margin']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else 1 if ((x[0] > 0) & (x[1] > 0)) | ((x[0] < 0) & (x[1] < 0)) else 0, axis = 1)

In [26]:
all_features_df['delta_adjusted_error'] = all_features_df[['p1_model_global_predeltadiff_adjusted', 'win_margin']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else x[0] - x[1], axis = 1)
all_features_df['delta_adjusted_error_abs'] = abs(all_features_df['delta_adjusted_error'])

all_features_df['delta_adjusted_success'] = all_features_df[['p1_model_global_predeltadiff_adjusted', 'win_margin']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else 1 if ((x[0] > 0) & (x[1] > 0)) | ((x[0] < 0) & (x[1] < 0)) else 0, axis = 1)

In [27]:
# Filter down to competition if we need to

In [28]:
list(all_features_df['key_competition_name'].drop_duplicates())

['Other Club League Women',
 'Heineken Champions Cup',
 'European Rugby Challenge Cup',
 'Other Club League',
 'Japan Top League',
 'ProD2',
 'Other',
 'International Womens',
 'Gallagher Premiership',
 'United Rugby Championship',
 'TOP 14',
 'Super Rugby',
 'Interational Age Grade',
 'International',
 'Shute Shield',
 'Mitre 10 Cup',
 'Currie Cup',
 'Other Age Grade']

In [29]:
# competitions_to_use = ['Gallagher Premiership']
# all_features_df = all_features_df[ (all_features_df['key_competition_name'].isin(competitions_to_use))].copy()

In [29]:
# If predicting close games, here are some key stats

# Checking out expected delta category
for threshold in range(0,10):
    print(threshold, all_features_df[ (all_features_df['pre_delta_diff'] >= -threshold) & (all_features_df['pre_delta_diff'] <= threshold) ]['delta_success'].count(), all_features_df[ (all_features_df['pre_delta_diff'] >= -threshold) & (all_features_df['pre_delta_diff'] <= threshold) ]['delta_success'].mean(),  all_features_df[ (all_features_df['pre_delta_diff'] <= -threshold) | (all_features_df['pre_delta_diff'] >= threshold) ]['delta_success'].count(), all_features_df[ (all_features_df['pre_delta_diff'] <= -threshold) | (all_features_df['pre_delta_diff'] >= threshold) ]['delta_success'].mean())

0 15 0.0 60944 0.7195950380677343
1 3762 0.48883572567783096 57182 0.7347766779755868
2 7160 0.5032122905027933 53784 0.7484010114532202
3 10695 0.5235156615240767 50249 0.761328583653406
4 14122 0.5384506443846481 46822 0.7742300627909957
5 17528 0.5503194888178914 43416 0.7879353233830846
6 20849 0.562904695668857 40095 0.8010724529243047
7 24045 0.5754210854647536 36899 0.8135450825225616
8 27201 0.5890224624094702 33743 0.824852562012862
9 30070 0.5989690721649484 30878 0.8371008485005506

In [30]:
# Create category for delta
all_features_df['expected_delta_category_1'] = all_features_df['pre_delta_diff'].apply(lambda x: None if pd.isna(x) else 'A' if abs(x) <= 3 else 'B')
all_features_df['expected_delta_category_2'] = all_features_df['pre_delta_diff'].apply(lambda x: None if pd.isna(x) else 'A' if x <= -3 else 'B' if x < -1 else 'C' if x < 1 else 'D' if x < 3 else 'E')
all_features_df['expected_delta_category_3'] = all_features_df['pre_delta_diff'].apply(lambda x: None if pd.isna(x) else 'A' if x < -7 else 'B' if x < -3 else 'C' if x < 0 else 'D' if x <= 3 else 'E' if x <= 7 else 'F')
all_features_df['expected_delta_category_4'] = all_features_df['pre_delta_diff'].apply(lambda x: None if pd.isna(x) else 'A' if x < 0 else 'B')

In [31]:
# Create category for delta adjusted
all_features_df['expected_delta_adjusted_category_1'] = all_features_df['p1_model_global_predeltadiff_adjusted'].apply(lambda x: None if pd.isna(x) else 'A' if abs(x) <= 3 else 'B')
all_features_df['expected_delta_adjusted_category_2'] = all_features_df['p1_model_global_predeltadiff_adjusted'].apply(lambda x: None if pd.isna(x) else 'A' if x <= -3 else 'B' if x < -1 else 'C' if x < 1 else 'D' if x < 3 else 'E')
all_features_df['expected_delta_adjusted_category_3'] = all_features_df['p1_model_global_predeltadiff_adjusted'].apply(lambda x: None if pd.isna(x) else 'A' if x < -7 else 'B' if x < -3 else 'C' if x < 0 else 'D' if x <= 3 else 'E' if x <= 7 else 'F')
all_features_df['expected_delta_adjusted_category_4'] = all_features_df['p1_model_global_predeltadiff_adjusted'].apply(lambda x: None if pd.isna(x) else 'A' if x < 0 else 'B')

In [32]:
# Create category for p1 global win margin
all_features_df['expected_globalwinmargin_category_1'] = all_features_df['p1_model_global_win_margin'].apply(lambda x: None if pd.isna(x) else 'A' if abs(x) <= 3 else 'B')
all_features_df['expected_globalwinmargin_category_2'] = all_features_df['p1_model_global_win_margin'].apply(lambda x: None if pd.isna(x) else 'A' if x <= -3 else 'B' if x < -1 else 'C' if x < 1 else 'D' if x < 3 else 'E')
all_features_df['expected_globalwinmargin_category_3'] = all_features_df['p1_model_global_win_margin'].apply(lambda x: None if pd.isna(x) else 'A' if x < -7 else 'B' if x < -3 else 'C' if x < 0 else 'D' if x <= 3 else 'E' if x <= 7 else 'F')
all_features_df['expected_globalwinmargin_category_4'] = all_features_df['p1_model_global_win_margin'].apply(lambda x: None if pd.isna(x) else 'A' if x < 0 else 'B')

In [33]:
# Limit the streaks to 5
# We could potentially experiment with different values of this
all_features_df['home_pos_error_streak'] = all_features_df['home_pos_error_streak'].apply(lambda x: 5 if x >= 5 else x)
all_features_df['away_pos_error_streak'] = all_features_df['away_pos_error_streak'].apply(lambda x: 5 if x >= 5 else x)
all_features_df['home_neg_error_streak'] = all_features_df['home_neg_error_streak'].apply(lambda x: 5 if x >= 5 else x)
all_features_df['away_neg_error_streak'] = all_features_df['away_neg_error_streak'].apply(lambda x: 5 if x >= 5 else x)

In [34]:
# Convert numerical categorical columns to integer so we don't get the 0.0 at the end
for col in [
'home_pos_error_streak',
'home_neg_error_streak',
'away_pos_error_streak',
'away_neg_error_streak'
]:
    
    # Convert the column to a nullable integer type
    all_features_df[col] = all_features_df[col].astype('Int64')

In [35]:
categorical_features = [
'level', 'type', 'hemisphere',
'home_competition_group', 'competition_group', 'cross_border_comp',
'home_team_gender', 'home_team_type', 'home_team_level',
'away_team_gender', 'away_team_type', 'away_team_level',
'key_competition_name',
'cross_competition_category',
'home_pos_error_streak',
'home_neg_error_streak',
'away_pos_error_streak',
'away_neg_error_streak',
'last_game_distance_category',
'features_z_score_cluster',
'general_features_cluster',
'expected_delta_category_1',
'expected_delta_category_2',
'expected_delta_category_3',
'expected_delta_category_4',
# 'expected_delta_adjusted_category_1',
# 'expected_delta_adjusted_category_2',
# 'expected_delta_adjusted_category_3',
# 'expected_delta_adjusted_category_4',
# 'expected_globalwinmargin_category_1',
# 'expected_globalwinmargin_category_2',
# 'expected_globalwinmargin_category_3',
# 'expected_globalwinmargin_category_4',
]

# Add categorical variables
all_features_df = pd.get_dummies(all_features_df, columns=categorical_features, drop_first=True)  # drop_first avoids multicollinearity

In [36]:
# Need to add these as formulas in the delta calculations
all_features_df['home_team_pre_delta_mean_last_10'] = all_features_df[['home_pre_delta', 'home_team_pre_delta_mean_last_10']].apply(lambda x: x[0] if pd.isna(x[1]) else x[1], axis = 1 )
all_features_df['home_team_pre_delta_mean_last_20'] = all_features_df[['home_pre_delta', 'home_team_pre_delta_mean_last_20']].apply(lambda x: x[0] if pd.isna(x[1]) else x[1], axis = 1 )
all_features_df['away_team_pre_delta_mean_last_10'] = all_features_df[['away_pre_delta', 'away_team_pre_delta_mean_last_10']].apply(lambda x: x[0] if pd.isna(x[1]) else x[1], axis = 1 )
all_features_df['away_team_pre_delta_mean_last_20'] = all_features_df[['away_pre_delta', 'away_team_pre_delta_mean_last_20']].apply(lambda x: x[0] if pd.isna(x[1]) else x[1], axis = 1 )

all_features_df['diff_pre_delta_mean_last_10'] = all_features_df[['diff_pre_delta_mean_last_10', 'home_team_pre_delta_mean_last_10', 'away_team_pre_delta_mean_last_10', 'home_team_buffer']].apply(lambda x: (float(x[0]) + float(x[3])) if pd.notna(float(x[0])) else (float(x[1]) + float(x[3])) - float(x[2]), axis = 1 )
all_features_df['diff_pre_delta_mean_last_20'] = all_features_df[['diff_pre_delta_mean_last_20', 'home_team_pre_delta_mean_last_20', 'away_team_pre_delta_mean_last_20', 'home_team_buffer']].apply(lambda x: (float(x[0]) + float(x[3])) if pd.notna(float(x[0])) else (float(x[1]) + float(x[3])) - float(x[2]), axis = 1 )

#

# Which features are we keeping

In [37]:
# Inspect the features
list(all_features_df.columns)

['event_id',
 'home_team_internal_id',
 'away_team_internal_id',
 'competition_internal_id',
 'start_time',
 'home_score',
 'away_score',
 'updated_at',
 'created_at',
 'home_pre_delta',
 'home_post_delta',
 'away_pre_delta',
 'away_post_delta',
 'home_team_buffer',
 'pre_delta_diff',
 'venue_internal_id',
 'home_delta_change_trend_5',
 'away_delta_change_trend_5',
 'home_error_trend_5',
 'away_error_trend_5',
 'home_delta_change_trend_10',
 'away_delta_change_trend_10',
 'home_error_trend_10',
 'away_error_trend_10',
 'home_delta_change_trend_20',
 'away_delta_change_trend_20',
 'home_error_trend_20',
 'away_error_trend_20',
 'home_pre_delta_halftime',
 'home_post_delta_halftime',
 'away_pre_delta_halftime',
 'away_post_delta_halftime',
 'pre_delta_diff_halftime',
 'home_team_buffer_halftime',
 'home_pre_delta_secondhalf',
 'home_post_delta_secondhalf',
 'away_pre_delta_secondhalf',
 'away_post_delta_secondhalf',
 'pre_delta_diff_secondhalf',
 'home_team_buffer_secondhalf',
 'home_delta_change_halftime_trend_5',
 'home_delta_change_halftime_trend_10',
 'home_delta_change_halftime_trend_20',
 'away_delta_change_halftime_trend_5',
 'away_delta_change_halftime_trend_10',
 'away_delta_change_halftime_trend_20',
 'home_error_halftime_trend_5',
 'home_error_halftime_trend_10',
 'home_error_halftime_trend_20',
 'away_error_halftime_trend_5',
 'away_error_halftime_trend_10',
 'away_error_halftime_trend_20',
 'home_delta_change_secondhalf_trend_5',
 'home_delta_change_secondhalf_trend_10',
 'home_delta_change_secondhalf_trend_20',
 'away_delta_change_secondhalf_trend_5',
 'away_delta_change_secondhalf_trend_10',
 'away_delta_change_secondhalf_trend_20',
 'home_error_secondhalf_trend_5',
 'home_error_secondhalf_trend_10',
 'home_error_secondhalf_trend_20',
 'away_error_secondhalf_trend_5',
 'away_error_secondhalf_trend_10',
 'away_error_secondhalf_trend_20',
 'pre_delta_adjustment',
 'home_attack_pre',
 'home_defence_pre',
 'home_home_attack_pre',
 'home_home_defence_pre',
 'away_attack_pre',
 'away_defence_pre',
 'away_away_attack_pre',
 'away_away_defence_pre',
 'home_attack_post',
 'home_defence_post',
 'home_home_attack_post',
 'home_home_defence_post',
 'away_attack_post',
 'away_defence_post',
 'away_away_attack_post',
 'away_away_defence_post',
 'pre_delta_adjustment_secondhalf',
 'pre_delta_adjustment_halftime',
 'pred_home_score_all',
 'pred_home_score_ha',
 'pred_away_score_all',
 'pred_away_score_ha',
 'pred_total_points_all',
 'pred_total_points_ha',
 'pred_total_points_all_adjusted',
 'pred_total_points_ha_adjusted',
 'pre_delta_diff_halftime_adjusted',
 'pre_delta_diff_secondhalf_adjusted',
 'pre_delta_diff_adjusted',
 'home_team_player_delta',
 'away_team_player_delta',
 'player_delta_diff',
 'home_triesscored_pre',
 'home_triesconceded_pre',
 'home_home_triesscored_pre',
 'home_home_triesconceded_pre',
 'away_triesscored_pre',
 'away_triesconceded_pre',
 'away_away_triesscored_pre',
 'away_away_triesconceded_pre',
 'home_triesscored_post',
 'home_triesconceded_post',
 'home_home_triesscored_post',
 'home_home_triesconceded_post',
 'away_triesscored_post',
 'away_triesconceded_post',
 'away_away_triesscored_post',
 'away_away_triesconceded_post',
 'pred_home_tries_all',
 'pred_home_tries_ha',
 'pred_away_tries_all',
 'pred_away_tries_ha',
 'pred_total_tries_all',
 'pred_total_tries_ha',
 'home_venue',
 'home_delta_change',
 'away_delta_change',
 'home_error',
 'away_error',
 'home_delta_change_stdev_5',
 'home_comp_delta_change_trend_5',
 'home_comp_delta_change_stdev_5',
 'away_delta_change_stdev_5',
 'away_comp_delta_change_trend_5',
 'away_comp_delta_change_stdev_5',
 'home_error_stdev_5',
 'home_comp_error_trend_5',
 'home_comp_error_stdev_5',
 'away_error_stdev_5',
 'away_comp_error_trend_5',
 'away_comp_error_stdev_5',
 'home_delta_change_stdev_10',
 'home_comp_delta_change_trend_10',
 'home_comp_delta_change_stdev_10',
 'away_delta_change_stdev_10',
 'away_comp_delta_change_trend_10',
 'away_comp_delta_change_stdev_10',
 'home_error_stdev_10',
 'home_comp_error_trend_10',
 'home_comp_error_stdev_10',
 'away_error_stdev_10',
 'away_comp_error_trend_10',
 'away_comp_error_stdev_10',
 'home_delta_change_stdev_20',
 'home_comp_delta_change_trend_20',
 'home_comp_delta_change_stdev_20',
 'away_delta_change_stdev_20',
 'away_comp_delta_change_trend_20',
 'away_comp_delta_change_stdev_20',
 'home_error_stdev_20',
 'home_comp_error_trend_20',
 'home_comp_error_stdev_20',
 'away_error_stdev_20',
 'away_comp_error_trend_20',
 'away_comp_error_stdev_20',
 'pre_delta_diff_first_plus_second',
 'pre_delta_diff_vs_first_plus_second',
 'home_team_first_vs_second_half_points',
 'away_team_first_vs_second_half_points',
 'team_first_vs_second_half_diff',
 'predicted_change_of_result_at_halftime',
 'pre_delta_diff - error_5 - std_devs_away - home',
 'pre_delta_diff - error_10 - std_devs_away - home',
 'pre_delta_diff - error_20 - std_devs_away - home',
 'pre_delta_diff - error_5 - std_devs_away - away',
 'pre_delta_diff - error_10 - std_devs_away - away',
 'pre_delta_diff - error_20 - std_devs_away - away',
 'pre_delta_diff - deltachange_5 - std_devs_away - away',
 'pre_delta_diff - deltachange_10 - std_devs_away - away',
 'pre_delta_diff - deltachange_20 - std_devs_away - away',
 'pre_delta_diff - deltachange_5 - std_devs_away - home',
 'pre_delta_diff - deltachange_10 - std_devs_away - home',
 'pre_delta_diff - deltachange_20 - std_devs_away - home',
 'home_ha_delta_change_trend_5',
 'home_ha_delta_change_stdev_5',
 'away_ha_delta_change_trend_5',
 'away_ha_delta_change_stdev_5',
 'home_ha_error_trend_5',
 'home_ha_error_stdev_5',
 'away_ha_error_trend_5',
 'away_ha_error_stdev_5',
 'home_ha_delta_change_trend_10',
 'home_ha_delta_change_stdev_10',
 'away_ha_delta_change_trend_10',
 'away_ha_delta_change_stdev_10',
 'home_ha_error_trend_10',
 'home_ha_error_stdev_10',
 'away_ha_error_trend_10',
 'away_ha_error_stdev_10',
 'home_ha_delta_change_trend_20',
 'home_ha_delta_change_stdev_20',
 'away_ha_delta_change_trend_20',
 'away_ha_delta_change_stdev_20',
 'home_ha_error_trend_20',
 'home_ha_error_stdev_20',
 'away_ha_error_trend_20',
 'away_ha_error_stdev_20',
 'pre_delta_diff - comp_error_5 - std_devs_away - home',
 'pre_delta_diff - comp_error_10 - std_devs_away - home',
 'pre_delta_diff - comp_error_20 - std_devs_away - home',
 'pre_delta_diff - comp_error_5 - std_devs_away - away',
 'pre_delta_diff - comp_error_10 - std_devs_away - away',
 'pre_delta_diff - comp_error_20 - std_devs_away - away',
 'pre_delta_diff - ha_error_5 - std_devs_away - home',
 'pre_delta_diff - ha_error_10 - std_devs_away - home',
 'pre_delta_diff - ha_error_20 - std_devs_away - home',
 'pre_delta_diff - ha_error_5 - std_devs_away - away',
 'pre_delta_diff - ha_error_10 - std_devs_away - away',
 'pre_delta_diff - ha_error_20 - std_devs_away - away',
 'pre_delta_diff - error_5 - std_devs_away - diff',
 'pre_delta_diff - error_10 - std_devs_away - diff',
 'pre_delta_diff - error_20 - std_devs_away - diff',
 'pre_delta_diff - comp_error_5 - std_devs_away - diff',
 'pre_delta_diff - comp_error_10 - std_devs_away - diff',
 'pre_delta_diff - comp_error_20 - std_devs_away - diff',
 'pre_delta_diff - ha_error_5 - std_devs_away - diff',
 'pre_delta_diff - ha_error_10 - std_devs_away - diff',
 'pre_delta_diff - ha_error_20 - std_devs_away - diff',
 'home_team_total_fixture_number',
 'away_team_total_fixture_number',
 'home_team_home_fixture_number',
 'away_team_away_fixture_number',
 'home_team_comp_fixture_number',
 'away_team_comp_fixture_number',
 'pre_delta_diff_vs_total_points_ratio',
 'pre_delta_diff_vs_total_points_ratio_abs',
 'weighted_form_diff',
 'home_weighted_form',
 'away_weighted_form',
 'home_weighted_form_ha',
 'home_weighted_form_comp',
 'away_weighted_form_ha',
 'away_weighted_form_comp',
 'weighted_form_ha_diff',
 'weighted_form_comp_diff',
 'pre_delta_diff_vs_total_points_ratio_ha',
 'pre_delta_diff_vs_total_points_ratio_ha_abs',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - away',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - away',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - away',
 'pre_delta_diff - deltachange_5 - std_devs_away - diff',
 'pre_delta_diff - deltachange_10 - std_devs_away - diff',
 'pre_delta_diff - deltachange_20 - std_devs_away - diff',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - diff',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - diff',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - diff',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - diff',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - diff',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - diff',
 'delta_change_diff_5',
 'delta_change_diff_10',
 'delta_change_diff_20',
 'error_trend_diff_5',
 'error_trend_diff_10',
 'error_trend_diff_20',
 'pred_score_all',
 'pred_score_ha',
 'tries_diff_all',
 'tries_diff_ha',
 'triesdiff_vs_total_tries_ratio',
 'triesdiff_vs_total_tries_ratio_abs',
 'triesdiff_vs_total_tries_ha_ratio',
 'triesdiff_vs_total_tries_ha_ratio_abs',
 'home_delta_change_halftime_stdev_5',
 'home_comp_delta_change_halftime_trend_5',
 'home_comp_delta_change_halftime_stdev_5',
 'home_ha_delta_change_halftime_trend_5',
 'home_ha_delta_change_halftime_stdev_5',
 'away_delta_change_halftime_stdev_5',
 'away_comp_delta_change_halftime_trend_5',
 'away_comp_delta_change_halftime_stdev_5',
 'away_ha_delta_change_halftime_trend_5',
 'away_ha_delta_change_halftime_stdev_5',
 'home_error_halftime_stdev_5',
 'home_comp_error_halftime_trend_5',
 'home_comp_error_halftime_stdev_5',
 'home_ha_error_halftime_trend_5',
 'home_ha_error_halftime_stdev_5',
 'away_error_halftime_stdev_5',
 'away_comp_error_halftime_trend_5',
 'away_comp_error_halftime_stdev_5',
 'away_ha_error_halftime_trend_5',
 'away_ha_error_halftime_stdev_5',
 'home_delta_change_halftime_stdev_10',
 'home_comp_delta_change_halftime_trend_10',
 'home_comp_delta_change_halftime_stdev_10',
 'home_ha_delta_change_halftime_trend_10',
 'home_ha_delta_change_halftime_stdev_10',
 'away_delta_change_halftime_stdev_10',
 'away_comp_delta_change_halftime_trend_10',
 'away_comp_delta_change_halftime_stdev_10',
 'away_ha_delta_change_halftime_trend_10',
 'away_ha_delta_change_halftime_stdev_10',
 'home_error_halftime_stdev_10',
 'home_comp_error_halftime_trend_10',
 'home_comp_error_halftime_stdev_10',
 'home_ha_error_halftime_trend_10',
 'home_ha_error_halftime_stdev_10',
 'away_error_halftime_stdev_10',
 'away_comp_error_halftime_trend_10',
 'away_comp_error_halftime_stdev_10',
 'away_ha_error_halftime_trend_10',
 'away_ha_error_halftime_stdev_10',
 'home_delta_change_halftime_stdev_20',
 'home_comp_delta_change_halftime_trend_20',
 'home_comp_delta_change_halftime_stdev_20',
 'home_ha_delta_change_halftime_trend_20',
 'home_ha_delta_change_halftime_stdev_20',
 'away_delta_change_halftime_stdev_20',
 'away_comp_delta_change_halftime_trend_20',
 'away_comp_delta_change_halftime_stdev_20',
 'away_ha_delta_change_halftime_trend_20',
 'away_ha_delta_change_halftime_stdev_20',
 'home_error_halftime_stdev_20',
 'home_comp_error_halftime_trend_20',
 'home_comp_error_halftime_stdev_20',
 'home_ha_error_halftime_trend_20',
 'home_ha_error_halftime_stdev_20',
 'away_error_halftime_stdev_20',
 'away_comp_error_halftime_trend_20',
 'away_comp_error_halftime_stdev_20',
 'away_ha_error_halftime_trend_20',
 'away_ha_error_halftime_stdev_20',
 'second_half_win_margin',
 'home_delta_change_secondhalf_stdev_5',
 'home_comp_delta_change_secondhalf_trend_5',
 'home_comp_delta_change_secondhalf_stdev_5',
 'home_ha_delta_change_secondhalf_trend_5',
 'home_ha_delta_change_secondhalf_stdev_5',
 'away_delta_change_secondhalf_stdev_5',
 'away_comp_delta_change_secondhalf_trend_5',
 'away_comp_delta_change_secondhalf_stdev_5',
 'away_ha_delta_change_secondhalf_trend_5',
 'away_ha_delta_change_secondhalf_stdev_5',
 'home_error_secondhalf_stdev_5',
 'home_comp_error_secondhalf_trend_5',
 'home_comp_error_secondhalf_stdev_5',
 'home_ha_error_secondhalf_trend_5',
 'home_ha_error_secondhalf_stdev_5',
 'away_error_secondhalf_stdev_5',
 'away_comp_error_secondhalf_trend_5',
 'away_comp_error_secondhalf_stdev_5',
 'away_ha_error_secondhalf_trend_5',
 'away_ha_error_secondhalf_stdev_5',
 'home_delta_change_secondhalf_stdev_10',
 'home_comp_delta_change_secondhalf_trend_10',
 'home_comp_delta_change_secondhalf_stdev_10',
 'home_ha_delta_change_secondhalf_trend_10',
 'home_ha_delta_change_secondhalf_stdev_10',
 'away_delta_change_secondhalf_stdev_10',
 'away_comp_delta_change_secondhalf_trend_10',
 'away_comp_delta_change_secondhalf_stdev_10',
 'away_ha_delta_change_secondhalf_trend_10',
 'away_ha_delta_change_secondhalf_stdev_10',
 'home_error_secondhalf_stdev_10',
 'home_comp_error_secondhalf_trend_10',
 'home_comp_error_secondhalf_stdev_10',
 'home_ha_error_secondhalf_trend_10',
 'home_ha_error_secondhalf_stdev_10',
 'away_error_secondhalf_stdev_10',
 'away_comp_error_secondhalf_trend_10',
 'away_comp_error_secondhalf_stdev_10',
 'away_ha_error_secondhalf_trend_10',
 'away_ha_error_secondhalf_stdev_10',
 'home_delta_change_secondhalf_stdev_20',
 'home_comp_delta_change_secondhalf_trend_20',
 'home_comp_delta_change_secondhalf_stdev_20',
 'home_ha_delta_change_secondhalf_trend_20',
 'home_ha_delta_change_secondhalf_stdev_20',
 'away_delta_change_secondhalf_stdev_20',
 'away_comp_delta_change_secondhalf_trend_20',
 'away_comp_delta_change_secondhalf_stdev_20',
 'away_ha_delta_change_secondhalf_trend_20',
 'away_ha_delta_change_secondhalf_stdev_20',
 'home_error_secondhalf_stdev_20',
 'home_comp_error_secondhalf_trend_20',
 'home_comp_error_secondhalf_stdev_20',
 'home_ha_error_secondhalf_trend_20',
 'home_ha_error_secondhalf_stdev_20',
 'away_error_secondhalf_stdev_20',
 'away_comp_error_secondhalf_trend_20',
 'away_comp_error_secondhalf_stdev_20',
 'away_ha_error_secondhalf_trend_20',
 'away_ha_error_secondhalf_stdev_20',
 'p1_model_global_win_margin',
 'p1_model_compspecific_homeawaywin_probability',
 'p1_model_compspecific_winmarginerror',
 'away_last_game_distance_category',
 'home_last_game_distance_category',
 'last_game_distance_value',
 'home_last_game_distance_value',
 'away_last_game_distance_value',
 'p1_model_global_win_margin_outlier_flag',
 'p1_model_compspecific_homeawaywin_probability_outlier_flag',
 'p1_model_compspecific_winmarginerror_outlier_flag',
 'home_weighted_form_vsopp',
 'away_weighted_form_vsopp',
 'weighted_form_vsopp_diff',
 'home_pos_deltachange_streak',
 'home_neg_deltachange_streak',
 'away_pos_deltachange_streak',
 'away_neg_deltachange_streak',
 'home_team_pre_delta_mean_last_10',
 'home_team_pre_delta_stdev_last_10',
 'home_upper_band_2std_last_10',
 'home_lower_band_2std_last_10',
 'home_upper_band_1_5std_last_10',
 'home_lower_band_1_5std_last_10',
 'home_above_upper_band_2std_last_10',
 'home_below_lower_band_2std_last_10',
 'home_above_upper_band_1_5std_last_10',
 'home_below_lower_band_1_5std_last_10',
 'home_std_deviation_away_last_10',
 'home_team_pre_delta_mean_last_20',
 'home_team_pre_delta_stdev_last_20',
 'home_upper_band_2std_last_20',
 'home_lower_band_2std_last_20',
 'home_upper_band_1_5std_last_20',
 'home_lower_band_1_5std_last_20',
 'home_above_upper_band_2std_last_20',
 'home_below_lower_band_2std_last_20',
 'home_above_upper_band_1_5std_last_20',
 'home_below_lower_band_1_5std_last_20',
 'home_std_deviation_away_last_20',
 'away_team_pre_delta_mean_last_10',
 'away_team_pre_delta_stdev_last_10',
 'away_upper_band_2std_last_10',
 'away_lower_band_2std_last_10',
 'away_upper_band_1_5std_last_10',
 'away_lower_band_1_5std_last_10',
 'away_above_upper_band_2std_last_10',
 'away_below_lower_band_2std_last_10',
 'away_above_upper_band_1_5std_last_10',
 'away_below_lower_band_1_5std_last_10',
 'away_std_deviation_away_last_10',
 'away_team_pre_delta_mean_last_20',
 'away_team_pre_delta_stdev_last_20',
 'away_upper_band_2std_last_20',
 'away_lower_band_2std_last_20',
 'away_upper_band_1_5std_last_20',
 'away_lower_band_1_5std_last_20',
 'away_above_upper_band_2std_last_20',
 'away_below_lower_band_2std_last_20',
 'away_above_upper_band_1_5std_last_20',
 'away_below_lower_band_1_5std_last_20',
 'away_std_deviation_away_last_20',
 'diff_std_deviation_away_last_10',
 'diff_std_deviation_away_last_20',
 'diff_pre_delta_mean_last_10',
 'diff_pre_delta_mean_last_20',
 'bookmakers_handicap_value',
 'bookmakers_totalpoints_value',
 'p1_model_global_delta_error',
 'p1_model_global_delta_error_outlier_flag',
 'p1_model_bookmakers_handicap_error',
 'bookmakers_home_1x2_odds',
 'bookmakers_away_1x2_odds',
 'p1_model_global_predeltadiff_adjusted',
 'p1_model_compspecific_deltaerror',
 'p1_model_compspecific_predeltadiff_adjusted',
 'win_margin',
 'win_margin_sign',
 'home_win_not_win',
 'home_away_win',
 'delta_error',
 'delta_error_abs',
 'delta_success',
 'delta_adjusted_error',
 'delta_adjusted_error_abs',
 'delta_adjusted_success',
 'expected_delta_adjusted_category_1',
 'expected_delta_adjusted_category_2',
 'expected_delta_adjusted_category_3',
 'expected_delta_adjusted_category_4',
 'expected_globalwinmargin_category_1',
 'expected_globalwinmargin_category_2',
 'expected_globalwinmargin_category_3',
 'expected_globalwinmargin_category_4',
 'level_2',
 'level_2.5',
 'level_3',
 'level_4',
 'level_5',
 'level_6',
 'type_U19s',
 'type_U20s',
 'type_U21s',
 'type_Womens',
 'hemisphere_northern',
 'hemisphere_southern',
 'home_competition_group_All Ireland League Div 1B',
 'home_competition_group_Argentinian National de Clubes',
 'home_competition_group_Austria Premiership',
 'home_competition_group_Canada CRC',
 'home_competition_group_Currie Cup',
 'home_competition_group_Currie Cup U21s',
 'home_competition_group_Czech Rep Liga',
 'home_competition_group_England RFU Championship',
 'home_competition_group_Farah Palmer Cup',
 'home_competition_group_Gallagher Premiership',
 'home_competition_group_Georgia Didi 10',
 'home_competition_group_German Bundesliga',
 'home_competition_group_Heartland Championship',
 'home_competition_group_Italian National Championship',
 'home_competition_group_Italy Coppa Italia',
 'home_competition_group_Japan Rugby League One - Division 2',
 'home_competition_group_Japan Rugby League One - Division 3',
 'home_competition_group_Japan Top Challenge League',
 'home_competition_group_Japan Top League',
 'home_competition_group_Major League Rugby',
 'home_competition_group_Mitre 10 Cup',
 'home_competition_group_National League One',
 'home_competition_group_National Rugby Championship',
 'home_competition_group_Netherlands Ereklasse',
 'home_competition_group_Poland Ekstraliga',
 'home_competition_group_Portugal CN Honra',
 'home_competition_group_Premier 15s Women',
 'home_competition_group_Principality Premiership',
 'home_competition_group_ProD2',
 'home_competition_group_Queensland Premier Rugby',
 'home_competition_group_Romania SuperLiga',
 'home_competition_group_Russia Premier League',
 'home_competition_group_Scotland Super6',
 'home_competition_group_Scottish Premiership',
 'home_competition_group_Shute Shield',
 'home_competition_group_Spain Division De Honour',
 'home_competition_group_Super 20s',
 'home_competition_group_Super Liga Americana',
 'home_competition_group_Super Rugby',
 'home_competition_group_Super W Women',
 'home_competition_group_SuperSport',
 'home_competition_group_TOP 14',

In [38]:
# Check for missing features and if we should keep the or not

In [39]:
# all_features_df[ pd.isna(all_features_df['p1_model_global_predeltadiff_adjusted'])].sort_values('start_time')

,event_id,home_team_internal_id,away_team_internal_id,competition_internal_id,start_time,home_score,away_score,updated_at,created_at,home_pre_delta,...,expected_delta_category_2_B,expected_delta_category_2_C,expected_delta_category_2_D,expected_delta_category_2_E,expected_delta_category_3_B,expected_delta_category_3_C,expected_delta_category_3_D,expected_delta_category_3_E,expected_delta_category_3_F,expected_delta_category_4_B
48526,7b1e7448-af1a-11ea-b8bf-4865ee11b869,2455554c-841c-4d22-ad24-6aa8a666a60a,7d6f269f-2b8d-4f2b-98af-800d51ef4132,4f0ae53d-8cd4-4d93-9fbe-0ce2df4bb56b,2003-01-04 00:00:00+00:00,24.0,17.0,2025-01-18 14:36:07.050800+00:00,2024-08-28 12:54:28.196954+00:00,189.3992768853996,...,False,False,False,True,False,False,False,True,False,True
48684,7b16ff52-af1a-11ea-a2eb-4865ee11b869,7bba86d7-8a8b-4cfc-8e8e-93fcd6c8f725,24f6863d-d768-40b8-9c1b-758399e030da,4f0ae53d-8cd4-4d93-9fbe-0ce2df4bb56b,2003-01-04 00:00:00+00:00,20.0,7.0,2025-01-18 14:36:07.050800+00:00,2024-08-28 12:54:28.196954+00:00,176.40319168677465,...,False,False,False,False,True,False,False,False,False,False
48805,9a7bc930-af1d-11ea-a74b-4865ee11b869,2f04ba9b-6d5d-44b1-a5e7-662507589dfd,0eb6b2cd-b7e4-4df8-9e9d-e4d7e10a32a8,d4f47c1f-2257-4dbc-8ff6-68666628f456,2003-01-04 00:00:00+00:00,39.0,5.0,2025-01-18 14:36:07.050800+00:00,2024-08-28 12:54:28.196954+00:00,162.05596653380948,...,False,False,False,True,False,False,False,False,True,True
48468,342e0024-af1b-11ea-9c84-4865ee11b869,e2b3b248-e74a-4660-a882-9cc185a6e849,4ee02e3e-8262-43ea-a594-3319a04b6927,5a15b335-c65a-4878-96b6-41f90e785dad,2003-01-04 00:00:00+00:00,13.0,6.0,2025-01-18 14:36:07.050800+00:00,2024-08-28 12:54:28.196954+00:00,171.90120730849492,...,False,False,False,True,False,False,False,True,False,True
48426,7b35210c-af1a-11ea-b9c1-4865ee11b869,b989dce0-9e78-43f7-8175-909cb6cf7b3d,acd1d4d7-b702-4e6d-bb7d-9015e3ba2927,4f0ae53d-8cd4-4d93-9fbe-0ce2df4bb56b,2003-01-04 00:00:00+00:00,38.0,3.0,2025-01-18 14:36:07.050800+00:00,2024-08-28 12:54:28.196954+00:00,187.9979524394384,...,False,False,False,True,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13802,b8755edc-c7ae-11ef-a4b4-6045bdcfcd7b,d0d85ab0-c123-487a-8f1e-88d7cd8598e2,2455554c-841c-4d22-ad24-6aa8a666a60a,396d8107-2dac-436e-a9f8-5883991655c0,2024-12-14 17:30:00+00:00,43.0,19.0,2025-01-21 23:31:24.559138+00:00,2024-12-31 20:00:06.177701+00:00,175.69968360589704,...,False,False,False,False,False,False,False,False,False,False
13768,0ad80a6d-cd4e-11ef-8be2-6045bdcfcd7b,e72cf7c2-876b-41c4-bdd1-d1e4a0ebbd31,e82cba06-a49b-413d-ad62-8e91a5a4ac0a,46217463-e5dd-4d3b-8b0d-1efe30308267,2025-02-01 12:00:00+00:00,NaN,NaN,2025-01-21 23:31:24.559138+00:00,2025-01-08 01:08:46.982414+00:00,223.53101241662264,...,False,False,False,True,False,False,False,False,True,True
13769,0afe4ce1-cd4e-11ef-a89c-6045bdcfcd7b,e82cba06-a49b-413d-ad62-8e91a5a4ac0a,a3a64375-a2ae-4342-bbd2-35665c2f31aa,46217463-e5dd-4d3b-8b0d-1efe30308267,2025-02-09 13:00:00+00:00,NaN,NaN,2025-01-21 23:31:24.559138+00:00,2025-01-08 01:08:46.982414+00:00,169.72605278336175,...,False,False,False,False,False,False,False,False,False,False
13770,0b19d18b-cd4e-11ef-adc8-6045bdcfcd7b,db719e32-2b29-40d3-8b62-b05da1bdd93b,e82cba06-a49b-413d-ad62-8e91a5a4ac0a,46217463-e5dd-4d3b-8b0d-1efe30308267,2025-02-15 12:00:00+00:00,NaN,NaN,2025-01-21 23:31:24.559138+00:00,2025-01-08 01:08:46.982414+00:00,186.6357866470475,...,False,False,False,True,False,False,False,False,True,True
13746,0b748b9c-cd4e-11ef-84f3-6045bdcfcd7b,8b48650e-c406-48f4-bdfa-ea7fb05b88e0,2de25f00-9bc7-4b60-b0c9-bbfcbdd2a250,64dbec2c-a624-4c9c-93e3-684a5d7bba4b,2025-08-23 16:30:00+00:00,NaN,NaN,2025-01-21 23:21:55.118591+00:00,2025-01-08 01:08:46.982414+00:00,222.89778984057605,...,False,False,False,True,False,False,False,False,True,True

In [41]:
# all_features_df = all_features_df[ pd.notna(all_features_df['p1_model_global_predeltadiff_adjusted'])].sort_values('start_time')

In [41]:
# all_features_df[ pd.isna(all_features_df['p1_model_global_win_margin'])].sort_values('start_time')

In [42]:
features_to_use = [
'pre_delta_diff',
# 'p1_model_global_predeltadiff_adjusted',
# 'p1_model_global_win_margin',
'level_2',
 'level_2.5',
 'level_3',
 'level_4',
 'level_5',
 'level_6',
 'type_U19s',
 'type_U20s',
 'type_U21s',
 'type_Womens',
 'hemisphere_northern',
 'hemisphere_southern',
 'home_competition_group_All Ireland League Div 1B',
 'home_competition_group_Argentinian National de Clubes',
 'home_competition_group_Austria Premiership',
 'home_competition_group_Canada CRC',
 'home_competition_group_Currie Cup',
 'home_competition_group_Currie Cup U21s',
 'home_competition_group_Czech Rep Liga',
 'home_competition_group_England RFU Championship',
 'home_competition_group_Farah Palmer Cup',
 'home_competition_group_Gallagher Premiership',
 'home_competition_group_Georgia Didi 10',
 'home_competition_group_German Bundesliga',
 'home_competition_group_Heartland Championship',
 'home_competition_group_Italian National Championship',
 'home_competition_group_Italy Coppa Italia',
 'home_competition_group_Japan Rugby League One - Division 2',
 'home_competition_group_Japan Rugby League One - Division 3',
 'home_competition_group_Japan Top Challenge League',
 'home_competition_group_Japan Top League',
 'home_competition_group_Major League Rugby',
 'home_competition_group_Mitre 10 Cup',
 'home_competition_group_National League One',
 'home_competition_group_National Rugby Championship',
 'home_competition_group_Netherlands Ereklasse',
 'home_competition_group_Poland Ekstraliga',
 'home_competition_group_Portugal CN Honra',
 'home_competition_group_Premier 15s Women',
 'home_competition_group_Principality Premiership',
 'home_competition_group_ProD2',
 'home_competition_group_Queensland Premier Rugby',
 'home_competition_group_Romania SuperLiga',
 'home_competition_group_Russia Premier League',
 'home_competition_group_Scotland Super6',
 'home_competition_group_Scottish Premiership',
 'home_competition_group_Shute Shield',
 'home_competition_group_Spain Division De Honour',
 'home_competition_group_Super 20s',
 'home_competition_group_Super Liga Americana',
 'home_competition_group_Super Rugby',
 'home_competition_group_Super W Women',
 'home_competition_group_SuperSport',
 'home_competition_group_TOP 14',
 'home_competition_group_URBA Top 12',
 'home_competition_group_USA Pro Rugby',
 'home_competition_group_United Rugby Championship',
 'home_competition_group_Varsity Cup South Africa',
 'home_competition_group_Vodacom Cup',
 'home_competition_group_international_mens',
 'home_competition_group_international_u19s',
 'home_competition_group_international_u20s',
 'home_competition_group_international_u21s',
 'home_competition_group_international_womens',
 'home_competition_group_na',
 'competition_group_Americas',
 'competition_group_Asia',
 'competition_group_Australia',
 'competition_group_Austria',
 'competition_group_Canada',
 'competition_group_Czech Republic',
 'competition_group_England',
 'competition_group_Europe',
 'competition_group_France',
 'competition_group_Georgia',
 'competition_group_Germany',
 'competition_group_Ireland',
 'competition_group_Italy',
 'competition_group_Japan',
 'competition_group_Netherlands',
 'competition_group_New Zealand',
 'competition_group_Oceania',
 'competition_group_Poland',
 'competition_group_Portugal',
 'competition_group_Romania',
 'competition_group_Russia',
 'competition_group_Scotland',
 'competition_group_South Africa',
 'competition_group_South America',
 'competition_group_Spain',
 'competition_group_UK',
 'competition_group_USA',
 'competition_group_Wales',
 'competition_group_World',
 'cross_border_comp_True',
 'home_team_gender_M',
 'home_team_type_club_adev_team',
 'home_team_type_club_u20s',
 'home_team_type_club_u21s',
 'home_team_type_club_women',
 'home_team_type_international',
 'home_team_type_international_a_team',
 'home_team_type_international_age_grade',
 'home_team_type_international_women',
 'home_team_type_international_women_a_team',
 'home_team_type_international_women_development',
 'home_team_type_other',
 'home_team_type_other_women',
 'home_team_type_select',
 'home_team_type_select_women',
 'home_team_level_2.0',
 'home_team_level_3.0',
 'home_team_level_4.0',
 'home_team_level_5.0',
 'home_team_level_11.0',
 'away_team_gender_M',
 'away_team_type_club_adev_team',
 'away_team_type_club_u20s',
 'away_team_type_club_u21s',
 'away_team_type_club_women',
 'away_team_type_international',
 'away_team_type_international_a_team',
 'away_team_type_international_age_grade',
 'away_team_type_international_women',
 'away_team_type_international_women_a_team',
 'away_team_type_international_women_development',
 'away_team_type_other',
 'away_team_type_other_women',
 'away_team_type_select',
 'away_team_type_select_women',
 'away_team_level_2.0',
 'away_team_level_3.0',
 'away_team_level_4.0',
 'away_team_level_5.0',
 'away_team_level_11.0',
'delta_change_diff_5',
'delta_change_diff_10',
'delta_change_diff_20',
'error_trend_diff_5',
'error_trend_diff_10',
'error_trend_diff_20',
'pre_delta_diff_halftime',
'pre_delta_diff_secondhalf',
'pred_score_all',
'pred_score_ha',
'tries_diff_all',
'tries_diff_ha',
'triesdiff_vs_total_tries_ratio',
'triesdiff_vs_total_tries_ratio_abs',
'triesdiff_vs_total_tries_ha_ratio',
'triesdiff_vs_total_tries_ha_ratio_abs',
'pred_total_points_all',
'pred_total_points_ha',
'pred_total_tries_all',
'pred_total_tries_ha',
'pre_delta_diff_vs_first_plus_second',
'team_first_vs_second_half_diff',
'pre_delta_diff - error_5 - std_devs_away - diff',
'pre_delta_diff - error_10 - std_devs_away - diff',
'pre_delta_diff - error_20 - std_devs_away - diff',
'pre_delta_diff - comp_error_5 - std_devs_away - diff',
'pre_delta_diff - comp_error_10 - std_devs_away - diff',
'pre_delta_diff - comp_error_20 - std_devs_away - diff',
'pre_delta_diff - ha_error_5 - std_devs_away - diff',
'pre_delta_diff - ha_error_10 - std_devs_away - diff',
'pre_delta_diff - ha_error_20 - std_devs_away - diff',
'pre_delta_diff - deltachange_5 - std_devs_away - diff',
'pre_delta_diff - deltachange_10 - std_devs_away - diff',
'pre_delta_diff - deltachange_20 - std_devs_away - diff',
'pre_delta_diff - comp_deltachange_5 - std_devs_away - diff',
'pre_delta_diff - comp_deltachange_10 - std_devs_away - diff',
'pre_delta_diff - comp_deltachange_20 - std_devs_away - diff',
'pre_delta_diff - ha_deltachange_5 - std_devs_away - diff',
'pre_delta_diff - ha_deltachange_10 - std_devs_away - diff',
'pre_delta_diff - ha_deltachange_20 - std_devs_away - diff',
'pre_delta_diff_vs_total_points_ratio',
'pre_delta_diff_vs_total_points_ratio_abs',
'weighted_form_diff',
'weighted_form_ha_diff',
'weighted_form_comp_diff',
'weighted_form_vsopp_diff',
'pre_delta_diff_vs_total_points_ratio_ha',
'pre_delta_diff_vs_total_points_ratio_ha_abs',
'predicted_change_of_result_at_halftime',
'expected_delta_category_1_B',
 'expected_delta_category_2_B',
 'expected_delta_category_2_C',
 'expected_delta_category_2_D',
 'expected_delta_category_2_E',
 'expected_delta_category_3_B',
 'expected_delta_category_3_C',
 'expected_delta_category_3_D',
 'expected_delta_category_3_E',
 'expected_delta_category_3_F',
 'expected_delta_category_4_B',
# 'expected_delta_adjusted_category_1_B',
#  'expected_delta_adjusted_category_2_B',
#  'expected_delta_adjusted_category_2_C',
#  'expected_delta_adjusted_category_2_D',
#  'expected_delta_adjusted_category_2_E',
#  'expected_delta_adjusted_category_3_B',
#  'expected_delta_adjusted_category_3_C',
#  'expected_delta_adjusted_category_3_D',
#  'expected_delta_adjusted_category_3_E',
#  'expected_delta_adjusted_category_3_F',
#  'expected_delta_adjusted_category_4_B',
#  'expected_globalwinmargin_category_1_B',
#  'expected_globalwinmargin_category_2_B',
#  'expected_globalwinmargin_category_2_C',
#  'expected_globalwinmargin_category_2_D',
#  'expected_globalwinmargin_category_2_E',
#  'expected_globalwinmargin_category_3_B',
#  'expected_globalwinmargin_category_3_C',
#  'expected_globalwinmargin_category_3_D',
#  'expected_globalwinmargin_category_3_E',
#  'expected_globalwinmargin_category_3_F',
#  'expected_globalwinmargin_category_4_B',
# 'home_team_pre_delta_mean_last_10',
'home_above_upper_band_2std_last_10',
'home_below_lower_band_2std_last_10',
'home_above_upper_band_1_5std_last_10',
'home_below_lower_band_1_5std_last_10',
# 'home_team_pre_delta_mean_last_20',
'home_above_upper_band_2std_last_20',
'home_below_lower_band_2std_last_20',
'home_above_upper_band_1_5std_last_20',
'home_below_lower_band_1_5std_last_20',
# 'away_team_pre_delta_mean_last_10',
'away_above_upper_band_2std_last_10',
'away_below_lower_band_2std_last_10',
'away_above_upper_band_1_5std_last_10',
'away_below_lower_band_1_5std_last_10',
# 'away_team_pre_delta_mean_last_20',
'away_above_upper_band_2std_last_20',
'away_below_lower_band_2std_last_20',
'away_above_upper_band_1_5std_last_20',
'away_below_lower_band_1_5std_last_20',
'diff_std_deviation_away_last_10',
'diff_std_deviation_away_last_20',
'diff_pre_delta_mean_last_10',
'diff_pre_delta_mean_last_20',
'home_venue',
'home_pos_error_streak_1',
'home_pos_error_streak_2',
'home_pos_error_streak_3',
'home_pos_error_streak_4',
'home_pos_error_streak_5',
'home_neg_error_streak_1',
'home_neg_error_streak_2',
'home_neg_error_streak_3',
'home_neg_error_streak_4',
'home_neg_error_streak_5',
'away_pos_error_streak_1',
'away_pos_error_streak_2',
'away_pos_error_streak_3',
'away_pos_error_streak_4',
'away_pos_error_streak_5',
'away_neg_error_streak_1',
'away_neg_error_streak_2',
'away_neg_error_streak_3',
'away_neg_error_streak_4',
'away_neg_error_streak_5',
# 'last_game_distance_category_A_G',
'last_game_distance_category_B_B',
'last_game_distance_category_B_C',
'last_game_distance_category_B_D',
'last_game_distance_category_B_E',
'last_game_distance_category_C_B',
'last_game_distance_category_C_C',
'last_game_distance_category_C_D',
'last_game_distance_category_C_E',
'last_game_distance_category_C_F',
'last_game_distance_category_D_B',
'last_game_distance_category_D_C',
'last_game_distance_category_D_D',
'last_game_distance_category_D_E',
'last_game_distance_category_D_F',
'last_game_distance_category_E_C',
'last_game_distance_category_E_D',
'last_game_distance_category_E_E',
'last_game_distance_category_E_F',
'last_game_distance_category_F_A',
'last_game_distance_category_F_C',
'last_game_distance_category_F_D',
'last_game_distance_category_F_E',
'last_game_distance_category_F_F',
'last_game_distance_category_F_G',
'last_game_distance_category_G_F',
'last_game_distance_category_G_G',
 'cross_competition_category_Gallagher Premiership_TOP 14',
 'cross_competition_category_Gallagher Premiership_United Rugby Championship',
 'cross_competition_category_Italian National Championship_Gallagher Premiership',
 'cross_competition_category_Italian National Championship_TOP 14',
 'cross_competition_category_Italian National Championship_United Rugby Championship',
 'cross_competition_category_TOP 14_Gallagher Premiership',
 'cross_competition_category_TOP 14_Italian National Championship',
 'cross_competition_category_TOP 14_United Rugby Championship',
 'cross_competition_category_United Rugby Championship_Gallagher Premiership',
 'cross_competition_category_United Rugby Championship_Italian National Championship',
 'cross_competition_category_United Rugby Championship_TOP 14',
 'cross_competition_category_na',
 'key_competition_name_European Rugby Challenge Cup',
 'key_competition_name_Gallagher Premiership',
 'key_competition_name_Heineken Champions Cup',
 'key_competition_name_Interational Age Grade',
 'key_competition_name_International',
 'key_competition_name_International Womens',
 'key_competition_name_Japan Top League',
 'key_competition_name_Mitre 10 Cup',
 'key_competition_name_Other',
 'key_competition_name_Other Age Grade',
 'key_competition_name_Other Club League',
 'key_competition_name_Other Club League Women',
 'key_competition_name_ProD2',
 'key_competition_name_Shute Shield',
 'key_competition_name_Super Rugby',
 'key_competition_name_TOP 14',
 'key_competition_name_United Rugby Championship',
# 'bookmakers_adjusted_prediction',
# 'expected_adjusted_bookmakers_category_B',
# 'expected_adjusted_bookmakers_category_2_B',
# 'expected_adjusted_bookmakers_category_2_C',
# 'expected_adjusted_bookmakers_category_2_D',
# 'expected_adjusted_bookmakers_category_2_E',
# 'expected_adjusted_bookmakers_category_3_B',
# 'expected_adjusted_bookmakers_category_3_C',
# 'expected_adjusted_bookmakers_category_3_D',
# 'expected_adjusted_bookmakers_category_3_E',
# 'expected_adjusted_bookmakers_category_3_F',
# 'expected_adjusted_bookmakers_category_4_B',
'features_z_score_cluster_0',
'features_z_score_cluster_1',
'features_z_score_cluster_2',
'features_z_score_cluster_3',
'features_z_score_cluster_4',
'features_z_score_cluster_5',
'features_z_score_cluster_6',
'features_z_score_cluster_7',
'features_z_score_cluster_8',
'features_z_score_cluster_9',
'general_features_cluster_0',
'general_features_cluster_1',
'general_features_cluster_2',
'general_features_cluster_3',
'general_features_cluster_4',
'general_features_cluster_5',
'general_features_cluster_6',
'general_features_cluster_7',
'general_features_cluster_8',
'general_features_cluster_9',
response_variable_name]

In [43]:
# features_to_clip = [
# 'delta_change_diff_5',
# 'delta_change_diff_10',
# 'delta_change_diff_20',
# 'error_trend_diff_5',
# 'error_trend_diff_10',
# 'error_trend_diff_20',
# 'pre_delta_diff_halftime',
# 'pre_delta_diff_secondhalf',
# 'pred_score_all',
# 'pred_score_ha',
# 'tries_diff_all',
# 'tries_diff_ha',
# 'triesdiff_vs_total_tries_ratio',
# 'triesdiff_vs_total_tries_ratio_abs',
# 'triesdiff_vs_total_tries_ha_ratio',
# 'triesdiff_vs_total_tries_ha_ratio_abs',
# 'pred_total_points_all',
# 'pred_total_points_ha',
# 'pred_total_tries_all',
# 'pred_total_tries_ha',
# 'pre_delta_diff_vs_first_plus_second',
# 'team_first_vs_second_half_diff',
# 'pre_delta_diff - error_5 - std_devs_away - diff',
# 'pre_delta_diff - error_10 - std_devs_away - diff',
# 'pre_delta_diff - error_20 - std_devs_away - diff',
# 'pre_delta_diff - comp_error_5 - std_devs_away - diff',
# 'pre_delta_diff - comp_error_10 - std_devs_away - diff',
# 'pre_delta_diff - comp_error_20 - std_devs_away - diff',
# 'pre_delta_diff - ha_error_5 - std_devs_away - diff',
# 'pre_delta_diff - ha_error_10 - std_devs_away - diff',
# 'pre_delta_diff - ha_error_20 - std_devs_away - diff',
# 'pre_delta_diff - deltachange_5 - std_devs_away - diff',
# 'pre_delta_diff - deltachange_10 - std_devs_away - diff',
# 'pre_delta_diff - deltachange_20 - std_devs_away - diff',
# 'pre_delta_diff - comp_deltachange_5 - std_devs_away - diff',
# 'pre_delta_diff - comp_deltachange_10 - std_devs_away - diff',
# 'pre_delta_diff - comp_deltachange_20 - std_devs_away - diff',
# 'pre_delta_diff - ha_deltachange_5 - std_devs_away - diff',
# 'pre_delta_diff - ha_deltachange_10 - std_devs_away - diff',
# 'pre_delta_diff - ha_deltachange_20 - std_devs_away - diff',
# 'pre_delta_diff_vs_total_points_ratio',
# 'pre_delta_diff_vs_total_points_ratio_abs',
# 'pre_delta_diff_vs_total_points_ratio_ha',
# 'pre_delta_diff_vs_total_points_ratio_ha_abs',
# 'diff_std_deviation_away_last_10',
# 'diff_std_deviation_away_last_20',
# 'diff_pre_delta_mean_last_10',
# 'diff_pre_delta_mean_last_20',
# ]

# # features_to_clip_dict = dict()
# temp_df = all_features_df[(all_features_df['home_team_total_fixture_number'] >=10) & (all_features_df['away_team_total_fixture_number']>= 10)]
# temp_df = temp_df[(temp_df['home_team_comp_fixture_number'] >=5) & (temp_df['away_team_comp_fixture_number']>= 5)]

# for feat in features_to_clip:
    
#     feat_mean = temp_df[feat].mean()
#     feat_stdev = temp_df[feat].std()
#     feat_max = temp_df[feat].max()
#     feat_min = temp_df[feat].max()
    
#     l_bound = feat_mean - (3.5 * feat_stdev)
#     u_bound = feat_mean + (3.5 * feat_stdev)
    
#     features_to_clip_dict[feat] = (l_bound, u_bound)


features_to_clip_dict = {'delta_change_diff_5': (-3.8803276001703133, 3.8826745000343705),
 'delta_change_diff_10': (-2.762889119824795, 2.7694875026381895),
 'delta_change_diff_20': (-1.908746166092025, 1.9142201736846574),
 'error_trend_diff_5': (-39.01319062124495, 39.07232642537519),
 'error_trend_diff_10': (-28.847691410380264, 28.832154033593078),
 'error_trend_diff_20': (-20.9402592937656, 20.909903885056046),
 'pre_delta_diff_halftime': (-23.916544335755795, 28.903793250171475),
 'pre_delta_diff_secondhalf': (-24.87210655542333, 29.881141250736206),
 'pred_score_all': (-42.7389126643786, 53.47549114132856),
 'pred_score_ha': (-44.46862942989905, 52.92911426806589),
 'tries_diff_all': (-8.461249449558169, 8.413819722745517),
 'tries_diff_ha': (-7.532951918752231, 9.059685551856212),
 'triesdiff_vs_total_tries_ratio': (-1, 1),
 'triesdiff_vs_total_tries_ratio_abs': (-0.5432440136747259, 1),
 'triesdiff_vs_total_tries_ha_ratio': (-1, 1),
 'triesdiff_vs_total_tries_ha_ratio_abs': (-0.5389515655575883, 1),
 'pred_total_points_all': (20.67962388044702, 73.38911727101834),
 'pred_total_points_ha': (22.032824758782517, 70.73173016545346),
 'pred_total_tries_all': (0.17231415579136744, 11.847802007278545),
 'pred_total_tries_ha': (0.2750156137472146, 11.689417158410198),
 'pre_delta_diff_vs_first_plus_second': (-13.009855209126963, 12.973033141134318),
 'team_first_vs_second_half_diff': (-12.235310871263131, 12.21352509036593),
 'pre_delta_diff - error_5 - std_devs_away - diff': (-3.1636058259326587, 3.168288853133352),
 'pre_delta_diff - error_10 - std_devs_away - diff': (-1.8679627666583765, 1.8668700105034108),
 'pre_delta_diff - error_20 - std_devs_away - diff': (-1.237348570870935, 1.2355253038062262),
 'pre_delta_diff - comp_error_5 - std_devs_away - diff': (-3.2786233825378237, 3.275385827500276),
 'pre_delta_diff - comp_error_10 - std_devs_away - diff': (-2.031110460214876, 2.028210676663014),
 'pre_delta_diff - comp_error_20 - std_devs_away - diff': (-1.5093916616074867, 1.5048110909231271),
 'pre_delta_diff - ha_error_5 - std_devs_away - diff': (-3.2365684544756474, 3.183146401764355),
 'pre_delta_diff - ha_error_10 - std_devs_away - diff': (-1.9682726144544518, 1.8877870544528579),
 'pre_delta_diff - ha_error_20 - std_devs_away - diff': (-1.5041055423472776, 1.4097297657188539),
 'pre_delta_diff - deltachange_5 - std_devs_away - diff': (-4.84898938506649, 4.838890402119485),
 'pre_delta_diff - deltachange_10 - std_devs_away - diff': (-1.9774059722262096, 1.9814862014550096),
 'pre_delta_diff - deltachange_20 - std_devs_away - diff': (-1.1961925011110672, 1.1991110959255136),
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - diff': (-5.502414743170416, 5.502883449953435),
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - diff': (-2.998169231402808, 2.9991545681386134),
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - diff': (-2.568711391768222, 2.5699267167145194),
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - diff': (-4.509756783872383, 4.540305387742048),
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - diff': (-2.073512631364599, 2.117923397864197),
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - diff': (-1.5785445206958548, 1.628128840445196),
 'pre_delta_diff_vs_total_points_ratio': (-0.9081622931355126, 1),
 'pre_delta_diff_vs_total_points_ratio_abs': (-0.4369227839241986, 0.9093549438406986),
 'pre_delta_diff_vs_total_points_ratio_ha': (-0.8985652477357522, 1),
 'pre_delta_diff_vs_total_points_ratio_ha_abs': (-0.4462604061691675, 0.9247357044158602),
 'diff_std_deviation_away_last_10': (-7.49819845698345, 7.4880239779639295),
 'diff_std_deviation_away_last_20': (-7.041135312891984, 7.0499031286881815),
 'diff_pre_delta_mean_last_10': (-49.35162338339965, 60.2118427568355),
 'diff_pre_delta_mean_last_20': (-48.591321636827, 59.41639366491113)}

for feature, (lower, upper) in features_to_clip_dict.items():
    if feature in features_to_use:  # Ensure the feature is in the model features
        all_features_df[feature] = all_features_df[feature].clip(lower=lower, upper=upper)

In [44]:
# Just check which features we aren't using
features_not_in_use = []

for col in all_features_df:
    
    if col not in features_to_use:
        
        features_not_in_use.append(col)
    
sorted(features_not_in_use)

['away_attack_post',
 'away_attack_pre',
 'away_away_attack_post',
 'away_away_attack_pre',
 'away_away_defence_post',
 'away_away_defence_pre',
 'away_away_triesconceded_post',
 'away_away_triesconceded_pre',
 'away_away_triesscored_post',
 'away_away_triesscored_pre',
 'away_comp_delta_change_halftime_stdev_10',
 'away_comp_delta_change_halftime_stdev_20',
 'away_comp_delta_change_halftime_stdev_5',
 'away_comp_delta_change_halftime_trend_10',
 'away_comp_delta_change_halftime_trend_20',
 'away_comp_delta_change_halftime_trend_5',
 'away_comp_delta_change_secondhalf_stdev_10',
 'away_comp_delta_change_secondhalf_stdev_20',
 'away_comp_delta_change_secondhalf_stdev_5',
 'away_comp_delta_change_secondhalf_trend_10',
 'away_comp_delta_change_secondhalf_trend_20',
 'away_comp_delta_change_secondhalf_trend_5',
 'away_comp_delta_change_stdev_10',
 'away_comp_delta_change_stdev_20',
 'away_comp_delta_change_stdev_5',
 'away_comp_delta_change_trend_10',
 'away_comp_delta_change_trend_20',
 'away_comp_delta_change_trend_5',
 'away_comp_error_halftime_stdev_10',
 'away_comp_error_halftime_stdev_20',
 'away_comp_error_halftime_stdev_5',
 'away_comp_error_halftime_trend_10',
 'away_comp_error_halftime_trend_20',
 'away_comp_error_halftime_trend_5',
 'away_comp_error_secondhalf_stdev_10',
 'away_comp_error_secondhalf_stdev_20',
 'away_comp_error_secondhalf_stdev_5',
 'away_comp_error_secondhalf_trend_10',
 'away_comp_error_secondhalf_trend_20',
 'away_comp_error_secondhalf_trend_5',
 'away_comp_error_stdev_10',
 'away_comp_error_stdev_20',
 'away_comp_error_stdev_5',
 'away_comp_error_trend_10',
 'away_comp_error_trend_20',
 'away_comp_error_trend_5',
 'away_defence_post',
 'away_defence_pre',
 'away_delta_change',
 'away_delta_change_halftime_stdev_10',
 'away_delta_change_halftime_stdev_20',
 'away_delta_change_halftime_stdev_5',
 'away_delta_change_halftime_trend_10',
 'away_delta_change_halftime_trend_20',
 'away_delta_change_halftime_trend_5',
 'away_delta_change_secondhalf_stdev_10',
 'away_delta_change_secondhalf_stdev_20',
 'away_delta_change_secondhalf_stdev_5',
 'away_delta_change_secondhalf_trend_10',
 'away_delta_change_secondhalf_trend_20',
 'away_delta_change_secondhalf_trend_5',
 'away_delta_change_stdev_10',
 'away_delta_change_stdev_20',
 'away_delta_change_stdev_5',
 'away_delta_change_trend_10',
 'away_delta_change_trend_20',
 'away_delta_change_trend_5',
 'away_error',
 'away_error_halftime_stdev_10',
 'away_error_halftime_stdev_20',
 'away_error_halftime_stdev_5',
 'away_error_halftime_trend_10',
 'away_error_halftime_trend_20',
 'away_error_halftime_trend_5',
 'away_error_secondhalf_stdev_10',
 'away_error_secondhalf_stdev_20',
 'away_error_secondhalf_stdev_5',
 'away_error_secondhalf_trend_10',
 'away_error_secondhalf_trend_20',
 'away_error_secondhalf_trend_5',
 'away_error_stdev_10',
 'away_error_stdev_20',
 'away_error_stdev_5',
 'away_error_trend_10',
 'away_error_trend_20',
 'away_error_trend_5',
 'away_ha_delta_change_halftime_stdev_10',
 'away_ha_delta_change_halftime_stdev_20',
 'away_ha_delta_change_halftime_stdev_5',
 'away_ha_delta_change_halftime_trend_10',
 'away_ha_delta_change_halftime_trend_20',
 'away_ha_delta_change_halftime_trend_5',
 'away_ha_delta_change_secondhalf_stdev_10',
 'away_ha_delta_change_secondhalf_stdev_20',
 'away_ha_delta_change_secondhalf_stdev_5',
 'away_ha_delta_change_secondhalf_trend_10',
 'away_ha_delta_change_secondhalf_trend_20',
 'away_ha_delta_change_secondhalf_trend_5',
 'away_ha_delta_change_stdev_10',
 'away_ha_delta_change_stdev_20',
 'away_ha_delta_change_stdev_5',
 'away_ha_delta_change_trend_10',
 'away_ha_delta_change_trend_20',
 'away_ha_delta_change_trend_5',
 'away_ha_error_halftime_stdev_10',
 'away_ha_error_halftime_stdev_20',
 'away_ha_error_halftime_stdev_5',
 'away_ha_error_halftime_trend_10',
 'away_ha_error_halftime_trend_20',
 'away_ha_error_halftime_trend_5',
 'away_ha_error_secondhalf_stdev_10',
 'away_ha_error_secondhalf_stdev_20',
 'away_ha_error_secondhalf_stdev_5',
 'away_ha_error_secondhalf_trend_10',
 'away_ha_error_secondhalf_trend_20',
 'away_ha_error_secondhalf_trend_5',
 'away_ha_error_stdev_10',
 'away_ha_error_stdev_20',
 'away_ha_error_stdev_5',
 'away_ha_error_trend_10',
 'away_ha_error_trend_20',
 'away_ha_error_trend_5',
 'away_last_game_distance_category',
 'away_last_game_distance_value',
 'away_lower_band_1_5std_last_10',
 'away_lower_band_1_5std_last_20',
 'away_lower_band_2std_last_10',
 'away_lower_band_2std_last_20',
 'away_neg_deltachange_streak',
 'away_pos_deltachange_streak',
 'away_post_delta',
 'away_post_delta_halftime',
 'away_post_delta_secondhalf',
 'away_pre_delta',
 'away_pre_delta_halftime',
 'away_pre_delta_secondhalf',
 'away_score',
 'away_std_deviation_away_last_10',
 'away_std_deviation_away_last_20',
 'away_team_away_fixture_number',
 'away_team_comp_fixture_number',
 'away_team_first_vs_second_half_points',
 'away_team_internal_id',
 'away_team_player_delta',
 'away_team_pre_delta_mean_last_10',
 'away_team_pre_delta_mean_last_20',
 'away_team_pre_delta_stdev_last_10',
 'away_team_pre_delta_stdev_last_20',
 'away_team_total_fixture_number',
 'away_triesconceded_post',
 'away_triesconceded_pre',
 'away_triesscored_post',
 'away_triesscored_pre',
 'away_upper_band_1_5std_last_10',
 'away_upper_band_1_5std_last_20',
 'away_upper_band_2std_last_10',
 'away_upper_band_2std_last_20',
 'away_weighted_form',
 'away_weighted_form_comp',
 'away_weighted_form_ha',
 'away_weighted_form_vsopp',
 'bookmakers_away_1x2_odds',
 'bookmakers_handicap_value',
 'bookmakers_home_1x2_odds',
 'bookmakers_totalpoints_value',
 'competition_internal_id',
 'created_at',
 'cross_competition_category_Currie Cup U21s_United Rugby Championship',
 'cross_competition_category_Currie Cup_Romania SuperLiga',
 'cross_competition_category_Currie Cup_Super Rugby',
 'cross_competition_category_Currie Cup_SuperSport',
 'cross_competition_category_Currie Cup_United Rugby Championship',
 'cross_competition_category_England RFU Championship_Gallagher Premiership',
 'cross_competition_category_England RFU Championship_National League One',
 'cross_competition_category_England RFU Championship_Principality Premiership',
 'cross_competition_category_England RFU Championship_Scottish Premiership',
 'cross_competition_category_England RFU Championship_United Rugby Championship',
 'cross_competition_category_England RFU Championship_international_mens',
 'cross_competition_category_Gallagher Premiership_Currie Cup',
 'cross_competition_category_Gallagher Premiership_England RFU Championship',
 'cross_competition_category_Gallagher Premiership_Italian National Championship',
 'cross_competition_category_Gallagher Premiership_National League One',
 'cross_competition_category_Gallagher Premiership_ProD2',
 'cross_competition_category_Gallagher Premiership_Romania SuperLiga',
 'cross_competition_category_Gallagher Premiership_Russia Premier League',
 'cross_competition_category_Gallagher Premiership_Super Rugby',
 'cross_competition_category_Gallagher Premiership_international_mens',
 'cross_competition_category_Georgia Didi 10_Italian National Championship',
 'cross_competition_category_Italian National Championship_Georgia Didi 10',
 'cross_competition_category_Japan Top League_Super Rugby',
 'cross_competition_category_Mitre 10 Cup_international_mens',
 'cross_competition_category_National League One_England RFU Championship',
 'cross_competition_category_National League One_Principality Premiership',
 'cross_competition_category_Principality Premiership_England RFU Championship',
 'cross_competition_category_Principality Premiership_Gallagher Premiership',
 'cross_competition_category_Principality Premiership_Scottish Premiership',
 'cross_competition_category_Principality Premiership_United Rugby Championship',
 'cross_competition_category_Principality Premiership_international_mens',
 'cross_competition_category_ProD2_Gallagher Premiership',
 'cross_competition_category_ProD2_Italian National Championship',
 'cross_competition_category_ProD2_TOP 14',
 'cross_competition_category_ProD2_United Rugby Championship',
 'cross_competition_category_Romania SuperLiga_Gallagher Premiership',
 'cross_competition_category_Romania SuperLiga_Russia Premier League',
 'cross_competition_category_Romania SuperLiga_TOP 14',
 'cross_competition_category_Romania SuperLiga_United Rugby Championship',
 'cross_competition_category_Russia Premier League_Gallagher Premiership',
 'cross_competition_category_Russia Premier League_Romania SuperLiga',
 'cross_competition_category_Russia Premier League_TOP 14',
 'cross_competition_category_Russia Premier League_United Rugby Championship',
 'cross_competition_category_Scottish Premiership_England RFU Championship',
 'cross_competition_category_Scottish Premiership_Principality Premiership',
 'cross_competition_category_Shute Shield_international_mens',
 'cross_competition_category_Super Rugby_Currie Cup',
 'cross_competition_category_Super Rugby_TOP 14',
 'cross_competition_category_Super Rugby_United Rugby Championship',
 'cross_competition_category_Super Rugby_international_mens',
 'cross_competition_category_SuperSport_Currie Cup',
 'cross_competition_category_SuperSport_Super Rugby',
 'cross_competition_category_TOP 14_Currie Cup U21s',
 'cross_competition_category_TOP 14_England RFU Championship',
 'cross_competition_category_TOP 14_ProD2',
 'cross_competition_category_TOP 14_Romania SuperLiga',
 'cross_competition_category_TOP 14_Russia Premier League',
 'cross_competition_category_TOP 14_Super Rugby',
 'cross_competition_category_TOP 14_international_mens',
 'cross_competition_category_United Rugby Championship_Currie Cup U21s',
 'cross_competition_category_United Rugby Championship_England RFU Championship',
 'cross_competition_category_United Rugby Championship_Romania SuperLiga',
 'cross_competition_category_United Rugby Championship_Russia Premier League',
 'cross_competition_category_United Rugby Championship_Super Rugby',
 'cross_competition_category_United Rugby Championship_international_mens',
 'cross_competition_category_Vodacom Cup_international_mens',
 'cross_competition_category_international_mens_England RFU Championship',
 'cross_competition_category_international_mens_Gallagher Premiership',
 'cross_competition_category_international_mens_National Rugby Championship',
 'cross_competition_category_international_mens_Super Rugby',
 'cross_competition_category_international_mens_TOP 14',
 'cross_competition_category_international_mens_United Rugby Championship',
 'cross_competition_category_international_u20s_URBA Top 12',
 'delta_adjusted_error',
 'delta_adjusted_error_abs',
 'delta_adjusted_success',
 'delta_error_abs',
 'delta_success',
 'event_id',
 'expected_delta_adjusted_category_1',
 'expected_delta_adjusted_category_2',
 'expected_delta_adjusted_category_3',
 'expected_delta_adjusted_category_4',
 'expected_globalwinmargin_category_1',
 'expected_globalwinmargin_category_2',
 'expected_globalwinmargin_category_3',
 'expected_globalwinmargin_category_4',
 'home_attack_post',
 'home_attack_pre',
 'home_away_win',
 'home_comp_delta_change_halftime_stdev_10',
 'home_comp_delta_change_halftime_stdev_20',
 'home_comp_delta_change_halftime_stdev_5',
 'home_comp_delta_change_halftime_trend_10',
 'home_comp_delta_change_halftime_trend_20',
 'home_comp_delta_change_halftime_trend_5',
 'home_comp_delta_change_secondhalf_stdev_10',
 'home_comp_delta_change_secondhalf_stdev_20',
 'home_comp_delta_change_secondhalf_stdev_5',
 'home_comp_delta_change_secondhalf_trend_10',
 'home_comp_delta_change_secondhalf_trend_20',
 'home_comp_delta_change_secondhalf_trend_5',
 'home_comp_delta_change_stdev_10',
 'home_comp_delta_change_stdev_20',
 'home_comp_delta_change_stdev_5',
 'home_comp_delta_change_trend_10',
 'home_comp_delta_change_trend_20',
 'home_comp_delta_change_trend_5',
 'home_comp_error_halftime_stdev_10',
 'home_comp_error_halftime_stdev_20',
 'home_comp_error_halftime_stdev_5',
 'home_comp_error_halftime_trend_10',
 'home_comp_error_halftime_trend_20',
 'home_comp_error_halftime_trend_5',
 'home_comp_error_secondhalf_stdev_10',
 'home_comp_error_secondhalf_stdev_20',
 'home_comp_error_secondhalf_stdev_5',
 'home_comp_error_secondhalf_trend_10',
 'home_comp_error_secondhalf_trend_20',
 'home_comp_error_secondhalf_trend_5',
 'home_comp_error_stdev_10',
 'home_comp_error_stdev_20',
 'home_comp_error_stdev_5',
 'home_comp_error_trend_10',
 'home_comp_error_trend_20',
 'home_comp_error_trend_5',
 'home_defence_post',
 'home_defence_pre',
 'home_delta_change',
 'home_delta_change_halftime_stdev_10',
 'home_delta_change_halftime_stdev_20',
 'home_delta_change_halftime_stdev_5',
 'home_delta_change_halftime_trend_10',
 'home_delta_change_halftime_trend_20',
 'home_delta_change_halftime_trend_5',
 'home_delta_change_secondhalf_stdev_10',
 'home_delta_change_secondhalf_stdev_20',
 'home_delta_change_secondhalf_stdev_5',
 'home_delta_change_secondhalf_trend_10',
 'home_delta_change_secondhalf_trend_20',
 'home_delta_change_secondhalf_trend_5',
 'home_delta_change_stdev_10',
 'home_delta_change_stdev_20',
 'home_delta_change_stdev_5',
 'home_delta_change_trend_10',
 'home_delta_change_trend_20',
 'home_delta_change_trend_5',
 'home_error',
 'home_error_halftime_stdev_10',
 'home_error_halftime_stdev_20',
 'home_error_halftime_stdev_5',
 'home_error_halftime_trend_10',
 'home_error_halftime_trend_20',
 'home_error_halftime_trend_5',
 'home_error_secondhalf_stdev_10',
 'home_error_secondhalf_stdev_20',
 'home_error_secondhalf_stdev_5',
 'home_error_secondhalf_trend_10',
 'home_error_secondhalf_trend_20',
 'home_error_secondhalf_trend_5',
 'home_error_stdev_10',
 'home_error_stdev_20',
 'home_error_stdev_5',
 'home_error_trend_10',
 'home_error_trend_20',
 'home_error_trend_5',
 'home_ha_delta_change_halftime_stdev_10',
 'home_ha_delta_change_halftime_stdev_20',
 'home_ha_delta_change_halftime_stdev_5',
 'home_ha_delta_change_halftime_trend_10',
 'home_ha_delta_change_halftime_trend_20',
 'home_ha_delta_change_halftime_trend_5',
 'home_ha_delta_change_secondhalf_stdev_10',
 'home_ha_delta_change_secondhalf_stdev_20',
 'home_ha_delta_change_secondhalf_stdev_5',
 'home_ha_delta_change_secondhalf_trend_10',
 'home_ha_delta_change_secondhalf_trend_20',
 'home_ha_delta_change_secondhalf_trend_5',
 'home_ha_delta_change_stdev_10',
 'home_ha_delta_change_stdev_20',
 'home_ha_delta_change_stdev_5',
 'home_ha_delta_change_trend_10',
 'home_ha_delta_change_trend_20',
 'home_ha_delta_change_trend_5',
 'home_ha_error_halftime_stdev_10',
 'home_ha_error_halftime_stdev_20',
 'home_ha_error_halftime_stdev_5',
 'home_ha_error_halftime_trend_10',
 'home_ha_error_halftime_trend_20',
 'home_ha_error_halftime_trend_5',
 'home_ha_error_secondhalf_stdev_10',
 'home_ha_error_secondhalf_stdev_20',
 'home_ha_error_secondhalf_stdev_5',
 'home_ha_error_secondhalf_trend_10',
 'home_ha_error_secondhalf_trend_20',
 'home_ha_error_secondhalf_trend_5',
 'home_ha_error_stdev_10',
 'home_ha_error_stdev_20',
 'home_ha_error_stdev_5',
 'home_ha_error_trend_10',
 'home_ha_error_trend_20',
 'home_ha_error_trend_5',
 'home_home_attack_post',
 'home_home_attack_pre',
 'home_home_defence_post',
 'home_home_defence_pre',
 'home_home_triesconceded_post',
 'home_home_triesconceded_pre',
 'home_home_triesscored_post',
 'home_home_triesscored_pre',
 'home_last_game_distance_category',
 'home_last_game_distance_value',
 'home_lower_band_1_5std_last_10',
 'home_lower_band_1_5std_last_20',
 'home_lower_band_2std_last_10',
 'home_lower_band_2std_last_20',
 'home_neg_deltachange_streak',
 'home_pos_deltachange_streak',
 'home_post_delta',
 'home_post_delta_halftime',
 'home_post_delta_secondhalf',
 'home_pre_delta',
 'home_pre_delta_halftime',
 'home_pre_delta_secondhalf',
 'home_score',
 'home_std_deviation_away_last_10',
 'home_std_deviation_away_last_20',
 'home_team_buffer',
 'home_team_buffer_halftime',
 'home_team_buffer_secondhalf',
 'home_team_comp_fixture_number',
 'home_team_first_vs_second_half_points',
 'home_team_home_fixture_number',
 'home_team_internal_id',
 'home_team_player_delta',
 'home_team_pre_delta_mean_last_10',
 'home_team_pre_delta_mean_last_20',
 'home_team_pre_delta_stdev_last_10',
 'home_team_pre_delta_stdev_last_20',
 'home_team_total_fixture_number',
 'home_triesconceded_post',
 'home_triesconceded_pre',
 'home_triesscored_post',
 'home_triesscored_pre',
 'home_upper_band_1_5std_last_10',
 'home_upper_band_1_5std_last_20',
 'home_upper_band_2std_last_10',
 'home_upper_band_2std_last_20',
 'home_weighted_form',
 'home_weighted_form_comp',
 'home_weighted_form_ha',
 'home_weighted_form_vsopp',
 'home_win_not_win',
 'last_game_distance_category_A_B',
 'last_game_distance_category_A_C',
 'last_game_distance_category_A_D',
 'last_game_distance_category_A_E',
 'last_game_distance_category_A_F',
 'last_game_distance_category_A_G',
 'last_game_distance_category_B_A',
 'last_game_distance_category_B_F',
 'last_game_distance_category_B_G',
 'last_game_distance_category_C_A',
 'last_game_distance_category_C_G',
 'last_game_distance_category_D_A',
 'last_game_distance_category_D_G',
 'last_game_distance_category_E_A',
 'last_game_distance_category_E_B',
 'last_game_distance_category_E_G',
 'last_game_distance_category_F_B',
 'last_game_distance_category_G_A',
 'last_game_distance_category_G_B',
 'last_game_distance_category_G_C',
 'last_game_distance_category_G_D',
 'last_game_distance_category_G_E',
 'last_game_distance_value',
 'p1_model_bookmakers_handicap_error',
 'p1_model_compspecific_deltaerror',
 'p1_model_compspecific_homeawaywin_probability',
 'p1_model_compspecific_homeawaywin_probability_outlier_flag',
 'p1_model_compspecific_predeltadiff_adjusted',
 'p1_model_compspecific_winmarginerror',
 'p1_model_compspecific_winmarginerror_outlier_flag',
 'p1_model_global_delta_error',
 'p1_model_global_delta_error_outlier_flag',
 'p1_model_global_predeltadiff_adjusted',
 'p1_model_global_win_margin',
 'p1_model_global_win_margin_outlier_flag',
 'player_delta_diff',
 'pre_delta_adjustment',
 'pre_delta_adjustment_halftime',
 'pre_delta_adjustment_secondhalf',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - away',
 'pre_delta_diff - comp_deltachange_10 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - away',
 'pre_delta_diff - comp_deltachange_20 - std_devs_away - home',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - away',
 'pre_delta_diff - comp_deltachange_5 - std_devs_away - home',
 'pre_delta_diff - comp_error_10 - std_devs_away - away',
 'pre_delta_diff - comp_error_10 - std_devs_away - home',
 'pre_delta_diff - comp_error_20 - std_devs_away - away',
 'pre_delta_diff - comp_error_20 - std_devs_away - home',
 'pre_delta_diff - comp_error_5 - std_devs_away - away',
 'pre_delta_diff - comp_error_5 - std_devs_away - home',
 'pre_delta_diff - deltachange_10 - std_devs_away - away',
 'pre_delta_diff - deltachange_10 - std_devs_away - home',
 'pre_delta_diff - deltachange_20 - std_devs_away - away',
 'pre_delta_diff - deltachange_20 - std_devs_away - home',
 'pre_delta_diff - deltachange_5 - std_devs_away - away',
 'pre_delta_diff - deltachange_5 - std_devs_away - home',
 'pre_delta_diff - error_10 - std_devs_away - away',
 'pre_delta_diff - error_10 - std_devs_away - home',
 'pre_delta_diff - error_20 - std_devs_away - away',
 'pre_delta_diff - error_20 - std_devs_away - home',
 'pre_delta_diff - error_5 - std_devs_away - away',
 'pre_delta_diff - error_5 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_10 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_20 - std_devs_away - home',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - away',
 'pre_delta_diff - ha_deltachange_5 - std_devs_away - home',
 'pre_delta_diff - ha_error_10 - std_devs_away - away',

In [45]:
# Replace null features and/or remove columns with high nulls

In [46]:
# These features we are replacing with zeros
zero_replacement_cols = ['Trend Diff - Home - points_scored_value_adjustment_factor',
       'Trend Diff - Away - points_scored_value_adjustment_factor',
       'Trend Diff - Home - points_conceded_value_adjustment_factor',
       'Trend Diff - Away - points_conceded_value_adjustment_factor',
       'Trend Diff - Home_Away - points_scored_value_adjustment_factor',
       'Trend Diff - Home_Away - points_conceded_value_adjustment_factor',
       'Trend Diff - Home_Away - points_value_adjustment_factor',
       'played_perc - squad - diff', 'played_perc - first_xv - diff',
       'played_perc - backs - diff', 'played_perc - forwards - diff',
       'played_perc - ten - diff', 'played_perc - nine - diff',
'diff_std_deviation_away_last_10',
 'diff_std_deviation_away_last_20',]

In [47]:
zero_replacement_cols = [
'Trend Diff - Home - points_scored_value_adjustment_factor',
'Trend Diff - Away - points_scored_value_adjustment_factor',
'Trend Diff - Home - points_conceded_value_adjustment_factor',
'Trend Diff - Away - points_conceded_value_adjustment_factor',
'Trend Diff - Home_Away - points_scored_value_adjustment_factor',
'Trend Diff - Home_Away - points_conceded_value_adjustment_factor',
'Trend Diff - Home_Away - points_value_adjustment_factor',
'delta_change_diff_5',
'delta_change_diff_10',
'delta_change_diff_20',
'error_trend_diff_5',
'error_trend_diff_10',
'error_trend_diff_20',
'pre_delta_diff_halftime',
'pre_delta_diff_secondhalf',
'tries_diff_all',
'tries_diff_ha',
'triesdiff_vs_total_tries_ratio',
'triesdiff_vs_total_tries_ratio_abs',
'triesdiff_vs_total_tries_ha_ratio',
'triesdiff_vs_total_tries_ha_ratio_abs',
'pre_delta_diff_vs_first_plus_second',
'team_first_vs_second_half_diff',
'pre_delta_diff - error_5 - std_devs_away - diff',
'pre_delta_diff - error_10 - std_devs_away - diff',
'pre_delta_diff - error_20 - std_devs_away - diff',
'pre_delta_diff - comp_error_5 - std_devs_away - diff',
'pre_delta_diff - comp_error_10 - std_devs_away - diff',
'pre_delta_diff - comp_error_20 - std_devs_away - diff',
'pre_delta_diff - ha_error_5 - std_devs_away - diff',
'pre_delta_diff - ha_error_10 - std_devs_away - diff',
'pre_delta_diff - ha_error_20 - std_devs_away - diff',
'pre_delta_diff - deltachange_5 - std_devs_away - diff',
'pre_delta_diff - deltachange_10 - std_devs_away - diff',
'pre_delta_diff - deltachange_20 - std_devs_away - diff',
'pre_delta_diff - comp_deltachange_5 - std_devs_away - diff',
'pre_delta_diff - comp_deltachange_10 - std_devs_away - diff',
'pre_delta_diff - comp_deltachange_20 - std_devs_away - diff',
'pre_delta_diff - ha_deltachange_5 - std_devs_away - diff',
'pre_delta_diff - ha_deltachange_10 - std_devs_away - diff',
'pre_delta_diff - ha_deltachange_20 - std_devs_away - diff',
'pre_delta_diff_vs_total_points_ratio',
'pre_delta_diff_vs_total_points_ratio_abs',
'weighted_form_diff',
'weighted_form_ha_diff',
'weighted_form_comp_diff',
'weighted_form_vsopp_diff',
'pre_delta_diff_vs_total_points_ratio_ha',
'pre_delta_diff_vs_total_points_ratio_ha_abs',
'predicted_change_of_result_at_halftime',
'home_above_upper_band_2std_last_10',
'home_below_lower_band_2std_last_10',
'home_above_upper_band_1_5std_last_10',
'home_below_lower_band_1_5std_last_10',
'home_above_upper_band_2std_last_20',
'home_below_lower_band_2std_last_20',
'home_above_upper_band_1_5std_last_20',
'home_below_lower_band_1_5std_last_20',
'away_above_upper_band_2std_last_10',
'away_below_lower_band_2std_last_10',
'away_above_upper_band_1_5std_last_10',
'away_below_lower_band_1_5std_last_10',
'away_above_upper_band_2std_last_20',
'away_below_lower_band_2std_last_20',
'away_above_upper_band_1_5std_last_20',
'away_below_lower_band_1_5std_last_20',
'diff_std_deviation_away_last_10',
'diff_std_deviation_away_last_20',
'home_above_upper_band_2std_last_10',
'home_below_lower_band_2std_last_10',
'home_above_upper_band_1_5std_last_10',
'home_below_lower_band_1_5std_last_10',
'home_above_upper_band_2std_last_20',
'home_below_lower_band_2std_last_20',
'home_above_upper_band_1_5std_last_20',
'home_below_lower_band_1_5std_last_20',
'away_above_upper_band_2std_last_10',
'away_below_lower_band_2std_last_10',
'away_above_upper_band_1_5std_last_10',
'away_below_lower_band_1_5std_last_10',
'away_above_upper_band_2std_last_20',
'away_below_lower_band_2std_last_20',
'away_above_upper_band_1_5std_last_20',
'away_below_lower_band_1_5std_last_20',
'diff_std_deviation_away_last_10',
'diff_std_deviation_away_last_20',
'diff_pre_delta_mean_last_10',
'diff_pre_delta_mean_last_20',
]

In [48]:
for col in features_to_use:
    if col not in all_features_df.columns:
        
        print(col, 'is not in the dataframe so removing it from features_to_use')
        features_to_use = [x for x in features_to_use if x != col]

In [49]:
# Add in zero replacements
for col in all_features_df.columns:
    if col in zero_replacement_cols:
        all_features_df[col].fillna(0, inplace = True)

In [50]:
# Categorical variables are already set
numerical_vars = [feature for feature in features_to_use if feature not in categorical_features and feature != response_variable_name]

# Convert numerical features
for col in all_features_df.columns:
    if col in numerical_vars:
        all_features_df[col] = all_features_df[col].astype('float32')

# Drop rows where the repsonse column is null
all_features_df = all_features_df.dropna(subset = response_variable_name)

# Remove high null features
all_features_df, features_to_use = remove_high_null_features(all_features_df, features_to_use, 0.5)


# Impute missing values
all_features_df = impute_missing_values(all_features_df, features_to_use)

# Remove low variance and correlated features
# var_thresh = 0.01
# corr_thresh = 0.01
# all_features_df = remove_low_varAndcorr_features(all_features_df, var_thresh, corr_thresh)

# Remove categorical variables where there are too many categories or only 1 category
#threshold_perc = 10
#all_features_df = drop_categorical_vars_with_too_many_categories(all_features_df, threshold_perc)

Column  home_venue with nulls 2.1
Replacing home_venue with median: 1.0

# Reduce data to just training set

In [51]:
# Drop to just the training data
all_features_df = all_features_df[(all_features_df['home_team_total_fixture_number'] >=10) & (all_features_df['away_team_total_fixture_number']>= 10)]
print(len(all_features_df))

all_features_df = all_features_df[(all_features_df['home_team_comp_fixture_number'] >=5) & (all_features_df['away_team_comp_fixture_number']>= 5)]
print(len(all_features_df))

# all_features_df  = all_features_df[ pd.notna(all_features_df['Trend Diff - Home_Away - points_value_adjustment_factor'])]
# print(len(all_features_df))

55012
52566

In [52]:
original_df = all_features_df.copy()

In [53]:
# Potentially keep some for validation
all_features_df = all_features_df[(all_features_df[validation_range_column]<= (validation_start_range)) & (all_features_df[validation_range_column]>= (train_start_range))]
print(len(all_features_df))

28310

# Transform target varable if applicable

In [54]:
if transform_target == 'tan':
    normalized_margin = (all_features_df['win_margin'] - all_features_df['win_margin'].mean()) / all_features_df['win_margin'].std()
    all_features_df['win_margin'] = np.tanh(normalized_margin)

elif transform_target == 'sqrt':
    all_features_df['win_margin'] = all_features_df[['win_margin', 'win_margin_sign']].apply(lambda x: np.sqrt(abs(x[0])) * x[1], axis = 1)

elif transform_target == 'power_34':
    all_features_df['win_margin'] = all_features_df[['win_margin', 'win_margin_sign']].apply(lambda x: np.power(abs(x[0]), 3/4) * x[1], axis=1)

In [55]:
all_features_df = all_features_df[features_to_use]

In [56]:
all_features_df = all_features_df[features_to_use].dropna()
all_features_df.describe()

,pre_delta_diff,level_2,level_2.5,level_3,level_4,level_5,level_6,type_U19s,type_U20s,type_U21s,...,general_features_cluster_1,general_features_cluster_2,general_features_cluster_3,general_features_cluster_4,general_features_cluster_5,general_features_cluster_6,general_features_cluster_7,general_features_cluster_8,general_features_cluster_9,delta_error
count,28310.000000,28310.000000,28310.000000,28310.000000,28310.000000,28310.000000,28310.0,28310.0,28310.000000,28310.0,...,28310.000000,28310.000000,28310.000000,28310.000000,28310.0,28310.00000,28310.000000,28310.000000,28310.0,28310.000000
mean,5.198317,0.268527,0.016602,0.459661,0.163123,0.000848,0.0,0.0,0.019534,0.0,...,0.151890,0.085517,0.142353,0.021724,0.0,0.15687,0.101554,0.282409,0.0,-0.124219
std,14.540740,0.443241,0.127773,0.498418,0.369491,0.029092,0.0,0.0,0.138395,0.0,...,0.358853,0.279673,0.349421,0.145777,0.0,0.36373,0.302013,0.450187,0.0,16.324808
min,-95.156998,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.0,-109.907459
25%,-3.051405,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.0,-9.785789
50%,5.280923,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.0,0.301446
75%,13.436223,1.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,1.000000,0.0,9.741964
max,101.803070,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,0.0,...,1.000000,1.000000,1.000000,1.000000,0.0,1.00000,1.000000,1.000000,0.0,98.356508

In [57]:
all_features_df = all_features_df[features_to_use].dropna()

In [58]:
X = all_features_df.drop(columns=[response_variable_name])
y = all_features_df[response_variable_name]

In [59]:
if model_type == 'binary_classification':
    # Step 1: Convert categorical labels to numeric labels
    le = LabelEncoder()
    y = le.fit_transform(y)

    # Step 2: One-hot encode the numeric labels
#     num_classes = len(np.unique(y_numeric))  # Determine the number of classes
#     y = to_categorical(y_numeric, num_classes=num_classes)

In [60]:
print(len(X), len(original_df))

28310 52566

# Modelling Part

In [61]:
# Function to generate activation combinations based on the number of layers
def generate_activation_combinations(num_layers, activations):
    # Generate all combinations of activations for the given number of hidden layers
    activation_combinations = list(itertools.product(activations, repeat=num_layers))
    return activation_combinations

In [62]:
def run_experiment(
    model_type, pca_enabled, pca_threshold, X, y, learning_rate, batch_size, optimizer, 
    loss_function, metrics, epochs, activation_layers, n_splits, class_weights_enabled, 
    outlier_dict=None, patience=5, shap_samples=1000, stratification_enabled=False, 
    lr_schedule_enabled=False, lr_schedule_strategy=None, dropout_enabled=False, dropout_rate=0.5, 
    early_stopping_metric='val_loss', validation_dict = {}):

    original_X = X.copy()

    # Convert X and y to numpy arrays if they are pandas DataFrames or Series
    X = X.values if hasattr(X, 'values') else X
    y = y.values if hasattr(y, 'values') else y
    

    # Apply PCA if enabled
    if pca_enabled and pd.notna(pca_threshold):
        pca = PCA(n_components=pca_threshold)
        X = pca.fit_transform(X)
        print('X_pca shape: ' + str(X.shape))
    else:
        pca = None
        
        
    # Set the scheduler if we are using one
    if lr_schedule_enabled and lr_schedule_strategy:
        lr_schedule_function = lr_schedule_strategy['method']


    # Handle Outlier Detection Configuration
    outlier_enabled = outlier_dict.get('enabled', False) if outlier_dict else False
    outlier_contamination = outlier_dict.get('contamination', 0.05) if outlier_enabled else None
    remove_outliers = outlier_dict.get('remove_outliers', False) if outlier_enabled else False

    # Step 1: Outlier Detection
    if outlier_enabled:
        outlier_detection = IsolationForest(contamination=outlier_contamination)
        outlier_flags = outlier_detection.fit_predict(X)  # -1 for outliers, 1 for inliers
        outlier_flags = np.where(outlier_flags == -1, 1, 0)  # 1 is an outlier, 0 is an inlier
        X = np.column_stack((X, outlier_flags))  # Append the outlier flag as a new feature
        print(f"Outlier detection enabled. Outliers detected: {np.sum(outlier_flags)}")

        # Outlier Summary
        total_outliers = np.sum(outlier_flags)
        total_samples = len(outlier_flags)
        percentage_outliers = (total_outliers / total_samples) * 100

        print(f"Outlier detection enabled.")
        print(f"Total samples: {total_samples}")
        print(f"Total outliers detected: {total_outliers} ({percentage_outliers:.2f}%)")
    else:
        outlier_detection = None

        
    # Track performance across folds
    fold_metrics = []
    feature_importances = []
    
    # Use KFold cross-validation with or without stratification
    if n_splits > 1:
        if stratification_enabled:
            kfold = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
        else:
            kfold = KFold(n_splits=n_splits, shuffle=True, random_state=42)
        splits = kfold.split(X, y)
    else:
        # Use a single train-test split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y if stratification_enabled else None)
        splits = [(np.arange(len(X_train)), np.arange(len(X_test)) + len(X_train))]
        
    for fold_idx, (train_idx, test_idx) in enumerate(splits):
        print(f"Training fold {fold_idx + 1}...")

        # Split the data into training and testing sets
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        # Step 2: Handle Outliers in Training Data
        if outlier_enabled and remove_outliers:
            inlier_indices = X_train[:, -1] == 0
            X_train = X_train[inlier_indices]
            y_train = y_train[inlier_indices]
            X_train = X_train[:, :-1]
            X_test = X_test[:, :-1]

        # Step 3: Scale the features
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)

        # Unpack optimizer and loss function
        optimizer_class, optimizer_params = optimizer
        optimizer_params['learning_rate'] = learning_rate
        optimizer_instance = optimizer_class(**optimizer_params)

        loss_function_class, loss_function_params = loss_function
        loss_function_to_use = loss_function_class(**loss_function_params)
        
        metrics_to_use = [m(**p) for m, p in metrics]

        # Learning Rate Scheduler (if enabled)            
        # Initialize the callbacks list
        callbacks = []

        # Learning Rate Scheduler (if enabled)
        if lr_schedule_enabled and lr_schedule_strategy:
            if isinstance(lr_schedule_function, ReduceLROnPlateau):
                # If lr_schedule_strategy is a ReduceLROnPlateau instance, add it directly
                callbacks.append(lr_schedule_function)
            elif callable(lr_schedule_function):
                # If lr_schedule_strategy is a callable function, use it with LearningRateScheduler
                lr_scheduler = LearningRateScheduler(lr_schedule_function)
                callbacks.append(lr_scheduler)
            else:
                print("Invalid lr_schedule_strategy provided. Must be callable or a ReduceLROnPlateau instance.")


        # Early Stopping with customizable metric
        early_stopping = EarlyStopping(monitor=early_stopping_metric, patience=patience, restore_best_weights=True)
        callbacks.append(early_stopping)

        # Initialize a sequential model
        model = tf.keras.Sequential()
        model.add(tf.keras.layers.Input(shape=X_train_scaled.shape[1]))

        # Hidden layers with Batch Normalization, Weight Initializers, and optional Dropout
        for a_layer in activation_layers:
            activation_function = a_layer['activation']
            initializer = HeNormal() if activation_function in ['relu', 'leaky_relu', 'elu'] else GlorotUniform()
            model.add(tf.keras.layers.Dense(
                a_layer['nodes'],
                activation=None,
                kernel_initializer=initializer,
                kernel_regularizer=tf.keras.regularizers.l2(a_layer['l2_reg']),
                activity_regularizer=tf.keras.regularizers.l1(a_layer['l1_reg'])
            ))
            model.add(tf.keras.layers.BatchNormalization())
            model.add(tf.keras.layers.Activation(activation_function))
            if dropout_enabled:
                model.add(tf.keras.layers.Dropout(dropout_rate))

        # Output layer
        if model_type == 'regression':
            model.add(tf.keras.layers.Dense(1, activation='linear'))
        else:
            model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

        # Compile the model
        model.compile(optimizer=optimizer_instance, loss=loss_function_to_use, metrics=metrics_to_use)

        # Class Weights for Binary Classification
        class_weights = None
        class_weights_dict = None
        if model_type == 'binary_classification' and class_weights_enabled:

            # Compute class weights
            class_weights = compute_class_weight('balanced', classes=np.unique(y), y=y)

            # Convert the result into a dictionary for use in model.fit()
            class_weights_dict = dict(enumerate(class_weights))
            print("Class Weights:", class_weights_dict)
            


#             y_train_labels = np.argmax(y_train, axis=1) if y_train.ndim > 1 else y_train
#             class_weights = compute_class_weight('balanced', classes=np.unique(y_train_labels), y=y_train_labels)
#             class_weights = dict(enumerate(class_weights))

        # Train the model
        model.fit(
            X_train_scaled, y_train,
            batch_size=batch_size,
            epochs=epochs,
            verbose=0,
            validation_data=(X_test_scaled, y_test),
            callbacks=callbacks,
            class_weight=class_weights_dict
        )

        # Evaluate the model on the test set
        score = model.evaluate(X_test_scaled, y_test, verbose=0)
        y_pred = model.predict(X_test_scaled)

        # Handle metrics based on model type
        if model_type == 'regression':
            residuals = y_test - y_pred.flatten()
            mae_residual = np.mean(np.abs(residuals))
            median_ae_residual = np.median(np.abs(residuals))
            correct_sign_predictions = np.sum(np.sign(y_pred.flatten()) == np.sign(y_test.flatten()))
            sign_accuracy = correct_sign_predictions / len(y_test)

            fold_metrics.append({
                'score': score,
                'mean_absolute_error_residuals': mae_residual,
                'median_absolute_error_residuals': median_ae_residual,
                'sign_accuracy': sign_accuracy
            })            

            
        elif model_type == 'binary_classification':
            
#             y_pred_labels = np.argmax(y_pred, axis=1) if y_pred.ndim > 1 else y_pred
            y_pred_labels = (y_pred >= 0.5).astype(int)
            y_test_labels = np.argmax(y_test, axis=1) if y_test.ndim > 1 else y_test
            
            accuracy = accuracy_score(y_test_labels, y_pred_labels)

            # Compute confusion matrix and metrics
            cm = confusion_matrix(y_test_labels, y_pred_labels)
            TP, FN, FP, TN = cm[0, 0], cm[0, 1], cm[1, 0], cm[1, 1]

            # Calculate precision and recall
            precision = TP / (TP + FP) if (TP + FP) > 0 else 0
            recall = TP / (TP + FN) if (TP + FN) > 0 else 0
            f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
            TP_accuracy = TP / (TP + FP) if (TP + FP) > 0 else 0
            TN_accuracy = TN / (TN + FN) if (TN + FN) > 0 else 0

            fold_metrics.append({
                'accuracy': accuracy,
                'score': score,
                'precision': precision,
                'recall': recall,
                'f1_score': f1_score,
                'TP_accuracy': TP_accuracy,
                'TN_accuracy': TN_accuracy
            })

    # Summarize results
    ave_dict = {
        'avg_score': np.mean([fm['score'] for fm in fold_metrics], axis=0),
        'variance_score': np.var([fm['score'] for fm in fold_metrics], axis=0)
    }

    if model_type == 'regression':
        ave_dict.update({
            'mean_absolute_error_residuals_cv': np.mean([fm['mean_absolute_error_residuals'] for fm in fold_metrics]),
            'median_absolute_error_residuals_cv': np.mean([fm['median_absolute_error_residuals'] for fm in fold_metrics]),
            'avg_sign_accuracy': np.mean([fm['sign_accuracy'] for fm in fold_metrics])
        })

        
    elif model_type == 'binary_classification':
        ave_dict.update({
            'avg_accuracy': np.mean([fm['accuracy'] for fm in fold_metrics], axis=0),
            'avg_precision': np.mean([fm['precision'] for fm in fold_metrics]),
            'avg_recall': np.mean([fm['recall'] for fm in fold_metrics]),
            'avg_f1_score': np.mean([fm['f1_score'] for fm in fold_metrics]),
            'avg_TP_accuracy': np.mean([fm['TP_accuracy'] for fm in fold_metrics]),
            'avg_TN_accuracy': np.mean([fm['TN_accuracy'] for fm in fold_metrics]),
            'avg_TP_TN_accuracy': (np.mean([fm['TP_accuracy'] for fm in fold_metrics]) + np.mean([fm['TN_accuracy'] for fm in fold_metrics]))/2,
            'confusion_matrix': cm
        })

        
    feature_importances_df = pd.DataFrame(feature_importances, columns=[f'Feature_{i}' for i in range(X.shape[1])])

    
    # Use the current model to get the validation results
    validation_results, original_df_wProbabilities = get_validation_success(model_type, original_X, model, scaler, pca_enabled, pca_threshold, pca, outlier_dict, outlier_detection, validation_dict)
    
    
    results_dict = {
        'learning_rate': learning_rate,
        'batch_size': batch_size,
        'optimizer': optimizer,
        'optimizer_name': optimizer_class,
        'optimizer_params': optimizer_params,
        'loss_function': loss_function,
        'loss_function_class': loss_function_class,
        'loss_function_params': loss_function_params,
        'metrics': metrics,
        'epochs': epochs,
        'activation_layers': activation_layers,
        'pca_threshold': pca_threshold,
        'pca': pca_enabled,
        'pca_transform': pca,
        'n_splits': n_splits,
        'class_weights_enabled': class_weights_enabled,
        'outlier_dict': outlier_dict,
        'stratification_enabled': stratification_enabled,
        'lr_schedule_enabled': lr_schedule_enabled,
        'lr_schedule_strategy': lr_schedule_strategy,
        'dropout_enabled': dropout_enabled,
        'dropout_rate': dropout_rate,
        'early_stopping_metric': early_stopping_metric,
        'model': model,
        'scaler': scaler,
        'outlier_detection': outlier_detection,
    }

    for key in ave_dict:
        results_dict[key] = ave_dict[key]

    for key in validation_results:
        results_dict[key] = validation_results[key]

    return results_dict, feature_importances_df, fold_metrics

In [63]:
def iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict):
    
    # create empty list to store results
    results = []
    folds = []
    loop_num = 0
    

    print("class_weights_enabled: %s, stratification_enabled: %s, lr_schedule_enabled: %s, lr_schedule_strategies: %s, dropout_enabled: %s, dropout_rates: %s, early_stopping_metrics: %s, outlier_dicts: %s, activation_layers_list: %s, epochs: %s, loss_functions: %s, optimizers: %s, batch_sizes: %s, learning_rates: %s, pcas: %s, pca_thresholds: %s"%(len(class_weights_enabled), len(stratification_enabled), len(lr_schedule_enabled), len(lr_schedule_strategies), len(dropout_enabled), len(dropout_rates), len(early_stopping_metrics), len(outlier_dicts), len(activation_layers_list), len(epochs), len(loss_functions), len(optimizers), len(batch_sizes), len(learning_rates), len(pcas), len(pca_thresholds)))
    num_iterations = len(stratification_enabled) * len(lr_schedule_enabled) * len(lr_schedule_strategies) * len(dropout_enabled) * len(dropout_rates) * len(early_stopping_metrics) * len(class_weights_enabled) * len(outlier_dicts) * len(activation_layers_list) * len(epochs) * len(loss_functions) * len(optimizers) * len(batch_sizes) * len(learning_rates) * len(pcas) * len(pca_thresholds)

    indices = all_features_df.index

    # perform PCA on predictor variables (optional)
    for pca_on in pcas:

        print('pca-' + str(pca_on))

        if pca_on == False:
            pca_thresholds_checked = [None]
        else:
            pca_thresholds_checked = pca_thresholds

            
        for pca_threshold in pca_thresholds_checked:
            print('  ' + 'pca_thresholds_checked-' + str(pca_threshold))

            # loop through hyperparameters and train and test models
            for lr in learning_rates:
                print('  ' + 'lr-' + str(lr))

                for batch in batch_sizes:
                    print('        ' + 'batch-' + str(batch))

                    for opt in optimizers:
                        print('           ' + 'opt-' + str(opt))

                        for loss in loss_functions:
                            print('              ' + 'loss-' + str(loss))

                            for epoch in epochs:
                                print('                        ' + 'epoch-' + str(epoch))

                                for activation_layers in activation_layers_list:
                                    print('                              ' + 'activation_layer -' + str(activation_layer))

                                    for outlier_dict in outlier_dicts:
                                        print('                                   ' + 'outlier_dict -' + str(outlier_dict))

                                        for cwe in class_weights_enabled:
                                            print('                              ' + 'class_weights_enabled -' + str(cwe))

                                            for strat_enabled in stratification_enabled:
                                                print('                              ' + 'stratification_enabled -' + str(strat_enabled))


                                                for lr_schedule in lr_schedule_enabled:
                                                    print('                              ' + 'lr_schedule_enabled -' + str(lr_schedule))

                                                    # If we aren't using dropout rates then make sure we set the different rates to None so we aren't iterating the same thing
                                                    if lr_schedule == False:
                                                        lr_schedule_strategies_checked = [None]
                                                    else:
                                                        lr_schedule_strategies_checked = lr_schedule_strategies


                                                    for lss in lr_schedule_strategies_checked:
                                                        print('                              ' + 'lr_schedule_strategies -' + str(lss))


                                                        
                                                        for de in dropout_enabled:
                                                            print('                              ' + 'dropout_enabled -' + str(de))


                                                            # If we aren't using dropout rates then make sure we set the different rates to None so we aren't iterating the same thing
                                                            if de == False:
                                                                dropout_rates_checked = [None]
                                                            else:
                                                                dropout_rates_checked = dropout_rates


                                                            for de_rate in dropout_rates_checked:
                                                                print('                              ' + 'dropout_rates -' + str(de_rate))


                                                                for esm in early_stopping_metrics:
                                                                    print('                              ' + 'early_stopping_metric -' + str(esm))


                                                                    loop_num = loop_num + 1
                                                                    print(loop_num, num_iterations)


                                                                    result, feature_importances_df, fold_metrics = run_experiment(model_type, pca_on, pca_threshold, X, y, lr, batch, opt, loss, metrics, epoch, activation_layers, n_splits, cwe, outlier_dict = outlier_dict, stratification_enabled = strat_enabled, lr_schedule_enabled = lr_schedule, lr_schedule_strategy = lss, dropout_enabled = de, dropout_rate = de_rate, early_stopping_metric = esm, validation_dict = validation_dict)
                                                                    results.append(result)
                                                                    folds.append(fold_metrics)
    #                                                                 print(result)

                                                                    results_df = pd.DataFrame(results)
                                                                    folds_df = pd.DataFrame(folds)

                                                                    print('')
                                                                    print('-------------------------')
                                                                    print(results_df.sort_values(model_ass_val, ascending = model_ass_val_direction)[:10])

                                                                
    # Only exports the latest feature importances with model and scaler
    return results_df, folds_df, feature_importances_df

# Parameters

In [64]:
all_optimizers = [
    # Adam optimizer with default options
    (tf.keras.optimizers.Adam, {
        "beta_1": 0.9,        # Default
        "beta_2": 0.999,      # Default
        "epsilon": 1e-07,     # Default
        "amsgrad": False      # AMSGrad variant
    }),
    
    # Adam optimizer with more aggressive updates
    (tf.keras.optimizers.Adam, {
        "beta_1": 0.85,       # More responsive to recent gradients
        "beta_2": 0.95,       # Slightly less smooth estimates
        "epsilon": 1e-08,     # For higher precision
        "amsgrad": False
    }),
    
    # Adam optimizer with more stability
    (tf.keras.optimizers.Adam, {
        "beta_1": 0.99,       # Smoother updates
        "beta_2": 0.9995,     # More stable estimates
        "epsilon": 1e-06,     # For stability with small gradients
        "amsgrad": False
    }),
    
    # RMSprop optimizer with default options
    (tf.keras.optimizers.RMSprop, {
        "rho": 0.9,          # Default
        "momentum": 0.0,     # Default
        "epsilon": 1e-07,    # Default
        "centered": False   # Default
    }),
    
    # RMSprop optimizer with different settings
    (tf.keras.optimizers.RMSprop, {
        "rho": 0.8,          # Lower rho for more responsiveness
        "momentum": 0.1,     # Slightly higher momentum
        "epsilon": 1e-08,    # For higher precision
        "centered": True    # Centered RMSProp
    }),
    
    # SGD optimizer with momentum
    (tf.keras.optimizers.SGD, {
        "momentum": 0.9,     # Default
        "nesterov": True    # Default
    }),
    
    # SGD optimizer with different settings
    (tf.keras.optimizers.SGD, {
        "momentum": 0.5,     # Lower momentum
        "nesterov": False   # Standard SGD
    }),
    
    # Nadam optimizer
    (tf.keras.optimizers.Nadam, {
        "beta_1": 0.9,      # Default
        "beta_2": 0.999,    # Default
        "epsilon": 1e-07    # Default
    }),
    
    # Nadam optimizer with different settings
    (tf.keras.optimizers.Nadam, {
        "beta_1": 0.85,     # More responsive
        "beta_2": 0.95,     # Less smooth
        "epsilon": 1e-08    # For higher precision
    }),
    
    # Adadelta optimizer
    (tf.keras.optimizers.Adadelta, {
        "rho": 0.95,         # Default
        "epsilon": 1e-07     # Default
    }),
    
    # Adadelta optimizer with different settings
    (tf.keras.optimizers.Adadelta, {
        "rho": 0.9,          # Slightly lower rho
        "epsilon": 1e-08     # For higher precision
    }),
    
    # Adagrad optimizer
    (tf.keras.optimizers.Adagrad, {
        "initial_accumulator_value": 0.1, # Default
        "epsilon": 1e-07   # Default
    }),
    
    # Adagrad optimizer with different settings
    (tf.keras.optimizers.Adagrad, {
        "initial_accumulator_value": 0.01, # Lower initial accumulator value
        "epsilon": 1e-08   # For higher precision
    }),
    
    # Adamax optimizer
    (tf.keras.optimizers.Adamax, {
        "beta_1": 0.9,      # Default
        "beta_2": 0.999,    # Default
        "epsilon": 1e-07    # Default
    }),
    
    # Adamax optimizer with different settings
    (tf.keras.optimizers.Adamax, {
        "beta_1": 0.85,     # More responsive
        "beta_2": 0.95,     # Less smooth
        "epsilon": 1e-08    # For higher precision
    }),
    
    # Ftrl optimizer
    (tf.keras.optimizers.Ftrl, {
        "learning_rate_power": -0.5,     # Default
        "initial_accumulator_value": 0.1, # Default
        "l1_regularization_strength": 0.0, # Default
        "l2_regularization_strength": 0.0  # Default
    }),
    
    # Ftrl optimizer with different settings
    (tf.keras.optimizers.Ftrl, {
        "learning_rate_power": -0.5,     # Default
        "initial_accumulator_value": 0.05, # Lower initial accumulator value
        "l1_regularization_strength": 0.01, # Some regularization
        "l2_regularization_strength": 0.01  # Some regularization
    })
]

In [65]:
# if model_type == 'regression':
#     all_loss_functions = [
#         tf.keras.losses.MeanSquaredError(reduction='auto'),         # Suitable for continuous regression
#         tf.keras.losses.MeanAbsoluteError(reduction='auto'),        # Good for less sensitive error measurement
#         tf.keras.losses.MeanAbsolutePercentageError(reduction='auto'), # Useful when relative error matters
#         tf.keras.losses.MeanSquaredLogarithmicError(reduction='auto'), # For handling smaller values in the dataset
#         tf.keras.losses.Huber(reduction='auto'),                    # Combines advantages of MSE and MAE, robust to outliers
#         tf.keras.losses.LogCosh(reduction='auto')                    # Smooth approximation to MAE, often used in regression
#     ]

# elif model_type == 'binary_classification':
#     all_loss_functions = [
#         tf.keras.losses.CategoricalCrossentropy(reduction='auto'),
#     #     tf.keras.losses.SparseCategoricalCrossentropy(reduction='auto'),
#         tf.keras.losses.BinaryCrossentropy(reduction='auto'),
#         tf.keras.losses.KLDivergence(reduction='auto'),
#         tf.keras.losses.CosineSimilarity(reduction='auto'),
#         tf.keras.losses.Poisson(reduction='auto'),
#         tf.keras.losses.Hinge(reduction='auto'),
#         tf.keras.losses.CategoricalHinge(reduction='auto')]

In [66]:
if model_type == 'regression':
    all_loss_functions = [
        (tf.keras.losses.MeanSquaredError, {'reduction':'auto'}),         # Suitable for continuous regression
        (tf.keras.losses.MeanAbsoluteError, {'reduction':'auto'}),        # Good for less sensitive error measurement
        (tf.keras.losses.MeanAbsolutePercentageError, {'reduction':'auto'}), # Useful when relative error matters
        (tf.keras.losses.MeanSquaredLogarithmicError, {'reduction':'auto'}), # For handling smaller values in the dataset
        (tf.keras.losses.Huber, {'reduction':'auto'}),                    # Combines advantages of MSE and MAE, robust to outliers
        (tf.keras.losses.LogCosh, {'reduction':'auto'})                    # Smooth approximation to MAE, often used in regression
    ]

elif model_type == 'binary_classification':
    all_loss_functions = [
#         (tf.keras.losses.CategoricalCrossentropy, {'reduction':'auto'}),
    #     tf.keras.losses.SparseCategoricalCrossentropy, {'reduction':'auto'}),
        (tf.keras.losses.BinaryCrossentropy, {'reduction':'auto'}),
        (tf.keras.losses.KLDivergence, {'reduction':'auto'}),
#         (tf.keras.losses.CosineSimilarity, {'reduction':'auto'}),
        (tf.keras.losses.Poisson, {'reduction':'auto'}),
        (tf.keras.losses.Hinge, {'reduction':'auto'}),
#         (tf.keras.losses.CategoricalHinge, {'reduction':'auto'})
    ]

In [67]:
def replace_df_objects_with_functions(value_to_check):
    
    if pd.isna(value_to_check):  # Check for NaN
        return value_to_check
    
    # Replace activation functions
    if 'swish' in value_to_check:
        value_to_check = re.sub(r"<function swish at [^>]+>", 'tf.keras.activations.swish', value_to_check)
    if 'silu' in value_to_check:
        value_to_check = re.sub(r"<function silu at [^>]+>", 'tf.keras.activations.swish', value_to_check)
    if 'gelu' in value_to_check:
        value_to_check = re.sub(r"<function gelu at [^>]+>", 'tf.keras.activations.gelu', value_to_check)


    # Replace optimizers
    optimizer_replacements = {
        r"<class 'keras.src.optimizers.adam.Adam'>": 'tf.keras.optimizers.Adam',
        r"<class 'keras.optimizers.optimizer_experimental.adam.Adam'>": 'tf.keras.optimizers.Adam',
        r"<class 'keras.src.optimizers.rmsprop.RMSprop'>": 'tf.keras.optimizers.RMSprop',
        r"<class 'keras.src.optimizers.nadam.Nadam'>": 'tf.keras.optimizers.Nadam',
        r"<class 'keras.src.optimizers.adadelta.Adadelta'>": 'tf.keras.optimizers.Adadelta',
        r"<class 'keras.src.optimizers.adagrad.Adagrad'>": 'tf.keras.optimizers.Adagrad',
        r"<class 'keras.src.optimizers.adamax.Adamax'>": 'tf.keras.optimizers.Adamax',
        r"<class 'keras.optimizers.optimizer_experimental.adamax.Adamax'>": 'tf.keras.optimizers.Adamax',
        r"<class 'keras.src.optimizers.ftrl.Ftrl'>": 'tf.keras.optimizers.Ftrl',
        r"<class 'keras.optimizers.optimizer_experimental.sgd.SGD'>":'tf.keras.optimizers.SGD',
        r"<class 'keras.src.optimizers.sgd.SGD'>":'tf.keras.optimizers.SGD'
    }
    
    
    for pattern, replacement in optimizer_replacements.items():
        value_to_check = re.sub(pattern, replacement, value_to_check)

    # Replace loss functions
    loss_replacements = {
        r"<class 'keras.src.losses.MeanSquaredError'>": 'tf.keras.losses.MeanSquaredError',
        r"<class 'keras.src.losses.MeanAbsoluteError'>": 'tf.keras.losses.MeanAbsoluteError',
        r"<class 'keras.losses.MeanAbsoluteError'>": 'tf.keras.losses.MeanAbsoluteError',
        r"<class 'keras.losses.MeanSquaredError'>": 'tf.keras.losses.MeanAbsoluteError',
        r"<class 'keras.src.losses.MeanAbsolutePercentageError'>": 'tf.keras.losses.MeanAbsolutePercentageError',
        r"<class 'keras.src.losses.MeanSquaredLogarithmicError'>": 'tf.keras.losses.MeanSquaredLogarithmicError',
        r"<class 'keras.losses.MeanSquaredLogarithmicError'>": 'tf.keras.losses.MeanSquaredLogarithmicError',
        r"<class 'keras.src.losses.Huber'>": 'tf.keras.losses.Huber',
        r"<class 'keras.losses.Huber'>": 'tf.keras.losses.Huber',
        r"<class 'keras.src.losses.LogCosh'>": 'tf.keras.losses.LogCosh',
        r"<class 'keras.losses.LogCosh'>": 'tf.keras.losses.LogCosh',
        r"<class 'keras.src.losses.CategoricalCrossentropy'>": 'tf.keras.losses.CategoricalCrossentropy',
        r"<class 'keras.src.losses.BinaryCrossentropy'>": 'tf.keras.losses.BinaryCrossentropy',
        r"<class 'keras.losses.BinaryCrossentropy'>": 'tf.keras.losses.BinaryCrossentropy',
        r"<class 'keras.src.losses.losses.BinaryCrossentropy'>": 'tf.keras.losses.BinaryCrossentropy',
        r"<class 'keras.src.losses.KLDivergence'>": 'tf.keras.losses.KLDivergence',
        r"<class 'keras.src.losses.CosineSimilarity'>": 'tf.keras.losses.CosineSimilarity',
        r"<class 'keras.src.losses.Poisson'>": 'tf.keras.losses.Poisson',
        r"<class 'keras.losses.Poisson'>": 'tf.keras.losses.Poisson',
        r"<class 'keras.src.losses.losses.Poisson'>": 'tf.keras.losses.Poisson',
        r"<class 'keras.src.losses.Hinge'>": 'tf.keras.losses.Hinge',
        r"<class 'keras.src.losses.CategoricalHinge'>": 'tf.keras.losses.CategoricalHinge',
    }
    
    
    
    
    
    for pattern, replacement in loss_replacements.items():
        value_to_check = re.sub(pattern, replacement, value_to_check)
        
        
    if '<function exponential_decay_95' in value_to_check:
        value_to_check = re.sub(r"<function exponential_decay_95 at [^>]+>", 'exponential_decay_95', value_to_check)
    if '<function exponential_decay_90' in value_to_check:
        value_to_check = re.sub(r"<function exponential_decay_90 at [^>]+>", 'exponential_decay_90', value_to_check)
    if '<function exponential_decay_85' in value_to_check:
        value_to_check = re.sub(r"<function exponential_decay_85 at [^>]+>", 'exponential_decay_85', value_to_check)
    if '<function exponential_decay_80' in value_to_check:
        value_to_check = re.sub(r"<function exponential_decay_80 at [^>]+>", 'exponential_decay_80', value_to_check)

    if '<function step_decay_50_10' in value_to_check:
        value_to_check = re.sub(r"<function step_decay_50_10 at [^>]+>", 'step_decay_50_10', value_to_check)
    if '<function step_decay_30_10' in value_to_check:
        value_to_check = re.sub(r"<function step_decay_30_10 at [^>]+>", 'step_decay_30_10', value_to_check)
    if '<function step_decay_50_5' in value_to_check:
        value_to_check = re.sub(r"<function step_decay_50_5 at [^>]+>", 'step_decay_50_5', value_to_check)
    if '<function step_decay_70_10' in value_to_check:
        value_to_check = re.sub(r"<function step_decay_70_10 at [^>]+>", 'step_decay_70_10', value_to_check)

    if '<function time_based_decay_1e4' in value_to_check:
        value_to_check = re.sub(r"<function time_based_decay_1e4 at [^>]+>", 'time_based_decay_1e4', value_to_check)
    if '<function time_based_decay_1e5' in value_to_check:
        value_to_check = re.sub(r"<function time_based_decay_1e5 at [^>]+>", 'time_based_decay_1e5', value_to_check)
    if '<function time_based_decay_5e4' in value_to_check:
        value_to_check = re.sub(r"<function time_based_decay_5e4 at [^>]+>", 'time_based_decay_5e4', value_to_check)
    if '<function time_based_decay_2e4' in value_to_check:
        value_to_check = re.sub(r"<function time_based_decay_2e4 at [^>]+>", 'time_based_decay_2e4', value_to_check)

    if '<function cosine_annealing_30' in value_to_check:
        value_to_check = re.sub(r"<function cosine_annealing_30 at [^>]+>", 'cosine_annealing_30', value_to_check)
    if '<function cosine_annealing_50' in value_to_check:
        value_to_check = re.sub(r"<function cosine_annealing_50 at [^>]+>", 'cosine_annealing_50', value_to_check)
    if '<function cosine_annealing_10' in value_to_check:
        value_to_check = re.sub(r"<function cosine_annealing_10 at [^>]+>", 'cosine_annealing_10', value_to_check)
    if '<function cosine_annealing_20' in value_to_check:
        value_to_check = re.sub(r"<function cosine_annealing_20 at [^>]+>", 'cosine_annealing_20', value_to_check)

    if '<function reduce_lr_50_5' in value_to_check:
        value_to_check = re.sub(r"<function reduce_lr_50_5 at [^>]+>", 'reduce_lr_50_5', value_to_check)
    if '<function reduce_lr_30_5' in value_to_check:
        value_to_check = re.sub(r"<function reduce_lr_30_5 at [^>]+>", 'reduce_lr_30_5', value_to_check)
    if '<function reduce_lr_50_10' in value_to_check:
        value_to_check = re.sub(r"<function reduce_lr_50_10 at [^>]+>", 'reduce_lr_50_10', value_to_check)
    if '<function reduce_lr_70_5' in value_to_check:
        value_to_check = re.sub(r"<function reduce_lr_70_5 at [^>]+>", 'reduce_lr_70_5', value_to_check)
        
        
    if 'Reduce on Plateau 50%, patience 5' in value_to_check:
        value_to_check = re.sub(r"{'method': <keras.src.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_50_5, 'description': 'Reduce on Plateau 50%, patience 5'}", value_to_check)
        value_to_check = re.sub(r"{'method': <keras.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_50_5, 'description': 'Reduce on Plateau 50%, patience 5'}", value_to_check)
    if 'Reduce on Plateau 30%, patience 5' in value_to_check:
        value_to_check = re.sub(r"{'method': <keras.src.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_30_5, 'description': 'Reduce on Plateau 30%, patience 5'}", value_to_check)
        value_to_check = re.sub(r"{'method': <keras.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_30_5, 'description': 'Reduce on Plateau 30%, patience 5'}", value_to_check)
    if 'Reduce on Plateau 50%, patience 10' in value_to_check:
        value_to_check = re.sub(r"{'method': <keras.src.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_50_10, 'description': 'Reduce on Plateau 50%, patience 10'}", value_to_check)
        value_to_check = re.sub(r"{'method': <keras.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_50_10, 'description': 'Reduce on Plateau 50%, patience 10'}", value_to_check)
    if 'Reduce on Plateau 70%, patience 5' in value_to_check:
        value_to_check = re.sub(r"{'method': <keras.src.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_70_5, 'description': 'Reduce on Plateau 70%, patience 5'}", value_to_check)
        value_to_check = re.sub(r"{'method': <keras.callbacks.ReduceLROnPlateau [^}]+}", "{'method': reduce_lr_70_5, 'description': 'Reduce on Plateau 70%, patience 5'}", value_to_check)
        
        
    return value_to_check

In [68]:
def make_serializable(obj):
    if isinstance(obj, (int, float, str, bool, list, dict)):
        return obj
    else:
        return str(obj)  # Convert non-serializable objects to strings

In [69]:
# Define each learning rate schedule with multiple variations

# 1. Exponential Decay: Trying different decay rates
def exponential_decay_95(epoch, lr): return lr * 0.95  # 5% reduction per epoch
def exponential_decay_90(epoch, lr): return lr * 0.90  # 10% reduction per epoch
def exponential_decay_85(epoch, lr): return lr * 0.85  # 15% reduction per epoch
def exponential_decay_80(epoch, lr): return lr * 0.80  # 20% reduction per epoch

# 2. Step Decay: Varying the drop rate and interval
def step_decay_50_10(epoch, lr):
    drop_rate = 0.5
    drop_every = 10
    return lr * drop_rate if epoch % drop_every == 0 else lr

def step_decay_30_10(epoch, lr):
    drop_rate = 0.3
    drop_every = 10
    return lr * drop_rate if epoch % drop_every == 0 else lr

def step_decay_50_5(epoch, lr):
    drop_rate = 0.5
    drop_every = 5
    return lr * drop_rate if epoch % drop_every == 0 else lr

def step_decay_70_10(epoch, lr):
    drop_rate = 0.7
    drop_every = 10
    return lr * drop_rate if epoch % drop_every == 0 else lr

# 3. Time-Based Decay: Trying different decay rates
def time_based_decay_1e4(epoch, lr): return lr / (1 + 1e-4 * epoch)
def time_based_decay_1e5(epoch, lr): return lr / (1 + 1e-5 * epoch)
def time_based_decay_5e4(epoch, lr): return lr / (1 + 5e-4 * epoch)
def time_based_decay_2e4(epoch, lr): return lr / (1 + 2e-4 * epoch)

# 4. Cosine Annealing: Different cycles and minimum learning rates
def cosine_annealing_30(epoch, lr):
    min_lr = 1e-5
    max_lr = lr
    return min_lr + 0.5 * (max_lr - min_lr) * (1 + np.cos(np.pi * epoch / 30))

def cosine_annealing_50(epoch, lr):
    min_lr = 1e-5
    max_lr = lr
    return min_lr + 0.5 * (max_lr - min_lr) * (1 + np.cos(np.pi * epoch / 50))

def cosine_annealing_10(epoch, lr):
    min_lr = 1e-5
    max_lr = lr
    return min_lr + 0.5 * (max_lr - min_lr) * (1 + np.cos(np.pi * epoch / 10))

def cosine_annealing_20(epoch, lr):
    min_lr = 1e-5
    max_lr = lr
    return min_lr + 0.5 * (max_lr - min_lr) * (1 + np.cos(np.pi * epoch / 20))

# 5. Reduce on Plateau: Trying different patience and reduction factors
reduce_lr_50_5 = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-5)
reduce_lr_30_5 = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=5, min_lr=1e-5)
reduce_lr_50_10 = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-5)
reduce_lr_70_5 = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.7, patience=5, min_lr=1e-5)

# Collect all learning rate schedules with variations
all_lr_schedule_strategies = [
    # Exponential Decay variations
    {'method': exponential_decay_95, 'description': "Exponential Decay 5%"},
    {'method': exponential_decay_90, 'description': "Exponential Decay 10%"},
    {'method': exponential_decay_85, 'description': "Exponential Decay 15%"},
    {'method': exponential_decay_80, 'description': "Exponential Decay 20%"},
    
    # Step Decay variations
    {'method': step_decay_50_10, 'description': "Step Decay 50% every 10 epochs"},
    {'method': step_decay_30_10, 'description': "Step Decay 30% every 10 epochs"},
    {'method': step_decay_50_5, 'description': "Step Decay 50% every 5 epochs"},
    {'method': step_decay_70_10, 'description': "Step Decay 70% every 10 epochs"},
    
    # Time-Based Decay variations
    {'method': time_based_decay_1e4, 'description': "Time-Based Decay 1e-4"},
    {'method': time_based_decay_1e5, 'description': "Time-Based Decay 1e-5"},
    {'method': time_based_decay_5e4, 'description': "Time-Based Decay 5e-4"},
    {'method': time_based_decay_2e4, 'description': "Time-Based Decay 2e-4"},
    
    # Cosine Annealing variations
    {'method': cosine_annealing_30, 'description': "Cosine Annealing with 30 epochs cycle"},
    {'method': cosine_annealing_50, 'description': "Cosine Annealing with 50 epochs cycle"},
    {'method': cosine_annealing_10, 'description': "Cosine Annealing with 10 epochs cycle"},
    {'method': cosine_annealing_20, 'description': "Cosine Annealing with 20 epochs cycle"},
    
    # Reduce on Plateau variations
    {'method': reduce_lr_50_5, 'description': "Reduce on Plateau 50%, patience 5"},
    {'method': reduce_lr_30_5, 'description': "Reduce on Plateau 30%, patience 5"},
    {'method': reduce_lr_50_10, 'description': "Reduce on Plateau 50%, patience 10"},
    {'method': reduce_lr_70_5, 'description': "Reduce on Plateau 70%, patience 5"}
]

In [70]:
def find_optimal_general_parameters(optimal_iterations, model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict):

    optimal_parameters_df = pd.DataFrame()

    for loop_num in range(0, optimal_iterations):
        
        print("'''''''' Getting optimal parameters ''''''''")
        print("''''''''", optimal_iterations)
        print('')

        
        print("'''''''' pcas")
        pcas = all_pcas
        pca_thresholds = all_pca_thresholds
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        pcas = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['pca']]
        pca_thresholds = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['pca_threshold']]
        print('pcas Selected - ', pcas)
        print('pca_thresholds Selected - ', pca_thresholds)
        print('')
        

        print("'''''''' LR & BS")
        learning_rates = all_learning_rates
        batch_sizes = all_batch_sizes
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        top_model = all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]
        batch_sizes = [top_model['batch_size']]
        learning_rates = [top_model['learning_rate']]
        print('BS Selected - ', batch_sizes)
        print('LR Selected - ', learning_rates)
        print('')


        print("'''''''' optimizers")
        # Now we have batch size and learning rates, lets get the best optimizers - top 2
#         optimizers = all_optimizers
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        optimizers = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['optimizer'], all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[1]['optimizer']]
        if optimizers[0] ==  optimizers[1]:
            optimizers = [optimizers[0]]
        print('optimizers Selected - ', optimizers)
        print('')

            
        print("'''''''' loss_functions")
        # Now add best 2 loss functions
        loss_functions = all_loss_functions
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        loss_functions = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['loss_function'], all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[1]['loss_function']]
        if loss_functions[0] ==  loss_functions[1]:
            loss_functions = [loss_functions[0]]
        print('loss_functions Selected - ', loss_functions)
        print('')

            

        print("'''''''' class_weights_enabled")
        class_weights_enabled = [True, False]
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        class_weights_enabled = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['class_weights_enabled']]
        print('class_weights_enabled Selected - ', class_weights_enabled)
        print('')
        
        
        
        print("'''''''' stratification_enabled")
        if model_type == 'binary_classification':
            stratification_enabled = [True, False]
            all_results_df = pd.DataFrame()
            for x in range(0,2):
                results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
                all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
            optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
            stratification_enabled = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['stratification_enabled']]
            print('stratification_enabled Selected - ', stratification_enabled)
            print('')

        
        
        print("'''''''' dropout_enabled")
        dropout_enabled = [False, True]
        dropout_rates = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 0.9]
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        dropout_enabled = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['dropout_enabled']]
        dropout_rates = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['dropout_rate']]
        print('dropout_enabled Selected - ', dropout_enabled)
        print('dropout_rates Selected - ', dropout_rates)
        print('')

        
        
        print("'''''''' early_stopping_metrics")
        early_stopping_metrics = all_early_stopping_metrics
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        early_stopping_metrics = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['early_stopping_metric']]
        print('early_stopping_metrics Selected - ', early_stopping_metrics)
        print('')

        
        
        print("'''''''' outlier_dicts")
        outlier_dicts = all_outlier_dicts
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        outlier_dicts = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['outlier_dict']]
        print('outlier_dicts Selected - ', outlier_dicts)
        print('')


        model_to_use = optimal_parameters_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0].to_dict()
        
        
        # Use just the top metrics
        print("'''''''' lr_schedule_enabled")
        lr_schedule_enabled = [True, False]
        lr_schedule_strategies = all_lr_schedule_strategies
        all_results_df = pd.DataFrame()
        for x in range(0,2):
            results_df, folds_df, feature_importances_df = iterate_through_model_variations(model_ass_val, model_ass_val_direction, [model_to_use['pca']], [model_to_use['pca_threshold']], [model_to_use['learning_rate']], [model_to_use['batch_size']], [model_to_use['optimizer']], [model_to_use['loss_function']], metrics, epochs, [model_to_use['activation_layers']], n_splits, [model_to_use['class_weights_enabled']], [model_to_use['outlier_dict']], [model_to_use['stratification_enabled']], lr_schedule_enabled, lr_schedule_strategies, [model_to_use['dropout_enabled']], [model_to_use['dropout_rate']], [model_to_use['early_stopping_metric']], validation_dict = validation_dict)
            all_results_df = pd.concat([all_results_df, results_df], ignore_index = True)
        optimal_parameters_df = pd.concat([optimal_parameters_df, all_results_df], ignore_index = True)
        lr_schedule_enabled = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['lr_schedule_enabled']]
        lr_schedule_strategies = [all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0]['lr_schedule_strategy']]
        print('lr_schedule_enabled Selected - ', lr_schedule_enabled)
        print('lr_schedule_strategies Selected - ', lr_schedule_strategies)
        print('')
        
        top_model = all_results_df.sort_values(model_ass_val, ascending = model_ass_val_direction).iloc[0].to_dict()
        
        
        return top_model, optimal_parameters_df

In [71]:
def get_validation_success(model_type, original_X, model, scaler_to_use, pca_enabled, pca_threshold, pca_transform, outlier_dict, outlier_detection, validation_dict):
    
    validation_range_column = validation_dict['validation_range_column']
    validation_start_range = validation_dict['validation_start_range']
    validation_end_range = validation_dict['validation_end_range']
    train_start_range = validation_dict['train_start_range']
    validation_comparison_column = validation_dict['validation_comparison_column']
    validation_success_column = validation_dict['validation_success_column']
    validation_agg_type = validation_dict['validation_agg_type']
    
    model_success_direction_asc = validation_dict['model_success_direction_asc']
        
    
    original_X_columns = original_X.columns
    original_df_to_use = original_df.copy()
    
    
    validation_results = dict()
    
    # Get the validation data
    test_data = original_df_to_use[original_X_columns]

    
    # Apply PCA if enabled
    if pca_enabled and pd.notna(pca_threshold):
        test_data = pca_transform.transform(test_data)
        
        
    # Need to see if we add an outlier column before making out predictions
    outlier_enabled = outlier_dict.get('enabled', False) if outlier_dict else False
    remove_outliers = outlier_dict.get('remove_outliers', False) if outlier_enabled else False

    # Outlier Detection
    if outlier_enabled & (remove_outliers == False):
        outlier_flags = outlier_detection.predict(test_data)  # -1 for outliers, 1 for inliers
        outlier_flags = np.where(outlier_flags == -1, 1, 0)  # 1 is an outlier, 0 is an inlier
        test_data = np.column_stack((test_data, outlier_flags))  # Append the outlier flag as a new feature


    # Eemember to scale
    test_data = scaler_to_use.transform(test_data)
    
    if model_type == 'binary_classification':

        # Now predict witht the current model
        original_df_to_use['prediction'] = model.predict(test_data)

        original_df_to_use['predicted_winner'] = original_df_to_use['prediction'].apply(lambda x: 1 if x >= 0.5 else 0)
        original_df_to_use['predicted_success'] = original_df_to_use[[response_variable_name, 'predicted_winner']].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else 1 if x[0] == x[1] else 0, axis = 1)

        # Train Results
        validation_df = original_df_to_use.loc[original_X.index]
        validation_results['validation_training_success'] = validation_df['predicted_success'].mean()
        
        if validation_comparison_column is not None:
            
            if model_success_direction_asc == True:
                
                if validation_agg_type == 'mean':
                    validation_results['validation_training_improvement'] = (validation_df[validation_comparison_column].mean() - validation_df[validation_success_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_training_improvement'] = (validation_df[validation_comparison_column].median() - validation_df[validation_success_column].median()) / validation_df[validation_comparison_column].median()

            else:
                
                if validation_agg_type == 'mean':
                    validation_results['validation_training_improvement'] = (validation_df[validation_success_column].mean() - validation_df[validation_comparison_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_training_improvement'] = (validation_df[validation_success_column].median() - validation_df[validation_comparison_column].median()) / validation_df[validation_comparison_column].median()

        else:
            validation_results['validation_training_improvement'] = None
        
        print('Training: Improvement: %s, Original: %s, New: %s'%(validation_results['validation_training_improvement'], validation_df[validation_comparison_column].mean(), validation_df[validation_success_column].mean()))

        # Test Results
        
        validation_df = original_df_to_use[(original_df_to_use[validation_range_column] >= (validation_start_range)) & (original_df_to_use[validation_range_column] < (validation_end_range))]
        validation_results['validation_test_success'] = validation_df['predicted_success'].mean()

        if validation_comparison_column is not None:

            if model_success_direction_asc == True:
                
                if validation_agg_type == 'mean':
                    validation_results['validation_test_improvement'] = (validation_df[validation_comparison_column].mean() - validation_df[validation_success_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_test_improvement'] = (validation_df[validation_comparison_column].median() - validation_df[validation_success_column].median()) / validation_df[validation_comparison_column].median()

            else:
                
                if validation_agg_type == 'mean':
                    validation_results['validation_test_improvement'] = (validation_df[validation_success_column].mean() - validation_df[validation_comparison_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_test_improvement'] = (validation_df[validation_success_column].median() - validation_df[validation_comparison_column].median()) / validation_df[validation_comparison_column].median()

            validation_results['validation_avg_train_test_improvement'] = (validation_results['validation_test_improvement'] + validation_results['validation_training_improvement']) / 2
            validation_results['validation_train_test_harmonic_mean'] = 2 * ((validation_results['validation_test_improvement'] * validation_results['validation_training_improvement']) / (validation_results['validation_test_improvement'] + validation_results['validation_training_improvement']))
            if (validation_results['validation_test_improvement'] < 0) & (validation_results['validation_training_improvement'] < 0):
                validation_results['validation_train_test_geometric_mean'] = None
            else:
                validation_results['validation_train_test_geometric_mean'] = np.sqrt((validation_results['validation_test_improvement'] * validation_results['validation_training_improvement']))
        else:
            validation_results['validation_test_improvement'] = None

        print('Test: Improvement: %s, Original: %s, New: %s'%(validation_results['validation_test_improvement'], validation_df[validation_comparison_column].mean(), validation_df[validation_success_column].mean()))

    elif model_type == 'regression':
        
        original_df_to_use['prediction'] = model.predict(test_data)
        
        # If transformed then transform back
        if transform_target == 'tan':
            temp_df = original_df_to_use.loc[original_X.index]
            # Original mean and standard deviation of the win margin
            mean = temp_df[response_variable_name].mean()
            std = temp_df[response_variable_name].std()

            # Assuming `predicted_transformed_margin` contains your model's predictions
            predicted_normalized_margin = np.arctanh( original_df_to_use['prediction'])
            print(predicted_normalized_margin)

            # De-normalize to get the original win margin scale
            original_df_to_use['prediction'] = (predicted_normalized_margin * std) + mean

        if transform_target == 'sqrt':

            original_df_to_use['prediction_sign'] = original_df_to_use['prediction'].apply(lambda x: -1 if x < 0 else 1)
            original_df_to_use['prediction'] = original_df_to_use['prediction'] * original_df_to_use['prediction'] * original_df_to_use['prediction_sign']
#             original_df_to_use['prediction'] = original_df_to_use[['prediction', 'prediction_sign']].apply(lambda x: np.power(abs(x[0]), 4/3) * x[1], axis = 1)
        
        elif transform_target == 'power_34':

            original_df_to_use['prediction_sign'] = original_df_to_use['prediction'].apply(lambda x: -1 if x < 0 else 1)
            original_df_to_use['prediction'] = original_df_to_use[['prediction', 'prediction_sign']].apply(lambda x: np.power(abs(x[0]), 4/3) * x[1], axis = 1)




#         print(mean, std, original_df_to_use[['prediction', response_variable_name]])
            
        original_df_to_use['prediction_error'] = original_df_to_use[['prediction', response_variable_name]].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else x[0] - x[1], axis = 1)
        original_df_to_use['prediction_error_abs'] = abs(original_df_to_use['prediction_error'])
        original_df_to_use['prediction_sign_success'] = original_df_to_use[['prediction', response_variable_name]].apply(lambda x: None if pd.isna(x[0]) | pd.isna(x[1]) else 1 if ((x[0] > 0) & (x[1] > 0)) | ((x[0] < 0) & (x[1] < 0)) else 0, axis = 1)

        # Training Results
        validation_df = original_df_to_use.loc[original_X.index]

        validation_results['validation_train_error_mean'] = validation_df['prediction_error'].mean()
        validation_results['validation_train_error_median'] = validation_df['prediction_error'].median()
        validation_results['validation_train_error_std'] = validation_df['prediction_error'].std()
        
        validation_results['validation_train_abserror_mean'] = validation_df['prediction_error_abs'].mean()
        validation_results['validation_train_abserror_median'] = validation_df['prediction_error_abs'].median()
        validation_results['validation_train_abserror_std'] = validation_df['prediction_error_abs'].std()
        
        validation_results['validation_training_success'] = validation_df['prediction_sign_success'].mean()
        
        if validation_comparison_column is not None:
            
            if model_success_direction_asc == True:
                
                if validation_agg_type == 'mean':
                    validation_results['validation_training_improvement'] = (validation_df[validation_comparison_column].mean() - validation_df[validation_success_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_training_improvement'] = (validation_df[validation_comparison_column].median() - validation_df[validation_success_column].median()) / validation_df[validation_comparison_column].median()

            else:
                
                if validation_agg_type == 'mean':
                    validation_results['validation_training_improvement'] = (validation_df[validation_success_column].mean() - validation_df[validation_comparison_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_training_improvement'] = (validation_df[validation_success_column].median() - validation_df[validation_comparison_column].median()) / validation_df[validation_comparison_column].median()

        else:
            validation_results['validation_training_improvement'] = None

#         print('Training: Improvement: %s, Original: %s, New: %s'%(validation_results['validation_training_improvement'], validation_df[validation_comparison_column].mean(), validation_df[validation_success_column].mean()))
        print('Training: Improvement: %s, Original: %s, New: %s'%(validation_results['validation_training_improvement'], validation_df[validation_comparison_column].median(), validation_df[validation_success_column].median()))

        
        # Test Results
        validation_df = original_df_to_use[(original_df_to_use[validation_range_column] >= (validation_start_range)) & (original_df_to_use[validation_range_column] < (validation_end_range))]

        validation_results['validation_test_error_mean'] = validation_df['prediction_error'].mean()
        validation_results['validation_test_error_median'] = validation_df['prediction_error'].median()
        validation_results['validation_test_error_std'] = validation_df['prediction_error'].std()
        
        validation_results['validation_test_abserror_mean'] = validation_df['prediction_error_abs'].mean()
        validation_results['validation_test_abserror_median'] = validation_df['prediction_error_abs'].median()
        validation_results['validation_test_abserror_std'] = validation_df['prediction_error_abs'].std()
        
        validation_results['validation_test_success'] = validation_df['prediction_sign_success'].mean()

        if validation_comparison_column is not None:
            
            if model_success_direction_asc == True:

                if validation_agg_type == 'mean':
                    validation_results['validation_test_improvement'] = (validation_df[validation_comparison_column].mean() - validation_df[validation_success_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_test_improvement'] = (validation_df[validation_comparison_column].median() - validation_df[validation_success_column].median()) / validation_df[validation_comparison_column].median()

            else:
                
                if validation_agg_type == 'mean':
                    validation_results['validation_test_improvement'] = (validation_df[validation_success_column].mean() - validation_df[validation_comparison_column].mean()) / validation_df[validation_comparison_column].mean()
                elif validation_agg_type == 'median':
                    validation_results['validation_test_improvement'] = (validation_df[validation_success_column].median() - validation_df[validation_comparison_column].median()) / validation_df[validation_comparison_column].median()

                    
            validation_results['validation_avg_train_test_improvement'] = (validation_results['validation_test_improvement'] + validation_results['validation_training_improvement']) / 2
            validation_results['validation_train_test_harmonic_mean'] = 2 * ((validation_results['validation_test_improvement'] * validation_results['validation_training_improvement']) / (validation_results['validation_test_improvement'] + validation_results['validation_training_improvement']))
            
            if (validation_results['validation_test_improvement'] < 0) & (validation_results['validation_training_improvement'] < 0):
                validation_results['validation_train_test_geometric_mean'] = None
            else:
                validation_results['validation_train_test_geometric_mean'] = np.sqrt((validation_results['validation_test_improvement'] * validation_results['validation_training_improvement']))
        else:
            validation_results['validation_test_improvement'] = None

        
#         print('Test: Improvement: %s, Original: %s, New: %s'%(validation_results['validation_test_improvement'], validation_df[validation_comparison_column].mean(), validation_df[validation_success_column].mean()))
        print('Test: Improvement: %s, Original: %s, New: %s'%(validation_results['validation_test_improvement'], validation_df[validation_comparison_column].median(), validation_df[validation_success_column].median()))


    return validation_results, original_df_to_use['prediction']

In [72]:
def save_model_and_attributes(folder_name, model_name, top_model):

    temp_model_name = os.path.join(folder_name, model_name)


    model = top_model['model']
    scaler_to_use = top_model['scaler']
    outlier_model = top_model['outlier_detection']
    pca_enabled = top_model['pca']
    pca_transform = top_model['pca_transform']

    final_result = {key: top_model[key] for key in model_keys_to_export if key in top_model}
    for key in ['optimizer', 'loss_function', 'activation_layers', 'outlier_dict', 'lr_schedule_strategy']:
        if key in final_result.keys():
            value = final_result[key]
            final_result[key] = replace_df_objects_with_functions(str(final_result[key]))
        
        
    # Save the entire model as a .h5 file (architecture, optimizer, and weights)
    model.save(folder_name + 'model_' + model_name + '.h5')

    # Save the scaler
    with open(folder_name + 'scaler_' + model_name +  '.pkl', 'wb') as f:
        pickle.dump(scaler_to_use, f)

    # Save the list of features (e.g., column names)
    features = list(X.columns)

    with open(folder_name + 'features_' + model_name + '.json', 'w') as f:
        json.dump(features, f)


    # Save the dictionary
    with open(folder_name + 'modelresult_' + model_name +  '.pkl', 'wb') as f:
        pickle.dump(final_result, f)


    # Save the model to a file
    with open(folder_name + model_name +'_outlier_model.pkl', 'wb') as f:
        pickle.dump(outlier_model, f)


    # Save the PCA model to a file
    if pca_enabled:
        with open(folder_name + model_name + '_pca_transformer.pkl', 'wb') as f:
            pickle.dump(pca_transform, f)
            
            
    return

In [73]:
if model_type == 'regression':
    all_metrics = [
    (tf.keras.metrics.MeanSquaredError, {}),                # Measures the average of the squares of errors
    (tf.keras.metrics.MeanAbsoluteError, {}),               # Measures the average of absolute differences
    (tf.keras.metrics.MeanAbsolutePercentageError, {}),     # Measures the percentage error on average
    (tf.keras.metrics.RootMeanSquaredError, {}),            # Square root of MSE, more interpretable in original units
    (tf.keras.metrics.CosineSimilarity, {}),                # Measures similarity between actual and predicted vectors
    (tf.keras.metrics.LogCoshError, {}),                    # Robust to outliers, smooth approximation of MAE
    (tfa.metrics.RSquare, {})                               # Coefficient of determination (R²), measures explained variance
]
    
elif model_type == 'binary_classification':
    all_metrics = [
#                (tf.keras.metrics.CategoricalAccuracy, {}), 
               (tf.keras.metrics.AUC, {}),
               (tf.keras.metrics.BinaryAccuracy, {}),
               (tf.keras.metrics.Precision, {}),
               (tf.keras.metrics.Recall, {}),
#                (tfa.metrics.F1Score, {'num_classes':num_classes, 'average':'macro'}), 
               (tf.keras.metrics.TruePositives, {}),
               (tf.keras.metrics.FalsePositives, {}),
               (tf.keras.metrics.TrueNegatives, {}),
               (tf.keras.metrics.FalseNegatives, {}),
               (tf.keras.metrics.BinaryCrossentropy, {}),
#                (tfa.metrics.MatthewsCorrelationCoefficient, {'num_classes':2})
              ]

In [74]:
all_activations = [
    'relu',          # Common choice for hidden layers
    'tanh',          # Useful if data has both positive and negative values
    'elu',           # More robust variant of ReLU
    tf.keras.activations.swish,  # Self-gated activation
    'softplus',      # Smooth approximation of ReLU
    'softsign',      # Similar to tanh, squashes inputs between -1 and 1
    tf.keras.activations.gelu,   # Gaussian Error Linear Unit (GELU)
    'linear'         # Typically used for the output layer in regression
]

In [75]:
model_keys_to_export = [
'learning_rate',
'batch_size',
'optimizer',
'loss_function',
'epochs',
'activation_layers',
'pca_threshold',
'pca',
'n_splits',
'class_weights_enabled',
'outlier_dict',
'stratification_enabled',
'lr_schedule_enabled',
'lr_schedule_strategy',
'dropout_enabled',
'dropout_rate',
'early_stopping_metric',
]

In [76]:
all_outlier_dicts = [{'enabled':False, 'contamination':0.05, 'remove_outliers':True},
                     {'enabled':True, 'contamination':0.05, 'remove_outliers':True},
                     {'enabled':True, 'contamination':0.05, 'remove_outliers':False},
                     {'enabled':True, 'contamination':0.02, 'remove_outliers':True}
                    ]

In [77]:
if model_type == 'binary_classification':
    all_early_stopping_metrics = [
    #     'val_loss',            # Validation Loss
    #     'val_binary_accuracy', # Validation Binary Accuracy (for binary classification)
        'loss',
        'val_binary_crossentropy',
        'val_MatthewsCorrelationCoefficient'
    ]

    early_stopping_min_metrics = [
        'val_loss', 'loss', 'val_binary_crossentropy', 
        'val_mean_absolute_error', 'val_mean_squared_error',
        'val_mean_squared_logarithmic_error', 'val_root_mean_squared_error'
    ]

    # Metrics that should be maximized
    early_stopping_max_metrics = [
        'val_binary_accuracy', 'val_MatthewsCorrelationCoefficient', 'val_r2'
    ]

elif model_type == 'regression':
    
    all_early_stopping_metrics = [
    'loss',              # General validation loss, can be set to MSE, MAE, etc.
    'val_loss',              # General validation loss, can be set to MSE, MAE, etc.
    'val_mean_absolute_error',   # Validation Mean Absolute Error
    'val_mean_squared_error',    # Validation Mean Squared Error
#     'val_mean_squared_logarithmic_error', # Validation MSLE (if target scale varies greatly)
    'val_root_mean_squared_error', # Validation RMSE
#     'val_r2'                    # Validation R-Squared (if available in your framework)
]

In [78]:
# pcas = [True, False]
all_pcas = [True, False]
all_pca_thresholds = [0.85, 0.9, 0.95, 0.99]

all_learning_rates = [0.001, 0.01, 0.1]

all_batch_sizes = [32, 64, 128]

epochs = [5, 10, 20, 30, 40, 50, 75, 100]

num_hidden_layers = [1, 2, 3, 4, 5]

all_num_nodes =  [256, 128, 64, 32, 16]

all_class_weights_enabled = [False, True]

In [79]:
# Create additional layers

all_l1_regs = [0.1, 0.01, 0.001, 0.0001]
all_l2_regs = [0.1, 0.01, 0.001, 0.0001]

additional_layers = []

for nodes in all_num_nodes:
    for activation in all_activations:
        for l2 in all_l2_regs:
            for l1 in all_l1_regs:
                
                additional_layer = dict()
                additional_layer['nodes'] = nodes
                additional_layer['activation'] = activation
                additional_layer['l2_reg'] = l2
                additional_layer['l1_reg'] = l1
                
                additional_layers.append(additional_layer)

# Set specfics below

In [85]:
n_splits = 5
epochs = [200]

class_weights_enabled = [True]
stratification_enabled = [False]

lr_schedule_enabled = [True]
lr_schedule_strategies = [None]
lr_schedule_strategies = []
lr_schedule_strategies.append({'method': cosine_annealing_50, 'description': "Cosine Annealing with 50 epochs cycle"})

        
dropout_enabled = [True]
dropout_rates = [0.9]

if model_type == 'regression':
    early_stopping_metrics = ['val_root_mean_squared_error']
elif model_type == 'binary_classification':
    early_stopping_metrics = ['loss']

    
pcas = [False]
pca_thresholds = [0.9]

learning_rates = [0.01]
batch_sizes = [32]


# outlier_dicts = []
# outlier_dict = dict()
# outlier_dict['enabled'] = True
# outlier_dict['contamination'] = 0.05
# outlier_dict['remove_outliers'] = True
# outlier_dicts.append(outlier_dict)

outlier_dicts = [{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}]

# optimizers =[(tf.keras.optimizers.Adam, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01}), (tf.keras.optimizers.Adamax, {'beta_1': 0.9, 'beta_2': 0.999, 'epsilon': 1e-07, 'learning_rate': 0.01})]
optimizers =[(tf.keras.optimizers.Adam, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})]


if model_type == 'regression':
    loss_functions = [ (tf.keras.losses.Huber, {'reduction': 'auto'})]
elif model_type == 'binary_classification':
    loss_functions = [(tf.keras.losses.BinaryCrossentropy, {'reduction':'auto'})]

    
metrics = all_metrics
    
activation_layer = dict()
activation_layer['nodes'] = 128
activation_layer['activation'] = 'relu'
activation_layer['l2_reg'] = 0.001
activation_layer['l1_reg'] = 0.001

activation_layers_list = [
    [activation_layer] # only addding 1 activation layer at the start
]


activation_layers_list = [[{'nodes': 128,
   'activation': 'softplus',
   'l2_reg': 0.0001,
   'l1_reg': 0.001}]]

In [81]:
# metrics = all_metrics

In [82]:
# Stop here

# First get the general features loss functions, optimisers and metrics that create the best model - Using a standard activation

In [83]:
# Checking to see what our current delta_success is
print('Specific training dataset results')
temp_df = original_df.loc[all_features_df.index]
delta_success = temp_df['delta_success'].mean()
delta_error_mean = temp_df[validation_dict['validation_comparison_column']].mean()
delta_error_median = temp_df[validation_dict['validation_comparison_column']].median()
print(delta_success, delta_error_mean, delta_error_median)
print('Mean + STD of training', temp_df['delta_error'].mean(), temp_df['delta_error'].std())

temp_df_home = temp_df[ temp_df['pre_delta_diff'] > 0]
temp_df_away = temp_df[ temp_df['pre_delta_diff'] < 0]

delta_success = temp_df_home['delta_success'].mean()
delta_error_mean = temp_df_home[validation_dict['validation_comparison_column']].mean()
delta_error_median = temp_df_home[validation_dict['validation_comparison_column']].median()
print('Home Accuracy', delta_success, delta_error_mean, delta_error_median)

delta_success = temp_df_away['delta_success'].mean()
delta_error_mean = temp_df_away[validation_dict['validation_comparison_column']].mean()
delta_error_median = temp_df_away[validation_dict['validation_comparison_column']].median()
print('Away Accuracy', delta_success, delta_error_mean, delta_error_median)

print('')
print('')

print('Train Results')
validation_df = original_df[(original_df[validation_range_column] > (train_start_range)) & (original_df[validation_range_column] < (validation_start_range))]
delta_success = validation_df['delta_success'].mean()
delta_mean_abs = validation_df[validation_dict['validation_comparison_column']].mean()
delta_median_abs = validation_df[validation_dict['validation_comparison_column']].median()
print(delta_success, delta_mean_abs, delta_median_abs)
temp_df_home = validation_df[ validation_df['pre_delta_diff'] > 0]
temp_df_away = validation_df[ validation_df['pre_delta_diff'] < 0]

delta_success= temp_df_home['delta_success'].mean()
print('Home Accuracy', delta_success)

delta_success = temp_df_away['delta_success'].mean()
print('Away Accuracy', delta_success)


print('Test Results')
validation_df = original_df[(original_df[validation_range_column] >= (validation_start_range)) & (original_df[validation_range_column] < (validation_end_range))]
delta_success = validation_df['delta_success'].mean()
delta_mean_abs = validation_df[validation_dict['validation_comparison_column']].mean()
delta_median_abs = validation_df[validation_dict['validation_comparison_column']].median()
print(delta_success, delta_mean_abs, delta_median_abs)

temp_df_home = validation_df[ validation_df['pre_delta_diff'] > 0]
temp_df_away = validation_df[ validation_df['pre_delta_diff'] < 0]

delta_success = temp_df_home['delta_success'].mean()
print('Home Accuracy', delta_success)

delta_success = temp_df_away['delta_success'].mean()
print('Away Accuracy', delta_success)

Specific training dataset results
0.7170257859413635 12.4034884786786 9.762922791515482
Mean + STD of training -0.12421902583777679 16.324808311346175
Home Accuracy 0.7516170077404305 12.229388491838227 9.687158089626761
Away Accuracy 0.6479678238780694 12.751061928274607 9.967358935260958


Train Results
0.7170157900314388 12.403860824284171 9.764349834651394
Home Accuracy 0.7516038386087694
Away Accuracy 0.6479678238780694
Test Results
0.710276923076923 12.842046879373708 10.2199936987652
Home Accuracy 0.7355387889340298
Away Accuracy 0.6661028416779432

In [86]:
# first make sure we have selected 1 for each parameter for the intial model or the number of iterations will explode
print("class_weights_enabled: %s, stratification_enabled: %s, lr_schedule_enabled: %s, dropout_enabled: %s, dropout_rates: %s, early_stopping_metrics: %s, outlier_dicts: %s, activation_layers_list: %s, epochs: %s, loss_functions: %s, optimizers: %s, batch_sizes: %s, learning_rates: %s, pcas: %s, pca_thresholds: %s"%(len(class_weights_enabled), len(stratification_enabled), len(lr_schedule_enabled), len(dropout_enabled), len(dropout_rates), len(early_stopping_metrics), len(outlier_dicts), len(activation_layers_list), len(epochs), len(loss_functions), len(optimizers), len(batch_sizes), len(learning_rates), len(pcas), len(pca_thresholds)))
num_iterations = len(stratification_enabled) * len(lr_schedule_enabled) * len(dropout_enabled) * len(dropout_rates) * len(early_stopping_metrics) * len(class_weights_enabled) * len(outlier_dicts) * len(activation_layers_list) * len(epochs) * len(loss_functions) * len(optimizers) * len(batch_sizes) * len(learning_rates) * len(pcas) * len(pca_thresholds)
print('This should equal 1 if we have 1 selected for everything: %s'%(num_iterations))

class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
This should equal 1 if we have 1 selected for everything: 1

In [87]:
n_splits = 1

# Set the initial names
parameters_df_name = model_name + '_parameters_df_0.csv'
best_model_name = model_name + '_best_model_layer_0_model_dict'

all_model_iterations = pd.DataFrame()


# Check if file exists - f not then we need to calculate the initial parameters and get the best model
if os.path.exists(best_model_name):
    with open(best_model_name, 'r') as f:
        model_to_use = f.read()
        print(f"{best_model_name} exists")
    parameters_df = pd.read_csv(parameters_df_name)
    
else:
    
    model_to_use, parameters_df = find_optimal_general_parameters(2, model_ass_val, model_ass_val_direction, pcas, pca_thresholds, learning_rates, batch_sizes, optimizers, loss_functions, metrics, epochs, activation_layers_list, n_splits, class_weights_enabled, outlier_dicts, stratification_enabled, lr_schedule_enabled, lr_schedule_strategies, dropout_enabled, dropout_rates, early_stopping_metrics, validation_dict = validation_dict)
    
    # Save the results
    parameters_df.to_csv(parameters_df_name, index = False)
    
    # Create a new dictionary containing only the keys you want to export
    filtered_model = {key: model_to_use[key] for key in model_keys_to_export if key in model_to_use}
    with open(best_model_name, 'w') as f:
        f.write(str(filtered_model))

        
# Add the parameters df to the global df
all_model_iterations = pd.concat([all_model_iterations, parameters_df], ignore_index = True)
    
    
    
    
###########################################################################################
######################## Work on getting optimum activation layers ########################
###########################################################################################

# Check to see if we already have results we can pre_load
activation_layers_df_name = model_name + '_activation_layers_df.csv'
if os.path.exists(activation_layers_df_name):
    activation_layers_df = pd.read_csv(activation_layers_df_name)
    
    # Replace the objects with the functions
    activation_layers_df['activation_layers'] = activation_layers_df['activation_layers'].apply(lambda x: replace_df_objects_with_functions(x) )
    activation_layers_df['optimizer'] = activation_layers_df['optimizer'].apply(lambda x: replace_df_objects_with_functions(x) )
    activation_layers_df['loss_function'] = activation_layers_df['loss_function'].apply(lambda x: replace_df_objects_with_functions(x) )
    activation_layers_df['lr_schedule_strategy'] = activation_layers_df['lr_schedule_strategy'].apply(lambda x: replace_df_objects_with_functions(x) )

else:
    activation_layers_df = pd.DataFrame()
    
    

for model_layer in range(1,10):
    
    n_splits = 1
    
    print('Adding model layer -', model_layer)
    
    # Check to see if we have already got the best model for this layer
    best_model_name = model_name + '_best_model_layer_' + str(model_layer) + '_model_dict'
    if os.path.exists(best_model_name):
        print('We have already got the best model for layer: %s'%(model_layer))
        continue

    
    # Get the previous model to use - This gives us the base parameters for us to add our activation layer onto
    previous_best_model_name = model_name + '_best_model_layer_' + str(model_layer-1) + '_model_dict'
    with open(previous_best_model_name, 'r') as f:
        model_to_use = f.read()
        model_to_use = replace_df_objects_with_functions(model_to_use)
        model_to_use = model_to_use.replace(': nan,', ': None,')
        model_to_use = eval(model_to_use)

    
    loop_num = 0

    for additional_layer in additional_layers:        

        loop_num += 1
        print(model_layer, loop_num, len(additional_layers))

        # Check if this exists in the dataframe
        if len(activation_layers_df) > 0:
            if len(activation_layers_df[ (activation_layers_df['iteration_number'] == loop_num) & (activation_layers_df['num_layers'] == (model_layer))]) == 1:
                continue

        
        # Get the additional_layers from the current model and add the new additional layer
        # If it is the first run through then we haven't set any activation layers yet
        # Otherwise we use the activation layers set in the best model from the previous layer number
        layers_to_use = []
        if model_layer > 1:
            layers_to_use = layers_to_use + model_to_use['activation_layers']
            
        # Add on the activation layer we want to test
        layers_to_use.append(additional_layer)
        
        print(layers_to_use)
        

        results_dict, feature_importances_df, fold_metrics = run_experiment(model_type, model_to_use['pca'], model_to_use['pca_threshold'], X, y, model_to_use['learning_rate'], model_to_use['batch_size'], model_to_use['optimizer'], model_to_use['loss_function'], metrics, epochs[0], layers_to_use, n_splits, model_to_use['class_weights_enabled'], outlier_dict = model_to_use['outlier_dict'], stratification_enabled = model_to_use['stratification_enabled'], lr_schedule_enabled = model_to_use['lr_schedule_enabled'], lr_schedule_strategy = model_to_use['lr_schedule_strategy'], dropout_enabled = model_to_use['dropout_enabled'], dropout_rate = model_to_use['dropout_rate'], early_stopping_metric = model_to_use['early_stopping_metric'], validation_dict = validation_dict)
        
        results_dict['num_layers'] = model_layer
        results_dict['iteration_number'] = loop_num
        
        activation_layers_df = pd.concat([activation_layers_df, pd.DataFrame([results_dict])], ignore_index=True)

        print(activation_layers_df.sort_values(model_ass_val, ascending = model_ass_val_direction)[:20])

        if (loop_num % 10) == 0:
            activation_layers_df.to_csv(activation_layers_df_name, index = False)
            
            
            
    ########## Retry the top models and reduce to best layer ##########
    # Only get the top models for this number of layers - The df contains all trials
    top_models = activation_layers_df[ activation_layers_df['num_layers'] == model_layer].sort_values(model_ass_val, ascending = model_ass_val_direction)
    print('\nRetraining Top Models To Get Best Model For Next Layer')
    
    n_splits = 3

    for best_num in [25, 10, 5]:
#     for best_num in [5]:
        

        # Get top 10
        top_models = top_models.iloc[0:best_num]

        results_dicts = []
        loop_num = 0

        for row in top_models.index:

            loop_num += 1
            print(loop_num, len(top_models))
            
            model_to_try = top_models.loc[row].to_dict()
#             model_to_try = replace_df_objects_with_functions(str(model_to_try))

            # If we have loaded the data from a csv then these dictionaries, tuples are stored as strings, convert back
            for key in ['optimizer', 'loss_function', 'activation_layers', 'outlier_dict', 'lr_schedule_strategy']:
                if key in model_to_try.keys():
                    value = model_to_try[key]
                    if isinstance(value, str):
                        model_to_try[key] = replace_df_objects_with_functions(str(model_to_try[key]))
                        model_to_try[key] = eval(model_to_try[key])

            results_dict, feature_importances_df, fold_metrics = run_experiment(model_type, model_to_try['pca'], model_to_try['pca_threshold'], X, y, model_to_try['learning_rate'], model_to_try['batch_size'], model_to_try['optimizer'], model_to_try['loss_function'], metrics, epochs[0], model_to_try['activation_layers'], n_splits, model_to_try['class_weights_enabled'], outlier_dict = model_to_try['outlier_dict'], stratification_enabled = model_to_try['stratification_enabled'], lr_schedule_enabled = model_to_try['lr_schedule_enabled'], lr_schedule_strategy = model_to_try['lr_schedule_strategy'], dropout_enabled = model_to_try['dropout_enabled'], dropout_rate = model_to_try['dropout_rate'], early_stopping_metric = model_to_try['early_stopping_metric'], validation_dict = validation_dict)
            results_dict['num_layers'] = model_layer
            results_dict['iteration_number'] = -1
            results_dicts.append(results_dict)
            
            
        # Reset what the top models are
        top_models = pd.DataFrame(results_dicts).sort_values(model_ass_val, ascending = model_ass_val_direction)
        
        # Add these top models to our global dataframe
        all_model_iterations = pd.concat([all_model_iterations, top_models], ignore_index = True)

        print("'''''''''''' Best Models ''''''''''''")
        print("''''''''''''",best_num)
        print(top_models)
        print('')
        
    


    ########### Now set our top model ###########
    top_model = pd.DataFrame(top_models).iloc[0].to_dict()
    print("'''''''''''' Top Model ''''''''''''")
    print(top_model)
    print('')
    
    
    ########### Double check this with the full parameter set to see if there is anything better we can use ###########
    if model_layer == 1:
        new_potential_model, parameters_df = find_optimal_general_parameters(1, model_ass_val, model_ass_val_direction, [top_model['pca']], [top_model['pca_threshold']], [top_model['learning_rate']], [top_model['batch_size']], [top_model['optimizer']], [top_model['loss_function']], metrics, epochs, [top_model['activation_layers']], n_splits, [top_model['class_weights_enabled']], [top_model['outlier_dict']], [top_model['stratification_enabled']], [top_model['lr_schedule_enabled']], [top_model['lr_schedule_strategy']], [top_model['dropout_enabled']], [top_model['dropout_rate']], [top_model['early_stopping_metric']], validation_dict = validation_dict)
        parameters_df_name = model_name + '_parameters_df_' + str(model_layer) + '.csv'
        parameters_df.to_csv(parameters_df_name, index = False)

        # Add these top models to our global dataframe
        all_model_iterations = pd.concat([all_model_iterations, parameters_df], ignore_index = True)

        # Compare this best model with the best one we already had while trying to get the best layer
        temp_df = pd.concat([top_models, parameters_df], ignore_index = True)
        temp_df = temp_df[ temp_df['num_layers'] == model_layer]
        temp_df.sort_values(model_ass_val, ascending = model_ass_val_direction, inplace = True)
        top_model = pd.DataFrame(temp_df).iloc[0].to_dict()

        
        
        
    # Create a new dictionary containing only the keys you want to export
    filtered_model = {key: top_model[key] for key in model_keys_to_export if key in top_model}
    best_model_name = model_name + '_best_model_layer_' + str(model_layer) + '_model_dict'
    with open(best_model_name, 'w') as f:
        f.write(str(filtered_model))

'''''''' Getting optimal parameters ''''''''
'''''''' 2

'''''''' pcas
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 2, pca_thresholds: 4
pca-True
  pca_thresholds_checked-0.85
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 8
X_pca shape: (28310, 3)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.01169602266473703, Original: 9.762922791515482, New: 9.64873542527184
Test: Improvement: 0.01843549471105464, Original: 10.2199936987652, New: 10.031583058984602

-------------------------
   learning_rate  batch_size  \
0           0.01          32

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -1.141178                   16.99782

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.825523                       10.031583

   validation_test_abserror_std  validation_test_success  \
0                     11.193962                 0.538954

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.018435                               0.015066

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.014312                             0.014684

[1 rows x 50 columns]
  pca_thresholds_checked-0.9
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 8
X_pca shape: (28310, 3)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.013402678711657536, Original: 9.762922791515482, New: 9.632073474054081
Test: Improvement: 0.019077251451921552, Original: 10.2199936987652, New: 10.025024309136802

-------------------------
   learning_rate  batch_size  \
1           0.01          32
0           0.01          32

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                    -0.682097                  17.247009
0                    -1.141178                  16.997820

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.933902                       10.025024
0                      12.825523                       10.031583

   validation_test_abserror_std  validation_test_success  \
1                     11.413423                 0.552246
0                     11.193962                 0.538954

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.019077                               0.016240
0                    0.018435                               0.015066

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.015744                             0.015990
0                             0.014312                             0.014684

[2 rows x 50 columns]
  pca_thresholds_checked-0.95
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 8
X_pca shape: (28310, 6)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.020544318911238892, Original: 9.762922791515482, New: 9.562350192180785
Test: Improvement: 0.022603744153629122, Original: 10.2199936987652, New: 9.988983575946609

-------------------------
   learning_rate  batch_size  \
2           0.01          32
1           0.01          32
0           0.01          32

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.354214                  17.350608
1                    -0.682097                  17.247009
0                    -1.141178                  16.997820

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.930489                        9.988984
1                      12.933902                       10.025024
0                      12.825523                       10.031583

   validation_test_abserror_std  validation_test_success  \
2                     11.605623                 0.565415
1                     11.413423                 0.552246
0                     11.193962                 0.538954

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.022604                               0.021574
1                    0.019077                               0.016240
0                    0.018435                               0.015066

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.021525                             0.021549
1                             0.015744                             0.015990
0                             0.014312                             0.014684

[3 rows x 50 columns]
  pca_thresholds_checked-0.99
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020314382947204723, Original: 9.762922791515482, New: 9.564595039244644
Test: Improvement: 0.02463618316160628, Original: 10.2199936987652, New: 9.968212062091958

-------------------------
   learning_rate  batch_size  \
3           0.01          32
2           0.01          32
1           0.01          32
0           0.01          32

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                    -0.626684                  17.851410
2                     0.354214                  17.350608
1                    -0.682097                  17.247009
0                    -1.141178                  16.997820

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.979868                        9.968212
2                      12.930489                        9.988984
1                      12.933902                       10.025024
0                      12.825523                       10.031583

   validation_test_abserror_std  validation_test_success  \
3                     12.256447                 0.565538
2                     11.605623                 0.565415
1                     11.413423                 0.552246
0                     11.193962                 0.538954

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.024636                               0.022475
2                    0.022604                               0.021574
1                    0.019077                               0.016240
0                    0.018435                               0.015066

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.022268                             0.022371
2                             0.021525                             0.021549
1                             0.015744                             0.015990
0                             0.014312                             0.014684

[4 rows x 50 columns]
pca-False
  pca_thresholds_checked-None
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 8
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but IsolationForest was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.026431947535224334, Original: 9.762922791515482, New: 9.504869728499699
Test: Improvement: 0.0161294163334995, Original: 10.2199936987652, New: 10.055151165472074

-------------------------
   learning_rate  batch_size  \
3           0.01          32
2           0.01          32
4           0.01          32
1           0.01          32
0           0.01          32

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                    -0.626684                  17.851410
2                     0.354214                  17.350608
4                     0.240506                  17.070587
1                    -0.682097                  17.247009
0                    -1.141178                  16.997820

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.979868                        9.968212
2                      12.930489                        9.988984
4                      12.857922                       10.055151
1                      12.933902                       10.025024
0                      12.825523                       10.031583

   validation_test_abserror_std  validation_test_success  \
3                     12.256447                 0.565538
2                     11.605623                 0.565415
4                     11.253854                 0.563077
1                     11.413423                 0.552246
0                     11.193962                 0.538954

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.024636                               0.022475
2                    0.022604                               0.021574
4                    0.016129                               0.021281
1                    0.019077                               0.016240
0                    0.018435                               0.015066

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.022268                             0.022371
2                             0.021525                             0.021549
4                             0.020034                             0.020648
1                             0.015744                             0.015990
0                             0.014312                             0.014684

[5 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 2, pca_thresholds: 4
pca-True
  pca_thresholds_checked-0.85
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 8
X_pca shape: (28310, 3)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0016684639669901492, Original: 9.762922791515482, New: 9.746633706625332
Test: Improvement: 0.011191495505204685, Original: 10.2199936987652, New: 10.105616685222248

-------------------------
   learning_rate  batch_size  \
0           0.01          32

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     -1.63561                  18.655745

   validation_test_abserror_mean validation_test_abserror_median  \
0                      13.543279                       10.105617

   validation_test_abserror_std  validation_test_success  \
0                     13.003245                   0.5344

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.011191                                0.00643

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.002904                             0.004321

[1 rows x 50 columns]
  pca_thresholds_checked-0.9
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 8
X_pca shape: (28310, 3)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.013027733414868433, Original: 9.762922791515482, New: 9.635734036037675
Test: Improvement: 0.017854137999174027, Original: 10.2199936987652, New: 10.037524520916756

-------------------------
   learning_rate  batch_size  \
1           0.01          32
0           0.01          32

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                    -0.898698                  17.012503
0                    -1.635610                  18.655745

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.819132                       10.037525
0                      13.543279                       10.105617

   validation_test_abserror_std  validation_test_success  \
1                     11.203451                 0.548185
0                     13.003245                 0.534400

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.017854                               0.015441
0                    0.011191                               0.006430

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.015064                             0.015251
0                             0.002904                             0.004321

[2 rows x 50 columns]
  pca_thresholds_checked-0.95
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 8
X_pca shape: (28310, 6)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.012449943144647901, Original: 9.762922791515482, New: 9.641374957835527
Test: Improvement: 0.01065107082002876, Original: 10.2199936987652, New: 10.111139822099403

-------------------------
   learning_rate  batch_size  \
1           0.01          32
2           0.01          32
0           0.01          32

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                    -0.898698                  17.012503
2                    -0.673733                  18.200876
0                    -1.635610                  18.655745

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.819132                       10.037525
2                      13.317794                       10.111140
0                      13.543279                       10.105617

   validation_test_abserror_std  validation_test_success  \
1                     11.203451                 0.548185
2                     12.407134                 0.559631
0                     13.003245                 0.534400

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.017854                               0.015441
2                    0.010651                               0.011551
0                    0.011191                               0.006430

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.015064                             0.015251
2                             0.011480                             0.011515
0                             0.002904                             0.004321

[3 rows x 50 columns]
  pca_thresholds_checked-0.99
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019678586857008542, Original: 9.762922791515482, New: 9.570802267384376
Test: Improvement: 0.014665268736492336, Original: 10.2199936987652, New: 10.07011474468755

-------------------------
   learning_rate  batch_size  \
3           0.01          32
1           0.01          32
2           0.01          32
0           0.01          32

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                    -0.908788                  18.508275
1                    -0.898698                  17.012503
2                    -0.673733                  18.200876
0                    -1.635610                  18.655745

   validation_test_abserror_mean validation_test_abserror_median  \
3                      13.143869                       10.070115
1                      12.819132                       10.037525
2                      13.317794                       10.111140
0                      13.543279                       10.105617

   validation_test_abserror_std  validation_test_success  \
3                     13.036752                 0.556431
1                     11.203451                 0.548185
2                     12.407134                 0.559631
0                     13.003245                 0.534400

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.014665                               0.017172
1                    0.017854                               0.015441
2                    0.010651                               0.011551
0                    0.011191                               0.006430

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.016806                             0.016988
1                             0.015064                             0.015251
2                             0.011480                             0.011515
0                             0.002904                             0.004321

[4 rows x 50 columns]
pca-False
  pca_thresholds_checked-None
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 8
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but IsolationForest was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.03169839438485375, Original: 9.762922791515482, New: 9.453453814521147
Test: Improvement: 0.013573019211699936, Original: 10.2199936987652, New: 10.081277527948407

-------------------------
   learning_rate  batch_size  \
4           0.01          32
3           0.01          32
1           0.01          32
2           0.01          32
0           0.01          32

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                    -0.695254                  22.078204
3                    -0.908788                  18.508275
1                    -0.898698                  17.012503
2                    -0.673733                  18.200876
0                    -1.635610                  18.655745

   validation_test_abserror_mean validation_test_abserror_median  \
4                      14.169225                       10.081278
3                      13.143869                       10.070115
1                      12.819132                       10.037525
2                      13.317794                       10.111140
0                      13.543279                       10.105617

   validation_test_abserror_std  validation_test_success  \
4                     16.930902                 0.566277
3                     13.036752                 0.556431
1                     11.203451                 0.548185
2                     12.407134                 0.559631
0                     13.003245                 0.534400

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.013573                               0.022636
3                    0.014665                               0.017172
1                    0.017854                               0.015441
2                    0.010651                               0.011551
0                    0.011191                               0.006430

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.019007                             0.020742
3                             0.016806                             0.016988
1                             0.015064                             0.015251
2                             0.011480                             0.011515
0                             0.002904                             0.004321

[5 rows x 50 columns]
pcas Selected -  [True]
pca_thresholds Selected -  [0.99]

'''''''' LR & BS
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 3, learning_rates: 3, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022588630969413732, Original: 9.762922791515482, New: 9.54239173139506
Test: Improvement: 0.02681566490503528, Original: 10.2199936987652, New: 9.94593777240754

-------------------------
   learning_rate  batch_size  \
0          0.001          32

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.206362                  17.392292

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.855606                        9.945938

   validation_test_abserror_std  validation_test_success  \
0                     11.737189                 0.573415

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.026816                               0.024702

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.024521                             0.024612

[1 rows x 50 columns]
        batch-64
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024224824164211647, Original: 9.762922791515482, New: 9.526417703562245
Test: Improvement: 0.029742173768724785, Original: 10.2199936987652, New: 9.916028870261252

-------------------------
   learning_rate  batch_size  \
1          0.001          64
0          0.001          32

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.197088                  17.147410
0                     0.206362                  17.392292

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.782373                        9.916029
0                      12.855606                        9.945938

   validation_test_abserror_std  validation_test_success  \
1                     11.445424                 0.568615
0                     11.737189                 0.573415

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.029742                               0.026983
0                    0.026816                               0.024702

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.026701                             0.026842
0                             0.024521                             0.024612

[2 rows x 50 columns]
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02503556118029106, Original: 9.762922791515482, New: 9.518502540670038
Test: Improvement: 0.03426760714210098, Original: 10.2199936987652, New: 9.869778969701166

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001          64
0          0.001          32

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.097675                  17.050711
1                     0.197088                  17.147410
0                     0.206362                  17.392292

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.741446                        9.869779
1                      12.782373                        9.916029
0                      12.855606                        9.945938

   validation_test_abserror_std  validation_test_success  \
2                     11.346390                 0.570338
1                     11.445424                 0.568615
0                     11.737189                 0.573415

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.034268                               0.029652
1                    0.029742                               0.026983
0                    0.026816                               0.024702

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.028933                             0.029290
1                             0.026701                             0.026842
0                             0.024521                             0.024612

[3 rows x 50 columns]
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.006017925647942782, Original: 9.762922791515482, New: 9.704170248049536
Test: Improvement: 0.005498969720908296, Original: 10.2199936987652, New: 10.163794262867816

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001          64
0          0.001          32
3          0.010          32

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.097675                  17.050711
1                     0.197088                  17.147410
0                     0.206362                  17.392292
3                    -0.781994                  25.708967

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.741446                        9.869779
1                      12.782373                        9.916029
0                      12.855606                        9.945938
3                      14.384992                       10.163794

   validation_test_abserror_std  validation_test_success  \
2                     11.346390                 0.570338
1                     11.445424                 0.568615
0                     11.737189                 0.573415
3                     21.325750                 0.563815

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.034268                               0.029652
1                    0.029742                               0.026983
0                    0.026816                               0.024702
3                    0.005499                               0.005758

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.028933                             0.029290
1                             0.026701                             0.026842
0                             0.024521                             0.024612
3                             0.005747                             0.005753

[4 rows x 50 columns]
        batch-64
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.018906495158289363, Original: 9.762922791515482, New: 9.578340139026942
Test: Improvement: 0.029824182942099053, Original: 10.2199936987652, New: 9.915190737026126

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001          64
0          0.001          32
4          0.010          64
3          0.010          32

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.097675                  17.050711
1                     0.197088                  17.147410
0                     0.206362                  17.392292
4                    -0.338996                  17.382994
3                    -0.781994                  25.708967

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.741446                        9.869779
1                      12.782373                        9.916029
0                      12.855606                        9.945938
4                      12.845314                        9.915191
3                      14.384992                       10.163794

   validation_test_abserror_std  validation_test_success  \
2                     11.346390                 0.570338
1                     11.445424                 0.568615
0                     11.737189                 0.573415
4                     11.711246                 0.569354
3                     21.325750                 0.563815

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.034268                               0.029652
1                    0.029742                               0.026983
0                    0.026816                               0.024702
4                    0.029824                               0.024365
3                    0.005499                               0.005758

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.028933                             0.029290
1                             0.026701                             0.026842
0                             0.024521                             0.024612
4                             0.023142                             0.023746
3                             0.005747                             0.005753

[5 rows x 50 columns]
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
6 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.00840387014743627, Original: 9.762922791515482, New: 9.68087645611614
Test: Improvement: 0.0024856543104742747, Original: 10.2199936987652, New: 10.194590327374843

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001          64
0          0.001          32
4          0.010          64
3          0.010          32
5          0.010         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.097675                  17.050711
1                     0.197088                  17.147410
0                     0.206362                  17.392292
4                    -0.338996                  17.382994
3                    -0.781994                  25.708967
5                    -0.907065                  21.949965

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.741446                        9.869779
1                      12.782373                        9.916029
0                      12.855606                        9.945938
4                      12.845314                        9.915191
3                      14.384992                       10.163794
5                      14.063710                       10.194590

   validation_test_abserror_std  validation_test_success  \
2                     11.346390                 0.570338
1                     11.445424                 0.568615
0                     11.737189                 0.573415
4                     11.711246                 0.569354
3                     21.325750                 0.563815
5                     16.882105                 0.564923

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.034268                               0.029652
1                    0.029742                               0.026983
0                    0.026816                               0.024702
4                    0.029824                               0.024365
3                    0.005499                               0.005758
5                    0.002486                               0.005445

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.028933                             0.029290
1                             0.026701                             0.026842
0                             0.024521                             0.024612
4                             0.023142                             0.023746
3                             0.005747                             0.005753
5                             0.003837                             0.004570

[6 rows x 50 columns]
  lr-0.1
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
7 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0004981061650591288, Original: 9.762922791515482, New: 9.767785763546932
Test: Improvement: 0.0003926781203367622, Original: 10.2199936987652, New: 10.215980530849714

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001          64
0          0.001          32
4          0.010          64
3          0.010          32
5          0.010         128
6          0.100          32

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.097675                  17.050711
1                     0.197088                  17.147410
0                     0.206362                  17.392292
4                    -0.338996                  17.382994
3                    -0.781994                  25.708967
5                    -0.907065                  21.949965
6                    -0.628464                  17.228162

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.741446                        9.869779
1                      12.782373                        9.916029
0                      12.855606                        9.945938
4                      12.845314                        9.915191
3                      14.384992                       10.163794
5                      14.063710                       10.194590
6                      12.906357                       10.215981

   validation_test_abserror_std  validation_test_success  \
2                     11.346390                 0.570338
1                     11.445424                 0.568615
0                     11.737189                 0.573415
4                     11.711246                 0.569354
3                     21.325750                 0.563815
5                     16.882105                 0.564923
6                     11.421280                 0.556800

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.034268                               0.029652
1                    0.029742                               0.026983
0                    0.026816                               0.024702
4                    0.029824                               0.024365
3                    0.005499                               0.005758
5                    0.002486                               0.005445
6                    0.000393                              -0.000053

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.028933                             0.029290
1                             0.026701                             0.026842
0                             0.024521                             0.024612
4                             0.023142                             0.023746
3                             0.005747                             0.005753
5                             0.003837                             0.004570
6                             0.003711                                  NaN

[7 rows x 50 columns]
        batch-64
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.1})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
8 9

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.003267171703310572, Original: 9.762922791515482, New: 9.794819936601527
Test: Improvement: -0.006865912321672537, Original: 10.2199936987652, New: 10.290163279428967

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001          64
0          0.001          32
4          0.010          64
3          0.010          32
5          0.010         128
6          0.100          32
7          0.100          64

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.097675                  17.050711
1                     0.197088                  17.147410
0                     0.206362                  17.392292
4                    -0.338996                  17.382994
3                    -0.781994                  25.708967
5                    -0.907065                  21.949965
6                    -0.628464                  17.228162
7                    -0.213435                  43.477895

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.741446                        9.869779
1                      12.782373                        9.916029
0                      12.855606                        9.945938
4                      12.845314                        9.915191
3                      14.384992                       10.163794
5                      14.063710                       10.194590
6                      12.906357                       10.215981
7                      15.298774                       10.290163

   validation_test_abserror_std  validation_test_success  \
2                     11.346390                 0.570338
1                     11.445424                 0.568615
0                     11.737189                 0.573415
4                     11.711246                 0.569354
3                     21.325750                 0.563815
5                     16.882105                 0.564923
6                     11.421280                 0.556800
7                     40.701000                 0.546215

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.034268                               0.029652
1                    0.029742                               0.026983
0                    0.026816                               0.024702
4                    0.029824                               0.024365
3                    0.005499                               0.005758
5                    0.002486                               0.005445
6                    0.000393                              -0.000053
7                   -0.006866                              -0.005067

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.028933                             0.029290
1                             0.026701                             0.026842
0                             0.024521                             0.024612
4                             0.023142                             0.023746
3                             0.005747                             0.005753
5                             0.003837                             0.004570
6                             0.003711                                  NaN
7                            -0.004427                                  NaN

[8 rows x 50 columns]
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.1})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
9 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.004377687839785799, Original: 9.762922791515482, New: 9.805661819900667
Test: Improvement: -0.005207236556288327, Original: 10.2199936987652, New: 10.273211623558446

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001          64
0          0.001          32
4          0.010          64
3          0.010          32
5          0.010         128
6          0.100          32
8          0.100         128
7          0.100          64

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.097675                  17.050711
1                     0.197088                  17.147410
0                     0.206362                  17.392292
4                    -0.338996                  17.382994
3                    -0.781994                  25.708967
5                    -0.907065                  21.949965
6                    -0.628464                  17.228162
8                    -0.028913                  26.675562
7                    -0.213435                  43.477895

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.741446                        9.869779
1                      12.782373                        9.916029
0                      12.855606                        9.945938
4                      12.845314                        9.915191
3                      14.384992                       10.163794
5                      14.063710                       10.194590
6                      12.906357                       10.215981
8                      14.135449                       10.273212
7                      15.298774                       10.290163

   validation_test_abserror_std  validation_test_success  \
2                     11.346390                 0.570338
1                     11.445424                 0.568615
0                     11.737189                 0.573415
4                     11.711246                 0.569354
3                     21.325750                 0.563815
5                     16.882105                 0.564923
6                     11.421280                 0.556800
8                     22.630905                 0.555815
7                     40.701000                 0.546215

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.034268                               0.029652
1                    0.029742                               0.026983
0                    0.026816                               0.024702
4                    0.029824                               0.024365
3                    0.005499                               0.005758
5                    0.002486                               0.005445
6                    0.000393                              -0.000053
8                   -0.005207                              -0.004792
7                   -0.006866                              -0.005067

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.028933                             0.029290
1                             0.026701                             0.026842
0                             0.024521                             0.024612
4                             0.023142                             0.023746
3                             0.005747                             0.005753
5                             0.003837                             0.004570
6                             0.003711                                  NaN
8                            -0.004757                                  NaN
7                            -0.004427                                  NaN

[9 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 3, learning_rates: 3, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.1})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 9

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021861116345499077, Original: 9.762922791515482, New: 9.549494400498038
Test: Improvement: 0.029701112030550505, Original: 10.2199936987652, New: 9.916448520966654

-------------------------
   learning_rate  batch_size  \
0          0.001          32

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                   0.5696

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481

[1 rows x 50 columns]
        batch-64
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.015065284593084809, Original: 9.762922791515482, New: 9.615841581200987
Test: Improvement: 0.00903161721481823, Original: 10.2199936987652, New: 10.127690627740098

-------------------------
   learning_rate  batch_size  \
0          0.001          32
1          0.001          64

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
1                     0.121240                  19.599332

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
1                      13.656527                       10.127691

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                   0.5696
1                     14.072658                   0.5728

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
1                    0.009032                               0.012048

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
1                             0.011293                             0.011665

[2 rows x 50 columns]
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019198252289145148, Original: 9.762922791515482, New: 9.575491736684523
Test: Improvement: 0.028407558294248413, Original: 10.2199936987652, New: 9.929668632000675

-------------------------
   learning_rate  batch_size  \
0          0.001          32
2          0.001         128
1          0.001          64

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
2                     0.019578                  16.779288
1                     0.121240                  19.599332

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
2                      12.671384                        9.929669
1                      13.656527                       10.127691

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                   0.5696
2                     11.011382                   0.5696
1                     14.072658                   0.5728

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
2                    0.028408                               0.023803
1                    0.009032                               0.012048

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
2                             0.022912                             0.023353
1                             0.011293                             0.011665

[3 rows x 50 columns]
  lr-0.01
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.014454560597921922, Original: 9.762922791515482, New: 9.621804032412689
Test: Improvement: 0.017916362140951148, Original: 10.2199936987652, New: 10.036888590579883

-------------------------
   learning_rate  batch_size  \
0          0.001          32
2          0.001         128
3          0.010          32
1          0.001          64

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
2                     0.019578                  16.779288
3                     0.028812                  19.862303
1                     0.121240                  19.599332

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
2                      12.671384                        9.929669
3                      13.478791                       10.036889
1                      13.656527                       10.127691

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                 0.569600
2                     11.011382                 0.569600
3                     14.603152                 0.566031
1                     14.072658                 0.572800

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
2                    0.028408                               0.023803
3                    0.017916                               0.016185
1                    0.009032                               0.012048

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
2                             0.022912                             0.023353
3                             0.016000                             0.016093
1                             0.011293                             0.011665

[4 rows x 50 columns]
        batch-64
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.010808033688982761, Original: 9.762922791515482, New: 9.657404793081845
Test: Improvement: 0.0014720544077684407, Original: 10.2199936987652, New: 10.204949311993566

-------------------------
   learning_rate  batch_size  \
0          0.001          32
2          0.001         128
3          0.010          32
1          0.001          64
4          0.010          64

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
2                     0.019578                  16.779288
3                     0.028812                  19.862303
1                     0.121240                  19.599332
4                    -0.317714                  30.469168

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
2                      12.671384                        9.929669
3                      13.478791                       10.036889
1                      13.656527                       10.127691
4                      14.768954                       10.204949

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                 0.569600
2                     11.011382                 0.569600
3                     14.603152                 0.566031
1                     14.072658                 0.572800
4                     26.652188                 0.567015

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
2                    0.028408                               0.023803
3                    0.017916                               0.016185
1                    0.009032                               0.012048
4                    0.001472                               0.006140

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
2                             0.022912                             0.023353
3                             0.016000                             0.016093
1                             0.011293                             0.011665
4                             0.002591                             0.003989

[5 rows x 50 columns]
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
6 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01414042123652744, Original: 9.762922791515482, New: 9.624870950743759
Test: Improvement: 0.011385396847436833, Original: 10.2199936987652, New: 10.103635014726454

-------------------------
   learning_rate  batch_size  \
0          0.001          32
2          0.001         128
3          0.010          32
5          0.010         128
1          0.001          64
4          0.010          64

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
2                     0.019578                  16.779288
3                     0.028812                  19.862303
5                    -0.837825                  19.519419
1                     0.121240                  19.599332
4                    -0.317714                  30.469168

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
2                      12.671384                        9.929669
3                      13.478791                       10.036889
5                      13.520456                       10.103635
1                      13.656527                       10.127691
4                      14.768954                       10.204949

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                 0.569600
2                     11.011382                 0.569600
3                     14.603152                 0.566031
5                     14.089289                 0.563077
1                     14.072658                 0.572800
4                     26.652188                 0.567015

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
2                    0.028408                               0.023803
3                    0.017916                               0.016185
5                    0.011385                               0.012763
1                    0.009032                               0.012048
4                    0.001472                               0.006140

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
2                             0.022912                             0.023353
3                             0.016000                             0.016093
5                             0.012614                             0.012688
1                             0.011293                             0.011665
4                             0.002591                             0.003989

[6 rows x 50 columns]
  lr-0.1
        batch-32
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.01})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
7 9
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0011385856585239518, Original: 9.762922791515482, New: 9.774038715391178
Test: Improvement: 0.005825190924855657, Original: 10.2199936987652, New: 10.16046028421907

-------------------------
   learning_rate  batch_size  \
0          0.001          32
2          0.001         128
3          0.010          32
5          0.010         128
1          0.001          64
4          0.010          64
6          0.100          32

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
2                     0.019578                  16.779288
3                     0.028812                  19.862303
5                    -0.837825                  19.519419
1                     0.121240                  19.599332
4                    -0.317714                  30.469168
6                    -1.069915                  19.310426

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
2                      12.671384                        9.929669
3                      13.478791                       10.036889
5                      13.520456                       10.103635
1                      13.656527                       10.127691
4                      14.768954                       10.204949
6                      13.335981                       10.160460

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                 0.569600
2                     11.011382                 0.569600
3                     14.603152                 0.566031
5                     14.089289                 0.563077
1                     14.072658                 0.572800
4                     26.652188                 0.567015
6                     14.027974                 0.560123

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
2                    0.028408                               0.023803
3                    0.017916                               0.016185
5                    0.011385                               0.012763
1                    0.009032                               0.012048
4                    0.001472                               0.006140
6                    0.005825                               0.002343

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
2                             0.022912                             0.023353
3                             0.016000                             0.016093
5                             0.012614                             0.012688
1                             0.011293                             0.011665
4                             0.002591                             0.003989
6                            -0.002830                                  NaN

[7 rows x 50 columns]
        batch-64
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.1})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
8 9

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0018205044043799257, Original: 9.762922791515482, New: 9.780696235457057
Test: Improvement: 0.0019769672178153877, Original: 10.2199936987652, New: 10.19978910625646

-------------------------
   learning_rate  batch_size  \
0          0.001          32
2          0.001         128
3          0.010          32
5          0.010         128
1          0.001          64
4          0.010          64
6          0.100          32
7          0.100          64

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
2                     0.019578                  16.779288
3                     0.028812                  19.862303
5                    -0.837825                  19.519419
1                     0.121240                  19.599332
4                    -0.317714                  30.469168
6                    -1.069915                  19.310426
7                    -0.958693                  26.420327

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
2                      12.671384                        9.929669
3                      13.478791                       10.036889
5                      13.520456                       10.103635
1                      13.656527                       10.127691
4                      14.768954                       10.204949
6                      13.335981                       10.160460
7                      13.417024                       10.199789

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                 0.569600
2                     11.011382                 0.569600
3                     14.603152                 0.566031
5                     14.089289                 0.563077
1                     14.072658                 0.572800
4                     26.652188                 0.567015
6                     14.027974                 0.560123
7                     22.798087                 0.497354

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
2                    0.028408                               0.023803
3                    0.017916                               0.016185
5                    0.011385                               0.012763
1                    0.009032                               0.012048
4                    0.001472                               0.006140
6                    0.005825                               0.002343
7                    0.001977                               0.000078

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
2                             0.022912                             0.023353
3                             0.016000                             0.016093
5                             0.012614                             0.012688
1                             0.011293                             0.011665
4                             0.002591                             0.003989
6                            -0.002830                                  NaN
7                            -0.046006                                  NaN

[8 rows x 50 columns]
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.1})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
9 9

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.00045850354002569156, Original: 9.762922791515482, New: 9.758446456854575
Test: Improvement: 0.003110024300012983, Original: 10.2199936987652, New: 10.18820927001606

-------------------------
   learning_rate  batch_size  \
0          0.001          32
2          0.001         128
3          0.010          32
5          0.010         128
1          0.001          64
4          0.010          64
8          0.100         128
6          0.100          32
7          0.100          64

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.303319                  17.385317
2                     0.019578                  16.779288
3                     0.028812                  19.862303
5                    -0.837825                  19.519419
1                     0.121240                  19.599332
4                    -0.317714                  30.469168
8                    -1.055546                  23.325843
6                    -1.069915                  19.310426
7                    -0.958693                  26.420327

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.878848                        9.916449
2                      12.671384                        9.929669
3                      13.478791                       10.036889
5                      13.520456                       10.103635
1                      13.656527                       10.127691
4                      14.768954                       10.204949
8                      13.583548                       10.188209
6                      13.335981                       10.160460
7                      13.417024                       10.199789

   validation_test_abserror_std  validation_test_success  \
0                     11.701023                 0.569600
2                     11.011382                 0.569600
3                     14.603152                 0.566031
5                     14.089289                 0.563077
1                     14.072658                 0.572800
4                     26.652188                 0.567015
8                     18.998929                 0.562708
6                     14.027974                 0.560123
7                     22.798087                 0.497354

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029701                               0.025781
2                    0.028408                               0.023803
3                    0.017916                               0.016185
5                    0.011385                               0.012763
1                    0.009032                               0.012048
4                    0.001472                               0.006140
8                    0.003110                               0.001784
6                    0.005825                               0.002343
7                    0.001977                               0.000078

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025185                             0.025481
2                             0.022912                             0.023353
3                             0.016000                             0.016093
5                             0.012614                             0.012688
1                             0.011293                             0.011665
4                             0.002591                             0.003989
8                             0.000799                             0.001194
6                            -0.002830                                  NaN
7                            -0.046006                                  NaN

[9 rows x 50 columns]
BS Selected -  [128]
LR Selected -  [0.001]

'''''''' optimizers
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.1})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 1

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02206176817164021, Original: 9.762922791515482, New: 9.547535452211445
Test: Improvement: 0.03018169632042263, Original: 10.2199936987652, New: 9.911536952552435

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.002112                  16.805052

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.670237                        9.911537

   validation_test_abserror_std  validation_test_success  \
0                     11.046981                 0.567015

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.030182                               0.026122

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025491                             0.025804

[1 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 1
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.026342844211493556, Original: 9.762922791515482, New: 9.50573963736975
Test: Improvement: 0.03002542587147697, Original: 10.2199936987652, New: 9.913134035555963

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.258406                  17.119878

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.764773                        9.913134

   validation_test_abserror_std  validation_test_success  \
0                     11.431706                 0.572185

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.030025                               0.028184

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.028064                             0.028124

[1 rows x 50 columns]
optimizers Selected -  [(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})]

'''''''' loss_functions
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 6, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.MeanSquaredError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.011368408464543013, Original: 9.762922791515482, New: 9.651933897413738
Test: Improvement: 0.015532923749074674, Original: 10.2199936987652, New: 10.061247315926256

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.MeanSquaredError'>, ...

                           loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.632036                  17.362714

   validation_test_abserror_mean validation_test_abserror_median  \
0                       12.88264                       10.061247

   validation_test_abserror_std  validation_test_success  \
0                     11.645341                 0.559508

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.015533                               0.013451

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.013128                             0.013289

[1 rows x 50 columns]
              loss-(<class 'keras.src.losses.MeanAbsoluteError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021076232660941746, Original: 9.762922791515482, New: 9.557157159310691
Test: Improvement: 0.030461225590212457, Original: 10.2199936987652, New: 9.908680165176563

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...

                            loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.257851                  16.698528
0                    -0.632036                  17.362714

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.636011                        9.908680
0                      12.882640                       10.061247

   validation_test_abserror_std  validation_test_success  \
1                     10.935729                 0.569477
0                     11.645341                 0.559508

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.030461                               0.025769
0                    0.015533                               0.013451

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.024914                             0.025338
0                             0.013128                             0.013289

[2 rows x 50 columns]
              loss-(<class 'keras.src.losses.MeanAbsolutePercentageError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0020403253822086614, Original: 9.762922791515482, New: 9.782842330691555
Test: Improvement: 0.0008951867911342724, Original: 10.2199936987652, New: 10.210844895400589

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128
2          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...

                                 loss_function_class   loss_function_params  \
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.257851                  16.698528
0                    -0.632036                  17.362714
2                    -0.608455                  16.908233

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.636011                        9.908680
0                      12.882640                       10.061247
2                      12.839651                       10.210845

   validation_test_abserror_std  validation_test_success  \
1                     10.935729                 0.569477
0                     11.645341                 0.559508
2                     11.001645                 0.508923

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.030461                               0.025769
0                    0.015533                               0.013451
2                    0.000895                              -0.000573

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.024914                             0.025338
0                             0.013128                             0.013289
2                             0.003190                                  NaN

[3 rows x 50 columns]
              loss-(<class 'keras.src.losses.MeanSquaredLogarithmicError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 6

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0155604557411793, Original: 9.762922791515482, New: 9.91483831951741
Test: Improvement: 0.004976034773733092, Original: 10.2199936987652, New: 10.16913865473281

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128
2          0.001         128
3          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...
3  (<class 'keras.src.losses.MeanSquaredLogarithm...

                                 loss_function_class   loss_function_params  \
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}
3  <class 'keras.src.losses.MeanSquaredLogarithmi...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.257851                  16.698528
0                    -0.632036                  17.362714
2                    -0.608455                  16.908233
3                     4.613841                  16.737923

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.636011                        9.908680
0                      12.882640                       10.061247
2                      12.839651                       10.210845
3                      13.243091                       10.169139

   validation_test_abserror_std  validation_test_success  \
1                     10.935729                 0.569477
0                     11.645341                 0.559508
2                     11.001645                 0.508923
3                     11.470301                 0.514954

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.030461                               0.025769
0                    0.015533                               0.013451
2                    0.000895                              -0.000573
3                    0.004976                              -0.005292

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.024914                             0.025338
0                             0.013128                             0.013289
2                             0.003190                                  NaN
3                             0.014631                                  NaN

[4 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 6

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02199989554831211, Original: 9.762922791515482, New: 9.548139509855906
Test: Improvement: 0.0293772275212838, Original: 10.2199936987652, New: 9.919758618610487

-------------------------
   learning_rate  batch_size  \
4          0.001         128
1          0.001         128
0          0.001         128
2          0.001         128
3          0.001         128

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...
3  (<class 'keras.src.losses.MeanSquaredLogarithm...

                                 loss_function_class   loss_function_params  \
4                   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}
3  <class 'keras.src.losses.MeanSquaredLogarithmi...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                     0.119345                  17.770689
1                     0.257851                  16.698528
0                    -0.632036                  17.362714
2                    -0.608455                  16.908233
3                     4.613841                  16.737923

   validation_test_abserror_mean validation_test_abserror_median  \
4                      12.987090                        9.919759
1                      12.636011                        9.908680
0                      12.882640                       10.061247
2                      12.839651                       10.210845
3                      13.243091                       10.169139

   validation_test_abserror_std  validation_test_success  \
4                     12.140010                 0.573538
1                     10.935729                 0.569477
0                     11.645341                 0.559508
2                     11.001645                 0.508923
3                     11.470301                 0.514954

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.029377                               0.025689
1                    0.030461                               0.025769
0                    0.015533                               0.013451
2                    0.000895                              -0.000573
3                    0.004976                              -0.005292

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.025159                             0.025422
1                             0.024914                             0.025338
0                             0.013128                             0.013289
2                             0.003190                                  NaN
3                             0.014631                                  NaN

[5 rows x 50 columns]
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
6 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02435734465925297, Original: 9.762922791515482, New: 9.525123916200863
Test: Improvement: 0.033573649257008925, Original: 10.2199936987652, New: 9.876871214914015

-------------------------
   learning_rate  batch_size  \
5          0.001         128
4          0.001         128
1          0.001         128
0          0.001         128
2          0.001         128
3          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...
3  (<class 'keras.src.losses.MeanSquaredLogarithm...

                                 loss_function_class   loss_function_params  \
5                 <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4                   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}
3  <class 'keras.src.losses.MeanSquaredLogarithmi...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.070719                  17.011438
4                     0.119345                  17.770689
1                     0.257851                  16.698528
0                    -0.632036                  17.362714
2                    -0.608455                  16.908233
3                     4.613841                  16.737923

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.730224                        9.876871
4                      12.987090                        9.919759
1                      12.636011                        9.908680
0                      12.882640                       10.061247
2                      12.839651                       10.210845
3                      13.243091                       10.169139

   validation_test_abserror_std  validation_test_success  \
5                     11.297306                 0.572062
4                     12.140010                 0.573538
1                     10.935729                 0.569477
0                     11.645341                 0.559508
2                     11.001645                 0.508923
3                     11.470301                 0.514954

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.033574                               0.028965
4                    0.029377                               0.025689
1                    0.030461                               0.025769
0                    0.015533                               0.013451
2                    0.000895                              -0.000573
3                    0.004976                              -0.005292

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.028232                             0.028597
4                             0.025159                             0.025422
1                             0.024914                             0.025338
0                             0.013128                             0.013289
2                             0.003190                                  NaN
3                             0.014631                                  NaN

[6 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 6, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.MeanSquaredError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.008615284097437996, Original: 9.762922791515482, New: 9.678812438045224
Test: Improvement: 0.021548474387203576, Original: 10.2199936987652, New: 9.999768426309975

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.MeanSquaredError'>, ...

                           loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.584101                  16.593461

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.623174                        9.999768

   validation_test_abserror_std  validation_test_success  \
0                     10.772278                   0.5568

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.021548                               0.015082

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.012309                             0.013625

[1 rows x 50 columns]
              loss-(<class 'keras.src.losses.MeanAbsoluteError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02456267208636838, Original: 9.762922791515482, New: 9.523119320382955
Test: Improvement: 0.02892574883702937, Original: 10.2199936987652, New: 9.924372727918694

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...

                            loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.226084                  16.904718
0                    -0.584101                  16.593461

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.693468                        9.924373
0                      12.623174                        9.999768

   validation_test_abserror_std  validation_test_success  \
1                     11.182865                 0.571569
0                     10.772278                 0.556800

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.028926                               0.026744
0                    0.021548                               0.015082

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.026566                             0.026655
0                             0.012309                             0.013625

[2 rows x 50 columns]
              loss-(<class 'keras.src.losses.MeanAbsolutePercentageError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: -0.0007181366791203373, Original: 9.762922791515482, New: 9.76993390446749
Test: Improvement: 0.004237639296617437, Original: 10.2199936987652, New: 10.17668505185613

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128
2          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...

                                 loss_function_class   loss_function_params  \
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.226084                  16.904718
0                    -0.584101                  16.593461
2                    -0.839660                  16.872029

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.693468                        9.924373
0                      12.623174                        9.999768
2                      12.820036                       10.176685

   validation_test_abserror_std  validation_test_success  \
1                     11.182865                 0.571569
0                     10.772278                 0.556800
2                     10.976231                 0.498708

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.028926                               0.026744
0                    0.021548                               0.015082
2                    0.004238                               0.001760

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.026566                             0.026655
0                             0.012309                             0.013625
2                            -0.001729                                  NaN

[3 rows x 50 columns]
              loss-(<class 'keras.src.losses.MeanSquaredLogarithmicError'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 6

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 4s 3ms/step
Training: Improvement: -0.0203710146210596, Original: 9.762922791515482, New: 9.96180343444572
Test: Improvement: 0.002920201827187431, Original: 10.2199936987652, New: 10.190149254492221

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128
2          0.001         128
3          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...
3  (<class 'keras.src.losses.MeanSquaredLogarithm...

                                 loss_function_class   loss_function_params  \
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}
3  <class 'keras.src.losses.MeanSquaredLogarithmi...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.226084                  16.904718
0                    -0.584101                  16.593461
2                    -0.839660                  16.872029
3                     4.609944                  16.750541

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.693468                        9.924373
0                      12.623174                        9.999768
2                      12.820036                       10.176685
3                      13.260189                       10.190149

   validation_test_abserror_std  validation_test_success  \
1                     11.182865                 0.571569
0                     10.772278                 0.556800
2                     10.976231                 0.498708
3                     11.481873                 0.514954

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.028926                               0.026744
0                    0.021548                               0.015082
2                    0.004238                               0.001760
3                    0.002920                              -0.008725

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.026566                             0.026655
0                             0.012309                             0.013625
2                            -0.001729                                  NaN
3                             0.006818                                  NaN

[4 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 6

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.022612440112563064, Original: 9.762922791515482, New: 9.542159284568761
Test: Improvement: 0.0329729508374242, Original: 10.2199936987652, New: 9.88301034897703

-------------------------
   learning_rate  batch_size  \
4          0.001         128
1          0.001         128
0          0.001         128
2          0.001         128
3          0.001         128

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...
3  (<class 'keras.src.losses.MeanSquaredLogarithm...

                                 loss_function_class   loss_function_params  \
4                   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}
3  <class 'keras.src.losses.MeanSquaredLogarithmi...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                     0.004031                  16.929113
1                     0.226084                  16.904718
0                    -0.584101                  16.593461
2                    -0.839660                  16.872029
3                     4.609944                  16.750541

   validation_test_abserror_mean validation_test_abserror_median  \
4                      12.703661                        9.883010
1                      12.693468                        9.924373
0                      12.623174                        9.999768
2                      12.820036                       10.176685
3                      13.260189                       10.190149

   validation_test_abserror_std  validation_test_success  \
4                     11.198931                 0.571200
1                     11.182865                 0.571569
0                     10.772278                 0.556800
2                     10.976231                 0.498708
3                     11.481873                 0.514954

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.032973                               0.027793
1                    0.028926                               0.026744
0                    0.021548                               0.015082
2                    0.004238                               0.001760
3                    0.002920                              -0.008725

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.026827                             0.027306
1                             0.026566                             0.026655
0                             0.012309                             0.013625
2                            -0.001729                                  NaN
3                             0.006818                                  NaN

[5 rows x 50 columns]
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
6 6
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.006745340422765642, Original: 9.762922791515482, New: 9.697068553765533
Test: Improvement: 0.013538047927569517, Original: 10.2199936987652, New: 10.081634934251857

-------------------------
   learning_rate  batch_size  \
4          0.001         128
1          0.001         128
0          0.001         128
5          0.001         128
2          0.001         128
3          0.001         128

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.MeanAbsoluteError'>,...
0  (<class 'keras.src.losses.MeanSquaredError'>, ...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.MeanAbsolutePercenta...
3  (<class 'keras.src.losses.MeanSquaredLogarithm...

                                 loss_function_class   loss_function_params  \
4                   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1       <class 'keras.src.losses.MeanAbsoluteError'>  {'reduction': 'auto'}
0        <class 'keras.src.losses.MeanSquaredError'>  {'reduction': 'auto'}
5                 <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.MeanAbsolutePercentag...  {'reduction': 'auto'}
3  <class 'keras.src.losses.MeanSquaredLogarithmi...  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                     0.004031                  16.929113
1                     0.226084                  16.904718
0                    -0.584101                  16.593461
5                    -0.283701                  16.722111
2                    -0.839660                  16.872029
3                     4.609944                  16.750541

   validation_test_abserror_mean validation_test_abserror_median  \
4                      12.703661                        9.883010
1                      12.693468                        9.924373
0                      12.623174                        9.999768
5                      12.705970                       10.081635
2                      12.820036                       10.176685
3                      13.260189                       10.190149

   validation_test_abserror_std  validation_test_success  \
4                     11.198931                 0.571200
1                     11.182865                 0.571569
0                     10.772278                 0.556800
5                     10.871140                 0.563077
2                     10.976231                 0.498708
3                     11.481873                 0.514954

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.032973                               0.027793
1                    0.028926                               0.026744
0                    0.021548                               0.015082
5                    0.013538                               0.010142
2                    0.004238                               0.001760
3                    0.002920                              -0.008725

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.026827                             0.027306
1                             0.026566                             0.026655
0                             0.012309                             0.013625
5                             0.009004                             0.009556
2                            -0.001729                                  NaN
3                             0.006818                                  NaN

[6 rows x 50 columns]
loss_functions Selected -  [(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'}), (<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})]

'''''''' class_weights_enabled
class_weights_enabled: 2, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02214813174889844, Original: 9.762922791515482, New: 9.546692291274674
Test: Improvement: 0.025850089055776376, Original: 10.2199936987652, New: 9.955805951502645

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.150675                  16.739316

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.644828                        9.955806

   validation_test_abserror_std  validation_test_success  \
0                     10.971945                 0.565292

  validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.02585                               0.023999

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.023856                             0.023928

[1 rows x 50 columns]
                              class_weights_enabled -False
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.018378633319920193, Original: 9.762922791515482, New: 9.583493613399527
Test: Improvement: 0.02603662141470528, Original: 10.2199936987652, New: 9.953899591969776

-------------------------
   learning_rate  batch_size  \
0          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.150675                  16.739316
1                     0.023232                  16.652858

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.644828                        9.955806
1                      12.616939                        9.953900

   validation_test_abserror_std  validation_test_success  \
0                     10.971945                 0.565292
1                     10.874570                 0.575877

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.025850                               0.023999
1                    0.026037                               0.022208

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.023856                             0.023928
1                             0.021547                             0.021875

[2 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02343794471683026, Original: 9.762922791515482, New: 9.53409994685326
Test: Improvement: 0.03225113448374535, Original: 10.2199936987652, New: 9.890387307563293

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.039069                  16.794435
0                    -0.150675                  16.739316
1                     0.023232                  16.652858

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.656705                        9.890387
0                      12.644828                        9.955806
1                      12.616939                        9.953900

   validation_test_abserror_std  validation_test_success  \
2                     11.045917                 0.570831
0                     10.971945                 0.565292
1                     10.874570                 0.575877

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.032251                               0.027845
0                    0.025850                               0.023999
1                    0.026037                               0.022208

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.027147                             0.027494
0                             0.023856                             0.023928
1                             0.021547                             0.021875

[3 rows x 50 columns]
                              class_weights_enabled -False
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01894379752250354, Original: 9.762922791515482, New: 9.577975958925178
Test: Improvement: 0.022298029052053178, Original: 10.2199936987652, New: 9.992107982358332

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128
3          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
2    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.039069                  16.794435
0                    -0.150675                  16.739316
1                     0.023232                  16.652858
3                     0.324555                  17.909495

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.656705                        9.890387
0                      12.644828                        9.955806
1                      12.616939                        9.953900
3                      13.061412                        9.992108

   validation_test_abserror_std  validation_test_success  \
2                     11.045917                 0.570831
0                     10.971945                 0.565292
1                     10.874570                 0.575877
3                     12.275982                 0.572800

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.032251                               0.027845
0                    0.025850                               0.023999
1                    0.026037                               0.022208
3                    0.022298                               0.020621

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.027147                             0.027494
0                             0.023856                             0.023928
1                             0.021547                             0.021875
3                             0.020485                             0.020553

[4 rows x 50 columns]
class_weights_enabled: 2, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.011712148142743793, Original: 9.762922791515482, New: 9.648577993475083
Test: Improvement: 0.01601964222555703, Original: 10.2199936987652, New: 10.056273056163533

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.078593                  16.707573

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.691665                       10.056273

   validation_test_abserror_std  validation_test_success  \
0                     10.870629                 0.565169

  validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.01602                               0.013866

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.013531                             0.013698

[1 rows x 50 columns]
                              class_weights_enabled -False
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022761598914673897, Original: 9.762922791515482, New: 9.540703058700078
Test: Improvement: 0.02560151592467121, Original: 10.2199936987652, New: 9.958346367336222

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.448767                  17.690564
0                    -0.078593                  16.707573

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.952514                        9.958346
0                      12.691665                       10.056273

   validation_test_abserror_std  validation_test_success  \
1                     12.092779                 0.573415
0                     10.870629                 0.565169

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.025602                               0.024182
0                    0.016020                               0.013866

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.024098                             0.024140
0                             0.013531                             0.013698

[2 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 4s 2ms/step
Training: Improvement: 0.021342665487104902, Original: 9.762922791515482, New: 9.554555996199735
Test: Improvement: 0.029576793146454318, Original: 10.2199936987652, New: 9.917719059178754

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.106925                  16.675812
1                     0.448767                  17.690564
0                    -0.078593                  16.707573

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.611867                        9.917719
1                      12.952514                        9.958346
0                      12.691665                       10.056273

   validation_test_abserror_std  validation_test_success  \
2                     10.919833                 0.572062
1                     12.092779                 0.573415
0                     10.870629                 0.565169

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.029577                               0.025460
1                    0.025602                               0.024182
0                    0.016020                               0.013866

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.024794                             0.025125
1                             0.024098                             0.024140
0                             0.013531                             0.013698

[3 rows x 50 columns]
                              class_weights_enabled -False
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 4
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 4s 2ms/step
Training: Improvement: 0.024322419589443957, Original: 9.762922791515482, New: 9.525464886960897
Test: Improvement: 0.02848669953185386, Original: 10.2199936987652, New: 9.928859809051035

-------------------------
   learning_rate  batch_size  \
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                    -0.089257                  16.913845
2                     0.106925                  16.675812
1                     0.448767                  17.690564
0                    -0.078593                  16.707573

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.701111                        9.928860
2                      12.611867                        9.917719
1                      12.952514                        9.958346
0                      12.691665                       10.056273

   validation_test_abserror_std  validation_test_success  \
3                     11.175715                 0.570338
2                     10.919833                 0.572062
1                     12.092779                 0.573415
0                     10.870629                 0.565169

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.028487                               0.026405
2                    0.029577                               0.025460
1                    0.025602                               0.024182
0                    0.016020                               0.013866

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026240                             0.026322
2                             0.024794                             0.025125
1                             0.024098                             0.024140
0                             0.013531                             0.013698

[4 rows x 50 columns]
class_weights_enabled Selected -  [True]

'''''''' stratification_enabled
'''''''' dropout_enabled
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 2, dropout_rates: 9, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -False
                              dropout_rates -None
                              early_stopping_metric -val_root_mean_squared_error
1 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.008973248388005324, Original: 9.762922791515482, New: 9.675317660314295
Test: Improvement: -0.002295807437347408, Original: 10.2199936987652, New: 10.243456836308468

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                      0.32949                  19.943449

   validation_test_abserror_mean validation_test_abserror_median  \
0                      13.804278                       10.243457

   validation_test_abserror_std  validation_test_success  \
0                     14.427803                 0.570954

  validation_test_improvement  validation_avg_train_test_improvement  \
0                   -0.002296                               0.003339

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             -0.00617                                  NaN

[1 rows x 50 columns]
                              dropout_enabled -True
                              dropout_rates -0.1
                              early_stopping_metric -val_root_mean_squared_error
2 36

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: -0.09329339357814068, Original: 9.762922791515482, New: 10.673738989977336
Test: Improvement: -0.1338298580282695, Original: 10.2199936987652, New: 11.587734004520755

-------------------------
   learning_rate  batch_size  \
0          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.329490                  19.943449
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
0                      13.804278                       10.243457
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
0                     14.427803                 0.570954
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
0                   -0.002296                               0.003339
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                            -0.006170                                  NaN
1                            -0.109944                                  NaN

[2 rows x 50 columns]
                              dropout_rates -0.2
                              early_stopping_metric -val_root_mean_squared_error
3 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.008817066364715225, Original: 9.762922791515482, New: 9.6768424533491
Test: Improvement: 0.012249629300078687, Original: 10.2199936987652, New: 10.094802564506185

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     1.784585                  18.726619
0                     0.329490                  19.943449
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
2                      13.509881                       10.094803
0                      13.804278                       10.243457
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
2                     13.227120                 0.563569
0                     14.427803                 0.570954
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
1                            -0.109944                                  NaN

[3 rows x 50 columns]
                              dropout_rates -0.3
                              early_stopping_metric -val_root_mean_squared_error
4 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.07106317374853963, Original: 9.762922791515482, New: 10.456707070142524
Test: Improvement: -0.09997087976950435, Original: 10.2199936987652, New: 11.241695460069547

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
3          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     1.784585                  18.726619
0                     0.329490                  19.943449
3                     0.328753                  33.269110
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
2                      13.509881                       10.094803
0                      13.804278                       10.243457
3                      17.725559                       11.241695
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
2                     13.227120                 0.563569
0                     14.427803                 0.570954
3                     28.156966                 0.568738
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
3                   -0.099971                              -0.085517
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
3                            -0.083074                                  NaN
1                            -0.109944                                  NaN

[4 rows x 50 columns]
                              dropout_rates -0.4
                              early_stopping_metric -val_root_mean_squared_error
5 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.012414436128041165, Original: 9.762922791515482, New: 9.641721610097216
Test: Improvement: 0.01248687316225332, Original: 10.2199936987652, New: 10.09237793372969

-------------------------
   learning_rate  batch_size  \
4          0.001         128
2          0.001         128
0          0.001         128
3          0.001         128
1          0.001         128

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                     0.966627                  18.924674
2                     1.784585                  18.726619
0                     0.329490                  19.943449
3                     0.328753                  33.269110
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
4                      13.434638                       10.092378
2                      13.509881                       10.094803
0                      13.804278                       10.243457
3                      17.725559                       11.241695
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
4                     13.436415                 0.571200
2                     13.227120                 0.563569
0                     14.427803                 0.570954
3                     28.156966                 0.568738
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.012487                               0.012451
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
3                   -0.099971                              -0.085517
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.012451                             0.012451
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
3                            -0.083074                                  NaN
1                            -0.109944                                  NaN

[5 rows x 50 columns]
                              dropout_rates -0.5
                              early_stopping_metric -val_root_mean_squared_error
6 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023052533905589954, Original: 9.762922791515482, New: 9.537862682846415
Test: Improvement: 0.030819201031762, Original: 10.2199936987652, New: 9.905021658419614

-------------------------
   learning_rate  batch_size  \
5          0.001         128
4          0.001         128
2          0.001         128
0          0.001         128
3          0.001         128
1          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.069935                  16.986607
4                     0.966627                  18.924674
2                     1.784585                  18.726619
0                     0.329490                  19.943449
3                     0.328753                  33.269110
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.726562                        9.905022
4                      13.434638                       10.092378
2                      13.509881                       10.094803
0                      13.804278                       10.243457
3                      17.725559                       11.241695
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
5                     11.259364                 0.574277
4                     13.436415                 0.571200
2                     13.227120                 0.563569
0                     14.427803                 0.570954
3                     28.156966                 0.568738
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.030819                               0.026936
4                    0.012487                               0.012451
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
3                   -0.099971                              -0.085517
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.026376                             0.026654
4                             0.012451                             0.012451
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
3                            -0.083074                                  NaN
1                            -0.109944                                  NaN

[6 rows x 50 columns]
                              dropout_rates -0.6
                              early_stopping_metric -val_root_mean_squared_error
7 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02221310000179225, Original: 9.762922791515482, New: 9.546058011237772
Test: Improvement: 0.030644978973807226, Original: 10.2199936987652, New: 9.906802206754097

-------------------------
   learning_rate  batch_size  \
5          0.001         128
6          0.001         128
4          0.001         128
2          0.001         128
0          0.001         128
3          0.001         128
1          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.069935                  16.986607
6                     0.703915                  17.010997
4                     0.966627                  18.924674
2                     1.784585                  18.726619
0                     0.329490                  19.943449
3                     0.328753                  33.269110
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.726562                        9.905022
6                      12.755514                        9.906802
4                      13.434638                       10.092378
2                      13.509881                       10.094803
0                      13.804278                       10.243457
3                      17.725559                       11.241695
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
5                     11.259364                 0.574277
6                     11.330951                 0.567877
4                     13.436415                 0.571200
2                     13.227120                 0.563569
0                     14.427803                 0.570954
3                     28.156966                 0.568738
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.030819                               0.026936
6                    0.030645                               0.026429
4                    0.012487                               0.012451
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
3                   -0.099971                              -0.085517
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.026376                             0.026654
6                             0.025757                             0.026091
4                             0.012451                             0.012451
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
3                            -0.083074                                  NaN
1                            -0.109944                                  NaN

[7 rows x 50 columns]
                              dropout_rates -0.7
                              early_stopping_metric -val_root_mean_squared_error
8 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024424513996614997, Original: 9.762922791515482, New: 9.52446814714624
Test: Improvement: 0.03067790031815656, Original: 10.2199936987652, New: 9.906465750822292

-------------------------
   learning_rate  batch_size  \
7          0.001         128
5          0.001         128
6          0.001         128
4          0.001         128
2          0.001         128
0          0.001         128
3          0.001         128
1          0.001         128

                                           optimizer  \
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
7  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
7  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
7  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
7                     0.060803                  16.890374
5                     0.069935                  16.986607
6                     0.703915                  17.010997
4                     0.966627                  18.924674
2                     1.784585                  18.726619
0                     0.329490                  19.943449
3                     0.328753                  33.269110
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
7                      12.708094                        9.906466
5                      12.726562                        9.905022
6                      12.755514                        9.906802
4                      13.434638                       10.092378
2                      13.509881                       10.094803
0                      13.804278                       10.243457
3                      17.725559                       11.241695
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
7                     11.141593                 0.574154
5                     11.259364                 0.574277
6                     11.330951                 0.567877
4                     13.436415                 0.571200
2                     13.227120                 0.563569
0                     14.427803                 0.570954
3                     28.156966                 0.568738
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
7                    0.030678                               0.027551
5                    0.030819                               0.026936
6                    0.030645                               0.026429
4                    0.012487                               0.012451
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
3                   -0.099971                              -0.085517
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                             0.027196                             0.027373
5                             0.026376                             0.026654
6                             0.025757                             0.026091
4                             0.012451                             0.012451
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
3                            -0.083074                                  NaN
1                            -0.109944                                  NaN

[8 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
9 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0214739529533081, Original: 9.762922791515482, New: 9.5532742468037
Test: Improvement: 0.03084181068024929, Original: 10.2199936987652, New: 9.904790587954542

-------------------------
   learning_rate  batch_size  \
7          0.001         128
5          0.001         128
6          0.001         128
8          0.001         128
4          0.001         128
2          0.001         128
0          0.001         128
3          0.001         128
1          0.001         128

                                           optimizer  \
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
7  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
7  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
7  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
7                     0.060803                  16.890374
5                     0.069935                  16.986607
6                     0.703915                  17.010997
8                    -0.028551                  16.742456
4                     0.966627                  18.924674
2                     1.784585                  18.726619
0                     0.329490                  19.943449
3                     0.328753                  33.269110
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
7                      12.708094                        9.906466
5                      12.726562                        9.905022
6                      12.755514                        9.906802
8                      12.643260                        9.904791
4                      13.434638                       10.092378
2                      13.509881                       10.094803
0                      13.804278                       10.243457
3                      17.725559                       11.241695
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
7                     11.141593                 0.574154
5                     11.259364                 0.574277
6                     11.330951                 0.567877
8                     10.982498                 0.566400
4                     13.436415                 0.571200
2                     13.227120                 0.563569
0                     14.427803                 0.570954
3                     28.156966                 0.568738
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
7                    0.030678                               0.027551
5                    0.030819                               0.026936
6                    0.030645                               0.026429
8                    0.030842                               0.026158
4                    0.012487                               0.012451
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
3                   -0.099971                              -0.085517
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                             0.027196                             0.027373
5                             0.026376                             0.026654
6                             0.025757                             0.026091
8                             0.025319                             0.025735
4                             0.012451                             0.012451
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
3                            -0.083074                                  NaN
1                            -0.109944                                  NaN

[9 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
10 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021266332157764162, Original: 9.762922791515482, New: 9.555301232600508
Test: Improvement: 0.028203189295349224, Original: 10.2199936987652, New: 9.931757281881648

-------------------------
   learning_rate  batch_size  \
7          0.001         128
5          0.001         128
6          0.001         128
8          0.001         128
9          0.001         128
4          0.001         128
2          0.001         128
0          0.001         128
3          0.001         128
1          0.001         128

                                           optimizer  \
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
7  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
9  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
7  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.LogCosh'>, {'reducti...
9  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
7  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
7                     0.060803                  16.890374
5                     0.069935                  16.986607
6                     0.703915                  17.010997
8                    -0.028551                  16.742456
9                     0.111419                  16.742096
4                     0.966627                  18.924674
2                     1.784585                  18.726619
0                     0.329490                  19.943449
3                     0.328753                  33.269110
1                     0.816052                  34.182586

   validation_test_abserror_mean validation_test_abserror_median  \
7                      12.708094                        9.906466
5                      12.726562                        9.905022
6                      12.755514                        9.906802
8                      12.643260                        9.904791
9                      12.651301                        9.931757
4                      13.434638                       10.092378
2                      13.509881                       10.094803
0                      13.804278                       10.243457
3                      17.725559                       11.241695
1                      18.297444                       11.587734

   validation_test_abserror_std  validation_test_success  \
7                     11.141593                 0.574154
5                     11.259364                 0.574277
6                     11.330951                 0.567877
8                     10.982498                 0.566400
9                     10.980678                 0.570462
4                     13.436415                 0.571200
2                     13.227120                 0.563569
0                     14.427803                 0.570954
3                     28.156966                 0.568738
1                     28.897546                 0.568985

  validation_test_improvement  validation_avg_train_test_improvement  \
7                    0.030678                               0.027551
5                    0.030819                               0.026936
6                    0.030645                               0.026429
8                    0.030842                               0.026158
9                    0.028203                               0.024735
4                    0.012487                               0.012451
2                    0.012250                               0.010533
0                   -0.002296                               0.003339
3                   -0.099971                              -0.085517
1                   -0.133830                              -0.113562

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                             0.027196                             0.027373
5                             0.026376                             0.026654
6                             0.025757                             0.026091
8                             0.025319                             0.025735
9                             0.024248                             0.024490
4                             0.012451                             0.012451
2                             0.010254                             0.010393
0                            -0.006170                                  NaN
3                            -0.083074                                  NaN
1                            -0.109944                                  NaN

[10 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -False
                              dropout_rates -None
                              early_stopping_metric -val_root_mean_squared_error
11 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.009219659148202995, Original: 9.762922791515482, New: 9.672911971087487
Test: Improvement: 0.0020742262849339946, Original: 10.2199936987652, New: 10.19879511920336

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
9           0.001         128
4           0.001         128
2           0.001         128
10          0.001         128
0           0.001         128
3           0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.LogCosh'>, {'reducti...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
10    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
9                      0.111419                  16.742096
4                      0.966627                  18.924674
2                      1.784585                  18.726619
10                     0.366429                  19.865404
0                      0.329490                  19.943449
3                      0.328753                  33.269110

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
9                       12.651301                        9.931757
4                       13.434638                       10.092378
2                       13.509881                       10.094803
10                      13.790877                       10.198795
0                       13.804278                       10.243457
3                       17.725559                       11.241695

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
9                      10.980678                 0.570462
4                      13.436415                 0.571200
2                      13.227120                 0.563569
10                     14.343284                 0.572554
0                      14.427803                 0.570954
3                      28.156966                 0.568738

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
9                     0.028203                               0.024735
4                     0.012487                               0.012451
2                     0.012250                               0.010533
10                    0.002074                               0.005647
0                    -0.002296                               0.003339
3                    -0.099971                              -0.085517

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
9                              0.024248                             0.024490
4                              0.012451                             0.012451
2                              0.010254                             0.010393
10                             0.003387                             0.004373
0                             -0.006170                                  NaN
3                             -0.083074                                  NaN

[10 rows x 50 columns]
                              dropout_enabled -True
                              dropout_rates -0.1
                              early_stopping_metric -val_root_mean_squared_error
12 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01595526165703857, Original: 9.762922791515482, New: 9.607152803839387
Test: Improvement: 0.017216180046583946, Original: 10.2199936987652, New: 10.044044447172304

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
9           0.001         128
11          0.001         128
4           0.001         128
2           0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
10    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
9                      0.111419                  16.742096
11                     0.360017                  18.770439
4                      0.966627                  18.924674
2                      1.784585                  18.726619
10                     0.366429                  19.865404
0                      0.329490                  19.943449

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
9                       12.651301                        9.931757
11                      13.418254                       10.044044
4                       13.434638                       10.092378
2                       13.509881                       10.094803
10                      13.790877                       10.198795
0                       13.804278                       10.243457

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
9                      10.980678                 0.570462
11                     13.167287                 0.572062
4                      13.436415                 0.571200
2                      13.227120                 0.563569
10                     14.343284                 0.572554
0                      14.427803                 0.570954

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
9                     0.028203                               0.024735
11                    0.017216                               0.016586
4                     0.012487                               0.012451
2                     0.012250                               0.010533
10                    0.002074                               0.005647
0                    -0.002296                               0.003339

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
9                              0.024248                             0.024490
11                             0.016562                             0.016574
4                              0.012451                             0.012451
2                              0.010254                             0.010393
10                             0.003387                             0.004373
0                             -0.006170                                  NaN

[10 rows x 50 columns]
                              dropout_rates -0.2
                              early_stopping_metric -val_root_mean_squared_error
13 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.009908055768147274, Original: 9.762922791515482, New: 9.66619120803703
Test: Improvement: 0.007479787133958067, Original: 10.2199936987652, New: 10.143550321388043

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
9           0.001         128
11          0.001         128
4           0.001         128
2           0.001         128
12          0.001         128
10          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
12    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
9                      0.111419                  16.742096
11                     0.360017                  18.770439
4                      0.966627                  18.924674
2                      1.784585                  18.726619
12                     1.954824                  18.615088
10                     0.366429                  19.865404

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
9                       12.651301                        9.931757
11                      13.418254                       10.044044
4                       13.434638                       10.092378
2                       13.509881                       10.094803
12                      13.501589                       10.143550
10                      13.790877                       10.198795

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
9                      10.980678                 0.570462
11                     13.167287                 0.572062
4                      13.436415                 0.571200
2                      13.227120                 0.563569
12                     13.076671                 0.566400
10                     14.343284                 0.572554

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
9                     0.028203                               0.024735
11                    0.017216                               0.016586
4                     0.012487                               0.012451
2                     0.012250                               0.010533
12                    0.007480                               0.008694
10                    0.002074                               0.005647

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
9                              0.024248                             0.024490
11                             0.016562                             0.016574
4                              0.012451                             0.012451
2                              0.010254                             0.010393
12                             0.008524                             0.008609
10                             0.003387                             0.004373

[10 rows x 50 columns]
                              dropout_rates -0.3
                              early_stopping_metric -val_root_mean_squared_error
14 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.015611890270244039, Original: 9.762922791515482, New: 9.610505112177478
Test: Improvement: 0.011503954741065681, Original: 10.2199936987652, New: 10.102423353800628

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
9           0.001         128
11          0.001         128
13          0.001         128
4           0.001         128
2           0.001         128
12          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
12  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
12    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
9                      0.111419                  16.742096
11                     0.360017                  18.770439
13                     0.268492                  18.930891
4                      0.966627                  18.924674
2                      1.784585                  18.726619
12                     1.954824                  18.615088

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
9                       12.651301                        9.931757
11                      13.418254                       10.044044
13                      13.387568                       10.102423
4                       13.434638                       10.092378
2                       13.509881                       10.094803
12                      13.501589                       10.143550

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
9                      10.980678                 0.570462
11                     13.167287                 0.572062
13                     13.423214                 0.570338
4                      13.436415                 0.571200
2                      13.227120                 0.563569
12                     13.076671                 0.566400

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
9                     0.028203                               0.024735
11                    0.017216                               0.016586
13                    0.011504                               0.013558
4                     0.012487                               0.012451
2                     0.012250                               0.010533
12                    0.007480                               0.008694

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
9                              0.024248                             0.024490
11                             0.016562                             0.016574
13                             0.013247                             0.013401
4                              0.012451                             0.012451
2                              0.010254                             0.010393
12                             0.008524                             0.008609

[10 rows x 50 columns]
                              dropout_rates -0.4
                              early_stopping_metric -val_root_mean_squared_error
15 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 2ms/step
Training: Improvement: 0.01461179704163678, Original: 9.762922791515482, New: 9.620268945152688
Test: Improvement: 0.012702113366323493, Original: 10.2199936987652, New: 10.090178180200372

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
9           0.001         128
11          0.001         128
14          0.001         128
13          0.001         128
4           0.001         128
2           0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
9                      0.111419                  16.742096
11                     0.360017                  18.770439
14                     0.352860                  18.936743
13                     0.268492                  18.930891
4                      0.966627                  18.924674
2                      1.784585                  18.726619

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
9                       12.651301                        9.931757
11                      13.418254                       10.044044
14                      13.414127                       10.090178
13                      13.387568                       10.102423
4                       13.434638                       10.092378
2                       13.509881                       10.094803

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
9                      10.980678                 0.570462
11                     13.167287                 0.572062
14                     13.397834                 0.569231
13                     13.423214                 0.570338
4                      13.436415                 0.571200
2                      13.227120                 0.563569

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
9                     0.028203                               0.024735
11                    0.017216                               0.016586
14                    0.012702                               0.013657
13                    0.011504                               0.013558
4                     0.012487                               0.012451
2                     0.012250                               0.010533

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
9                              0.024248                             0.024490
11                             0.016562                             0.016574
14                             0.013590                             0.013624
13                             0.013247                             0.013401
4                              0.012451                             0.012451
2                              0.010254                             0.010393

[10 rows x 50 columns]
                              dropout_rates -0.5
                              early_stopping_metric -val_root_mean_squared_error
16 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.0227203907741519, Original: 9.762922791515482, New: 9.541105370594376
Test: Improvement: 0.02756332815572145, Original: 10.2199936987652, New: 9.938296658696729

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
15          0.001         128
9           0.001         128
11          0.001         128
14          0.001         128
13          0.001         128
4           0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
15                     1.130671                  17.887568
9                      0.111419                  16.742096
11                     0.360017                  18.770439
14                     0.352860                  18.936743
13                     0.268492                  18.930891
4                      0.966627                  18.924674

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
15                      13.073917                        9.938297
9                       12.651301                        9.931757
11                      13.418254                       10.044044
14                      13.414127                       10.090178
13                      13.387568                       10.102423
4                       13.434638                       10.092378

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
15                     12.343417                 0.566892
9                      10.980678                 0.570462
11                     13.167287                 0.572062
14                     13.397834                 0.569231
13                     13.423214                 0.570338
4                      13.436415                 0.571200

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
15                    0.027563                               0.025142
9                     0.028203                               0.024735
11                    0.017216                               0.016586
14                    0.012702                               0.013657
13                    0.011504                               0.013558
4                     0.012487                               0.012451

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
15                             0.024909                             0.025025
9                              0.024248                             0.024490
11                             0.016562                             0.016574
14                             0.013590                             0.013624
13                             0.013247                             0.013401
4                              0.012451                             0.012451

[10 rows x 50 columns]
                              dropout_rates -0.6
                              early_stopping_metric -val_root_mean_squared_error
17 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02267591155116238, Original: 9.762922791515482, New: 9.54153961781425
Test: Improvement: 0.028390752594419564, Original: 10.2199936987652, New: 9.92984038614703

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
16          0.001         128
15          0.001         128
9           0.001         128
11          0.001         128
14          0.001         128
13          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
16    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
16                     0.843446                  17.510554
15                     1.130671                  17.887568
9                      0.111419                  16.742096
11                     0.360017                  18.770439
14                     0.352860                  18.936743
13                     0.268492                  18.930891

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
16                      12.916533                        9.929840
15                      13.073917                        9.938297
9                       12.651301                        9.931757
11                      13.418254                       10.044044
14                      13.414127                       10.090178
13                      13.387568                       10.102423

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
16                     11.919901                 0.560615
15                     12.343417                 0.566892
9                      10.980678                 0.570462
11                     13.167287                 0.572062
14                     13.397834                 0.569231
13                     13.423214                 0.570338

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
16                    0.028391                               0.025533
15                    0.027563                               0.025142
9                     0.028203                               0.024735
11                    0.017216                               0.016586
14                    0.012702                               0.013657
13                    0.011504                               0.013558

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
16                             0.025214                             0.025373
15                             0.024909                             0.025025
9                              0.024248                             0.024490
11                             0.016562                             0.016574
14                             0.013590                             0.013624
13                             0.013247                             0.013401

[10 rows x 50 columns]
                              dropout_rates -0.7
                              early_stopping_metric -val_root_mean_squared_error
18 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021683786461021964, Original: 9.762922791515482, New: 9.551225658468816
Test: Improvement: 0.029831929400890692, Original: 10.2199936987652, New: 9.915111568266088

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
17          0.001         128
16          0.001         128
15          0.001         128
9           0.001         128
11          0.001         128
14          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
17    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
17                     0.360573                  16.847741
16                     0.843446                  17.510554
15                     1.130671                  17.887568
9                      0.111419                  16.742096
11                     0.360017                  18.770439
14                     0.352860                  18.936743

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
17                      12.681405                        9.915112
16                      12.916533                        9.929840
15                      13.073917                        9.938297
9                       12.651301                        9.931757
11                      13.418254                       10.044044
14                      13.414127                       10.090178

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
17                     11.126623                 0.568738
16                     11.919901                 0.560615
15                     12.343417                 0.566892
9                      10.980678                 0.570462
11                     13.167287                 0.572062
14                     13.397834                 0.569231

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
17                    0.029832                               0.025758
16                    0.028391                               0.025533
15                    0.027563                               0.025142
9                     0.028203                               0.024735
11                    0.017216                               0.016586
14                    0.012702                               0.013657

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
17                             0.025113                             0.025434
16                             0.025214                             0.025373
15                             0.024909                             0.025025
9                              0.024248                             0.024490
11                             0.016562                             0.016574
14                             0.013590                             0.013624

[10 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
19 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020377429517476835, Original: 9.762922791515482, New: 9.563979520446807
Test: Improvement: 0.025800778421922393, Original: 10.2199936987652, New: 9.956309905869915

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
17          0.001         128
16          0.001         128
15          0.001         128
9           0.001         128
18          0.001         128
11          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
17    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
18    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
17                     0.360573                  16.847741
16                     0.843446                  17.510554
15                     1.130671                  17.887568
9                      0.111419                  16.742096
18                     0.248302                  17.636593
11                     0.360017                  18.770439

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
17                      12.681405                        9.915112
16                      12.916533                        9.929840
15                      13.073917                        9.938297
9                       12.651301                        9.931757
18                      12.937591                        9.956310
11                      13.418254                       10.044044

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
17                     11.126623                 0.568738
16                     11.919901                 0.560615
15                     12.343417                 0.566892
9                      10.980678                 0.570462
18                     12.007904                 0.570585
11                     13.167287                 0.572062

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
17                    0.029832                               0.025758
16                    0.028391                               0.025533
15                    0.027563                               0.025142
9                     0.028203                               0.024735
18                    0.025801                               0.023089
11                    0.017216                               0.016586

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
17                             0.025113                             0.025434
16                             0.025214                             0.025373
15                             0.024909                             0.025025
9                              0.024248                             0.024490
18                             0.022771                             0.022929
11                             0.016562                             0.016574

[10 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
20 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021977968351167203, Original: 9.762922791515482, New: 9.548353583388666
Test: Improvement: 0.024944331275889395, Original: 10.2199936987652, New: 9.965062790305698

-------------------------
    learning_rate  batch_size  \
7           0.001         128
5           0.001         128
6           0.001         128
8           0.001         128
17          0.001         128
16          0.001         128
15          0.001         128
9           0.001         128
19          0.001         128
18          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
6   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
17    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
19    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.060803                  16.890374
5                      0.069935                  16.986607
6                      0.703915                  17.010997
8                     -0.028551                  16.742456
17                     0.360573                  16.847741
16                     0.843446                  17.510554
15                     1.130671                  17.887568
9                      0.111419                  16.742096
19                     0.089886                  17.713702
18                     0.248302                  17.636593

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.708094                        9.906466
5                       12.726562                        9.905022
6                       12.755514                        9.906802
8                       12.643260                        9.904791
17                      12.681405                        9.915112
16                      12.916533                        9.929840
15                      13.073917                        9.938297
9                       12.651301                        9.931757
19                      12.990608                        9.965063
18                      12.937591                        9.956310

    validation_test_abserror_std  validation_test_success  \
7                      11.141593                 0.574154
5                      11.259364                 0.574277
6                      11.330951                 0.567877
8                      10.982498                 0.566400
17                     11.126623                 0.568738
16                     11.919901                 0.560615
15                     12.343417                 0.566892
9                      10.980678                 0.570462
19                     12.050860                 0.572923
18                     12.007904                 0.570585

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.030678                               0.027551
5                     0.030819                               0.026936
6                     0.030645                               0.026429
8                     0.030842                               0.026158
17                    0.029832                               0.025758
16                    0.028391                               0.025533
15                    0.027563                               0.025142
9                     0.028203                               0.024735
19                    0.024944                               0.023461
18                    0.025801                               0.023089

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027196                             0.027373
5                              0.026376                             0.026654
6                              0.025757                             0.026091
8                              0.025319                             0.025735
17                             0.025113                             0.025434
16                             0.025214                             0.025373
15                             0.024909                             0.025025
9                              0.024248                             0.024490
19                             0.023367                             0.023414
18                             0.022771                             0.022929

[10 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 2, dropout_rates: 9, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -False
                              dropout_rates -None
                              early_stopping_metric -val_root_mean_squared_error
1 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0011260707065638776, Original: 9.762922791515482, New: 9.773916532881453
Test: Improvement: -0.01642770226647992, Original: 10.2199936987652, New: 10.387884712413815

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.283936                   20.80439

   validation_test_abserror_mean validation_test_abserror_median  \
0                      14.125409                       10.387885

   validation_test_abserror_std  validation_test_success  \
0                     15.273558                   0.5664

  validation_test_improvement  validation_avg_train_test_improvement  \
0                   -0.016428                              -0.008777

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                            -0.002108                                 None

[1 rows x 50 columns]
                              dropout_enabled -True
                              dropout_rates -0.1
                              early_stopping_metric -val_root_mean_squared_error
2 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0010626883991878737, Original: 9.762922791515482, New: 9.752547846722772
Test: Improvement: -0.011522392748810022, Original: 10.2199936987652, New: 10.337752480052735

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     1.191193                  20.857399
0                    -0.283936                  20.804390

   validation_test_abserror_mean validation_test_abserror_median  \
1                      14.126636                       10.337752
0                      14.125409                       10.387885

   validation_test_abserror_std  validation_test_success  \
1                     15.428066                 0.568492
0                     15.273558                 0.566400

  validation_test_improvement  validation_avg_train_test_improvement  \
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.002341                                  NaN
0                            -0.002108                                  NaN

[2 rows x 50 columns]
                              dropout_rates -0.2
                              early_stopping_metric -val_root_mean_squared_error
3 36

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01716746305618084, Original: 9.762922791515482, New: 9.595318175171794
Test: Improvement: 0.02010609457100349, Original: 10.2199936987652, New: 10.014509538942766

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390

   validation_test_abserror_mean validation_test_abserror_median  \
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885

   validation_test_abserror_std  validation_test_success  \
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN

[3 rows x 50 columns]
                              dropout_rates -0.3
                              early_stopping_metric -val_root_mean_squared_error
4 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.017803965893709136, Original: 9.762922791515482, New: 9.589104047112425
Test: Improvement: 0.01963624656741409, Original: 10.2199936987652, New: 10.019311382578827

-------------------------
   learning_rate  batch_size  \
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.718728                  18.110239
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390

   validation_test_abserror_mean validation_test_abserror_median  \
3                      13.130285                       10.019311
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885

   validation_test_abserror_std  validation_test_success  \
3                     12.526742                 0.569600
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.019636                               0.018720
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.018675                             0.018698
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN

[4 rows x 50 columns]
                              dropout_rates -0.4
                              early_stopping_metric -val_root_mean_squared_error
5 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01929186943095041, Original: 9.762922791515482, New: 9.574577759757116
Test: Improvement: 0.03167751389206479, Original: 10.2199936987652, New: 9.89624970639575

-------------------------
   learning_rate  batch_size  \
4          0.001         128
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                     0.665465                  17.508177
3                     0.718728                  18.110239
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390

   validation_test_abserror_mean validation_test_abserror_median  \
4                      12.922280                        9.896250
3                      13.130285                       10.019311
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885

   validation_test_abserror_std  validation_test_success  \
4                     11.868437                 0.571446
3                     12.526742                 0.569600
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.031678                               0.025485
3                    0.019636                               0.018720
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.023980                             0.024721
3                             0.018675                             0.018698
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN

[5 rows x 50 columns]
                              dropout_rates -0.5
                              early_stopping_metric -val_root_mean_squared_error
6 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.017820458198060482, Original: 9.762922791515482, New: 9.588943034018389
Test: Improvement: 0.02361721395831215, Original: 10.2199936987652, New: 9.97862592092886

-------------------------
   learning_rate  batch_size  \
4          0.001         128
5          0.001         128
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                     0.665465                  17.508177
5                     0.856451                  17.844434
3                     0.718728                  18.110239
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390

   validation_test_abserror_mean validation_test_abserror_median  \
4                      12.922280                        9.896250
5                      13.041094                        9.978626
3                      13.130285                       10.019311
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885

   validation_test_abserror_std  validation_test_success  \
4                     11.868437                 0.571446
5                     12.281769                 0.572431
3                     12.526742                 0.569600
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.031678                               0.025485
5                    0.023617                               0.020719
3                    0.019636                               0.018720
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.023980                             0.024721
5                             0.020313                             0.020515
3                             0.018675                             0.018698
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN

[6 rows x 50 columns]
                              dropout_rates -0.6
                              early_stopping_metric -val_root_mean_squared_error
7 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.024817430311512, Original: 9.762922791515482, New: 10.00521344753059
Test: Improvement: -0.05140162946400921, Original: 10.2199936987652, New: 10.745318027993637

-------------------------
   learning_rate  batch_size  \
4          0.001         128
5          0.001         128
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128
6          0.001         128

                                           optimizer  \
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
4                     0.665465                  17.508177
5                     0.856451                  17.844434
3                     0.718728                  18.110239
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390
6                     0.774373                  25.100762

   validation_test_abserror_mean validation_test_abserror_median  \
4                      12.922280                        9.896250
5                      13.041094                        9.978626
3                      13.130285                       10.019311
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885
6                      15.470328                       10.745318

   validation_test_abserror_std  validation_test_success  \
4                     11.868437                 0.571446
5                     12.281769                 0.572431
3                     12.526742                 0.569600
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400
6                     19.844531                 0.570708

  validation_test_improvement  validation_avg_train_test_improvement  \
4                    0.031678                               0.025485
5                    0.023617                               0.020719
3                    0.019636                               0.018720
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777
6                   -0.051402                              -0.038110

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
4                             0.023980                             0.024721
5                             0.020313                             0.020515
3                             0.018675                             0.018698
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN
6                            -0.033473                                  NaN

[7 rows x 50 columns]
                              dropout_rates -0.7
                              early_stopping_metric -val_root_mean_squared_error
8 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023550693378397863, Original: 9.762922791515482, New: 9.532999190375529
Test: Improvement: 0.03378455411880412, Original: 10.2199936987652, New: 9.87471576855543

-------------------------
   learning_rate  batch_size  \
7          0.001         128
4          0.001         128
5          0.001         128
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128
6          0.001         128

                                           optimizer  \
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
7  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
7  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
7  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
7                     0.212836                  16.992784
4                     0.665465                  17.508177
5                     0.856451                  17.844434
3                     0.718728                  18.110239
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390
6                     0.774373                  25.100762

   validation_test_abserror_mean validation_test_abserror_median  \
7                      12.722531                        9.874716
4                      12.922280                        9.896250
5                      13.041094                        9.978626
3                      13.130285                       10.019311
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885
6                      15.470328                       10.745318

   validation_test_abserror_std  validation_test_success  \
7                     11.279642                 0.567262
4                     11.868437                 0.571446
5                     12.281769                 0.572431
3                     12.526742                 0.569600
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400
6                     19.844531                 0.570708

  validation_test_improvement  validation_avg_train_test_improvement  \
7                    0.033785                               0.028668
4                    0.031678                               0.025485
5                    0.023617                               0.020719
3                    0.019636                               0.018720
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777
6                   -0.051402                              -0.038110

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                             0.027754                             0.028207
4                             0.023980                             0.024721
5                             0.020313                             0.020515
3                             0.018675                             0.018698
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN
6                            -0.033473                                  NaN

[8 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
9 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02283931714620087, Original: 9.762922791515482, New: 9.539944301606187
Test: Improvement: 0.029875029502644167, Original: 10.2199936987652, New: 9.914671085497751

-------------------------
   learning_rate  batch_size  \
7          0.001         128
8          0.001         128
4          0.001         128
5          0.001         128
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128
6          0.001         128

                                           optimizer  \
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
7  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
7  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
7  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
7                     0.212836                  16.992784
8                     0.478243                  17.419597
4                     0.665465                  17.508177
5                     0.856451                  17.844434
3                     0.718728                  18.110239
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390
6                     0.774373                  25.100762

   validation_test_abserror_mean validation_test_abserror_median  \
7                      12.722531                        9.874716
8                      12.856402                        9.914671
4                      12.922280                        9.896250
5                      13.041094                        9.978626
3                      13.130285                       10.019311
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885
6                      15.470328                       10.745318

   validation_test_abserror_std  validation_test_success  \
7                     11.279642                 0.567262
8                     11.796107                 0.573292
4                     11.868437                 0.571446
5                     12.281769                 0.572431
3                     12.526742                 0.569600
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400
6                     19.844531                 0.570708

  validation_test_improvement  validation_avg_train_test_improvement  \
7                    0.033785                               0.028668
8                    0.029875                               0.026357
4                    0.031678                               0.025485
5                    0.023617                               0.020719
3                    0.019636                               0.018720
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777
6                   -0.051402                              -0.038110

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                             0.027754                             0.028207
8                             0.025888                             0.026121
4                             0.023980                             0.024721
5                             0.020313                             0.020515
3                             0.018675                             0.018698
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN
6                            -0.033473                                  NaN

[9 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
10 36
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02271751977312901, Original: 9.762922791515482, New: 9.541133399955697
Test: Improvement: 0.03195566885376253, Original: 10.2199936987652, New: 9.893406964439919

-------------------------
   learning_rate  batch_size  \
7          0.001         128
9          0.001         128
8          0.001         128
4          0.001         128
5          0.001         128
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128
6          0.001         128

                                           optimizer  \
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
7  <class 'keras.src.optimizers.adam.Adam'>
9  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
7  (<class 'keras.src.losses.LogCosh'>, {'reducti...
9  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
7  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
7                     0.212836                  16.992784
9                     0.216980                  16.847500
8                     0.478243                  17.419597
4                     0.665465                  17.508177
5                     0.856451                  17.844434
3                     0.718728                  18.110239
2                    -0.281880                  18.070626
1                     1.191193                  20.857399
0                    -0.283936                  20.804390
6                     0.774373                  25.100762

   validation_test_abserror_mean validation_test_abserror_median  \
7                      12.722531                        9.874716
9                      12.687941                        9.893407
8                      12.856402                        9.914671
4                      12.922280                        9.896250
5                      13.041094                        9.978626
3                      13.130285                       10.019311
2                      13.120896                       10.014510
1                      14.126636                       10.337752
0                      14.125409                       10.387885
6                      15.470328                       10.745318

   validation_test_abserror_std  validation_test_success  \
7                     11.279642                 0.567262
9                     11.103282                 0.561108
8                     11.796107                 0.573292
4                     11.868437                 0.571446
5                     12.281769                 0.572431
3                     12.526742                 0.569600
2                     12.426654                 0.569969
1                     15.428066                 0.568492
0                     15.273558                 0.566400
6                     19.844531                 0.570708

  validation_test_improvement  validation_avg_train_test_improvement  \
7                    0.033785                               0.028668
9                    0.031956                               0.027337
8                    0.029875                               0.026357
4                    0.031678                               0.025485
5                    0.023617                               0.020719
3                    0.019636                               0.018720
2                    0.020106                               0.018637
1                   -0.011522                              -0.005230
0                   -0.016428                              -0.008777
6                   -0.051402                              -0.038110

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                             0.027754                             0.028207
9                             0.026556                             0.026944
8                             0.025888                             0.026121
4                             0.023980                             0.024721
5                             0.020313                             0.020515
3                             0.018675                             0.018698
2                             0.018521                             0.018579
1                             0.002341                                  NaN
0                            -0.002108                                  NaN
6                            -0.033473                                  NaN

[10 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -False
                              dropout_rates -None
                              early_stopping_metric -val_root_mean_squared_error
11 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0004592832586940709, Original: 9.762922791515482, New: 9.758438844521416
Test: Improvement: -0.024026850878586057, Original: 10.2199936987652, New: 10.46554796334552

-------------------------
    learning_rate  batch_size  \
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
3           0.001         128
2           0.001         128
1           0.001         128
0           0.001         128
10          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
1   (<class 'keras.src.losses.LogCosh'>, {'reducti...
0   (<class 'keras.src.losses.LogCosh'>, {'reducti...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
10    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
1                      1.191193                  20.857399
0                     -0.283936                  20.804390
10                    -0.126016                  22.165508

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
3                       13.130285                       10.019311
2                       13.120896                       10.014510
1                       14.126636                       10.337752
0                       14.125409                       10.387885
10                      14.470423                       10.465548

    validation_test_abserror_std  validation_test_success  \
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
3                      12.526742                 0.569600
2                      12.426654                 0.569969
1                      15.428066                 0.568492
0                      15.273558                 0.566400
10                     16.794003                 0.568123

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
3                     0.019636                               0.018720
2                     0.020106                               0.018637
1                    -0.011522                              -0.005230
0                    -0.016428                              -0.008777
10                   -0.024027                              -0.011784

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
3                              0.018675                             0.018698
2                              0.018521                             0.018579
1                              0.002341                                  NaN
0                             -0.002108                                  NaN
10                             0.000936                                  NaN

[10 rows x 50 columns]
                              dropout_enabled -True
                              dropout_rates -0.1
                              early_stopping_metric -val_root_mean_squared_error
12 36

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.003963419830217194, Original: 9.762922791515482, New: 9.72422822972271
Test: Improvement: 0.0004641335842324463, Original: 10.2199936987652, New: 10.215250256458958

-------------------------
    learning_rate  batch_size  \
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
3           0.001         128
2           0.001         128
11          0.001         128
1           0.001         128
0           0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.LogCosh'>, {'reducti...
0   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
11                     0.791763                  20.560407
1                      1.191193                  20.857399
0                     -0.283936                  20.804390

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
3                       13.130285                       10.019311
2                       13.120896                       10.014510
11                      13.939057                       10.215250
1                       14.126636                       10.337752
0                       14.125409                       10.387885

    validation_test_abserror_std  validation_test_success  \
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
3                      12.526742                 0.569600
2                      12.426654                 0.569969
11                     15.218439                 0.566892
1                      15.428066                 0.568492
0                      15.273558                 0.566400

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
3                     0.019636                               0.018720
2                     0.020106                               0.018637
11                    0.000464                               0.002214
1                    -0.011522                              -0.005230
0                    -0.016428                              -0.008777

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
3                              0.018675                             0.018698
2                              0.018521                             0.018579
11                             0.000831                             0.001356
1                              0.002341                                  NaN
0                             -0.002108                                  NaN

[10 rows x 50 columns]
                              dropout_rates -0.2
                              early_stopping_metric -val_root_mean_squared_error
13 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01256667627742812, Original: 9.762922791515482, New: 9.640235301272982
Test: Improvement: 0.010937864885150934, Original: 10.2199936987652, New: 10.108208788561011

-------------------------
    learning_rate  batch_size  \
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
3           0.001         128
2           0.001         128
12          0.001         128
11          0.001         128
1           0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
12    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
12                     0.362973                  18.661993
11                     0.791763                  20.560407
1                      1.191193                  20.857399

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
3                       13.130285                       10.019311
2                       13.120896                       10.014510
12                      13.333912                       10.108209
11                      13.939057                       10.215250
1                       14.126636                       10.337752

    validation_test_abserror_std  validation_test_success  \
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
3                      12.526742                 0.569600
2                      12.426654                 0.569969
12                     13.089773                 0.568369
11                     15.218439                 0.566892
1                      15.428066                 0.568492

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
3                     0.019636                               0.018720
2                     0.020106                               0.018637
12                    0.010938                               0.011752
11                    0.000464                               0.002214
1                    -0.011522                              -0.005230

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
3                              0.018675                             0.018698
2                              0.018521                             0.018579
12                             0.011696                             0.011724
11                             0.000831                             0.001356
1                              0.002341                                  NaN

[10 rows x 50 columns]
                              dropout_rates -0.3
                              early_stopping_metric -val_root_mean_squared_error
14 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.016765194230344817, Original: 9.762922791515482, New: 9.599245494659865
Test: Improvement: 0.013024982625684505, Original: 10.2199936987652, New: 10.086878458404177

-------------------------
    learning_rate  batch_size  \
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
3           0.001         128
2           0.001         128
13          0.001         128
12          0.001         128
11          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
13                    -0.380997                  18.130507
12                     0.362973                  18.661993
11                     0.791763                  20.560407

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
3                       13.130285                       10.019311
2                       13.120896                       10.014510
13                      13.188240                       10.086878
12                      13.333912                       10.108209
11                      13.939057                       10.215250

    validation_test_abserror_std  validation_test_success  \
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
3                      12.526742                 0.569600
2                      12.426654                 0.569969
13                     12.440494                 0.569477
12                     13.089773                 0.568369
11                     15.218439                 0.566892

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
3                     0.019636                               0.018720
2                     0.020106                               0.018637
13                    0.013025                               0.014895
12                    0.010938                               0.011752
11                    0.000464                               0.002214

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
3                              0.018675                             0.018698
2                              0.018521                             0.018579
13                             0.014660                             0.014777
12                             0.011696                             0.011724
11                             0.000831                             0.001356

[10 rows x 50 columns]
                              dropout_rates -0.4
                              early_stopping_metric -val_root_mean_squared_error
15 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021225510222601364, Original: 9.762922791515482, New: 9.555699774001702
Test: Improvement: 0.019007137105446995, Original: 10.2199936987652, New: 10.025740877315965

-------------------------
    learning_rate  batch_size  \
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
14          0.001         128
3           0.001         128
2           0.001         128
13          0.001         128
12          0.001         128

                                            optimizer  \
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
14                     0.184197                  17.700403
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
13                    -0.380997                  18.130507
12                     0.362973                  18.661993

    validation_test_abserror_mean validation_test_abserror_median  \
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
14                      13.008734                       10.025741
3                       13.130285                       10.019311
2                       13.120896                       10.014510
13                      13.188240                       10.086878
12                      13.333912                       10.108209

    validation_test_abserror_std  validation_test_success  \
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
14                     12.017971                 0.568862
3                      12.526742                 0.569600
2                      12.426654                 0.569969
13                     12.440494                 0.569477
12                     13.089773                 0.568369

   validation_test_improvement  validation_avg_train_test_improvement  \
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
14                    0.019007                               0.020116
3                     0.019636                               0.018720
2                     0.020106                               0.018637
13                    0.013025                               0.014895
12                    0.010938                               0.011752

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
14                             0.020055                             0.020086
3                              0.018675                             0.018698
2                              0.018521                             0.018579
13                             0.014660                             0.014777
12                             0.011696                             0.011724

[10 rows x 50 columns]
                              dropout_rates -0.5
                              early_stopping_metric -val_root_mean_squared_error
16 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.027531872659361845, Original: 9.762922791515482, New: 9.494131244436296
Test: Improvement: 0.02918724626970281, Original: 10.2199936987652, New: 9.921700225804528

-------------------------
    learning_rate  batch_size  \
15          0.001         128
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
14          0.001         128
3           0.001         128
2           0.001         128
13          0.001         128

                                            optimizer  \
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
15  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
15  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
13  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
15                     0.381432                  17.117391
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
14                     0.184197                  17.700403
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
13                    -0.380997                  18.130507

    validation_test_abserror_mean validation_test_abserror_median  \
15                      12.798478                        9.921700
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
14                      13.008734                       10.025741
3                       13.130285                       10.019311
2                       13.120896                       10.014510
13                      13.188240                       10.086878

    validation_test_abserror_std  validation_test_success  \
15                     11.403181                 0.573292
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
14                     12.017971                 0.568862
3                      12.526742                 0.569600
2                      12.426654                 0.569969
13                     12.440494                 0.569477

   validation_test_improvement  validation_avg_train_test_improvement  \
15                    0.029187                               0.028360
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
14                    0.019007                               0.020116
3                     0.019636                               0.018720
2                     0.020106                               0.018637
13                    0.013025                               0.014895

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
15                             0.028335                             0.028347
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
14                             0.020055                             0.020086
3                              0.018675                             0.018698
2                              0.018521                             0.018579
13                             0.014660                             0.014777

[10 rows x 50 columns]
                              dropout_rates -0.6
                              early_stopping_metric -val_root_mean_squared_error
17 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.03311024297661784, Original: 9.762922791515482, New: 10.08617553730452
Test: Improvement: -0.06104733682523964, Original: 10.2199936987652, New: 10.843897096445545

-------------------------
    learning_rate  batch_size  \
15          0.001         128
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
14          0.001         128
3           0.001         128
2           0.001         128
13          0.001         128

                                            optimizer  \
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
15  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
15  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
13  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
15                     0.381432                  17.117391
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
14                     0.184197                  17.700403
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
13                    -0.380997                  18.130507

    validation_test_abserror_mean validation_test_abserror_median  \
15                      12.798478                        9.921700
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
14                      13.008734                       10.025741
3                       13.130285                       10.019311
2                       13.120896                       10.014510
13                      13.188240                       10.086878

    validation_test_abserror_std  validation_test_success  \
15                     11.403181                 0.573292
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
14                     12.017971                 0.568862
3                      12.526742                 0.569600
2                      12.426654                 0.569969
13                     12.440494                 0.569477

   validation_test_improvement  validation_avg_train_test_improvement  \
15                    0.029187                               0.028360
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
14                    0.019007                               0.020116
3                     0.019636                               0.018720
2                     0.020106                               0.018637
13                    0.013025                               0.014895

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
15                             0.028335                             0.028347
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
14                             0.020055                             0.020086
3                              0.018675                             0.018698
2                              0.018521                             0.018579
13                             0.014660                             0.014777

[10 rows x 50 columns]
                              dropout_rates -0.7
                              early_stopping_metric -val_root_mean_squared_error
18 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.00860021320503101, Original: 9.762922791515482, New: 9.846886009026772
Test: Improvement: -0.023290402263002673, Original: 10.2199936987652, New: 10.458021463134793

-------------------------
    learning_rate  batch_size  \
15          0.001         128
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
5           0.001         128
14          0.001         128
3           0.001         128
2           0.001         128
13          0.001         128

                                            optimizer  \
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
15  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
15  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...
13  (<class 'keras.src.losses.Huber'>, {'reduction...

                   loss_function_class   loss_function_params  \
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
13    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
15                     0.381432                  17.117391
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
5                      0.856451                  17.844434
14                     0.184197                  17.700403
3                      0.718728                  18.110239
2                     -0.281880                  18.070626
13                    -0.380997                  18.130507

    validation_test_abserror_mean validation_test_abserror_median  \
15                      12.798478                        9.921700
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
5                       13.041094                        9.978626
14                      13.008734                       10.025741
3                       13.130285                       10.019311
2                       13.120896                       10.014510
13                      13.188240                       10.086878

    validation_test_abserror_std  validation_test_success  \
15                     11.403181                 0.573292
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
5                      12.281769                 0.572431
14                     12.017971                 0.568862
3                      12.526742                 0.569600
2                      12.426654                 0.569969
13                     12.440494                 0.569477

   validation_test_improvement  validation_avg_train_test_improvement  \
15                    0.029187                               0.028360
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
5                     0.023617                               0.020719
14                    0.019007                               0.020116
3                     0.019636                               0.018720
2                     0.020106                               0.018637
13                    0.013025                               0.014895

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
15                             0.028335                             0.028347
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
5                              0.020313                             0.020515
14                             0.020055                             0.020086
3                              0.018675                             0.018698
2                              0.018521                             0.018579
13                             0.014660                             0.014777

[10 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
19 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019131870550947856, Original: 9.762922791515482, New: 9.57613981646931
Test: Improvement: 0.026048069402026724, Original: 10.2199936987652, New: 9.953782593611487

-------------------------
    learning_rate  batch_size  \
15          0.001         128
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
18          0.001         128
5           0.001         128
14          0.001         128
3           0.001         128
2           0.001         128

                                            optimizer  \
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
15  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
15  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...
2   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
18    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
15                     0.381432                  17.117391
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
18                    -0.174649                  16.730753
5                      0.856451                  17.844434
14                     0.184197                  17.700403
3                      0.718728                  18.110239
2                     -0.281880                  18.070626

    validation_test_abserror_mean validation_test_abserror_median  \
15                      12.798478                        9.921700
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
18                      12.640506                        9.953783
5                       13.041094                        9.978626
14                      13.008734                       10.025741
3                       13.130285                       10.019311
2                       13.120896                       10.014510

    validation_test_abserror_std  validation_test_success  \
15                     11.403181                 0.573292
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
18                     10.962793                 0.570215
5                      12.281769                 0.572431
14                     12.017971                 0.568862
3                      12.526742                 0.569600
2                      12.426654                 0.569969

   validation_test_improvement  validation_avg_train_test_improvement  \
15                    0.029187                               0.028360
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
18                    0.026048                               0.022590
5                     0.023617                               0.020719
14                    0.019007                               0.020116
3                     0.019636                               0.018720
2                     0.020106                               0.018637

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
15                             0.028335                             0.028347
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
18                             0.022061                             0.022324
5                              0.020313                             0.020515
14                             0.020055                             0.020086
3                              0.018675                             0.018698
2                              0.018521                             0.018579

[10 rows x 50 columns]
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
20 36

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0209942412897758, Original: 9.762922791515482, New: 9.557957634736955
Test: Improvement: 0.0268694249813685, Original: 10.2199936987652, New: 9.945388344766169

-------------------------
    learning_rate  batch_size  \
15          0.001         128
7           0.001         128
9           0.001         128
8           0.001         128
4           0.001         128
19          0.001         128
18          0.001         128
5           0.001         128
14          0.001         128
3           0.001         128

                                            optimizer  \
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
15  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
15  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.LogCosh'>, {'reducti...
9   (<class 'keras.src.losses.LogCosh'>, {'reducti...
8   (<class 'keras.src.losses.LogCosh'>, {'reducti...
4   (<class 'keras.src.losses.LogCosh'>, {'reducti...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.LogCosh'>, {'reducti...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.LogCosh'>, {'reducti...

                   loss_function_class   loss_function_params  \
15    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
19    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
14    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
15                     0.381432                  17.117391
7                      0.212836                  16.992784
9                      0.216980                  16.847500
8                      0.478243                  17.419597
4                      0.665465                  17.508177
19                    -0.106613                  16.836225
18                    -0.174649                  16.730753
5                      0.856451                  17.844434
14                     0.184197                  17.700403
3                      0.718728                  18.110239

    validation_test_abserror_mean validation_test_abserror_median  \
15                      12.798478                        9.921700
7                       12.722531                        9.874716
9                       12.687941                        9.893407
8                       12.856402                        9.914671
4                       12.922280                        9.896250
19                      12.678513                        9.945388
18                      12.640506                        9.953783
5                       13.041094                        9.978626
14                      13.008734                       10.025741
3                       13.130285                       10.019311

    validation_test_abserror_std  validation_test_success  \
15                     11.403181                 0.573292
7                      11.279642                 0.567262
9                      11.103282                 0.561108
8                      11.796107                 0.573292
4                      11.868437                 0.571446
19                     11.083146                 0.566400
18                     10.962793                 0.570215
5                      12.281769                 0.572431
14                     12.017971                 0.568862
3                      12.526742                 0.569600

   validation_test_improvement  validation_avg_train_test_improvement  \
15                    0.029187                               0.028360
7                     0.033785                               0.028668
9                     0.031956                               0.027337
8                     0.029875                               0.026357
4                     0.031678                               0.025485
19                    0.026869                               0.023932
18                    0.026048                               0.022590
5                     0.023617                               0.020719
14                    0.019007                               0.020116
3                     0.019636                               0.018720

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
15                             0.028335                             0.028347
7                              0.027754                             0.028207
9                              0.026556                             0.026944
8                              0.025888                             0.026121
4                              0.023980                             0.024721
19                             0.023571                             0.023751
18                             0.022061                             0.022324
5                              0.020313                             0.020515
14                             0.020055                             0.020086
3                              0.018675                             0.018698

[10 rows x 50 columns]
dropout_enabled Selected -  [True]
dropout_rates Selected -  [0.5]

'''''''' early_stopping_metrics
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 5, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -loss
1 10

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0850086824520405, Original: 9.762922791515482, New: 10.59285599490321
Test: Improvement: -0.11532964206899163, Original: 10.2199936987652, New: 11.39866191399114

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     1.095575                  33.337623

   validation_test_abserror_mean validation_test_abserror_median  \
0                      17.990874                       11.398662

   validation_test_abserror_std  validation_test_success  \
0                     28.107005                 0.571692

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    -0.11533                              -0.100169

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                            -0.097875                                 None

[1 rows x 50 columns]
                              early_stopping_metric -val_loss
2 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.014236545880609283, Original: 9.762922791515482, New: 9.623932493265226
Test: Improvement: 0.022828848947972605, Original: 10.2199936987652, New: 9.986683006366857

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.448239                  17.398793
0                     1.095575                  33.337623

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.916629                        9.986683
0                      17.990874                       11.398662

   validation_test_abserror_std  validation_test_success  \
1                     11.688459                 0.566031
0                     28.107005                 0.571692

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.022829                               0.018533
0                   -0.115330                              -0.100169

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.017537                             0.018028
0                            -0.097875                                  NaN

[2 rows x 50 columns]
                              early_stopping_metric -val_mean_absolute_error
3 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.015809289632877872, Original: 9.762922791515482, New: 9.60857791744099
Test: Improvement: 0.02635042856100193, Original: 10.2199936987652, New: 9.950692484911997

-------------------------
   learning_rate  batch_size  \
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.533792                  17.604229
1                     0.448239                  17.398793
0                     1.095575                  33.337623

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.950535                        9.950692
1                      12.916629                        9.986683
0                      17.990874                       11.398662

   validation_test_abserror_std  validation_test_success  \
2                     11.978668                 0.569231
1                     11.688459                 0.566031
0                     28.107005                 0.571692

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.026350                               0.021080
1                    0.022829                               0.018533
0                   -0.115330                              -0.100169

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.019762                             0.020410
1                             0.017537                             0.018028
0                            -0.097875                                  NaN

[3 rows x 50 columns]
                              early_stopping_metric -val_mean_squared_error
4 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022144527894600953, Original: 9.762922791515482, New: 9.546727475425932
Test: Improvement: 0.025181785954676086, Original: 10.2199936987652, New: 9.962636004984756

-------------------------
   learning_rate  batch_size  \
3          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.398717                  17.366732
2                     0.533792                  17.604229
1                     0.448239                  17.398793
0                     1.095575                  33.337623

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.868399                        9.962636
2                      12.950535                        9.950692
1                      12.916629                        9.986683
0                      17.990874                       11.398662

   validation_test_abserror_std  validation_test_success  \
3                     11.683440                 0.572431
2                     11.978668                 0.569231
1                     11.688459                 0.566031
0                     28.107005                 0.571692

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.025182                               0.023663
2                    0.026350                               0.021080
1                    0.022829                               0.018533
0                   -0.115330                              -0.100169

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.023566                             0.023614
2                             0.019762                             0.020410
1                             0.017537                             0.018028
0                            -0.097875                                  NaN

[4 rows x 50 columns]
                              early_stopping_metric -val_root_mean_squared_error
5 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020332780051109625, Original: 9.762922791515482, New: 9.564415429739633
Test: Improvement: 0.02441695412924839, Original: 10.2199936987652, New: 9.970452581421242

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.398717                  17.366732
4                     1.092420                  17.322748
2                     0.533792                  17.604229
1                     0.448239                  17.398793
0                     1.095575                  33.337623

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.868399                        9.962636
4                      12.889095                        9.970453
2                      12.950535                        9.950692
1                      12.916629                        9.986683
0                      17.990874                       11.398662

   validation_test_abserror_std  validation_test_success  \
3                     11.683440                 0.572431
4                     11.705446                 0.568246
2                     11.978668                 0.569231
1                     11.688459                 0.566031
0                     28.107005                 0.571692

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.025182                               0.023663
4                    0.024417                               0.022375
2                    0.026350                               0.021080
1                    0.022829                               0.018533
0                   -0.115330                              -0.100169

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.023566                             0.023614
4                             0.022188                             0.022281
2                             0.019762                             0.020410
1                             0.017537                             0.018028
0                            -0.097875                                  NaN

[5 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -loss
6 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.08400117899918799, Original: 9.762922791515482, New: 10.583019816480826
Test: Improvement: -0.11709306017153673, Original: 10.2199936987652, New: 11.416684035887439

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128
0          0.001         128
5          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.398717                  17.366732
4                     1.092420                  17.322748
2                     0.533792                  17.604229
1                     0.448239                  17.398793
0                     1.095575                  33.337623
5                     1.226944                  35.609943

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.868399                        9.962636
4                      12.889095                        9.970453
2                      12.950535                        9.950692
1                      12.916629                        9.986683
0                      17.990874                       11.398662
5                      18.290049                       11.416684

   validation_test_abserror_std  validation_test_success  \
3                     11.683440                 0.572431
4                     11.705446                 0.568246
2                     11.978668                 0.569231
1                     11.688459                 0.566031
0                     28.107005                 0.571692
5                     30.601666                 0.570585

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.025182                               0.023663
4                    0.024417                               0.022375
2                    0.026350                               0.021080
1                    0.022829                               0.018533
0                   -0.115330                              -0.100169
5                   -0.117093                              -0.100547

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.023566                             0.023614
4                             0.022188                             0.022281
2                             0.019762                             0.020410
1                             0.017537                             0.018028
0                            -0.097875                                  NaN
5                            -0.097824                                  NaN

[6 rows x 50 columns]
                              early_stopping_metric -val_loss
7 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.05575321820245996, Original: 9.762922791515482, New: 10.307237156204614
Test: Improvement: -0.08488629787695777, Original: 10.2199936987652, New: 11.087531128179213

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128
6          0.001         128
0          0.001         128
5          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.398717                  17.366732
4                     1.092420                  17.322748
2                     0.533792                  17.604229
1                     0.448239                  17.398793
6                    -0.063065                  26.379132
0                     1.095575                  33.337623
5                     1.226944                  35.609943

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.868399                        9.962636
4                      12.889095                        9.970453
2                      12.950535                        9.950692
1                      12.916629                        9.986683
6                      16.262948                       11.087531
0                      17.990874                       11.398662
5                      18.290049                       11.416684

   validation_test_abserror_std  validation_test_success  \
3                     11.683440                 0.572431
4                     11.705446                 0.568246
2                     11.978668                 0.569231
1                     11.688459                 0.566031
6                     20.774235                 0.569600
0                     28.107005                 0.571692
5                     30.601666                 0.570585

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.025182                               0.023663
4                    0.024417                               0.022375
2                    0.026350                               0.021080
1                    0.022829                               0.018533
6                   -0.084886                              -0.070320
0                   -0.115330                              -0.100169
5                   -0.117093                              -0.100547

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.023566                             0.023614
4                             0.022188                             0.022281
2                             0.019762                             0.020410
1                             0.017537                             0.018028
6                            -0.067302                                  NaN
0                            -0.097875                                  NaN
5                            -0.097824                                  NaN

[7 rows x 50 columns]
                              early_stopping_metric -val_mean_absolute_error
8 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.05360193115528884, Original: 9.762922791515482, New: 10.286234306860695
Test: Improvement: -0.08815158971680505, Original: 10.2199936987652, New: 11.120902390207082

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128
6          0.001         128
7          0.001         128
0          0.001         128
5          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.398717                  17.366732
4                     1.092420                  17.322748
2                     0.533792                  17.604229
1                     0.448239                  17.398793
6                    -0.063065                  26.379132
7                     0.681719                  28.289947
0                     1.095575                  33.337623
5                     1.226944                  35.609943

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.868399                        9.962636
4                      12.889095                        9.970453
2                      12.950535                        9.950692
1                      12.916629                        9.986683
6                      16.262948                       11.087531
7                      16.572892                       11.120902
0                      17.990874                       11.398662
5                      18.290049                       11.416684

   validation_test_abserror_std  validation_test_success  \
3                     11.683440                 0.572431
4                     11.705446                 0.568246
2                     11.978668                 0.569231
1                     11.688459                 0.566031
6                     20.774235                 0.569600
7                     22.963489                 0.569846
0                     28.107005                 0.571692
5                     30.601666                 0.570585

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.025182                               0.023663
4                    0.024417                               0.022375
2                    0.026350                               0.021080
1                    0.022829                               0.018533
6                   -0.084886                              -0.070320
7                   -0.088152                              -0.070877
0                   -0.115330                              -0.100169
5                   -0.117093                              -0.100547

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.023566                             0.023614
4                             0.022188                             0.022281
2                             0.019762                             0.020410
1                             0.017537                             0.018028
6                            -0.067302                                  NaN
7                            -0.066666                                  NaN
0                            -0.097875                                  NaN
5                            -0.097824                                  NaN

[8 rows x 50 columns]
                              early_stopping_metric -val_mean_squared_error
9 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.0209542027846389, Original: 9.762922791515482, New: 9.558348527571294
Test: Improvement: 0.024371042562903355, Original: 10.2199936987652, New: 9.970921797339988

-------------------------
   learning_rate  batch_size  \
3          0.001         128
8          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128
6          0.001         128
7          0.001         128
0          0.001         128
5          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.398717                  17.366732
8                     0.089352                  17.479672
4                     1.092420                  17.322748
2                     0.533792                  17.604229
1                     0.448239                  17.398793
6                    -0.063065                  26.379132
7                     0.681719                  28.289947
0                     1.095575                  33.337623
5                     1.226944                  35.609943

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.868399                        9.962636
8                      12.918427                        9.970922
4                      12.889095                        9.970453
2                      12.950535                        9.950692
1                      12.916629                        9.986683
6                      16.262948                       11.087531
7                      16.572892                       11.120902
0                      17.990874                       11.398662
5                      18.290049                       11.416684

   validation_test_abserror_std  validation_test_success  \
3                     11.683440                 0.572431
8                     11.787911                 0.572677
4                     11.705446                 0.568246
2                     11.978668                 0.569231
1                     11.688459                 0.566031
6                     20.774235                 0.569600
7                     22.963489                 0.569846
0                     28.107005                 0.571692
5                     30.601666                 0.570585

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.025182                               0.023663
8                    0.024371                               0.022663
4                    0.024417                               0.022375
2                    0.026350                               0.021080
1                    0.022829                               0.018533
6                   -0.084886                              -0.070320
7                   -0.088152                              -0.070877
0                   -0.115330                              -0.100169
5                   -0.117093                              -0.100547

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.023566                             0.023614
8                             0.022534                             0.022598
4                             0.022188                             0.022281
2                             0.019762                             0.020410
1                             0.017537                             0.018028
6                            -0.067302                                  NaN
7                            -0.066666                                  NaN
0                            -0.097875                                  NaN
5                            -0.097824                                  NaN

[9 rows x 50 columns]
                              early_stopping_metric -val_root_mean_squared_error
10 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02319262823182866, Original: 9.762922791515482, New: 9.536494952755817
Test: Improvement: 0.029110767989435415, Original: 10.2199936987652, New: 9.922481833346954

-------------------------
   learning_rate  batch_size  \
9          0.001         128
3          0.001         128
8          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128
6          0.001         128
7          0.001         128
0          0.001         128
5          0.001         128

                                           optimizer  \
9  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
9  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
9  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
9  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
9    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
9  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
9                     0.421698                  17.370672
3                     0.398717                  17.366732
8                     0.089352                  17.479672
4                     1.092420                  17.322748
2                     0.533792                  17.604229
1                     0.448239                  17.398793
6                    -0.063065                  26.379132
7                     0.681719                  28.289947
0                     1.095575                  33.337623
5                     1.226944                  35.609943

   validation_test_abserror_mean validation_test_abserror_median  \
9                      12.852826                        9.922482
3                      12.868399                        9.962636
8                      12.918427                        9.970922
4                      12.889095                        9.970453
2                      12.950535                        9.950692
1                      12.916629                        9.986683
6                      16.262948                       11.087531
7                      16.572892                       11.120902
0                      17.990874                       11.398662
5                      18.290049                       11.416684

   validation_test_abserror_std  validation_test_success  \
9                     11.722423                 0.567631
3                     11.683440                 0.572431
8                     11.787911                 0.572677
4                     11.705446                 0.568246
2                     11.978668                 0.569231
1                     11.688459                 0.566031
6                     20.774235                 0.569600
7                     22.963489                 0.569846
0                     28.107005                 0.571692
5                     30.601666                 0.570585

  validation_test_improvement  validation_avg_train_test_improvement  \
9                    0.029111                               0.026152
3                    0.025182                               0.023663
8                    0.024371                               0.022663
4                    0.024417                               0.022375
2                    0.026350                               0.021080
1                    0.022829                               0.018533
6                   -0.084886                              -0.070320
7                   -0.088152                              -0.070877
0                   -0.115330                              -0.100169
5                   -0.117093                              -0.100547

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                             0.025817                             0.025984
3                             0.023566                             0.023614
8                             0.022534                             0.022598
4                             0.022188                             0.022281
2                             0.019762                             0.020410
1                             0.017537                             0.018028
6                            -0.067302                                  NaN
7                            -0.066666                                  NaN
0                            -0.097875                                  NaN
5                            -0.097824                                  NaN

[10 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 5, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -loss
1 10

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.08420317131437965, Original: 9.762922791515482, New: 10.584991851858522
Test: Improvement: -0.11633695217627138, Original: 10.2199936987652, New: 11.408956616940241

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                      1.26066                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
0                   -0.116337                               -0.10027

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                            -0.097696                                 None

[1 rows x 50 columns]
                              early_stopping_metric -val_loss
2 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02327549659822057, Original: 9.762922791515482, New: 9.535685915292873
Test: Improvement: 0.023749661251280654, Original: 10.2199936987652, New: 9.977272310429303

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     -0.18575                  17.480981
0                      1.26066                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.872871                        9.977272
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
1                     11.828379                 0.569846
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.023750                               0.023513
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.023510                             0.023511
0                            -0.097696                                  NaN

[2 rows x 50 columns]
                              early_stopping_metric -val_mean_absolute_error
3 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021915177514433403, Original: 9.762922791515482, New: 9.548966605479713
Test: Improvement: 0.02441552699390447, Original: 10.2199936987652, New: 9.970467166735464

-------------------------
   learning_rate  batch_size  \
1          0.001         128
2          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.872871                        9.977272
2                      12.951436                        9.970467
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
1                     11.828379                 0.569846
2                     12.001359                 0.570585
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.023750                               0.023513
2                    0.024416                               0.023165
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.023510                             0.023511
2                             0.023098                             0.023132
0                            -0.097696                                  NaN

[3 rows x 50 columns]
                              early_stopping_metric -val_mean_squared_error
4 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.025211539676469736, Original: 9.762922791515482, New: 9.516784476198879
Test: Improvement: 0.027169551910983736, Original: 10.2199936987652, New: 9.942321049436671

-------------------------
   learning_rate  batch_size  \
3          0.001         128
1          0.001         128
2          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.265467                  17.432046
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.878805                        9.942321
1                      12.872871                        9.977272
2                      12.951436                        9.970467
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
3                     11.774525                 0.567262
1                     11.828379                 0.569846
2                     12.001359                 0.570585
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.027170                               0.026191
1                    0.023750                               0.023513
2                    0.024416                               0.023165
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026154                             0.026172
1                             0.023510                             0.023511
2                             0.023098                             0.023132
0                            -0.097696                                  NaN

[4 rows x 50 columns]
                              early_stopping_metric -val_root_mean_squared_error
5 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02103209866964206, Original: 9.762922791515482, New: 9.557588036060231
Test: Improvement: 0.028253643940333018, Original: 10.2199936987652, New: 9.93124163572784

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
1          0.001         128
2          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.265467                  17.432046
4                     1.216826                  17.171892
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.878805                        9.942321
4                      12.860939                        9.931242
1                      12.872871                        9.977272
2                      12.951436                        9.970467
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
3                     11.774525                 0.567262
4                     11.503885                 0.563077
1                     11.828379                 0.569846
2                     12.001359                 0.570585
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.027170                               0.026191
4                    0.028254                               0.024643
1                    0.023750                               0.023513
2                    0.024416                               0.023165
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026154                             0.026172
4                             0.024114                             0.024377
1                             0.023510                             0.023511
2                             0.023098                             0.023132
0                            -0.097696                                  NaN

[5 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -loss
6 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: -0.0815412400298547, Original: 9.762922791515482, New: 10.559003622251385
Test: Improvement: -0.1103557330288152, Original: 10.2199936987652, New: 11.347828594942305

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
1          0.001         128
2          0.001         128
5          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.265467                  17.432046
4                     1.216826                  17.171892
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
5                     1.137931                  34.234651
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.878805                        9.942321
4                      12.860939                        9.931242
1                      12.872871                        9.977272
2                      12.951436                        9.970467
5                      18.078820                       11.347829
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
3                     11.774525                 0.567262
4                     11.503885                 0.563077
1                     11.828379                 0.569846
2                     12.001359                 0.570585
5                     29.128498                 0.572677
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.027170                               0.026191
4                    0.028254                               0.024643
1                    0.023750                               0.023513
2                    0.024416                               0.023165
5                   -0.110356                              -0.095948
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026154                             0.026172
4                             0.024114                             0.024377
1                             0.023510                             0.023511
2                             0.023098                             0.023132
5                            -0.093785                                  NaN
0                            -0.097696                                  NaN

[6 rows x 50 columns]
                              early_stopping_metric -val_loss
7 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.059435942766858145, Original: 9.762922791515482, New: 10.343191311789251
Test: Improvement: -0.09231904465227479, Original: 10.2199936987652, New: 11.16349375338747

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
1          0.001         128
2          0.001         128
6          0.001         128
5          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.265467                  17.432046
4                     1.216826                  17.171892
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
6                     0.270056                  31.436426
5                     1.137931                  34.234651
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.878805                        9.942321
4                      12.860939                        9.931242
1                      12.872871                        9.977272
2                      12.951436                        9.970467
6                      17.140266                       11.163494
5                      18.078820                       11.347829
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
3                     11.774525                 0.567262
4                     11.503885                 0.563077
1                     11.828379                 0.569846
2                     12.001359                 0.570585
6                     26.363981                 0.569108
5                     29.128498                 0.572677
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.027170                               0.026191
4                    0.028254                               0.024643
1                    0.023750                               0.023513
2                    0.024416                               0.023165
6                   -0.092319                              -0.075877
5                   -0.110356                              -0.095948
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026154                             0.026172
4                             0.024114                             0.024377
1                             0.023510                             0.023511
2                             0.023098                             0.023132
6                            -0.072315                                  NaN
5                            -0.093785                                  NaN
0                            -0.097696                                  NaN

[7 rows x 50 columns]
                              early_stopping_metric -val_mean_absolute_error
8 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: -0.03986405071805937, Original: 9.762922791515482, New: 10.152112440832953
Test: Improvement: -0.056883930360163454, Original: 10.2199936987652, New: 10.801347108607068

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
1          0.001         128
2          0.001         128
7          0.001         128
6          0.001         128
5          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.265467                  17.432046
4                     1.216826                  17.171892
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
7                     0.678378                  26.318429
6                     0.270056                  31.436426
5                     1.137931                  34.234651
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.878805                        9.942321
4                      12.860939                        9.931242
1                      12.872871                        9.977272
2                      12.951436                        9.970467
7                      15.933542                       10.801347
6                      17.140266                       11.163494
5                      18.078820                       11.347829
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
3                     11.774525                 0.567262
4                     11.503885                 0.563077
1                     11.828379                 0.569846
2                     12.001359                 0.570585
7                     21.003585                 0.569723
6                     26.363981                 0.569108
5                     29.128498                 0.572677
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.027170                               0.026191
4                    0.028254                               0.024643
1                    0.023750                               0.023513
2                    0.024416                               0.023165
7                   -0.056884                              -0.048374
6                   -0.092319                              -0.075877
5                   -0.110356                              -0.095948
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026154                             0.026172
4                             0.024114                             0.024377
1                             0.023510                             0.023511
2                             0.023098                             0.023132
7                            -0.046877                                  NaN
6                            -0.072315                                  NaN
5                            -0.093785                                  NaN
0                            -0.097696                                  NaN

[8 rows x 50 columns]
                              early_stopping_metric -val_mean_squared_error
9 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.016533279755273685, Original: 9.762922791515482, New: 9.60150965777422
Test: Improvement: 0.017813669804974917, Original: 10.2199936987652, New: 10.037938105606472

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
1          0.001         128
2          0.001         128
8          0.001         128
7          0.001         128
6          0.001         128
5          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.265467                  17.432046
4                     1.216826                  17.171892
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
8                     1.683032                  18.283232
7                     0.678378                  26.318429
6                     0.270056                  31.436426
5                     1.137931                  34.234651
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.878805                        9.942321
4                      12.860939                        9.931242
1                      12.872871                        9.977272
2                      12.951436                        9.970467
8                      13.291107                       10.037938
7                      15.933542                       10.801347
6                      17.140266                       11.163494
5                      18.078820                       11.347829
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
3                     11.774525                 0.567262
4                     11.503885                 0.563077
1                     11.828379                 0.569846
2                     12.001359                 0.570585
8                     12.771912                 0.568492
7                     21.003585                 0.569723
6                     26.363981                 0.569108
5                     29.128498                 0.572677
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.027170                               0.026191
4                    0.028254                               0.024643
1                    0.023750                               0.023513
2                    0.024416                               0.023165
8                    0.017814                               0.017173
7                   -0.056884                              -0.048374
6                   -0.092319                              -0.075877
5                   -0.110356                              -0.095948
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026154                             0.026172
4                             0.024114                             0.024377
1                             0.023510                             0.023511
2                             0.023098                             0.023132
8                             0.017150                             0.017162
7                            -0.046877                                  NaN
6                            -0.072315                                  NaN
5                            -0.093785                                  NaN
0                            -0.097696                                  NaN

[9 rows x 50 columns]
                              early_stopping_metric -val_root_mean_squared_error
10 10
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02312250028400278, Original: 9.762922791515482, New: 9.537179606495968
Test: Improvement: 0.02679881642180999, Original: 10.2199936987652, New: 9.946109963799936

-------------------------
   learning_rate  batch_size  \
3          0.001         128
9          0.001         128
4          0.001         128
1          0.001         128
2          0.001         128
8          0.001         128
7          0.001         128
6          0.001         128
5          0.001         128
0          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
9  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
9  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
9    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
8    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.265467                  17.432046
9                     0.461821                  17.294494
4                     1.216826                  17.171892
1                    -0.185750                  17.480981
2                     0.334511                  17.637852
8                     1.683032                  18.283232
7                     0.678378                  26.318429
6                     0.270056                  31.436426
5                     1.137931                  34.234651
0                     1.260660                  34.349731

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.878805                        9.942321
9                      12.847960                        9.946110
4                      12.860939                        9.931242
1                      12.872871                        9.977272
2                      12.951436                        9.970467
8                      13.291107                       10.037938
7                      15.933542                       10.801347
6                      17.140266                       11.163494
5                      18.078820                       11.347829
0                      18.160206                       11.408957

   validation_test_abserror_std  validation_test_success  \
3                     11.774525                 0.567262
9                     11.612166                 0.572308
4                     11.503885                 0.563077
1                     11.828379                 0.569846
2                     12.001359                 0.570585
8                     12.771912                 0.568492
7                     21.003585                 0.569723
6                     26.363981                 0.569108
5                     29.128498                 0.572677
0                     29.222171                 0.570338

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.027170                               0.026191
9                    0.026799                               0.024961
4                    0.028254                               0.024643
1                    0.023750                               0.023513
2                    0.024416                               0.023165
8                    0.017814                               0.017173
7                   -0.056884                              -0.048374
6                   -0.092319                              -0.075877
5                   -0.110356                              -0.095948
0                   -0.116337                              -0.100270

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.026154                             0.026172
9                             0.024825                             0.024893
4                             0.024114                             0.024377
1                             0.023510                             0.023511
2                             0.023098                             0.023132
8                             0.017150                             0.017162
7                            -0.046877                                  NaN
6                            -0.072315                                  NaN
5                            -0.093785                                  NaN
0                            -0.097696                                  NaN

[10 rows x 50 columns]
early_stopping_metrics Selected -  ['val_mean_squared_error']

'''''''' outlier_dicts
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 4, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': False, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
1 8

X_pca shape: (28310, 15)
Training fold 1...
177/177 [==============================] - 0s 2ms/step
   1/1643 [..............................] - ETA: 51s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.020872402388854534, Original: 9.762922791515482, New: 9.559147138519652
Test: Improvement: 0.026372109776729387, Original: 10.2199936987652, New: 9.95047090302388

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.931152                  17.482066

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.950804                        9.950471

   validation_test_abserror_std  validation_test_success  \
0                     11.823049                 0.568615

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.026372                               0.023622

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.023302                             0.023462

[1 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
2 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
   1/1643 [..............................] - ETA: 51s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0200177399456695, Original: 9.762922791515482, New: 9.567491141965276
Test: Improvement: 0.019597061270519925, Original: 10.2199936987652, New: 10.01971185606617

-------------------------
   learning_rate  batch_size  \
0          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.931152                  17.482066
1                     0.735189                  18.452406

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.950804                        9.950471
1                      13.191655                       10.019712

   validation_test_abserror_std  validation_test_success  \
0                     11.823049                 0.568615
1                     12.991278                 0.567877

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.026372                               0.023622
1                    0.019597                               0.019807

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.023302                             0.023462
1                             0.019805                             0.019806

[2 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
3 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022367231156431713, Original: 9.762922791515482, New: 9.54455324067526
Test: Improvement: 0.028401516147333206, Original: 10.2199936987652, New: 9.929730382704076

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.448421                  17.286368
0                     0.931152                  17.482066
1                     0.735189                  18.452406

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.841634                        9.929730
0                      12.950804                        9.950471
1                      13.191655                       10.019712

   validation_test_abserror_std  validation_test_success  \
2                     11.602428                 0.571938
0                     11.823049                 0.568615
1                     12.991278                 0.567877

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.028402                               0.025384
0                    0.026372                               0.023622
1                    0.019597                               0.019807

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.025026                             0.025204
0                             0.023302                             0.023462
1                             0.019805                             0.019806

[3 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.02, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
4 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 567
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 567 (2.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
  41/1643 [..............................] - ETA: 2s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024977969682749138, Original: 9.762922791515482, New: 9.519064802013988
Test: Improvement: 0.022897902372039113, Original: 10.2199936987652, New: 9.985977280808019

-------------------------
   learning_rate  batch_size  \
2          0.001         128
3          0.001         128
0          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.448421                  17.286368
3                     0.794375                  17.750551
0                     0.931152                  17.482066
1                     0.735189                  18.452406

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.841634                        9.929730
3                      13.023467                        9.985977
0                      12.950804                        9.950471
1                      13.191655                       10.019712

   validation_test_abserror_std  validation_test_success  \
2                     11.602428                 0.571938
3                     12.127454                 0.569723
0                     11.823049                 0.568615
1                     12.991278                 0.567877

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.028402                               0.025384
3                    0.022898                               0.023938
0                    0.026372                               0.023622
1                    0.019597                               0.019807

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.025026                             0.025204
3                             0.023893                             0.023915
0                             0.023302                             0.023462
1                             0.019805                             0.019806

[4 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': False, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
5 8
X_pca shape: (28310, 15)
Training fold 1...
177/177 [==============================] - 0s 2ms/step
  27/1643 [..............................] - ETA: 3s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021210055326834756, Original: 9.762922791515482, New: 9.555850658955823
Test: Improvement: 0.028141254413467647, Original: 10.2199936987652, New: 9.932390255984211

-------------------------
   learning_rate  batch_size  \
2          0.001         128
4          0.001         128
3          0.001         128
0          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.448421                  17.286368
4                    -0.169888                  17.091302
3                     0.794375                  17.750551
0                     0.931152                  17.482066
1                     0.735189                  18.452406

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.841634                        9.929730
4                      12.771363                        9.932390
3                      13.023467                        9.985977
0                      12.950804                        9.950471
1                      13.191655                       10.019712

   validation_test_abserror_std  validation_test_success  \
2                     11.602428                 0.571938
4                     11.357875                 0.569354
3                     12.127454                 0.569723
0                     11.823049                 0.568615
1                     12.991278                 0.567877

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.028402                               0.025384
4                    0.028141                               0.024676
3                    0.022898                               0.023938
0                    0.026372                               0.023622
1                    0.019597                               0.019807

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.025026                             0.025204
4                             0.024189                             0.024431
3                             0.023893                             0.023915
0                             0.023302                             0.023462
1                             0.019805                             0.019806

[5 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
6 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
  30/1643 [..............................] - ETA: 2s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02091133853764697, Original: 9.762922791515482, New: 9.558767007905193
Test: Improvement: 0.019079458053695725, Original: 10.2199936987652, New: 10.025001757680574

-------------------------
   learning_rate  batch_size  \
2          0.001         128
4          0.001         128
3          0.001         128
0          0.001         128
5          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.448421                  17.286368
4                    -0.169888                  17.091302
3                     0.794375                  17.750551
0                     0.931152                  17.482066
5                     0.861472                  18.125646
1                     0.735189                  18.452406

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.841634                        9.929730
4                      12.771363                        9.932390
3                      13.023467                        9.985977
0                      12.950804                        9.950471
5                      13.173658                       10.025002
1                      13.191655                       10.019712

   validation_test_abserror_std  validation_test_success  \
2                     11.602428                 0.571938
4                     11.357875                 0.569354
3                     12.127454                 0.569723
0                     11.823049                 0.568615
5                     12.526723                 0.566277
1                     12.991278                 0.567877

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.028402                               0.025384
4                    0.028141                               0.024676
3                    0.022898                               0.023938
0                    0.026372                               0.023622
5                    0.019079                               0.019995
1                    0.019597                               0.019807

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.025026                             0.025204
4                             0.024189                             0.024431
3                             0.023893                             0.023915
0                             0.023302                             0.023462
5                             0.019953                             0.019974
1                             0.019805                             0.019806

[6 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
7 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02357722106507798, Original: 9.762922791515482, New: 9.532740202618633
Test: Improvement: 0.02975691021898156, Original: 10.2199936987652, New: 9.915878263832486

-------------------------
   learning_rate  batch_size  \
6          0.001         128
2          0.001         128
4          0.001         128
3          0.001         128
0          0.001         128
5          0.001         128
1          0.001         128

                                           optimizer  \
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
6  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
6  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
6                     0.250013                  17.075428
2                     0.448421                  17.286368
4                    -0.169888                  17.091302
3                     0.794375                  17.750551
0                     0.931152                  17.482066
5                     0.861472                  18.125646
1                     0.735189                  18.452406

   validation_test_abserror_mean validation_test_abserror_median  \
6                      12.766603                        9.915878
2                      12.841634                        9.929730
4                      12.771363                        9.932390
3                      13.023467                        9.985977
0                      12.950804                        9.950471
5                      13.173658                       10.025002
1                      13.191655                       10.019712

   validation_test_abserror_std  validation_test_success  \
6                     11.367776                 0.572185
2                     11.602428                 0.571938
4                     11.357875                 0.569354
3                     12.127454                 0.569723
0                     11.823049                 0.568615
5                     12.526723                 0.566277
1                     12.991278                 0.567877

  validation_test_improvement  validation_avg_train_test_improvement  \
6                    0.029757                               0.026667
2                    0.028402                               0.025384
4                    0.028141                               0.024676
3                    0.022898                               0.023938
0                    0.026372                               0.023622
5                    0.019079                               0.019995
1                    0.019597                               0.019807

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
6                             0.026309                             0.026487
2                             0.025026                             0.025204
4                             0.024189                             0.024431
3                             0.023893                             0.023915
0                             0.023302                             0.023462
5                             0.019953                             0.019974
1                             0.019805                             0.019806

[7 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.02, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
8 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 567
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 567 (2.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
  38/1643 [..............................] - ETA: 2s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02291800825842777, Original: 9.762922791515482, New: 9.539176046353138
Test: Improvement: 0.02458612869091089, Original: 10.2199936987652, New: 9.96872361846706

-------------------------
   learning_rate  batch_size  \
6          0.001         128
2          0.001         128
4          0.001         128
3          0.001         128
7          0.001         128
0          0.001         128
5          0.001         128
1          0.001         128

                                           optimizer  \
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
6  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
6  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
6                     0.250013                  17.075428
2                     0.448421                  17.286368
4                    -0.169888                  17.091302
3                     0.794375                  17.750551
7                    -0.242436                  18.208164
0                     0.931152                  17.482066
5                     0.861472                  18.125646
1                     0.735189                  18.452406

   validation_test_abserror_mean validation_test_abserror_median  \
6                      12.766603                        9.915878
2                      12.841634                        9.929730
4                      12.771363                        9.932390
3                      13.023467                        9.985977
7                      13.188236                        9.968724
0                      12.950804                        9.950471
5                      13.173658                       10.025002
1                      13.191655                       10.019712

   validation_test_abserror_std  validation_test_success  \
6                     11.367776                 0.572185
2                     11.602428                 0.571938
4                     11.357875                 0.569354
3                     12.127454                 0.569723
7                     12.555505                 0.566523
0                     11.823049                 0.568615
5                     12.526723                 0.566277
1                     12.991278                 0.567877

  validation_test_improvement  validation_avg_train_test_improvement  \
6                    0.029757                               0.026667
2                    0.028402                               0.025384
4                    0.028141                               0.024676
3                    0.022898                               0.023938
7                    0.024586                               0.023752
0                    0.026372                               0.023622
5                    0.019079                               0.019995
1                    0.019597                               0.019807

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
6                             0.026309                             0.026487
2                             0.025026                             0.025204
4                             0.024189                             0.024431
3                             0.023893                             0.023915
7                             0.023723                             0.023737
0                             0.023302                             0.023462
5                             0.019953                             0.019974
1                             0.019805                             0.019806

[8 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 1, lr_schedule_strategies: 1, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 4, activation_layers_list: 1, epochs: 1, loss_functions: 2, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.LogCosh'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': False, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
1 8

X_pca shape: (28310, 15)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
  41/1643 [..............................] - ETA: 2s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02096746405946374, Original: 9.762922791515482, New: 9.558219058769062
Test: Improvement: 0.031601904001102785, Original: 10.2199936987652, New: 9.897022439004946

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.445168                  17.377827

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.896333                        9.897022

   validation_test_abserror_std  validation_test_success  \
0                     11.676976                 0.572554

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.031602                               0.026285

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025209                             0.025741

[1 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
2 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
  31/1643 [..............................] - ETA: 2s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02352917776886973, Original: 9.762922791515482, New: 9.533209245610164
Test: Improvement: 0.019609566040233287, Original: 10.2199936987652, New: 10.019584057398495

-------------------------
   learning_rate  batch_size  \
0          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.445168                  17.377827
1                     0.233607                  17.307492

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.896333                        9.897022
1                      12.861033                       10.019584

   validation_test_abserror_std  validation_test_success  \
0                     11.676976                 0.572554
1                     11.603444                 0.563815

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.031602                               0.026285
1                    0.019610                               0.021569

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025209                             0.025741
1                             0.021391                             0.021480

[2 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
3 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.01898641249380896, Original: 9.762922791515482, New: 9.57755991225056
Test: Improvement: 0.025701568231185877, Original: 10.2199936987652, New: 9.957323833394096

-------------------------
   learning_rate  batch_size  \
0          0.001         128
2          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                     0.445168                  17.377827
2                     1.162819                  18.264393
1                     0.233607                  17.307492

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.896333                        9.897022
2                      13.162003                        9.957324
1                      12.861033                       10.019584

   validation_test_abserror_std  validation_test_success  \
0                     11.676976                 0.572554
2                     12.794434                 0.567385
1                     11.603444                 0.563815

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.031602                               0.026285
2                    0.025702                               0.022344
1                    0.019610                               0.021569

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.025209                             0.025741
2                             0.021839                             0.022090
1                             0.021391                             0.021480

[3 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.02, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
4 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 567
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 567 (2.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step
   1/1643 [..............................] - ETA: 51s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02177425547396382, Original: 9.762922791515482, New: 9.55034241648044
Test: Improvement: 0.030805635011179666, Original: 10.2199936987652, New: 9.905160303064482

-------------------------
   learning_rate  batch_size  \
3          0.001         128
0          0.001         128
2          0.001         128
1          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.243648                  17.274581
0                     0.445168                  17.377827
2                     1.162819                  18.264393
1                     0.233607                  17.307492

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.856956                        9.905160
0                      12.896333                        9.897022
2                      13.162003                        9.957324
1                      12.861033                       10.019584

   validation_test_abserror_std  validation_test_success  \
3                     11.557743                 0.571446
0                     11.676976                 0.572554
2                     12.794434                 0.567385
1                     11.603444                 0.563815

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.030806                               0.026290
0                    0.031602                               0.026285
2                    0.025702                               0.022344
1                    0.019610                               0.021569

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.025514                             0.025899
0                             0.025209                             0.025741
2                             0.021839                             0.022090
1                             0.021391                             0.021480

[4 rows x 50 columns]
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': False, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
5 8
X_pca shape: (28310, 15)
Training fold 1...
177/177 [==============================] - 0s 2ms/step
   1/1643 [..............................] - ETA: 51s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024264803347508627, Original: 9.762922791515482, New: 9.526027389882449
Test: Improvement: 0.02575066340847363, Original: 10.2199936987652, New: 9.956822080991575

-------------------------
   learning_rate  batch_size  \
3          0.001         128
0          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.243648                  17.274581
0                     0.445168                  17.377827
4                     0.345034                  17.331226
2                     1.162819                  18.264393
1                     0.233607                  17.307492

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.856956                        9.905160
0                      12.896333                        9.897022
4                      12.865111                        9.956822
2                      13.162003                        9.957324
1                      12.861033                       10.019584

   validation_test_abserror_std  validation_test_success  \
3                     11.557743                 0.571446
0                     11.676976                 0.572554
4                     11.636980                 0.570954
2                     12.794434                 0.567385
1                     11.603444                 0.563815

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.030806                               0.026290
0                    0.031602                               0.026285
4                    0.025751                               0.025008
2                    0.025702                               0.022344
1                    0.019610                               0.021569

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.025514                             0.025899
0                             0.025209                             0.025741
4                             0.024986                             0.024997
2                             0.021839                             0.022090
1                             0.021391                             0.021480

[5 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
6 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
   1/1643 [..............................] - ETA: 51s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024612127293799167, Original: 9.762922791515482, New: 9.52263649301117
Test: Improvement: 0.017384436753184844, Original: 10.2199936987652, New: 10.042324864691068

-------------------------
   learning_rate  batch_size  \
3          0.001         128
0          0.001         128
4          0.001         128
2          0.001         128
1          0.001         128
5          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.243648                  17.274581
0                     0.445168                  17.377827
4                     0.345034                  17.331226
2                     1.162819                  18.264393
1                     0.233607                  17.307492
5                     1.144745                  18.365501

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.856956                        9.905160
0                      12.896333                        9.897022
4                      12.865111                        9.956822
2                      13.162003                        9.957324
1                      12.861033                       10.019584
5                      13.251212                       10.042325

   validation_test_abserror_std  validation_test_success  \
3                     11.557743                 0.571446
0                     11.676976                 0.572554
4                     11.636980                 0.570954
2                     12.794434                 0.567385
1                     11.603444                 0.563815
5                     12.839335                 0.566523

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.030806                               0.026290
0                    0.031602                               0.026285
4                    0.025751                               0.025008
2                    0.025702                               0.022344
1                    0.019610                               0.021569
5                    0.017384                               0.020998

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.025514                             0.025899
0                             0.025209                             0.025741
4                             0.024986                             0.024997
2                             0.021839                             0.022090
1                             0.021391                             0.021480
5                             0.020376                             0.020685

[6 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
7 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019591904186140843, Original: 9.762922791515482, New: 9.57164854360742
Test: Improvement: 0.024420026515489024, Original: 10.2199936987652, New: 9.970421181653222

-------------------------
   learning_rate  batch_size  \
3          0.001         128
0          0.001         128
4          0.001         128
2          0.001         128
6          0.001         128
1          0.001         128
5          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.243648                  17.274581
0                     0.445168                  17.377827
4                     0.345034                  17.331226
2                     1.162819                  18.264393
6                     0.777975                  17.775437
1                     0.233607                  17.307492
5                     1.144745                  18.365501

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.856956                        9.905160
0                      12.896333                        9.897022
4                      12.865111                        9.956822
2                      13.162003                        9.957324
6                      13.043282                        9.970421
1                      12.861033                       10.019584
5                      13.251212                       10.042325

   validation_test_abserror_std  validation_test_success  \
3                     11.557743                 0.571446
0                     11.676976                 0.572554
4                     11.636980                 0.570954
2                     12.794434                 0.567385
6                     12.150932                 0.572677
1                     11.603444                 0.563815
5                     12.839335                 0.566523

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.030806                               0.026290
0                    0.031602                               0.026285
4                    0.025751                               0.025008
2                    0.025702                               0.022344
6                    0.024420                               0.022006
1                    0.019610                               0.021569
5                    0.017384                               0.020998

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.025514                             0.025899
0                             0.025209                             0.025741
4                             0.024986                             0.024997
2                             0.021839                             0.022090
6                             0.021741                             0.021873
1                             0.021391                             0.021480
5                             0.020376                             0.020685

[7 rows x 50 columns]
                                   outlier_dict -{'enabled': True, 'contamination': 0.02, 'remove_outliers': True}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.5
                              early_stopping_metric -val_mean_squared_error
8 8
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 567
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 567 (2.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step
   1/1643 [..............................] - ETA: 51s

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021507678577772756, Original: 9.762922791515482, New: 9.552944986135955
Test: Improvement: 0.02610442784762054, Original: 10.2199936987652, New: 9.953206610652646

-------------------------
   learning_rate  batch_size  \
3          0.001         128
0          0.001         128
4          0.001         128
7          0.001         128
2          0.001         128
6          0.001         128
1          0.001         128
5          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.LogCosh'>, {'reducti...
0  (<class 'keras.src.losses.LogCosh'>, {'reducti...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.LogCosh'>, {'reducti...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.LogCosh'>, {'reducti...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
4    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
6    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.LogCosh'>  {'reduction': 'auto'}
5    <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.243648                  17.274581
0                     0.445168                  17.377827
4                     0.345034                  17.331226
7                     1.259017                  17.979456
2                     1.162819                  18.264393
6                     0.777975                  17.775437
1                     0.233607                  17.307492
5                     1.144745                  18.365501

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.856956                        9.905160
0                      12.896333                        9.897022
4                      12.865111                        9.956822
7                      13.164732                        9.953207
2                      13.162003                        9.957324
6                      13.043282                        9.970421
1                      12.861033                       10.019584
5                      13.251212                       10.042325

   validation_test_abserror_std  validation_test_success  \
3                     11.557743                 0.571446
0                     11.676976                 0.572554
4                     11.636980                 0.570954
7                     12.386905                 0.567877
2                     12.794434                 0.567385
6                     12.150932                 0.572677
1                     11.603444                 0.563815
5                     12.839335                 0.566523

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.030806                               0.026290
0                    0.031602                               0.026285
4                    0.025751                               0.025008
7                    0.026104                               0.023806
2                    0.025702                               0.022344
6                    0.024420                               0.022006
1                    0.019610                               0.021569
5                    0.017384                               0.020998

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.025514                             0.025899
0                             0.025209                             0.025741
4                             0.024986                             0.024997
7                             0.023584                             0.023695
2                             0.021839                             0.022090
6                             0.021741                             0.021873
1                             0.021391                             0.021480
5                             0.020376                             0.020685

[8 rows x 50 columns]
outlier_dicts Selected -  [{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}]

'''''''' lr_schedule_enabled
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 2, lr_schedule_strategies: 20, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function exponential_decay_95 at 0x000001F6CE23ED30>, 'description': 'Exponential Decay 5%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02456452105529946, Original: 9.762922791515482, New: 9.523101269042037
Test: Improvement: 0.029869194734888187, Original: 10.2199936987652, New: 9.914730716787451

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.008559                  16.951075

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.720727                        9.914731

   validation_test_abserror_std  validation_test_success  \
0                     11.212632                   0.5696

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029869                               0.027217

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.026958                             0.027087

[1 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function exponential_decay_90 at 0x000001F6CE23EC10>, 'description': 'Exponential Decay 10%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023845938690643186, Original: 9.762922791515482, New: 9.530116733187521
Test: Improvement: 0.029681699616176678, Original: 10.2199936987652, New: 9.916646915719232

-------------------------
   learning_rate  batch_size  \
0          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.008559                  16.951075
1                     0.058154                  16.789144

   validation_test_abserror_mean validation_test_abserror_median  \
0                      12.720727                        9.914731
1                      12.650389                        9.916647

   validation_test_abserror_std  validation_test_success  \
0                     11.212632                 0.569600
1                     11.046908                 0.571938

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.029869                               0.027217
1                    0.029682                               0.026764

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.026958                             0.027087
1                             0.026446                             0.026604

[2 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function exponential_decay_85 at 0x000001F6CE23EA60>, 'description': 'Exponential Decay 15%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023738114680073943, Original: 9.762922791515482, New: 9.53116941067778
Test: Improvement: 0.031025847034040807, Original: 10.2199936987652, New: 9.90290973757845

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647

   validation_test_abserror_std  validation_test_success  \
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604

[3 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function exponential_decay_80 at 0x000001F6CE23E8B0>, 'description': 'Exponential Decay 20%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020651930324629163, Original: 9.762922791515482, New: 9.56129959026037
Test: Improvement: 0.027710095875101873, Original: 10.2199936987652, New: 9.936796693529478

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128
3          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144
3                     0.063888                  16.785046

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647
3                      12.668617                        9.936797

   validation_test_abserror_std  validation_test_success  \
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938
3                     11.021888                 0.568123

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764
3                    0.027710                               0.024181

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604
3                             0.023666                             0.023922

[4 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_50_10 at 0x000001F6CE23E160>, 'description': 'Step Decay 50% every 10 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.014702996246062897, Original: 9.762922791515482, New: 9.619378574361228
Test: Improvement: 0.026196112873906732, Original: 10.2199936987652, New: 9.95226959026173

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128
3          0.001         128
4          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144
3                     0.063888                  16.785046
4                    -0.121270                  16.649066

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647
3                      12.668617                        9.936797
4                      12.624274                        9.952270

   validation_test_abserror_std  validation_test_success  \
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938
3                     11.021888                 0.568123
4                     10.857124                 0.573538

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764
3                    0.027710                               0.024181
4                    0.026196                               0.020450

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604
3                             0.023666                             0.023922
4                             0.018835                             0.019626

[5 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_30_10 at 0x000001F6CE23E820>, 'description': 'Step Decay 30% every 10 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
6 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.012122729795426095, Original: 9.762922791515482, New: 9.644569516500333
Test: Improvement: 0.01884569487942181, Original: 10.2199936987652, New: 10.027390815848657

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128
3          0.001         128
4          0.001         128
5          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144
3                     0.063888                  16.785046
4                    -0.121270                  16.649066
5                    -0.178174                  16.675025

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647
3                      12.668617                        9.936797
4                      12.624274                        9.952270
5                      12.639790                       10.027391

   validation_test_abserror_std  validation_test_success  \
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938
3                     11.021888                 0.568123
4                     10.857124                 0.573538
5                     10.875920                 0.564431

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764
3                    0.027710                               0.024181
4                    0.026196                               0.020450
5                    0.018846                               0.015484

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604
3                             0.023666                             0.023922
4                             0.018835                             0.019626
5                             0.014754                             0.015115

[6 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_50_5 at 0x000001F714CEA670>, 'description': 'Step Decay 50% every 5 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
7 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021542086185280872, Original: 9.762922791515482, New: 9.552609067320413
Test: Improvement: 0.030860668154658294, Original: 10.2199936987652, New: 9.904597864684908

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128
6          0.001         128
3          0.001         128
4          0.001         128
5          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144
6                     0.201681                  16.764482
3                     0.063888                  16.785046
4                    -0.121270                  16.649066
5                    -0.178174                  16.675025

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647
6                      12.647483                        9.904598
3                      12.668617                        9.936797
4                      12.624274                        9.952270
5                      12.639790                       10.027391

   validation_test_abserror_std  validation_test_success  \
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938
6                     11.022772                 0.569723
3                     11.021888                 0.568123
4                     10.857124                 0.573538
5                     10.875920                 0.564431

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764
6                    0.030861                               0.026201
3                    0.027710                               0.024181
4                    0.026196                               0.020450
5                    0.018846                               0.015484

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604
6                             0.025373                             0.025784
3                             0.023666                             0.023922
4                             0.018835                             0.019626
5                             0.014754                             0.015115

[7 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_70_10 at 0x000001F714CEA700>, 'description': 'Step Decay 70% every 10 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
8 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01802964435530894, Original: 9.762922791515482, New: 9.586900765716118
Test: Improvement: 0.027025382326739584, Original: 10.2199936987652, New: 9.9437944616792

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128
6          0.001         128
3          0.001         128
7          0.001         128
4          0.001         128
5          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144
6                     0.201681                  16.764482
3                     0.063888                  16.785046
7                     0.109631                  16.708200
4                    -0.121270                  16.649066
5                    -0.178174                  16.675025

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647
6                      12.647483                        9.904598
3                      12.668617                        9.936797
7                      12.650159                        9.943794
4                      12.624274                        9.952270
5                      12.639790                       10.027391

   validation_test_abserror_std  validation_test_success  \
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938
6                     11.022772                 0.569723
3                     11.021888                 0.568123
7                     10.926910                 0.567877
4                     10.857124                 0.573538
5                     10.875920                 0.564431

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764
6                    0.030861                               0.026201
3                    0.027710                               0.024181
7                    0.027025                               0.022528
4                    0.026196                               0.020450
5                    0.018846                               0.015484

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604
6                             0.025373                             0.025784
3                             0.023666                             0.023922
7                             0.021629                             0.022074
4                             0.018835                             0.019626
5                             0.014754                             0.015115

[8 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_1e4 at 0x000001F714CEA790>, 'description': 'Time-Based Decay 1e-4'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
9 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0068366711545828785, Original: 9.762922791515482, New: 9.696176898882308
Test: Improvement: 0.007561617482527429, Original: 10.2199936987652, New: 10.142714015741296

-------------------------
   learning_rate  batch_size  \
2          0.001         128
0          0.001         128
1          0.001         128
6          0.001         128
3          0.001         128
7          0.001         128
4          0.001         128
5          0.001         128
8          0.001         128

                                           optimizer  \
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144
6                     0.201681                  16.764482
3                     0.063888                  16.785046
7                     0.109631                  16.708200
4                    -0.121270                  16.649066
5                    -0.178174                  16.675025
8                    -0.333692                  16.790131

   validation_test_abserror_mean validation_test_abserror_median  \
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647
6                      12.647483                        9.904598
3                      12.668617                        9.936797
7                      12.650159                        9.943794
4                      12.624274                        9.952270
5                      12.639790                       10.027391
8                      12.751797                       10.142714

   validation_test_abserror_std  validation_test_success  \
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938
6                     11.022772                 0.569723
3                     11.021888                 0.568123
7                     10.926910                 0.567877
4                     10.857124                 0.573538
5                     10.875920                 0.564431
8                     10.922196                 0.559631

  validation_test_improvement  validation_avg_train_test_improvement  \
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764
6                    0.030861                               0.026201
3                    0.027710                               0.024181
7                    0.027025                               0.022528
4                    0.026196                               0.020450
5                    0.018846                               0.015484
8                    0.007562                               0.007199

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604
6                             0.025373                             0.025784
3                             0.023666                             0.023922
7                             0.021629                             0.022074
4                             0.018835                             0.019626
5                             0.014754                             0.015115
8                             0.007181                             0.007190

[9 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_1e5 at 0x000001F714CEA820>, 'description': 'Time-Based Decay 1e-5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
10 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023377676837572317, Original: 9.762922791515482, New: 9.534688337505264
Test: Improvement: 0.035346200352111744, Original: 10.2199936987652, New: 9.858755753891325

-------------------------
   learning_rate  batch_size  \
9          0.001         128
2          0.001         128
0          0.001         128
1          0.001         128
6          0.001         128
3          0.001         128
7          0.001         128
4          0.001         128
5          0.001         128
8          0.001         128

                                           optimizer  \
9  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
9  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
9  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
9  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
9  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
9  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
9                     0.239345                  17.012395
2                     0.450236                  16.996905
0                    -0.008559                  16.951075
1                     0.058154                  16.789144
6                     0.201681                  16.764482
3                     0.063888                  16.785046
7                     0.109631                  16.708200
4                    -0.121270                  16.649066
5                    -0.178174                  16.675025
8                    -0.333692                  16.790131

   validation_test_abserror_mean validation_test_abserror_median  \
9                      12.722775                        9.858756
2                      12.756768                        9.902910
0                      12.720727                        9.914731
1                      12.650389                        9.916647
6                      12.647483                        9.904598
3                      12.668617                        9.936797
7                      12.650159                        9.943794
4                      12.624274                        9.952270
5                      12.639790                       10.027391
8                      12.751797                       10.142714

   validation_test_abserror_std  validation_test_success  \
9                     11.313678                 0.572554
2                     11.277419                 0.569477
0                     11.212632                 0.569600
1                     11.046908                 0.571938
6                     11.022772                 0.569723
3                     11.021888                 0.568123
7                     10.926910                 0.567877
4                     10.857124                 0.573538
5                     10.875920                 0.564431
8                     10.922196                 0.559631

  validation_test_improvement  validation_avg_train_test_improvement  \
9                    0.035346                               0.029362
2                    0.031026                               0.027382
0                    0.029869                               0.027217
1                    0.029682                               0.026764
6                    0.030861                               0.026201
3                    0.027710                               0.024181
7                    0.027025                               0.022528
4                    0.026196                               0.020450
5                    0.018846                               0.015484
8                    0.007562                               0.007199

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                             0.028142                             0.028746
2                             0.026897                             0.027138
0                             0.026958                             0.027087
1                             0.026446                             0.026604
6                             0.025373                             0.025784
3                             0.023666                             0.023922
7                             0.021629                             0.022074
4                             0.018835                             0.019626
5                             0.014754                             0.015115
8                             0.007181                             0.007190

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_5e4 at 0x000001F714CEA8B0>, 'description': 'Time-Based Decay 5e-4'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
11 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023922963995496264, Original: 9.762922791515482, New: 9.529364741083247
Test: Improvement: 0.0312093884744766, Original: 10.2199936987652, New: 9.901033945213733

-------------------------
    learning_rate  batch_size  \
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
3           0.001         128
7           0.001         128
4           0.001         128
5           0.001         128

                                            optimizer  \
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
3                      0.063888                  16.785046
7                      0.109631                  16.708200
4                     -0.121270                  16.649066
5                     -0.178174                  16.675025

    validation_test_abserror_mean validation_test_abserror_median  \
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
3                       12.668617                        9.936797
7                       12.650159                        9.943794
4                       12.624274                        9.952270
5                       12.639790                       10.027391

    validation_test_abserror_std  validation_test_success  \
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
3                      11.021888                 0.568123
7                      10.926910                 0.567877
4                      10.857124                 0.573538
5                      10.875920                 0.564431

   validation_test_improvement  validation_avg_train_test_improvement  \
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
3                     0.027710                               0.024181
7                     0.027025                               0.022528
4                     0.026196                               0.020450
5                     0.018846                               0.015484

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
3                              0.023666                             0.023922
7                              0.021629                             0.022074
4                              0.018835                             0.019626
5                              0.014754                             0.015115

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_2e4 at 0x000001F714CEA940>, 'description': 'Time-Based Decay 2e-4'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
12 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020367453301813995, Original: 9.762922791515482, New: 9.564076917470075
Test: Improvement: 0.02370120827126822, Original: 10.2199936987652, New: 9.977767499579716

-------------------------
    learning_rate  batch_size  \
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
3           0.001         128
7           0.001         128
11          0.001         128
4           0.001         128

                                            optimizer  \
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
3                      0.063888                  16.785046
7                      0.109631                  16.708200
11                     0.364443                  17.820325
4                     -0.121270                  16.649066

    validation_test_abserror_mean validation_test_abserror_median  \
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
3                       12.668617                        9.936797
7                       12.650159                        9.943794
11                      12.997926                        9.977767
4                       12.624274                        9.952270

    validation_test_abserror_std  validation_test_success  \
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
3                      11.021888                 0.568123
7                      10.926910                 0.567877
11                     12.230877                 0.570954
4                      10.857124                 0.573538

   validation_test_improvement  validation_avg_train_test_improvement  \
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
3                     0.027710                               0.024181
7                     0.027025                               0.022528
11                    0.023701                               0.022034
4                     0.026196                               0.020450

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
3                              0.023666                             0.023922
7                              0.021629                             0.022074
11                             0.021908                             0.021971
4                              0.018835                             0.019626

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_30 at 0x000001F714CEA9D0>, 'description': 'Cosine Annealing with 30 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
13 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02315292192567641, Original: 9.762922791515482, New: 9.536882602357117
Test: Improvement: 0.028685840025682887, Original: 10.2199936987652, New: 9.926824594458934

-------------------------
    learning_rate  batch_size  \
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
3           0.001         128
7           0.001         128
11          0.001         128

                                            optimizer  \
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
3                      0.063888                  16.785046
7                      0.109631                  16.708200
11                     0.364443                  17.820325

    validation_test_abserror_mean validation_test_abserror_median  \
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
3                       12.668617                        9.936797
7                       12.650159                        9.943794
11                      12.997926                        9.977767

    validation_test_abserror_std  validation_test_success  \
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
3                      11.021888                 0.568123
7                      10.926910                 0.567877
11                     12.230877                 0.570954

   validation_test_improvement  validation_avg_train_test_improvement  \
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
3                     0.027710                               0.024181
7                     0.027025                               0.022528
11                    0.023701                               0.022034

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
3                              0.023666                             0.023922
7                              0.021629                             0.022074
11                             0.021908                             0.021971

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
14 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020096608913239496, Original: 9.762922791515482, New: 9.566721150324243
Test: Improvement: 0.02345171569454934, Original: 10.2199936987652, New: 9.980317312141672

-------------------------
    learning_rate  batch_size  \
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
3           0.001         128
7           0.001         128
11          0.001         128

                                            optimizer  \
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
3                      0.063888                  16.785046
7                      0.109631                  16.708200
11                     0.364443                  17.820325

    validation_test_abserror_mean validation_test_abserror_median  \
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
3                       12.668617                        9.936797
7                       12.650159                        9.943794
11                      12.997926                        9.977767

    validation_test_abserror_std  validation_test_success  \
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
3                      11.021888                 0.568123
7                      10.926910                 0.567877
11                     12.230877                 0.570954

   validation_test_improvement  validation_avg_train_test_improvement  \
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
3                     0.027710                               0.024181
7                     0.027025                               0.022528
11                    0.023701                               0.022034

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
3                              0.023666                             0.023922
7                              0.021629                             0.022074
11                             0.021908                             0.021971

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_10 at 0x000001F714CEAAF0>, 'description': 'Cosine Annealing with 10 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
15 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023579174391746137, Original: 9.762922791515482, New: 9.532721132441186
Test: Improvement: 0.02722863700540333, Original: 10.2199936987652, New: 9.941717200144012

-------------------------
    learning_rate  batch_size  \
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
14          0.001         128
3           0.001         128
7           0.001         128

                                            optimizer  \
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
14                     0.693294                  17.782371
3                      0.063888                  16.785046
7                      0.109631                  16.708200

    validation_test_abserror_mean validation_test_abserror_median  \
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
14                      13.020177                        9.941717
3                       12.668617                        9.936797
7                       12.650159                        9.943794

    validation_test_abserror_std  validation_test_success  \
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
14                     12.179772                 0.571077
3                      11.021888                 0.568123
7                      10.926910                 0.567877

   validation_test_improvement  validation_avg_train_test_improvement  \
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
14                    0.027229                               0.025404
3                     0.027710                               0.024181
7                     0.027025                               0.022528

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
14                             0.025273                             0.025338
3                              0.023666                             0.023922
7                              0.021629                             0.022074

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_20 at 0x000001F717BD9DC0>, 'description': 'Cosine Annealing with 20 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
16 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01947041658225621, Original: 9.762922791515482, New: 9.572834617704272
Test: Improvement: 0.015995793339294514, Original: 10.2199936987652, New: 10.056516791630859

-------------------------
    learning_rate  batch_size  \
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
14          0.001         128
3           0.001         128
7           0.001         128

                                            optimizer  \
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
14                     0.693294                  17.782371
3                      0.063888                  16.785046
7                      0.109631                  16.708200

    validation_test_abserror_mean validation_test_abserror_median  \
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
14                      13.020177                        9.941717
3                       12.668617                        9.936797
7                       12.650159                        9.943794

    validation_test_abserror_std  validation_test_success  \
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
14                     12.179772                 0.571077
3                      11.021888                 0.568123
7                      10.926910                 0.567877

   validation_test_improvement  validation_avg_train_test_improvement  \
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
14                    0.027229                               0.025404
3                     0.027710                               0.024181
7                     0.027025                               0.022528

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
14                             0.025273                             0.025338
3                              0.023666                             0.023922
7                              0.021629                             0.022074

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D197C0>, 'description': 'Reduce on Plateau 50%, patience 5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
17 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02506784730635665, Original: 9.762922791515482, New: 9.518187333714023
Test: Improvement: 0.033767694851701925, Original: 10.2199936987652, New: 9.87488807015898

-------------------------
    learning_rate  batch_size  \
16          0.001         128
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
14          0.001         128
3           0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
16                     0.325227                  17.339575
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
14                     0.693294                  17.782371
3                      0.063888                  16.785046

    validation_test_abserror_mean validation_test_abserror_median  \
16                      12.840355                        9.874888
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
14                      13.020177                        9.941717
3                       12.668617                        9.936797

    validation_test_abserror_std  validation_test_success  \
16                     11.684345                 0.572062
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
14                     12.179772                 0.571077
3                      11.021888                 0.568123

   validation_test_improvement  validation_avg_train_test_improvement  \
16                    0.033768                               0.029418
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
14                    0.027229                               0.025404
3                     0.027710                               0.024181

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
16                             0.028775                             0.029094
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
14                             0.025273                             0.025338
3                              0.023666                             0.023922

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D3BDC0>, 'description': 'Reduce on Plateau 30%, patience 5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
18 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.006880904681480648, Original: 9.762922791515482, New: 9.69574505037441
Test: Improvement: 0.014173764319963004, Original: 10.2199936987652, New: 10.075137916727394

-------------------------
    learning_rate  batch_size  \
16          0.001         128
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
14          0.001         128
3           0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
16                     0.325227                  17.339575
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
14                     0.693294                  17.782371
3                      0.063888                  16.785046

    validation_test_abserror_mean validation_test_abserror_median  \
16                      12.840355                        9.874888
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
14                      13.020177                        9.941717
3                       12.668617                        9.936797

    validation_test_abserror_std  validation_test_success  \
16                     11.684345                 0.572062
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
14                     12.179772                 0.571077
3                      11.021888                 0.568123

   validation_test_improvement  validation_avg_train_test_improvement  \
16                    0.033768                               0.029418
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
14                    0.027229                               0.025404
3                     0.027710                               0.024181

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
16                             0.028775                             0.029094
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
14                             0.025273                             0.025338
3                              0.023666                             0.023922

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D197F0>, 'description': 'Reduce on Plateau 50%, patience 10'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
19 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.007272838970392925, Original: 9.762922791515482, New: 9.691918626172411
Test: Improvement: 0.010804687063410031, Original: 10.2199936987652, New: 10.109569865060019

-------------------------
    learning_rate  batch_size  \
16          0.001         128
9           0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
14          0.001         128
3           0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
16                     0.325227                  17.339575
9                      0.239345                  17.012395
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
14                     0.693294                  17.782371
3                      0.063888                  16.785046

    validation_test_abserror_mean validation_test_abserror_median  \
16                      12.840355                        9.874888
9                       12.722775                        9.858756
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
14                      13.020177                        9.941717
3                       12.668617                        9.936797

    validation_test_abserror_std  validation_test_success  \
16                     11.684345                 0.572062
9                      11.313678                 0.572554
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
14                     12.179772                 0.571077
3                      11.021888                 0.568123

   validation_test_improvement  validation_avg_train_test_improvement  \
16                    0.033768                               0.029418
9                     0.035346                               0.029362
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
14                    0.027229                               0.025404
3                     0.027710                               0.024181

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
16                             0.028775                             0.029094
9                              0.028142                             0.028746
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
14                             0.025273                             0.025338
3                              0.023666                             0.023922

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D19220>, 'description': 'Reduce on Plateau 70%, patience 5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
20 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02384145445964718, Original: 9.762922791515482, New: 9.530160512388514
Test: Improvement: 0.03452732407150693, Original: 10.2199936987652, New: 9.867124664319174

-------------------------
    learning_rate  batch_size  \
16          0.001         128
9           0.001         128
19          0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128
14          0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
16                     0.325227                  17.339575
9                      0.239345                  17.012395
19                     0.139074                  17.038571
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284
14                     0.693294                  17.782371

    validation_test_abserror_mean validation_test_abserror_median  \
16                      12.840355                        9.874888
9                       12.722775                        9.858756
19                      12.723624                        9.867125
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825
14                      13.020177                        9.941717

    validation_test_abserror_std  validation_test_success  \
16                     11.684345                 0.572062
9                      11.313678                 0.572554
19                     11.351394                 0.572677
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077
14                     12.179772                 0.571077

   validation_test_improvement  validation_avg_train_test_improvement  \
16                    0.033768                               0.029418
9                     0.035346                               0.029362
19                    0.034527                               0.029184
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919
14                    0.027229                               0.025404

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
16                             0.028775                             0.029094
9                              0.028142                             0.028746
19                             0.028206                             0.028691
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771
14                             0.025273                             0.025338

[10 rows x 50 columns]
                              lr_schedule_enabled -False
                              lr_schedule_strategies -None
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
21 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0244529933751089, Original: 9.762922791515482, New: 9.524190105172854
Test: Improvement: 0.030548919478493884, Original: 10.2199936987652, New: 9.907783934190906

-------------------------
    learning_rate  batch_size  \
16          0.001         128
9           0.001         128
19          0.001         128
20          0.001         128
10          0.001         128
2           0.001         128
0           0.001         128
1           0.001         128
6           0.001         128
12          0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
16                     0.325227                  17.339575
9                      0.239345                  17.012395
19                     0.139074                  17.038571
20                     0.218265                  16.703296
10                     0.252865                  17.019312
2                      0.450236                  16.996905
0                     -0.008559                  16.951075
1                      0.058154                  16.789144
6                      0.201681                  16.764482
12                     0.225705                  17.186284

    validation_test_abserror_mean validation_test_abserror_median  \
16                      12.840355                        9.874888
9                       12.722775                        9.858756
19                      12.723624                        9.867125
20                      12.622044                        9.907784
10                      12.733668                        9.901034
2                       12.756768                        9.902910
0                       12.720727                        9.914731
1                       12.650389                        9.916647
6                       12.647483                        9.904598
12                      12.789549                        9.926825

    validation_test_abserror_std  validation_test_success  \
16                     11.684345                 0.572062
9                      11.313678                 0.572554
19                     11.351394                 0.572677
20                     10.953969                 0.570462
10                     11.317919                 0.569723
2                      11.277419                 0.569477
0                      11.212632                 0.569600
1                      11.046908                 0.571938
6                      11.022772                 0.569723
12                     11.501163                 0.571077

   validation_test_improvement  validation_avg_train_test_improvement  \
16                    0.033768                               0.029418
9                     0.035346                               0.029362
19                    0.034527                               0.029184
20                    0.030549                               0.027501
10                    0.031209                               0.027566
2                     0.031026                               0.027382
0                     0.029869                               0.027217
1                     0.029682                               0.026764
6                     0.030861                               0.026201
12                    0.028686                               0.025919

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
16                             0.028775                             0.029094
9                              0.028142                             0.028746
19                             0.028206                             0.028691
20                             0.027163                             0.027332
10                             0.027085                             0.027324
2                              0.026897                             0.027138
0                              0.026958                             0.027087
1                              0.026446                             0.026604
6                              0.025373                             0.025784
12                             0.025624                             0.025771

[10 rows x 50 columns]
class_weights_enabled: 1, stratification_enabled: 1, lr_schedule_enabled: 2, lr_schedule_strategies: 20, dropout_enabled: 1, dropout_rates: 1, early_stopping_metrics: 1, outlier_dicts: 1, activation_layers_list: 1, epochs: 1, loss_functions: 1, optimizers: 1, batch_sizes: 1, learning_rates: 1, pcas: 1, pca_thresholds: 1
pca-True
  pca_thresholds_checked-0.99
  lr-0.001
        batch-128
           opt-(<class 'keras.src.optimizers.adam.Adam'>, {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': 1e-06, 'amsgrad': False, 'learning_rate': 0.001})
              loss-(<class 'keras.src.losses.Huber'>, {'reduction': 'auto'})
                        epoch-200
                              activation_layer -{'nodes': 128, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}
                                   outlier_dict -{'enabled': True, 'contamination': 0.05, 'remove_outliers': False}
                              class_weights_enabled -True
                              stratification_enabled -False
                              lr_schedule_enabled -True
                              lr_schedule_strategies -{'method': <function exponential_decay_95 at 0x000001F6CE23ED30>, 'description': 'Exponential Decay 5%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
1 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01740621932341146, Original: 9.762922791515482, New: 9.592987216168831
Test: Improvement: 0.0267784793580992, Original: 10.2199936987652, New: 9.946317808462911

-------------------------
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
0                    -0.189368                  16.689051

   validation_test_abserror_mean validation_test_abserror_median  \
0                        12.6201                        9.946318

   validation_test_abserror_std  validation_test_success  \
0                     10.922262                 0.569231

  validation_test_improvement  validation_avg_train_test_improvement  \
0                    0.026778                               0.022092

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
0                             0.021098                              0.02159

[1 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function exponential_decay_90 at 0x000001F6CE23EC10>, 'description': 'Exponential Decay 10%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
2 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022034424231730628, Original: 9.762922791515482, New: 9.547802408985598
Test: Improvement: 0.0314337213245136, Original: 10.2199936987652, New: 9.898741264899929

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.252894                  17.014997
0                    -0.189368                  16.689051

   validation_test_abserror_mean validation_test_abserror_median  \
1                       12.74229                        9.898741
0                       12.62010                        9.946318

   validation_test_abserror_std  validation_test_success  \
1                     11.300455                 0.571077
0                     10.922262                 0.569231

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.031434                               0.026734
0                    0.026778                               0.022092

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.025908                             0.026318
0                             0.021098                             0.021590

[2 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function exponential_decay_85 at 0x000001F6CE23EA60>, 'description': 'Exponential Decay 15%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
3 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.006285599601180584, Original: 9.762922791515482, New: 9.701556967910776
Test: Improvement: 0.011807059614703469, Original: 10.2199936987652, New: 10.099325623901985

-------------------------
   learning_rate  batch_size  \
1          0.001         128
0          0.001         128
2          0.001         128

                                           optimizer  \
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
1                     0.252894                  17.014997
0                    -0.189368                  16.689051
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
1                      12.742290                        9.898741
0                      12.620100                        9.946318
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
1                     11.300455                 0.571077
0                     10.922262                 0.569231
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
1                    0.031434                               0.026734
0                    0.026778                               0.022092
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
1                             0.025908                             0.026318
0                             0.021098                             0.021590
2                             0.008204                             0.008615

[3 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function exponential_decay_80 at 0x000001F6CE23E8B0>, 'description': 'Exponential Decay 20%'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
4 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.025526964566013326, Original: 9.762922791515482, New: 9.513705007355743
Test: Improvement: 0.033351416823120796, Original: 10.2199936987652, New: 9.879142428988013

-------------------------
   learning_rate  batch_size  \
3          0.001         128
1          0.001         128
0          0.001         128
2          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.238250                  16.937427
1                     0.252894                  17.014997
0                    -0.189368                  16.689051
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.700573                        9.879142
1                      12.742290                        9.898741
0                      12.620100                        9.946318
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
3                     11.227485                 0.572554
1                     11.300455                 0.571077
0                     10.922262                 0.569231
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.033351                               0.029439
1                    0.031434                               0.026734
0                    0.026778                               0.022092
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.028919                             0.029178
1                             0.025908                             0.026318
0                             0.021098                             0.021590
2                             0.008204                             0.008615

[4 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_50_10 at 0x000001F6CE23E160>, 'description': 'Step Decay 50% every 10 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
5 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022031299003216435, Original: 9.762922791515482, New: 9.547832920350288
Test: Improvement: 0.033754434740340594, Original: 10.2199936987652, New: 9.875023588413537

-------------------------
   learning_rate  batch_size  \
3          0.001         128
4          0.001         128
1          0.001         128
0          0.001         128
2          0.001         128

                                           optimizer  \
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
3                     0.238250                  16.937427
4                     0.257905                  16.855464
1                     0.252894                  17.014997
0                    -0.189368                  16.689051
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
3                      12.700573                        9.879142
4                      12.686564                        9.875024
1                      12.742290                        9.898741
0                      12.620100                        9.946318
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
3                     11.227485                 0.572554
4                     11.125038                 0.568738
1                     11.300455                 0.571077
0                     10.922262                 0.569231
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
3                    0.033351                               0.029439
4                    0.033754                               0.027893
1                    0.031434                               0.026734
0                    0.026778                               0.022092
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
3                             0.028919                             0.029178
4                             0.026661                             0.027270
1                             0.025908                             0.026318
0                             0.021098                             0.021590
2                             0.008204                             0.008615

[5 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_30_10 at 0x000001F6CE23E820>, 'description': 'Step Decay 30% every 10 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
6 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02400143817996485, Original: 9.762922791515482, New: 9.528598603679153
Test: Improvement: 0.03820210311095857, Original: 10.2199936987652, New: 9.829568445691624

-------------------------
   learning_rate  batch_size  \
5          0.001         128
3          0.001         128
4          0.001         128
1          0.001         128
0          0.001         128
2          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.305217                  16.921742
3                     0.238250                  16.937427
4                     0.257905                  16.855464
1                     0.252894                  17.014997
0                    -0.189368                  16.689051
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.703088                        9.829568
3                      12.700573                        9.879142
4                      12.686564                        9.875024
1                      12.742290                        9.898741
0                      12.620100                        9.946318
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
5                     11.204326                 0.572062
3                     11.227485                 0.572554
4                     11.125038                 0.568738
1                     11.300455                 0.571077
0                     10.922262                 0.569231
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.038202                               0.031102
3                    0.033351                               0.029439
4                    0.033754                               0.027893
1                    0.031434                               0.026734
0                    0.026778                               0.022092
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.029481                             0.030280
3                             0.028919                             0.029178
4                             0.026661                             0.027270
1                             0.025908                             0.026318
0                             0.021098                             0.021590
2                             0.008204                             0.008615

[6 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_50_5 at 0x000001F714CEA670>, 'description': 'Step Decay 50% every 5 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
7 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01095695203966602, Original: 9.762922791515482, New: 9.655950914721885
Test: Improvement: 0.021392980321239482, Original: 10.2199936987652, New: 10.001357574684324

-------------------------
   learning_rate  batch_size  \
5          0.001         128
3          0.001         128
4          0.001         128
1          0.001         128
0          0.001         128
6          0.001         128
2          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.305217                  16.921742
3                     0.238250                  16.937427
4                     0.257905                  16.855464
1                     0.252894                  17.014997
0                    -0.189368                  16.689051
6                    -0.304160                  16.717799
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.703088                        9.829568
3                      12.700573                        9.879142
4                      12.686564                        9.875024
1                      12.742290                        9.898741
0                      12.620100                        9.946318
6                      12.662856                       10.001358
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
5                     11.204326                 0.572062
3                     11.227485                 0.572554
4                     11.125038                 0.568738
1                     11.300455                 0.571077
0                     10.922262                 0.569231
6                     10.914808                 0.562462
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.038202                               0.031102
3                    0.033351                               0.029439
4                    0.033754                               0.027893
1                    0.031434                               0.026734
0                    0.026778                               0.022092
6                    0.021393                               0.016175
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.029481                             0.030280
3                             0.028919                             0.029178
4                             0.026661                             0.027270
1                             0.025908                             0.026318
0                             0.021098                             0.021590
6                             0.014492                             0.015310
2                             0.008204                             0.008615

[7 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function step_decay_70_10 at 0x000001F714CEA700>, 'description': 'Step Decay 70% every 10 epochs'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
8 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019095260655564217, Original: 9.762922791515482, New: 9.576497236051345
Test: Improvement: 0.026575287260058804, Original: 10.2199936987652, New: 9.948394430424523

-------------------------
   learning_rate  batch_size  \
5          0.001         128
3          0.001         128
4          0.001         128
1          0.001         128
7          0.001         128
0          0.001         128
6          0.001         128
2          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.305217                  16.921742
3                     0.238250                  16.937427
4                     0.257905                  16.855464
1                     0.252894                  17.014997
7                    -0.185784                  16.665313
0                    -0.189368                  16.689051
6                    -0.304160                  16.717799
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.703088                        9.829568
3                      12.700573                        9.879142
4                      12.686564                        9.875024
1                      12.742290                        9.898741
7                      12.622931                        9.948394
0                      12.620100                        9.946318
6                      12.662856                       10.001358
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
5                     11.204326                 0.572062
3                     11.227485                 0.572554
4                     11.125038                 0.568738
1                     11.300455                 0.571077
7                     10.881961                 0.570708
0                     10.922262                 0.569231
6                     10.914808                 0.562462
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.038202                               0.031102
3                    0.033351                               0.029439
4                    0.033754                               0.027893
1                    0.031434                               0.026734
7                    0.026575                               0.022835
0                    0.026778                               0.022092
6                    0.021393                               0.016175
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.029481                             0.030280
3                             0.028919                             0.029178
4                             0.026661                             0.027270
1                             0.025908                             0.026318
7                             0.022223                             0.022527
0                             0.021098                             0.021590
6                             0.014492                             0.015310
2                             0.008204                             0.008615

[8 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_1e4 at 0x000001F714CEA790>, 'description': 'Time-Based Decay 1e-4'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
9 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.008180015194454458, Original: 9.762922791515482, New: 9.6830619347386
Test: Improvement: 0.01416107710883004, Original: 10.2199936987652, New: 10.075267579945228

-------------------------
   learning_rate  batch_size  \
5          0.001         128
3          0.001         128
4          0.001         128
1          0.001         128
7          0.001         128
0          0.001         128
6          0.001         128
8          0.001         128
2          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.305217                  16.921742
3                     0.238250                  16.937427
4                     0.257905                  16.855464
1                     0.252894                  17.014997
7                    -0.185784                  16.665313
0                    -0.189368                  16.689051
6                    -0.304160                  16.717799
8                    -0.494683                  16.743799
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.703088                        9.829568
3                      12.700573                        9.879142
4                      12.686564                        9.875024
1                      12.742290                        9.898741
7                      12.622931                        9.948394
0                      12.620100                        9.946318
6                      12.662856                       10.001358
8                      12.718015                       10.075268
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
5                     11.204326                 0.572062
3                     11.227485                 0.572554
4                     11.125038                 0.568738
1                     11.300455                 0.571077
7                     10.881961                 0.570708
0                     10.922262                 0.569231
6                     10.914808                 0.562462
8                     10.890467                 0.559877
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.038202                               0.031102
3                    0.033351                               0.029439
4                    0.033754                               0.027893
1                    0.031434                               0.026734
7                    0.026575                               0.022835
0                    0.026778                               0.022092
6                    0.021393                               0.016175
8                    0.014161                               0.011171
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.029481                             0.030280
3                             0.028919                             0.029178
4                             0.026661                             0.027270
1                             0.025908                             0.026318
7                             0.022223                             0.022527
0                             0.021098                             0.021590
6                             0.014492                             0.015310
8                             0.010370                             0.010763
2                             0.008204                             0.008615

[9 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_1e5 at 0x000001F714CEA820>, 'description': 'Time-Based Decay 1e-5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
10 40
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022299515685281497, Original: 9.762922791515482, New: 9.54521434159189
Test: Improvement: 0.03371180720446194, Original: 10.2199936987652, New: 9.875459241561611

-------------------------
   learning_rate  batch_size  \
5          0.001         128
3          0.001         128
9          0.001         128
4          0.001         128
1          0.001         128
7          0.001         128
0          0.001         128
6          0.001         128
8          0.001         128
2          0.001         128

                                           optimizer  \
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>
9  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
0  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...
9  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
0  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_error_median  validation_test_error_std  \
5                     0.305217                  16.921742
3                     0.238250                  16.937427
9                     0.074420                  16.715465
4                     0.257905                  16.855464
1                     0.252894                  17.014997
7                    -0.185784                  16.665313
0                    -0.189368                  16.689051
6                    -0.304160                  16.717799
8                    -0.494683                  16.743799
2                    -0.758664                  16.743247

   validation_test_abserror_mean validation_test_abserror_median  \
5                      12.703088                        9.829568
3                      12.700573                        9.879142
9                      12.630286                        9.875459
4                      12.686564                        9.875024
1                      12.742290                        9.898741
7                      12.622931                        9.948394
0                      12.620100                        9.946318
6                      12.662856                       10.001358
8                      12.718015                       10.075268
2                      12.721343                       10.099326

   validation_test_abserror_std  validation_test_success  \
5                     11.204326                 0.572062
3                     11.227485                 0.572554
9                     10.962044                 0.572800
4                     11.125038                 0.568738
1                     11.300455                 0.571077
7                     10.881961                 0.570708
0                     10.922262                 0.569231
6                     10.914808                 0.562462
8                     10.890467                 0.559877
2                     10.893280                 0.555938

  validation_test_improvement  validation_avg_train_test_improvement  \
5                    0.038202                               0.031102
3                    0.033351                               0.029439
9                    0.033712                               0.028006
4                    0.033754                               0.027893
1                    0.031434                               0.026734
7                    0.026575                               0.022835
0                    0.026778                               0.022092
6                    0.021393                               0.016175
8                    0.014161                               0.011171
2                    0.011807                               0.009046

   validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                             0.029481                             0.030280
3                             0.028919                             0.029178
9                             0.026843                             0.027418
4                             0.026661                             0.027270
1                             0.025908                             0.026318
7                             0.022223                             0.022527
0                             0.021098                             0.021590
6                             0.014492                             0.015310
8                             0.010370                             0.010763
2                             0.008204                             0.008615

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_5e4 at 0x000001F714CEA8B0>, 'description': 'Time-Based Decay 5e-4'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
11 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.007066853101097888, Original: 9.762922791515482, New: 9.693929650310482
Test: Improvement: 0.011278680403252974, Original: 10.2199936987652, New: 10.104725656113567

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
9           0.001         128
4           0.001         128
1           0.001         128
7           0.001         128
0           0.001         128
6           0.001         128
8           0.001         128
10          0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
9                      0.074420                  16.715465
4                      0.257905                  16.855464
1                      0.252894                  17.014997
7                     -0.185784                  16.665313
0                     -0.189368                  16.689051
6                     -0.304160                  16.717799
8                     -0.494683                  16.743799
10                    -0.345598                  16.766123

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
9                       12.630286                        9.875459
4                       12.686564                        9.875024
1                       12.742290                        9.898741
7                       12.622931                        9.948394
0                       12.620100                        9.946318
6                       12.662856                       10.001358
8                       12.718015                       10.075268
10                      12.721937                       10.104726

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
9                      10.962044                 0.572800
4                      11.125038                 0.568738
1                      11.300455                 0.571077
7                      10.881961                 0.570708
0                      10.922262                 0.569231
6                      10.914808                 0.562462
8                      10.890467                 0.559877
10                     10.919515                 0.564800

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
9                     0.033712                               0.028006
4                     0.033754                               0.027893
1                     0.031434                               0.026734
7                     0.026575                               0.022835
0                     0.026778                               0.022092
6                     0.021393                               0.016175
8                     0.014161                               0.011171
10                    0.011279                               0.009173

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
9                              0.026843                             0.027418
4                              0.026661                             0.027270
1                              0.025908                             0.026318
7                              0.022223                             0.022527
0                              0.021098                             0.021590
6                              0.014492                             0.015310
8                              0.010370                             0.010763
10                             0.008689                             0.008928

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function time_based_decay_2e4 at 0x000001F714CEA940>, 'description': 'Time-Based Decay 2e-4'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
12 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022026368129127796, Original: 9.762922791515482, New: 9.54788106009331
Test: Improvement: 0.03254099628009179, Original: 10.2199936987652, New: 9.88742492183112

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
1           0.001         128
7           0.001         128
0           0.001         128
6           0.001         128
8           0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
1                      0.252894                  17.014997
7                     -0.185784                  16.665313
0                     -0.189368                  16.689051
6                     -0.304160                  16.717799
8                     -0.494683                  16.743799

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
1                       12.742290                        9.898741
7                       12.622931                        9.948394
0                       12.620100                        9.946318
6                       12.662856                       10.001358
8                       12.718015                       10.075268

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
1                      11.300455                 0.571077
7                      10.881961                 0.570708
0                      10.922262                 0.569231
6                      10.914808                 0.562462
8                      10.890467                 0.559877

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
1                     0.031434                               0.026734
7                     0.026575                               0.022835
0                     0.026778                               0.022092
6                     0.021393                               0.016175
8                     0.014161                               0.011171

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
1                              0.025908                             0.026318
7                              0.022223                             0.022527
0                              0.021098                             0.021590
6                              0.014492                             0.015310
8                              0.010370                             0.010763

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_30 at 0x000001F714CEA9D0>, 'description': 'Cosine Annealing with 30 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
13 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020004297101978298, Original: 9.762922791515482, New: 9.567622383410331
Test: Improvement: 0.026342439247451593, Original: 10.2199936987652, New: 9.950774135646139

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
1           0.001         128
12          0.001         128
7           0.001         128
0           0.001         128
6           0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
1                      0.252894                  17.014997
12                     0.382294                  17.899587
7                     -0.185784                  16.665313
0                     -0.189368                  16.689051
6                     -0.304160                  16.717799

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
1                       12.742290                        9.898741
12                      13.031793                        9.950774
7                       12.622931                        9.948394
0                       12.620100                        9.946318
6                       12.662856                       10.001358

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
1                      11.300455                 0.571077
12                     12.302939                 0.573169
7                      10.881961                 0.570708
0                      10.922262                 0.569231
6                      10.914808                 0.562462

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
1                     0.031434                               0.026734
12                    0.026342                               0.023173
7                     0.026575                               0.022835
0                     0.026778                               0.022092
6                     0.021393                               0.016175

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
1                              0.025908                             0.026318
12                             0.022740                             0.022956
7                              0.022223                             0.022527
0                              0.021098                             0.021590
6                              0.014492                             0.015310

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_50 at 0x000001F714CEAA60>, 'description': 'Cosine Annealing with 50 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
14 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022219073935052482, Original: 9.762922791515482, New: 9.54599968818859
Test: Improvement: 0.030940060525917093, Original: 10.2199936987652, New: 9.903786475150913

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
1           0.001         128
13          0.001         128
12          0.001         128
7           0.001         128
0           0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
1                      0.252894                  17.014997
13                     0.223045                  17.410534
12                     0.382294                  17.899587
7                     -0.185784                  16.665313
0                     -0.189368                  16.689051

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
1                       12.742290                        9.898741
13                      12.848699                        9.903786
12                      13.031793                        9.950774
7                       12.622931                        9.948394
0                       12.620100                        9.946318

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
1                      11.300455                 0.571077
13                     11.769426                 0.573292
12                     12.302939                 0.573169
7                      10.881961                 0.570708
0                      10.922262                 0.569231

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
1                     0.031434                               0.026734
13                    0.030940                               0.026580
12                    0.026342                               0.023173
7                     0.026575                               0.022835
0                     0.026778                               0.022092

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
1                              0.025908                             0.026318
13                             0.025864                             0.026219
12                             0.022740                             0.022956
7                              0.022223                             0.022527
0                              0.021098                             0.021590

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_10 at 0x000001F714CEAAF0>, 'description': 'Cosine Annealing with 10 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
15 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024109377201063854, Original: 9.762922791515482, New: 9.527544803349972
Test: Improvement: 0.02966970173618048, Original: 10.2199936987652, New: 9.916769533977192

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
14          0.001         128
1           0.001         128
13          0.001         128
12          0.001         128
7           0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
14                     0.409060                  17.183777
1                      0.252894                  17.014997
13                     0.223045                  17.410534
12                     0.382294                  17.899587
7                     -0.185784                  16.665313

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
14                      12.783198                        9.916770
1                       12.742290                        9.898741
13                      12.848699                        9.903786
12                      13.031793                        9.950774
7                       12.622931                        9.948394

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
14                     11.521642                 0.571323
1                      11.300455                 0.571077
13                     11.769426                 0.573292
12                     12.302939                 0.573169
7                      10.881961                 0.570708

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
14                    0.029670                               0.026890
1                     0.031434                               0.026734
13                    0.030940                               0.026580
12                    0.026342                               0.023173
7                     0.026575                               0.022835

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
14                             0.026602                             0.026745
1                              0.025908                             0.026318
13                             0.025864                             0.026219
12                             0.022740                             0.022956
7                              0.022223                             0.022527

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <function cosine_annealing_20 at 0x000001F717BD9DC0>, 'description': 'Cosine Annealing with 20 epochs cycle'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
16 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.007868965330367577, Original: 9.762922791515482, New: 9.686098690545991
Test: Improvement: 0.011949326243055291, Original: 10.2199936987652, New: 10.097871659856684

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
14          0.001         128
1           0.001         128
13          0.001         128
12          0.001         128
7           0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
14                     0.409060                  17.183777
1                      0.252894                  17.014997
13                     0.223045                  17.410534
12                     0.382294                  17.899587
7                     -0.185784                  16.665313

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
14                      12.783198                        9.916770
1                       12.742290                        9.898741
13                      12.848699                        9.903786
12                      13.031793                        9.950774
7                       12.622931                        9.948394

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
14                     11.521642                 0.571323
1                      11.300455                 0.571077
13                     11.769426                 0.573292
12                     12.302939                 0.573169
7                      10.881961                 0.570708

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
14                    0.029670                               0.026890
1                     0.031434                               0.026734
13                    0.030940                               0.026580
12                    0.026342                               0.023173
7                     0.026575                               0.022835

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
14                             0.026602                             0.026745
1                              0.025908                             0.026318
13                             0.025864                             0.026219
12                             0.022740                             0.022956
7                              0.022223                             0.022527

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D197C0>, 'description': 'Reduce on Plateau 50%, patience 5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
17 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023629294403433528, Original: 9.762922791515482, New: 9.532231814636772
Test: Improvement: 0.03333239200295069, Original: 10.2199936987652, New: 9.879336862530272

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
16          0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
14          0.001         128
1           0.001         128
13          0.001         128
12          0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
16                     0.346731                  17.105230
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
14                     0.409060                  17.183777
1                      0.252894                  17.014997
13                     0.223045                  17.410534
12                     0.382294                  17.899587

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
16                      12.773749                        9.879337
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
14                      12.783198                        9.916770
1                       12.742290                        9.898741
13                      12.848699                        9.903786
12                      13.031793                        9.950774

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
16                     11.405001                 0.571446
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
14                     11.521642                 0.571323
1                      11.300455                 0.571077
13                     11.769426                 0.573292
12                     12.302939                 0.573169

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
16                    0.033332                               0.028481
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
14                    0.029670                               0.026890
1                     0.031434                               0.026734
13                    0.030940                               0.026580
12                    0.026342                               0.023173

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
16                             0.027654                             0.028065
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
14                             0.026602                             0.026745
1                              0.025908                             0.026318
13                             0.025864                             0.026219
12                             0.022740                             0.022956

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D3BDC0>, 'description': 'Reduce on Plateau 30%, patience 5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
18 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020256434547966957, Original: 9.762922791515482, New: 9.565160784992294
Test: Improvement: 0.030245228214243042, Original: 10.2199936987652, New: 9.91088765699792

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
16          0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
14          0.001         128
1           0.001         128
13          0.001         128
17          0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
16                     0.346731                  17.105230
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
14                     0.409060                  17.183777
1                      0.252894                  17.014997
13                     0.223045                  17.410534
17                     0.168378                  16.729707

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
16                      12.773749                        9.879337
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
14                      12.783198                        9.916770
1                       12.742290                        9.898741
13                      12.848699                        9.903786
17                      12.639573                        9.910888

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
16                     11.405001                 0.571446
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
14                     11.521642                 0.571323
1                      11.300455                 0.571077
13                     11.769426                 0.573292
17                     10.974999                 0.570585

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
16                    0.033332                               0.028481
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
14                    0.029670                               0.026890
1                     0.031434                               0.026734
13                    0.030940                               0.026580
17                    0.030245                               0.025251

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
16                             0.027654                             0.028065
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
14                             0.026602                             0.026745
1                              0.025908                             0.026318
13                             0.025864                             0.026219
17                             0.024263                             0.024752

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D197F0>, 'description': 'Reduce on Plateau 50%, patience 10'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
19 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01874899485204824, Original: 9.762922791515482, New: 9.579877802356414
Test: Improvement: 0.023876934701557884, Original: 10.2199936987652, New: 9.97597157656945

-------------------------
    learning_rate  batch_size  \
5           0.001         128
3           0.001         128
16          0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
14          0.001         128
1           0.001         128
13          0.001         128
17          0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
3                      0.238250                  16.937427
16                     0.346731                  17.105230
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
14                     0.409060                  17.183777
1                      0.252894                  17.014997
13                     0.223045                  17.410534
17                     0.168378                  16.729707

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
3                       12.700573                        9.879142
16                      12.773749                        9.879337
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
14                      12.783198                        9.916770
1                       12.742290                        9.898741
13                      12.848699                        9.903786
17                      12.639573                        9.910888

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
3                      11.227485                 0.572554
16                     11.405001                 0.571446
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
14                     11.521642                 0.571323
1                      11.300455                 0.571077
13                     11.769426                 0.573292
17                     10.974999                 0.570585

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
3                     0.033351                               0.029439
16                    0.033332                               0.028481
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
14                    0.029670                               0.026890
1                     0.031434                               0.026734
13                    0.030940                               0.026580
17                    0.030245                               0.025251

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
3                              0.028919                             0.029178
16                             0.027654                             0.028065
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
14                             0.026602                             0.026745
1                              0.025908                             0.026318
13                             0.025864                             0.026219
17                             0.024263                             0.024752

[10 rows x 50 columns]
                              lr_schedule_strategies -{'method': <keras.src.callbacks.ReduceLROnPlateau object at 0x000001F717D19220>, 'description': 'Reduce on Plateau 70%, patience 5'}
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
20 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.025384774521448276, Original: 9.762922791515482, New: 9.515093197782553
Test: Improvement: 0.03423982902737023, Original: 10.2199936987652, New: 9.870062861858678

-------------------------
    learning_rate  batch_size  \
5           0.001         128
19          0.001         128
3           0.001         128
16          0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
14          0.001         128
1           0.001         128
13          0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
19                     0.337576                  17.357039
3                      0.238250                  16.937427
16                     0.346731                  17.105230
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
14                     0.409060                  17.183777
1                      0.252894                  17.014997
13                     0.223045                  17.410534

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
19                      12.836121                        9.870063
3                       12.700573                        9.879142
16                      12.773749                        9.879337
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
14                      12.783198                        9.916770
1                       12.742290                        9.898741
13                      12.848699                        9.903786

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
19                     11.715715                 0.573292
3                      11.227485                 0.572554
16                     11.405001                 0.571446
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
14                     11.521642                 0.571323
1                      11.300455                 0.571077
13                     11.769426                 0.573292

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
19                    0.034240                               0.029812
3                     0.033351                               0.029439
16                    0.033332                               0.028481
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
14                    0.029670                               0.026890
1                     0.031434                               0.026734
13                    0.030940                               0.026580

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
19                             0.029155                             0.029482
3                              0.028919                             0.029178
16                             0.027654                             0.028065
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
14                             0.026602                             0.026745
1                              0.025908                             0.026318
13                             0.025864                             0.026219

[10 rows x 50 columns]
                              lr_schedule_enabled -False
                              lr_schedule_strategies -None
                              dropout_enabled -True
                              dropout_rates -0.9
                              early_stopping_metric -val_root_mean_squared_error
21 40

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02436199060887827, Original: 9.762922791515482, New: 9.525078558153378
Test: Improvement: 0.036089069461260295, Original: 10.2199936987652, New: 9.85116363627682

-------------------------
    learning_rate  batch_size  \
5           0.001         128
20          0.001         128
19          0.001         128
3           0.001         128
16          0.001         128
9           0.001         128
4           0.001         128
11          0.001         128
14          0.001         128
1           0.001         128

                                            optimizer  \
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
5   <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
5   (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_error_median  validation_test_error_std  \
5                      0.305217                  16.921742
20                     0.241735                  17.093194
19                     0.337576                  17.357039
3                      0.238250                  16.937427
16                     0.346731                  17.105230
9                      0.074420                  16.715465
4                      0.257905                  16.855464
11                    -0.030086                  16.722084
14                     0.409060                  17.183777
1                      0.252894                  17.014997

    validation_test_abserror_mean validation_test_abserror_median  \
5                       12.703088                        9.829568
20                      12.752773                        9.851164
19                      12.836121                        9.870063
3                       12.700573                        9.879142
16                      12.773749                        9.879337
9                       12.630286                        9.875459
4                       12.686564                        9.875024
11                      12.629068                        9.887425
14                      12.783198                        9.916770
1                       12.742290                        9.898741

    validation_test_abserror_std  validation_test_success  \
5                      11.204326                 0.572062
20                     11.404835                 0.570215
19                     11.715715                 0.573292
3                      11.227485                 0.572554
16                     11.405001                 0.571446
9                      10.962044                 0.572800
4                      11.125038                 0.568738
11                     10.966357                 0.570338
14                     11.521642                 0.571323
1                      11.300455                 0.571077

   validation_test_improvement  validation_avg_train_test_improvement  \
5                     0.038202                               0.031102
20                    0.036089                               0.030226
19                    0.034240                               0.029812
3                     0.033351                               0.029439
16                    0.033332                               0.028481
9                     0.033712                               0.028006
4                     0.033754                               0.027893
11                    0.032541                               0.027284
14                    0.029670                               0.026890
1                     0.031434                               0.026734

    validation_train_test_harmonic_mean validation_train_test_geometric_mean
5                              0.029481                             0.030280
20                             0.029088                             0.029651
19                             0.029155                             0.029482
3                              0.028919                             0.029178
16                             0.027654                             0.028065
9                              0.026843                             0.027418
4                              0.026661                             0.027270
11                             0.026271                             0.026772
14                             0.026602                             0.026745
1                              0.025908                             0.026318

[10 rows x 50 columns]
lr_schedule_enabled Selected -  [True]
lr_schedule_strategies Selected -  [{'method': <function step_decay_30_10 at 0x000001F6CE23E820>, 'description': 'Step Decay 30% every 10 epochs'}]

Adding model layer - 1
1 1 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.1, 'l1_reg': 0.1}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023513201547964463, Original: 9.762922791515482, New: 9.533365220221363
Test: Improvement: 0.030429955967167775, Original: 10.2199936987652, New: 9.908999740527042
   learning_rate  batch_size  \
0          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                      12.82853                            9.909

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354

   validation_test_improvement  validation_avg_train_test_improvement  \
0                      0.03043                               0.026972

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749

   num_layers iteration_number
0           1                1

[1 rows x 52 columns]
1 2 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.1, 'l1_reg': 0.01}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02252708107432697, Original: 9.762922791515482, New: 9.542992638268618
Test: Improvement: 0.025728909742613652, Original: 10.2199936987652, New: 9.957044403319589
   learning_rate  batch_size  \
0          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
1                     12.643244                         9.957044

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
1                     11.035188                0.568000

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
1                     0.025729                               0.024128

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
1                            0.024022                              0.024075

   num_layers iteration_number
0           1                1
1           1                2

[2 rows x 52 columns]
1 3 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.1, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022106542785536757, Original: 9.762922791515482, New: 9.547098321112953
Test: Improvement: 0.029623103416766747, Original: 10.2199936987652, New: 9.917245768507973
   learning_rate  batch_size  \
0          0.001         128
2          0.001         128
1          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
2                     12.741454                         9.917246
1                     12.643244                         9.957044

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
2                     11.317726                0.569969
1                     11.035188                0.568000

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
2                     0.029623                               0.025865
1                     0.025729                               0.024128

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
2                            0.025319                              0.025590
1                            0.024022                              0.024075

   num_layers iteration_number
0           1                1
2           1                3
1           1                2

[3 rows x 52 columns]
1 4 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.1, 'l1_reg': 0.0001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: -0.0014934266335658705, Original: 9.762922791515482, New: 9.777503000433779
Test: Improvement: 0.007583681517982177, Original: 10.2199936987652, New: 10.14248852143798
   learning_rate  batch_size  \
0          0.001         128
2          0.001         128
1          0.001         128
3          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
2                     12.741454                         9.917246
1                     12.643244                         9.957044
3                     12.809443                        10.142489

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
2                     11.317726                0.569969
1                     11.035188                0.568000
3                     10.942125                0.528246

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
2                     0.029623                               0.025865
1                     0.025729                               0.024128
3                     0.007584                               0.003045

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
2                            0.025319                              0.025590
1                            0.024022                              0.024075
3                           -0.003719                                   NaN

   num_layers iteration_number
0           1                1
2           1                3
1           1                2
3           1                4

[4 rows x 52 columns]
1 5 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.01, 'l1_reg': 0.1}]

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020887789295043067, Original: 9.762922791515482, New: 9.558996917342533
Test: Improvement: 0.029206559641328234, Original: 10.2199936987652, New: 9.921502843268215
   learning_rate  batch_size  \
0          0.001         128
2          0.001         128
4          0.001         128
1          0.001         128
3          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
2                     12.741454                         9.917246
4                     12.676083                         9.921503
1                     12.643244                         9.957044
3                     12.809443                        10.142489

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
2                     11.317726                0.569969
4                     11.038366                0.567877
1                     11.035188                0.568000
3                     10.942125                0.528246

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
2                     0.029623                               0.025865
4                     0.029207                               0.025047
1                     0.025729                               0.024128
3                     0.007584                               0.003045

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
2                            0.025319                              0.025590
4                            0.024356                              0.024699
1                            0.024022                              0.024075
3                           -0.003719                                   NaN

   num_layers iteration_number
0           1                1
2           1                3
4           1                5
1           1                2
3           1                4

[5 rows x 52 columns]
1 6 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.01, 'l1_reg': 0.01}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020966729764285624, Original: 9.762922791515482, New: 9.558226227636192
Test: Improvement: 0.02483289661864739, Original: 10.2199936987652, New: 9.966201651800535
   learning_rate  batch_size  \
0          0.001         128
2          0.001         128
4          0.001         128
1          0.001         128
5          0.001         128
3          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
2                     12.741454                         9.917246
4                     12.676083                         9.921503
1                     12.643244                         9.957044
5                     12.875042                         9.966202
3                     12.809443                        10.142489

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
2                     11.317726                0.569969
4                     11.038366                0.567877
1                     11.035188                0.568000
5                     11.633251                0.567877
3                     10.942125                0.528246

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
2                     0.029623                               0.025865
4                     0.029207                               0.025047
1                     0.025729                               0.024128
5                     0.024833                               0.022900
3                     0.007584                               0.003045

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
2                            0.025319                              0.025590
4                            0.024356                              0.024699
1                            0.024022                              0.024075
5                            0.022737                              0.022818
3                           -0.003719                                   NaN

   num_layers iteration_number
0           1                1
2           1                3
4           1                5
1           1                2
5           1                6
3           1                4

[6 rows x 52 columns]
1 7 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.01, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022249818823967787, Original: 9.762922791515482, New: 9.545699528211877
Test: Improvement: 0.026293184161664745, Original: 10.2199936987652, New: 9.951277522312513
   learning_rate  batch_size  \
0          0.001         128
2          0.001         128
4          0.001         128
6          0.001         128
1          0.001         128
5          0.001         128
3          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
2                     12.741454                         9.917246
4                     12.676083                         9.921503
6                     12.660680                         9.951278
1                     12.643244                         9.957044
5                     12.875042                         9.966202
3                     12.809443                        10.142489

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
2                     11.317726                0.569969
4                     11.038366                0.567877
6                     11.008345                0.568862
1                     11.035188                0.568000
5                     11.633251                0.567877
3                     10.942125                0.528246

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
2                     0.029623                               0.025865
4                     0.029207                               0.025047
6                     0.026293                               0.024272
1                     0.025729                               0.024128
5                     0.024833                               0.022900
3                     0.007584                               0.003045

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
2                            0.025319                              0.025590
4                            0.024356                              0.024699
6                            0.024103                              0.024187
1                            0.024022                              0.024075
5                            0.022737                              0.022818
3                           -0.003719                                   NaN

   num_layers iteration_number
0           1                1
2           1                3
4           1                5
6           1                7
1           1                2
5           1                6
3           1                4

[7 rows x 52 columns]
1 8 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.01, 'l1_reg': 0.0001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020862647712052936, Original: 9.762922791515482, New: 9.559242372676122
Test: Improvement: 0.029549557902435755, Original: 10.2199936987652, New: 9.917997403201008
   learning_rate  batch_size  \
0          0.001         128
2          0.001         128
7          0.001         128
4          0.001         128
6          0.001         128
1          0.001         128
5          0.001         128
3          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
2                     12.741454                         9.917246
7                     12.808694                         9.917997
4                     12.676083                         9.921503
6                     12.660680                         9.951278
1                     12.643244                         9.957044
5                     12.875042                         9.966202
3                     12.809443                        10.142489

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
2                     11.317726                0.569969
7                     11.470663                0.564062
4                     11.038366                0.567877
6                     11.008345                0.568862
1                     11.035188                0.568000
5                     11.633251                0.567877
3                     10.942125                0.528246

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
2                     0.029623                               0.025865
7                     0.029550                               0.025206
4                     0.029207                               0.025047
6                     0.026293                               0.024272
1                     0.025729                               0.024128
5                     0.024833                               0.022900
3                     0.007584                               0.003045

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
2                            0.025319                              0.025590
7                            0.024458                              0.024829
4                            0.024356                              0.024699
6                            0.024103                              0.024187
1                            0.024022                              0.024075
5                            0.022737                              0.022818
3                           -0.003719                                   NaN

   num_layers iteration_number
0           1                1
2           1                3
7           1                8
4           1                5
6           1                7
1           1                2
5           1                6
3           1                4

[8 rows x 52 columns]
1 9 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.1}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022763061423883225, Original: 9.762922791515482, New: 9.540688780335586
Test: Improvement: 0.03129807166277099, Original: 10.2199936987652, New: 9.900127603588178
   learning_rate  batch_size  \
0          0.001         128
8          0.001         128
2          0.001         128
7          0.001         128
4          0.001         128
6          0.001         128
1          0.001         128
5          0.001         128
3          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
8                     12.657468                         9.900128
2                     12.741454                         9.917246
7                     12.808694                         9.917997
4                     12.676083                         9.921503
6                     12.660680                         9.951278
1                     12.643244                         9.957044
5                     12.875042                         9.966202
3                     12.809443                        10.142489

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
8                     11.047042                0.567015
2                     11.317726                0.569969
7                     11.470663                0.564062
4                     11.038366                0.567877
6                     11.008345                0.568862
1                     11.035188                0.568000
5                     11.633251                0.567877
3                     10.942125                0.528246

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
8                     0.031298                               0.027031
2                     0.029623                               0.025865
7                     0.029550                               0.025206
4                     0.029207                               0.025047
6                     0.026293                               0.024272
1                     0.025729                               0.024128
5                     0.024833                               0.022900
3                     0.007584                               0.003045

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
8                            0.026357                              0.026692
2                            0.025319                              0.025590
7                            0.024458                              0.024829
4                            0.024356                              0.024699
6                            0.024103                              0.024187
1                            0.024022                              0.024075
5                            0.022737                              0.022818
3                           -0.003719                                   NaN

   num_layers iteration_number
0           1                1
8           1                9
2           1                3
7           1                8
4           1                5
6           1                7
1           1                2
5           1                6
3           1                4

[9 rows x 52 columns]
1 10 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.01}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02319156612430945, Original: 9.762922791515482, New: 9.536505322029523
Test: Improvement: 0.030490029286283096, Original: 10.2199936987652, New: 9.90838579158422
   learning_rate  batch_size  \
0          0.001         128
8          0.001         128
9          0.001         128
2          0.001         128
7          0.001         128
4          0.001         128
6          0.001         128
1          0.001         128
5          0.001         128
3          0.001         128

                                           optimizer  \
0  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                             optimizer_name  \
0  <class 'keras.src.optimizers.adam.Adam'>
8  <class 'keras.src.optimizers.adam.Adam'>
9  <class 'keras.src.optimizers.adam.Adam'>
2  <class 'keras.src.optimizers.adam.Adam'>
7  <class 'keras.src.optimizers.adam.Adam'>
4  <class 'keras.src.optimizers.adam.Adam'>
6  <class 'keras.src.optimizers.adam.Adam'>
1  <class 'keras.src.optimizers.adam.Adam'>
5  <class 'keras.src.optimizers.adam.Adam'>
3  <class 'keras.src.optimizers.adam.Adam'>

                                    optimizer_params  \
0  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                       loss_function  \
0  (<class 'keras.src.losses.Huber'>, {'reduction...
8  (<class 'keras.src.losses.Huber'>, {'reduction...
9  (<class 'keras.src.losses.Huber'>, {'reduction...
2  (<class 'keras.src.losses.Huber'>, {'reduction...
7  (<class 'keras.src.losses.Huber'>, {'reduction...
4  (<class 'keras.src.losses.Huber'>, {'reduction...
6  (<class 'keras.src.losses.Huber'>, {'reduction...
1  (<class 'keras.src.losses.Huber'>, {'reduction...
5  (<class 'keras.src.losses.Huber'>, {'reduction...
3  (<class 'keras.src.losses.Huber'>, {'reduction...

                loss_function_class   loss_function_params  \
0  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                             metrics  epochs  ...  \
0  [(<class 'keras.src.metrics.regression_metrics...     200  ...
8  [(<class 'keras.src.metrics.regression_metrics...     200  ...
9  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2  [(<class 'keras.src.metrics.regression_metrics...     200  ...
7  [(<class 'keras.src.metrics.regression_metrics...     200  ...
4  [(<class 'keras.src.metrics.regression_metrics...     200  ...
6  [(<class 'keras.src.metrics.regression_metrics...     200  ...
1  [(<class 'keras.src.metrics.regression_metrics...     200  ...
5  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3  [(<class 'keras.src.metrics.regression_metrics...     200  ...

  validation_test_abserror_mean  validation_test_abserror_median  \
0                     12.828530                         9.909000
8                     12.657468                         9.900128
9                     12.770602                         9.908386
2                     12.741454                         9.917246
7                     12.808694                         9.917997
4                     12.676083                         9.921503
6                     12.660680                         9.951278
1                     12.643244                         9.957044
5                     12.875042                         9.966202
3                     12.809443                        10.142489

   validation_test_abserror_std validation_test_success  \
0                     11.799702                0.569354
8                     11.047042                0.567015
9                     11.300852                0.568246
2                     11.317726                0.569969
7                     11.470663                0.564062
4                     11.038366                0.567877
6                     11.008345                0.568862
1                     11.035188                0.568000
5                     11.633251                0.567877
3                     10.942125                0.528246

   validation_test_improvement  validation_avg_train_test_improvement  \
0                     0.030430                               0.026972
8                     0.031298                               0.027031
9                     0.030490                               0.026841
2                     0.029623                               0.025865
7                     0.029550                               0.025206
4                     0.029207                               0.025047
6                     0.026293                               0.024272
1                     0.025729                               0.024128
5                     0.024833                               0.022900
3                     0.007584                               0.003045

  validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
0                            0.026528                              0.026749
8                            0.026357                              0.026692
9                            0.026345                              0.026592
2                            0.025319                              0.025590
7                            0.024458                              0.024829
4                            0.024356                              0.024699
6                            0.024103                              0.024187
1                            0.024022                              0.024075
5                            0.022737                              0.022818
3                           -0.003719                                   NaN

   num_layers iteration_number
0           1                1
8           1                9
9           1               10
2           1                3
7           1                8
4           1                5
6           1                7
1           1                2
5           1                6
3           1                4

[10 rows x 52 columns]
1 11 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021751216590788783, Original: 9.762922791515482, New: 9.55056734331808
Test: Improvement: 0.033516726803072466, Original: 10.2199936987652, New: 9.877452962034564
    learning_rate  batch_size  \
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
3           0.001         128

                                            optimizer  \
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
3                      12.809443                        10.142489

    validation_test_abserror_std validation_test_success  \
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
3                      10.942125                0.528246

    validation_test_improvement  validation_avg_train_test_improvement  \
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
3                      0.007584                               0.003045

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
3                            -0.003719                                   NaN

    num_layers iteration_number
10           1               11
0            1                1
8            1                9
9            1               10
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
3            1                4

[11 rows x 52 columns]
1 12 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021495627069665426, Original: 9.762922791515482, New: 9.553062644079128
Test: Improvement: 0.022899619818496614, Original: 10.2199936987652, New: 9.985959728516045
    learning_rate  batch_size  \
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128

                                            optimizer  \
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489

    validation_test_abserror_std validation_test_success  \
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246

    validation_test_improvement  validation_avg_train_test_improvement  \
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN

    num_layers iteration_number
10           1               11
0            1                1
8            1                9
9            1               10
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4

[12 rows x 52 columns]
1 13 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.0001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024802015698702877, Original: 9.762922791515482, New: 9.520782627175091
Test: Improvement: 0.03154353593233552, Original: 10.2199936987652, New: 9.897618960299956
    learning_rate  batch_size  \
12          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128

                                            optimizer  \
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
12  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
12  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
12                     12.727644                         9.897619
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489

    validation_test_abserror_std validation_test_success  \
12                     11.311885                0.561846
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246

    validation_test_improvement  validation_avg_train_test_improvement  \
12                     0.031544                               0.028173
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
12                            0.027769                              0.027970
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN

    num_layers iteration_number
12           1               13
10           1               11
0            1                1
8            1                9
9            1               10
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4

[13 rows x 52 columns]
1 14 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.0001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0003649763704198941, Original: 9.762922791515482, New: 9.76648602764062
Test: Improvement: 0.005030577290268709, Original: 10.2199936987652, New: 10.168581230557502
    learning_rate  batch_size  \
12          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128
13          0.001         128

                                            optimizer  \
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
12  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
12  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
12                     12.727644                         9.897619
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489
13                     12.845186                        10.168581

    validation_test_abserror_std validation_test_success  \
12                     11.311885                0.561846
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246
13                     11.034602                0.509169

    validation_test_improvement  validation_avg_train_test_improvement  \
12                     0.031544                               0.028173
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045
13                     0.005031                               0.002333

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
12                            0.027769                              0.027970
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN

    num_layers iteration_number
12           1               13
10           1               11
0            1                1
8            1                9
9            1               10
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4
13           1               14

[14 rows x 52 columns]
1 15 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.0001, 'l1_reg': 0.001}]

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.006016096205771139, Original: 9.762922791515482, New: 9.821657474278755
Test: Improvement: 0.005862289601929067, Original: 10.2199936987652, New: 10.160081135973147
    learning_rate  batch_size  \
12          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128
13          0.001         128
14          0.001         128

                                            optimizer  \
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
12  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
12  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
12                     12.727644                         9.897619
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489
13                     12.845186                        10.168581
14                     12.824016                        10.160081

    validation_test_abserror_std validation_test_success  \
12                     11.311885                0.561846
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246
13                     11.034602                0.509169
14                     10.930723                0.515446

    validation_test_improvement  validation_avg_train_test_improvement  \
12                     0.031544                               0.028173
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045
13                     0.005031                               0.002333
14                     0.005862                              -0.000077

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
12                            0.027769                              0.027970
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN
14                            0.458603                                   NaN

    num_layers iteration_number
12           1               13
10           1               11
0            1                1
8            1                9
9            1               10
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4
13           1               14
14           1               15

[15 rows x 52 columns]
1 16 640
[{'nodes': 256, 'activation': 'relu', 'l2_reg': 0.0001, 'l1_reg': 0.0001}]

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024060587922833162, Original: 9.762922791515482, New: 9.528021129306392
Test: Improvement: 0.028165502532966187, Original: 10.2199936987652, New: 9.93214244035573
    learning_rate  batch_size  \
12          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128
13          0.001         128
14          0.001         128

                                            optimizer  \
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
12  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
12  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
12                     12.727644                         9.897619
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489
13                     12.845186                        10.168581
14                     12.824016                        10.160081

    validation_test_abserror_std validation_test_success  \
12                     11.311885                0.561846
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246
13                     11.034602                0.509169
14                     10.930723                0.515446

    validation_test_improvement  validation_avg_train_test_improvement  \
12                     0.031544                               0.028173
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045
13                     0.005031                               0.002333
14                     0.005862                              -0.000077

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
12                            0.027769                              0.027970
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN
14                            0.458603                                   NaN

    num_layers iteration_number
12           1               13
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4
13           1               14
14           1               15

[16 rows x 52 columns]
1 17 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.1, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02998910522230277, Original: 9.762922791515482, New: 9.470141472643506
Test: Improvement: 0.034075593238178895, Original: 10.2199936987652, New: 9.871741350589325
    learning_rate  batch_size  \
16          0.001         128
12          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128
13          0.001         128
14          0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
16                     12.655114                         9.871741
12                     12.727644                         9.897619
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489
13                     12.845186                        10.168581
14                     12.824016                        10.160081

    validation_test_abserror_std validation_test_success  \
16                     11.069855                0.566646
12                     11.311885                0.561846
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246
13                     11.034602                0.509169
14                     10.930723                0.515446

    validation_test_improvement  validation_avg_train_test_improvement  \
16                     0.034076                               0.032032
12                     0.031544                               0.028173
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045
13                     0.005031                               0.002333
14                     0.005862                              -0.000077

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
16                            0.031902                              0.031967
12                            0.027769                              0.027970
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN
14                            0.458603                                   NaN

    num_layers iteration_number
16           1               17
12           1               13
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4
13           1               14
14           1               15

[17 rows x 52 columns]
1 18 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.1, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.025613639710029487, Original: 9.762922791515482, New: 9.51285880461677
Test: Improvement: 0.02944967391265039, Original: 10.2199936987652, New: 9.919018216947222
    learning_rate  batch_size  \
16          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128
13          0.001         128
14          0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
16                     12.655114                         9.871741
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489
13                     12.845186                        10.168581
14                     12.824016                        10.160081

    validation_test_abserror_std validation_test_success  \
16                     11.069855                0.566646
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246
13                     11.034602                0.509169
14                     10.930723                0.515446

    validation_test_improvement  validation_avg_train_test_improvement  \
16                     0.034076                               0.032032
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045
13                     0.005031                               0.002333
14                     0.005862                              -0.000077

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
16                            0.031902                              0.031967
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN
14                            0.458603                                   NaN

    num_layers iteration_number
16           1               17
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4
13           1               14
14           1               15

[18 rows x 52 columns]
1 19 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.1, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.029877885932362926, Original: 9.762922791515482, New: 9.471227297984116
Test: Improvement: 0.030084243668389073, Original: 10.2199936987652, New: 9.912532918042146
    learning_rate  batch_size  \
16          0.001         128
18          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
3           0.001         128
13          0.001         128
14          0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
16                     12.655114                         9.871741
18                     12.627546                         9.912533
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
3                      12.809443                        10.142489
13                     12.845186                        10.168581
14                     12.824016                        10.160081

    validation_test_abserror_std validation_test_success  \
16                     11.069855                0.566646
18                     11.057780                0.573169
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
3                      10.942125                0.528246
13                     11.034602                0.509169
14                     10.930723                0.515446

    validation_test_improvement  validation_avg_train_test_improvement  \
16                     0.034076                               0.032032
18                     0.030084                               0.029981
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
3                      0.007584                               0.003045
13                     0.005031                               0.002333
14                     0.005862                              -0.000077

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
16                            0.031902                              0.031967
18                            0.029981                              0.029981
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN
14                            0.458603                                   NaN

    num_layers iteration_number
16           1               17
18           1               19
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
3            1                4
13           1               14
14           1               15

[19 rows x 52 columns]
1 20 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.1, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.014808967326729313, Original: 9.762922791515482, New: 9.618343986882548
Test: Improvement: 0.0237143370078752, Original: 10.2199936987652, New: 9.97763332397432
    learning_rate  batch_size  \
16          0.001         128
18          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
19          0.001         128
3           0.001         128
13          0.001         128
14          0.001         128

                                            optimizer  \
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
14  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
16  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>
14  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
14  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
16  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...
14  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
14  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...
14  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
16                     12.655114                         9.871741
18                     12.627546                         9.912533
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
19                     12.733375                         9.977633
3                      12.809443                        10.142489
13                     12.845186                        10.168581
14                     12.824016                        10.160081

    validation_test_abserror_std validation_test_success  \
16                     11.069855                0.566646
18                     11.057780                0.573169
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
19                     11.031693                0.564431
3                      10.942125                0.528246
13                     11.034602                0.509169
14                     10.930723                0.515446

    validation_test_improvement  validation_avg_train_test_improvement  \
16                     0.034076                               0.032032
18                     0.030084                               0.029981
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
19                     0.023714                               0.019262
3                      0.007584                               0.003045
13                     0.005031                               0.002333
14                     0.005862                              -0.000077

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
16                            0.031902                              0.031967
18                            0.029981                              0.029981
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
19                            0.018232                              0.018740
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN
14                            0.458603                                   NaN

    num_layers iteration_number
16           1               17
18           1               19
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
19           1               20
3            1                4
13           1               14
14           1               15

[20 rows x 52 columns]
1 21 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.01, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.03026719475598433, Original: 9.762922791515482, New: 9.467426505997045
Test: Improvement: 0.03583683443588156, Original: 10.2199936987652, New: 9.853741476646798
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
18          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
19          0.001         128
3           0.001         128
13          0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
13  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>
13  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
13  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...
13  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
13  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...
13  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
18                     12.627546                         9.912533
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
19                     12.733375                         9.977633
3                      12.809443                        10.142489
13                     12.845186                        10.168581

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
18                     11.057780                0.573169
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
19                     11.031693                0.564431
3                      10.942125                0.528246
13                     11.034602                0.509169

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
18                     0.030084                               0.029981
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
19                     0.023714                               0.019262
3                      0.007584                               0.003045
13                     0.005031                               0.002333

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
18                            0.029981                              0.029981
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
19                            0.018232                              0.018740
3                            -0.003719                                   NaN
13                           -0.000787                                   NaN

    num_layers iteration_number
20           1               21
16           1               17
18           1               19
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
19           1               20
3            1                4
13           1               14

[20 rows x 52 columns]
1 22 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.01, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.027776149814958278, Original: 9.762922791515482, New: 9.491746385426477
Test: Improvement: 0.03154322810777934, Original: 10.2199936987652, New: 9.897622106264981
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
18          0.001         128
21          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
19          0.001         128
3           0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
3   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
3   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
3   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
3   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
3   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
3   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
19                     12.733375                         9.977633
3                      12.809443                        10.142489

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
18                     11.057780                0.573169
21                     10.961830                0.559877
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
19                     11.031693                0.564431
3                      10.942125                0.528246

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
18                     0.030084                               0.029981
21                     0.031543                               0.029660
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
19                     0.023714                               0.019262
3                      0.007584                               0.003045

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
18                            0.029981                              0.029981
21                            0.029540                              0.029600
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
19                            0.018232                              0.018740
3                            -0.003719                                   NaN

    num_layers iteration_number
20           1               21
16           1               17
18           1               19
21           1               22
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
19           1               20
3            1                4

[20 rows x 52 columns]
1 23 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.01, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.013235354936698428, Original: 9.762922791515482, New: 9.633707043150192
Test: Improvement: 0.017455557755938916, Original: 10.2199936987652, New: 10.041598008491071
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
18          0.001         128
21          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
19          0.001         128
22          0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
22  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>
22  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
22  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...
22  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
22  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...
22  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
19                     12.733375                         9.977633
22                     12.705237                        10.041598

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
18                     11.057780                0.573169
21                     10.961830                0.559877
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
19                     11.031693                0.564431
22                     10.951262                0.559631

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
18                     0.030084                               0.029981
21                     0.031543                               0.029660
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
19                     0.023714                               0.019262
22                     0.017456                               0.015345

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
18                            0.029981                              0.029981
21                            0.029540                              0.029600
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
19                            0.018232                              0.018740
22                            0.015055                              0.015200

    num_layers iteration_number
20           1               21
16           1               17
18           1               19
21           1               22
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
19           1               20
22           1               23

[20 rows x 52 columns]
1 24 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.01, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.032128339613081876, Original: 9.762922791515482, New: 9.449256292453375
Test: Improvement: 0.03143949726136888, Original: 10.2199936987652, New: 9.898682234861663
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
23          0.001         128
18          0.001         128
21          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128
19          0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
19  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>
19  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
19  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...
19  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
19  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...
19  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
23                     12.647896                         9.898682
18                     12.627546                         9.912533
21                     12.610680                         9.897622
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960
19                     12.733375                         9.977633

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
23                     11.021342                0.565169
18                     11.057780                0.573169
21                     10.961830                0.559877
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569
19                     11.031693                0.564431

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
23                     0.031439                               0.031784
18                     0.030084                               0.029981
21                     0.031543                               0.029660
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198
19                     0.023714                               0.019262

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
23                            0.031780                              0.031782
18                            0.029981                              0.029981
21                            0.029540                              0.029600
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187
19                            0.018232                              0.018740

    num_layers iteration_number
20           1               21
16           1               17
23           1               24
18           1               19
21           1               22
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12
19           1               20

[20 rows x 52 columns]
1 25 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.030666405291476274, Original: 9.762922791515482, New: 9.463529044361477
Test: Improvement: 0.027262459772281825, Original: 10.2199936987652, New: 9.94137153167964
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
23          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128
11          0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
11  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>
11  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
11  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...
11  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
11  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...
11  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
23                     12.647896                         9.898682
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202
11                     12.699768                         9.985960

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
23                     11.021342                0.565169
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877
11                     10.974273                0.563569

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
23                     0.031439                               0.031784
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900
11                     0.022900                               0.022198

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
23                            0.031780                              0.031782
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818
11                            0.022175                              0.022187

    num_layers iteration_number
20           1               21
16           1               17
23           1               24
18           1               19
21           1               22
24           1               25
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6
11           1               12

[20 rows x 52 columns]
1 26 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.032554879373950546, Original: 9.762922791515482, New: 9.445092017700503
Test: Improvement: 0.031251959985502016, Original: 10.2199936987652, New: 9.900598864639306
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128
5           0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
5   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>
5   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
5   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...
5   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
5   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...
5   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044
5                      12.875042                         9.966202

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000
5                      11.633251                0.567877

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128
5                      0.024833                               0.022900

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075
5                             0.022737                              0.022818

    num_layers iteration_number
20           1               21
16           1               17
25           1               26
23           1               24
18           1               19
21           1               22
24           1               25
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2
5            1                6

[20 rows x 52 columns]
1 27 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02906421931955065, Original: 9.762922791515482, New: 9.479171062303037
Test: Improvement: 0.03346586265266399, Original: 10.2199936987652, New: 9.877972793331232
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075

    num_layers iteration_number
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
18           1               19
21           1               22
24           1               25
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2

[20 rows x 52 columns]
1 28 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01295539067674358, Original: 9.762922791515482, New: 9.636440312604515
Test: Improvement: 0.018412622311566127, Original: 10.2199936987652, New: 10.03181681476325
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128
1           0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
1   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>
1   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
1   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...
1   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
1   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...
1   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278
1                      12.643244                         9.957044

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862
1                      11.035188                0.568000

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272
1                      0.025729                               0.024128

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187
1                             0.024022                              0.024075

    num_layers iteration_number
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
18           1               19
21           1               22
24           1               25
12           1               13
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7
1            1                2

[20 rows x 52 columns]
1 29 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.0001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.03317208420209597, Original: 9.762922791515482, New: 9.439066294616769
Test: Improvement: 0.023093918725027664, Original: 10.2199936987652, New: 9.98397399491562
    learning_rate  batch_size  \
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128
6           0.001         128

                                            optimizer  \
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
6   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>
6   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
6   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...
6   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
6   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...
6   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503
6                      12.660680                         9.951278

    validation_test_abserror_std validation_test_success  \
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877
6                      11.008345                0.568862

    validation_test_improvement  validation_avg_train_test_improvement  \
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047
6                      0.026293                               0.024272

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699
6                             0.024103                              0.024187

    num_layers iteration_number
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5
6            1                7

[20 rows x 52 columns]
1 30 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.0001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.03650729068047031, Original: 9.762922791515482, New: 9.406504931274638
Test: Improvement: 0.03844852422472683, Original: 10.2199936987652, New: 9.82705002346167
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128
4           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
4   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>
4   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
4   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...
4   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
4   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...
4   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997
4                      12.676083                         9.921503

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062
4                      11.038366                0.567877

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206
4                      0.029207                               0.025047

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829
4                             0.024356                              0.024699

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8
4            1                5

[20 rows x 52 columns]

1 31 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.0001, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.029717158720879988, Original: 9.762922791515482, New: 9.47279646534032
Test: Improvement: 0.031923019079138346, Original: 10.2199936987652, New: 9.893740644930844
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
7           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
7   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
7   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
7   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
7   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
7   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
7   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
7                      12.808694                         9.917997

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
7                      11.470663                0.564062

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
7                      0.029550                               0.025206

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
7                             0.024458                              0.024829

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
7            1                8

[20 rows x 52 columns]
1 32 640
[{'nodes': 256, 'activation': 'tanh', 'l2_reg': 0.0001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023911757884180214, Original: 9.762922791515482, New: 9.52947414548282
Test: Improvement: 0.02599557901734968, Original: 10.2199936987652, New: 9.954319045012133
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
31          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
31  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
31  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
31  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
31  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
31  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
31  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
31                     12.628729                         9.954319

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
31                     11.009317                0.568246

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
31                     0.025996                               0.024954

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
31                            0.024910                              0.024932

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
31           1               32

[20 rows x 52 columns]
1 33 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.1, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01963196568735939, Original: 9.762922791515482, New: 9.571257426264111
Test: Improvement: 0.023645495004374108, Original: 10.2199936987652, New: 9.978336888816312
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
31          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
31  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
31  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
31  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
31  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
31  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
31  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
31                     12.628729                         9.954319

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
31                     11.009317                0.568246

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
31                     0.025996                               0.024954

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
31                            0.024910                              0.024932

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
31           1               32

[20 rows x 52 columns]
1 34 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.1, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: -0.0007142899991563154, Original: 9.762922791515482, New: 9.769896349627997
Test: Improvement: 0.003395858732500858, Original: 10.2199936987652, New: 10.185288043917144
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
31          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
31  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
31  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
31  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
31  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
31  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
31  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
31                     12.628729                         9.954319

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
31                     11.009317                0.568246

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
31                     0.025996                               0.024954

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
31                            0.024910                              0.024932

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
31           1               32

[20 rows x 52 columns]
1 35 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.1, 'l1_reg': 0.001}]

invalid value encountered in sqrt

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02168689540853329, Original: 9.762922791515482, New: 9.5511953060543
Test: Improvement: 0.02990961092361201, Original: 10.2199936987652, New: 9.914317663593366
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
34          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
34  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
34  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
34  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
34  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
34  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
34  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
34                     12.737736                         9.914318

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
34                     11.158319                0.560862

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
34                     0.029910                               0.025798

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
34                            0.025143                              0.025469

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
34           1               35

[20 rows x 52 columns]
1 36 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.1, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.013315972099824802, Original: 9.762922791515482, New: 9.632919984010918
Test: Improvement: 0.01282164121728301, Original: 10.2199936987652, New: 10.088956606316739
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128
34          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
34  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>
34  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
34  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...
34  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
34  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...
34  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246
34                     12.737736                         9.914318

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969
34                     11.158319                0.560862

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865
34                     0.029910                               0.025798

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590
34                            0.025143                              0.025469

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3
34           1               35

[20 rows x 52 columns]
1 37 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.01, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02497836983636359, Original: 9.762922791515482, New: 9.519060895345145
Test: Improvement: 0.033193944795650285, Original: 10.2199936987652, New: 9.880751792116493
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
36          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
36                     12.614977                         9.880752
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
36                     10.948780                0.565169
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
36                     0.033194                               0.029086
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
36                            0.028506                              0.028795
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
36           1               37
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3

[20 rows x 52 columns]
1 38 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.01, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.010776280863132388, Original: 9.762922791515482, New: 9.657714793469035
Test: Improvement: 0.01630344409998166, Original: 10.2199936987652, New: 10.053372602795216
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
36          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
36                     12.614977                         9.880752
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
36                     10.948780                0.565169
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
36                     0.033194                               0.029086
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
36                            0.028506                              0.028795
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
36           1               37
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3

[20 rows x 52 columns]
1 39 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.01, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02076093855715543, Original: 9.762922791515482, New: 9.560235351302577
Test: Improvement: 0.0289345227689927, Original: 10.2199936987652, New: 9.924283058389316
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
36          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
36                     12.614977                         9.880752
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
36                     10.948780                0.565169
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
36                     0.033194                               0.029086
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
36                            0.028506                              0.028795
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
36           1               37
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3

[20 rows x 52 columns]
1 40 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.01, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.009330243682914305, Original: 9.762922791515482, New: 9.671832342813165
Test: Improvement: 0.017863276903839757, Original: 10.2199936987652, New: 10.037431121368659
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
36          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
36                     12.614977                         9.880752
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
36                     10.948780                0.565169
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
36                     0.033194                               0.029086
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
36                            0.028506                              0.028795
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
36           1               37
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3

[20 rows x 52 columns]
1 41 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019537864946529686, Original: 9.762922791515482, New: 9.572176124531456
Test: Improvement: 0.031241275571634416, Original: 10.2199936987652, New: 9.900708059281708
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
36          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128
2           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
2   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>
2   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
2   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...
2   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
2   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...
2   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
36                     12.614977                         9.880752
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142
2                      12.741454                         9.917246

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
36                     10.948780                0.565169
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692
2                      11.317726                0.569969

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
36                     0.033194                               0.029086
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113
2                      0.029623                               0.025865

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
36                            0.028506                              0.028795
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032
2                             0.025319                              0.025590

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
36           1               37
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16
2            1                3

[20 rows x 52 columns]
1 42 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.029924826156519188, Original: 9.762922791515482, New: 9.470769024199862
Test: Improvement: 0.02695887270933395, Original: 10.2199936987652, New: 9.944474189549993
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128
15          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
15  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>
15  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
15  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...
15  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
15  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...
15  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386
15                     12.718281                         9.932142

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246
15                     11.181478                0.563692

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841
15                     0.028166                               0.026113

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592
15                            0.025952                              0.026032

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10
15           1               16

[20 rows x 52 columns]
1 43 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021912181274550645, Original: 9.762922791515482, New: 9.548995857538353
Test: Improvement: 0.03903446164271177, Original: 10.2199936987652, New: 9.821061746741993
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128
9           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
9   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>
9   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
9   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...
9   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
9   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...
9   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128
9                      12.770602                         9.908386

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015
9                      11.300852                0.568246

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031
9                      0.030490                               0.026841

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692
9                             0.026345                              0.026592

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9
9            1               10

[20 rows x 52 columns]
1 44 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.024790830840020397, Original: 9.762922791515482, New: 9.520891824086842
Test: Improvement: 0.03500269674149019, Original: 10.2199936987652, New: 9.86226635862738
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9

[20 rows x 52 columns]
1 45 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.0001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.018721407212168133, Original: 9.762922791515482, New: 9.580147138354564
Test: Improvement: 0.0361512958269178, Original: 10.2199936987652, New: 9.850527683211903
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
8           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
8   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
8   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
8   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
8   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
8   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
8   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
8                      12.657468                         9.900128

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
8                      11.047042                0.567015

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
8                      0.031298                               0.027031

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
8                             0.026357                              0.026692

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
8            1                9

[20 rows x 52 columns]
1 46 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.0001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022008659771780584, Original: 9.762922791515482, New: 9.548053945418856
Test: Improvement: 0.03239150355380313, Original: 10.2199936987652, New: 9.8889527365518
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
45          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
45  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
45  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
45  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
45  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
45  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
45  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
45                     12.663407                         9.888953

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
45                     11.028807                0.565415

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
45                     0.032392                               0.027200

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
45                            0.026209                              0.026700

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
45           1               46

[20 rows x 52 columns]
1 47 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.0001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.023534630317823574, Original: 9.762922791515482, New: 9.533156012795711
Test: Improvement: 0.029224037943093115, Original: 10.2199936987652, New: 9.921324215134312
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
45          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
45  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
45  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
45  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
45  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
45  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
45  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
45                     12.663407                         9.888953

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
45                     11.028807                0.565415

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
45                     0.032392                               0.027200

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
45                            0.026209                              0.026700

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
45           1               46

[20 rows x 52 columns]
1 48 640
[{'nodes': 256, 'activation': 'elu', 'l2_reg': 0.0001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024783658549919957, Original: 9.762922791515482, New: 9.520961846601331
Test: Improvement: 0.02661736910119124, Original: 10.2199936987652, New: 9.947964354273317
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128
45          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
45  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>
45  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
45  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...
45  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
45  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...
45  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000
45                     12.663407                         9.888953

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354
45                     11.028807                0.565415

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972
45                     0.032392                               0.027200

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749
45                            0.026209                              0.026700

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1
45           1               46

[20 rows x 52 columns]
1 49 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.1, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.025468504954570946, Original: 9.762922791515482, New: 9.514275744028676
Test: Improvement: 0.03641056123016243, Original: 10.2199936987652, New: 9.847877992424435
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 50 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.1, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019643838173206245, Original: 9.762922791515482, New: 9.571141516101445
Test: Improvement: 0.02422535053579848, Original: 10.2199936987652, New: 9.97241076893896
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]

1 51 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.1, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.014002076977991737, Original: 9.762922791515482, New: 9.626221595058492
Test: Improvement: 0.02183943751434779, Original: 10.2199936987652, New: 9.996794784983988
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 52 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.1, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.015119628550657491, Original: 9.762922791515482, New: 9.61531102533902
Test: Improvement: 0.02388673227137934, Original: 10.2199936987652, New: 9.975871445467611
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 53 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.01, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 2ms/step
Training: Improvement: 0.019971846140425534, Original: 9.762922791515482, New: 9.567939199642481
Test: Improvement: 0.026735526671910488, Original: 10.2199936987652, New: 9.946756784645105
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 54 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.01, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.01365529846771423, Original: 9.762922791515482, New: 9.629607166880088
Test: Improvement: 0.023992549440758026, Original: 10.2199936987652, New: 9.97478999466334
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 55 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.01, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019857281433152855, Original: 9.762922791515482, New: 9.569057686034217
Test: Improvement: 0.032843499636575124, Original: 10.2199936987652, New: 9.884333339434004
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 56 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.01, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.018880429883233848, Original: 9.762922791515482, New: 9.578594612294848
Test: Improvement: 0.028247288684124645, Original: 10.2199936987652, New: 9.931306586406244
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 57 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.011352578396605261, Original: 9.762922791515482, New: 9.652088445144798
Test: Improvement: 0.021058678547241933, Original: 10.2199936987652, New: 10.004774136708065
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 58 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.015362976284558006, Original: 9.762922791515482, New: 9.612935240201459
Test: Improvement: 0.021617097525576622, Original: 10.2199936987652, New: 9.999067098268213
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 59 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.018504463421147144, Original: 9.762922791515482, New: 9.5822651438364
Test: Improvement: 0.02410797871644567, Original: 10.2199936987652, New: 9.973610308193159
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 60 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019625452140243325, Original: 9.762922791515482, New: 9.571321017521704
Test: Improvement: 0.029391518679375166, Original: 10.2199936987652, New: 9.919612563064845
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 61 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.0001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.010947417142324464, Original: 9.762922791515482, New: 9.656044003188455
Test: Improvement: 0.017292313406816816, Original: 10.2199936987652, New: 10.043266364710458
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 62 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.0001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.017642391596729562, Original: 9.762922791515482, New: 9.59068148449893
Test: Improvement: 0.026698587836839725, Original: 10.2199936987652, New: 9.947134299306768
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 63 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.0001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.013475595807980991, Original: 9.762922791515482, New: 9.631361590072494
Test: Improvement: 0.019354478247147852, Original: 10.2199936987652, New: 10.02219105303646
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 64 640
[{'nodes': 256, 'activation': <function swish at 0x000001F6C52FB700>, 'l2_reg': 0.0001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01916163533155478, Original: 9.762922791515482, New: 9.575849225214338
Test: Improvement: 0.02279568953269765, Original: 10.2199936987652, New: 9.987021895382021
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 65 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.1, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.024364134086185367, Original: 9.762922791515482, New: 9.525057631549924
Test: Improvement: 0.027913713637697398, Original: 10.2199936987652, New: 9.934715721278796
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 66 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.1, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.016162768240830676, Original: 9.762922791515482, New: 9.605126933083094
Test: Improvement: 0.012282126748402513, Original: 10.2199936987652, New: 10.09447044078909
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 67 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.1, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.017599023817843854, Original: 9.762922791515482, New: 9.59110488077583
Test: Improvement: 0.023474194610234752, Original: 10.2199936987652, New: 9.980087577765012
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 68 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.1, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0027673252301959233, Original: 9.762922791515482, New: 9.735905608954067
Test: Improvement: 0.006211248541491641, Original: 10.2199936987652, New: 10.15651477780969
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 69 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.01, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.01995671242837298, Original: 9.762922791515482, New: 9.5680869489048
Test: Improvement: 0.028351453631845408, Original: 10.2199936987652, New: 9.930242021296905
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 70 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.01, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.011745359820573155, Original: 9.762922791515482, New: 9.648253750428658
Test: Improvement: 0.0028795032371305425, Original: 10.2199936987652, New: 10.190565193826151
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]

1 71 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.01, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.020241448199720763, Original: 9.762922791515482, New: 9.565307095553148
Test: Improvement: 0.02170788415477522, Original: 10.2199936987652, New: 9.998139259489871
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 72 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.01, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.021438177529064264, Original: 9.762922791515482, New: 9.553623519508426
Test: Improvement: 0.025261018787058855, Original: 10.2199936987652, New: 9.961826245937068
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 73 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021940242374740022, Original: 9.762922791515482, New: 9.548721899183759
Test: Improvement: 0.028107414928731388, Original: 10.2199936987652, New: 9.932736095304985
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 74 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.015135420856948875, Original: 9.762922791515482, New: 9.615156846271997
Test: Improvement: 0.027636099119580315, Original: 10.2199936987652, New: 9.937552939904638
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 75 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019366879477292754, Original: 9.762922791515482, New: 9.573845442466087
Test: Improvement: 0.01939917057652163, Original: 10.2199936987652, New: 10.021734297711877
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 76 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020688165473171406, Original: 9.762922791515482, New: 9.560945829302813
Test: Improvement: 0.030569781088348912, Original: 10.2199936987652, New: 9.907570728669642
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 77 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.0001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02285394705090189, Original: 9.762922791515482, New: 9.539801470976144
Test: Improvement: 0.02590148874578129, Original: 10.2199936987652, New: 9.955280646994677
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128
0           0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
0   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>
0   <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
0   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...
0   (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
0   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...
0   [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453
0                      12.828530                         9.909000

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800
0                      11.799702                0.569354

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634
0                      0.030430                               0.026972

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001
0                             0.026528                              0.026749

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
28           1               29
17           1               18
10           1               11
0            1                1

[20 rows x 52 columns]
1 78 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.0001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.025224273352919137, Original: 9.762922791515482, New: 9.516660158298851
Test: Improvement: 0.03077904679382352, Original: 10.2199936987652, New: 9.905432034478324
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
17           1               18
10           1               11

[20 rows x 52 columns]
1 79 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.0001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02095113886940285, Original: 9.762922791515482, New: 9.558378440339183
Test: Improvement: 0.029902384667676987, Original: 10.2199936987652, New: 9.914391515883487
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
17           1               18
10           1               11

[20 rows x 52 columns]
1 80 640
[{'nodes': 256, 'activation': 'softplus', 'l2_reg': 0.0001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024546655154128596, Original: 9.762922791515482, New: 9.523275692455769
Test: Improvement: 0.023914523547551535, Original: 10.2199936987652, New: 9.97558741880025
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
17           1               18
10           1               11

[20 rows x 52 columns]

1 81 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.1, 'l1_reg': 0.1}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02290357077977616, Original: 9.762922791515482, New: 9.539316998342517
Test: Improvement: 0.02956222144854993, Original: 10.2199936987652, New: 9.917867981839517
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
17           1               18
10           1               11

[20 rows x 52 columns]
1 82 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.1, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024178626759742635, Original: 9.762922791515482, New: 9.526868725255245
Test: Improvement: 0.02924129913828399, Original: 10.2199936987652, New: 9.921147805828229
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
17           1               18
10           1               11

[20 rows x 52 columns]
1 83 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.1, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.019956886398588804, Original: 9.762922791515482, New: 9.568085250447014
Test: Improvement: 0.029378747543803818, Original: 10.2199936987652, New: 9.91974308398991
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
17          0.001         128
10          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
10  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>
10  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
10  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...
10  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
10  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...
10  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
17                     12.612428                         9.919018
10                     12.836802                         9.877453

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
17                     10.989754                0.562585
10                     11.472294                0.572800

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
17                     0.029450                               0.027532
10                     0.033517                               0.027634

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
17                            0.027398                              0.027465
10                            0.026382                              0.027001

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
17           1               18
10           1               11

[20 rows x 52 columns]
1 84 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.1, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0231884174249688, Original: 9.762922791515482, New: 9.53653606253808
Test: Improvement: 0.03282032536628118, Original: 10.2199936987652, New: 9.884570180330382
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128
17          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570
17                     12.612428                         9.919018

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508
17                     10.989754                0.562585

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004
17                     0.029450                               0.027532

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587
17                            0.027398                              0.027465

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84
17           1               18

[20 rows x 52 columns]
1 85 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.01, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022024200409854047, Original: 9.762922791515482, New: 9.547902223369213
Test: Improvement: 0.025553716074344243, Original: 10.2199936987652, New: 9.958834881505366
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128
17          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570
17                     12.612428                         9.919018

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508
17                     10.989754                0.562585

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004
17                     0.029450                               0.027532

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587
17                            0.027398                              0.027465

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84
17           1               18

[20 rows x 52 columns]
1 86 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.01, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02393329499639519, Original: 9.762922791515482, New: 9.529263880319112
Test: Improvement: 0.027780672947309334, Original: 10.2199936987652, New: 9.936075396296241
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128
17          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570
17                     12.612428                         9.919018

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508
17                     10.989754                0.562585

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004
17                     0.029450                               0.027532

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587
17                            0.027398                              0.027465

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84
17           1               18

[20 rows x 52 columns]
1 87 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.01, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.024311385811362003, Original: 9.762922791515482, New: 9.52557260888441
Test: Improvement: 0.030356315996471796, Original: 10.2199936987652, New: 9.909752340563532
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128
17          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570
17                     12.612428                         9.919018

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508
17                     10.989754                0.562585

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004
17                     0.029450                               0.027532

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587
17                            0.027398                              0.027465

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84
17           1               18

[20 rows x 52 columns]
1 88 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.01, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.017128311015232118, Original: 9.762922791515482, New: 9.595700413524707
Test: Improvement: 0.02767097238714658, Original: 10.2199936987652, New: 9.937196535329855
    learning_rate  batch_size  \
29          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128
17          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
17  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>
17  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
17  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...
17  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
17  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...
17  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570
17                     12.612428                         9.919018

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508
17                     10.989754                0.562585

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004
17                     0.029450                               0.027532

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587
17                            0.027398                              0.027465

    num_layers iteration_number
29           1               30
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84
17           1               18

[20 rows x 52 columns]
1 89 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.035953825025842566, Original: 9.762922791515482, New: 9.411908373728524
Test: Improvement: 0.030811024671774614, Original: 10.2199936987652, New: 9.905105220767163
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 90 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02275953700988381, Original: 9.762922791515482, New: 9.540723188917347
Test: Improvement: 0.0266635419507823, Original: 10.2199936987652, New: 9.947492468041442
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]

1 91 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.001, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.0199591368033628, Original: 9.762922791515482, New: 9.568063279918956
Test: Improvement: 0.032079130870032786, Original: 10.2199936987652, New: 9.8921451834116
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 92 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.022490642780031506, Original: 9.762922791515482, New: 9.54334838252248
Test: Improvement: 0.03304843316588578, Original: 10.2199936987652, New: 9.882238920055784
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 93 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.0001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.018668770305846422, Original: 9.762922791515482, New: 9.580661028406967
Test: Improvement: 0.028693331893368843, Original: 10.2199936987652, New: 9.926748027618391
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 94 640

[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.0001, 'l1_reg': 0.01}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02169111092455201, Original: 9.762922791515482, New: 9.551154150296883
Test: Improvement: 0.026184752808462396, Original: 10.2199936987652, New: 9.952385690058989
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 95 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.0001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.021812046928523433, Original: 9.762922791515482, New: 9.549973461427395
Test: Improvement: 0.025703658998984216, Original: 10.2199936987652, New: 9.957302465760371
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 96 640
[{'nodes': 256, 'activation': 'softsign', 'l2_reg': 0.0001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.022354620515735623, Original: 9.762922791515482, New: 9.544676357386727
Test: Improvement: 0.0308506600314221, Original: 10.2199936987652, New: 9.904700147641318
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 97 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.1, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 4ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 8s 5ms/step
Training: Improvement: 0.02258442669660458, Original: 9.762922791515482, New: 9.54243277738589
Test: Improvement: 0.02819910376094893, Original: 10.2199936987652, New: 9.931799036017475
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 98 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.1, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 3ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 4s 2ms/step
Training: Improvement: 0.01203072151033676, Original: 9.762922791515482, New: 9.64546778628384
Test: Improvement: 0.02900696564629537, Original: 10.2199936987652, New: 9.923542692639762
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 99 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.1, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.021373515555025785, Original: 9.762922791515482, New: 9.55425480936851
Test: Improvement: 0.03314666273020847, Original: 10.2199936987652, New: 9.881235014527373
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 100 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.1, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.01490022674664, Original: 9.762922791515482, New: 9.617453028211962
Test: Improvement: 0.02495291768070054, Original: 10.2199936987652, New: 9.964975037302633
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]

1 101 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.01, 'l1_reg': 0.1}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02186026068136049, Original: 9.762922791515482, New: 9.549502754280958
Test: Improvement: 0.01986064256804669, Original: 10.2199936987652, New: 10.017018056866334
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 102 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.01, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.021286346163677545, Original: 9.762922791515482, New: 9.555105837406026
Test: Improvement: 0.024235157132453236, Original: 10.2199936987652, New: 9.972310545582943
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 103 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.01, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 4s 2ms/step
Training: Improvement: 0.01979934954004726, Original: 9.762922791515482, New: 9.569623270633773
Test: Improvement: 0.025647527770372228, Original: 10.2199936987652, New: 9.95787612656309
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 104 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.01, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 3ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 4s 3ms/step
Training: Improvement: 0.012540731067184088, Original: 9.762922791515482, New: 9.640488602357404
Test: Improvement: 0.02555999457784792, Original: 10.2199936987652, New: 9.95877071523912
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 105 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01757010352208019, Original: 9.762922791515482, New: 9.591387227390479
Test: Improvement: 0.023952017779150396, Original: 10.2199936987652, New: 9.97520422798957
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 106 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.020196211018285823, Original: 9.762922791515482, New: 9.565748742662803
Test: Improvement: 0.02331678340357534, Original: 10.2199936987652, New: 9.981696319305186
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 107 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.001, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.014728500314107093, Original: 9.762922791515482, New: 9.619129580114043
Test: Improvement: 0.023551628199484708, Original: 10.2199936987652, New: 9.979296206970805
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 108 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.006633123844918335, Original: 9.762922791515482, New: 9.698164115550984
Test: Improvement: 0.006043781972827618, Original: 10.2199936987652, New: 10.15822628508619
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 109 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.0001, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.018384774554223264, Original: 9.762922791515482, New: 9.583433657003182
Test: Improvement: 0.0195070347764166, Original: 10.2199936987652, New: 10.020631926268628
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 110 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.0001, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 4s 2ms/step
Training: Improvement: 0.015869225535710622, Original: 9.762922791515482, New: 9.607992767849193
Test: Improvement: 0.018623178641586472, Original: 10.2199936987652, New: 10.029664930397207
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]

1 111 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.0001, 'l1_reg': 0.001}]
X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 4ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 6s 4ms/step
Training: Improvement: 0.0156955625582092, Original: 9.762922791515482, New: 9.609688226090285
Test: Improvement: 0.025390078654199955, Original: 10.2199936987652, New: 9.960507254908123
    learning_rate  batch_size  \
29          0.001         128
88          0.001         128
20          0.001         128
16          0.001         128
25          0.001         128
23          0.001         128
26          0.001         128
30          0.001         128
48          0.001         128
18          0.001         128
21          0.001         128
43          0.001         128
42          0.001         128
24          0.001         128
36          0.001         128
41          0.001         128
12          0.001         128
77          0.001         128
28          0.001         128
83          0.001         128

                                            optimizer  \
29  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
83  (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                              optimizer_name  \
29  <class 'keras.src.optimizers.adam.Adam'>
88  <class 'keras.src.optimizers.adam.Adam'>
20  <class 'keras.src.optimizers.adam.Adam'>
16  <class 'keras.src.optimizers.adam.Adam'>
25  <class 'keras.src.optimizers.adam.Adam'>
23  <class 'keras.src.optimizers.adam.Adam'>
26  <class 'keras.src.optimizers.adam.Adam'>
30  <class 'keras.src.optimizers.adam.Adam'>
48  <class 'keras.src.optimizers.adam.Adam'>
18  <class 'keras.src.optimizers.adam.Adam'>
21  <class 'keras.src.optimizers.adam.Adam'>
43  <class 'keras.src.optimizers.adam.Adam'>
42  <class 'keras.src.optimizers.adam.Adam'>
24  <class 'keras.src.optimizers.adam.Adam'>
36  <class 'keras.src.optimizers.adam.Adam'>
41  <class 'keras.src.optimizers.adam.Adam'>
12  <class 'keras.src.optimizers.adam.Adam'>
77  <class 'keras.src.optimizers.adam.Adam'>
28  <class 'keras.src.optimizers.adam.Adam'>
83  <class 'keras.src.optimizers.adam.Adam'>

                                     optimizer_params  \
29  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
83  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                        loss_function  \
29  (<class 'keras.src.losses.Huber'>, {'reduction...
88  (<class 'keras.src.losses.Huber'>, {'reduction...
20  (<class 'keras.src.losses.Huber'>, {'reduction...
16  (<class 'keras.src.losses.Huber'>, {'reduction...
25  (<class 'keras.src.losses.Huber'>, {'reduction...
23  (<class 'keras.src.losses.Huber'>, {'reduction...
26  (<class 'keras.src.losses.Huber'>, {'reduction...
30  (<class 'keras.src.losses.Huber'>, {'reduction...
48  (<class 'keras.src.losses.Huber'>, {'reduction...
18  (<class 'keras.src.losses.Huber'>, {'reduction...
21  (<class 'keras.src.losses.Huber'>, {'reduction...
43  (<class 'keras.src.losses.Huber'>, {'reduction...
42  (<class 'keras.src.losses.Huber'>, {'reduction...
24  (<class 'keras.src.losses.Huber'>, {'reduction...
36  (<class 'keras.src.losses.Huber'>, {'reduction...
41  (<class 'keras.src.losses.Huber'>, {'reduction...
12  (<class 'keras.src.losses.Huber'>, {'reduction...
77  (<class 'keras.src.losses.Huber'>, {'reduction...
28  (<class 'keras.src.losses.Huber'>, {'reduction...
83  (<class 'keras.src.losses.Huber'>, {'reduction...

                 loss_function_class   loss_function_params  \
29  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
83  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                              metrics  epochs  ...  \
29  [(<class 'keras.src.metrics.regression_metrics...     200  ...
88  [(<class 'keras.src.metrics.regression_metrics...     200  ...
20  [(<class 'keras.src.metrics.regression_metrics...     200  ...
16  [(<class 'keras.src.metrics.regression_metrics...     200  ...
25  [(<class 'keras.src.metrics.regression_metrics...     200  ...
23  [(<class 'keras.src.metrics.regression_metrics...     200  ...
26  [(<class 'keras.src.metrics.regression_metrics...     200  ...
30  [(<class 'keras.src.metrics.regression_metrics...     200  ...
48  [(<class 'keras.src.metrics.regression_metrics...     200  ...
18  [(<class 'keras.src.metrics.regression_metrics...     200  ...
21  [(<class 'keras.src.metrics.regression_metrics...     200  ...
43  [(<class 'keras.src.metrics.regression_metrics...     200  ...
42  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24  [(<class 'keras.src.metrics.regression_metrics...     200  ...
36  [(<class 'keras.src.metrics.regression_metrics...     200  ...
41  [(<class 'keras.src.metrics.regression_metrics...     200  ...
12  [(<class 'keras.src.metrics.regression_metrics...     200  ...
77  [(<class 'keras.src.metrics.regression_metrics...     200  ...
28  [(<class 'keras.src.metrics.regression_metrics...     200  ...
83  [(<class 'keras.src.metrics.regression_metrics...     200  ...

   validation_test_abserror_mean  validation_test_abserror_median  \
29                     12.635708                         9.827050
88                     12.716035                         9.905105
20                     12.586595                         9.853741
16                     12.655114                         9.871741
25                     12.655870                         9.900599
23                     12.647896                         9.898682
26                     12.658295                         9.877973
30                     12.646721                         9.893741
48                     12.759424                         9.847878
18                     12.627546                         9.912533
21                     12.610680                         9.897622
43                     12.691234                         9.862266
42                     12.587036                         9.821062
24                     12.661850                         9.941372
36                     12.614977                         9.880752
41                     12.808724                         9.944474
12                     12.727644                         9.897619
77                     12.742423                         9.905432
28                     12.725132                         9.983974
83                     12.590574                         9.884570

    validation_test_abserror_std validation_test_success  \
29                     11.081309                0.567138
88                     11.188376                0.569969
20                     10.996522                0.566646
16                     11.069855                0.566646
25                     11.064878                0.566892
23                     11.021342                0.565169
26                     11.042697                0.561846
30                     11.061687                0.561846
48                     11.587685                0.566400
18                     11.057780                0.573169
21                     10.961830                0.559877
43                     11.139631                0.568123
42                     10.946263                0.565538
24                     11.083350                0.564554
36                     10.948780                0.565169
41                     11.394268                0.566277
12                     11.311885                0.561846
77                     11.411437                0.566646
28                     11.188626                0.566523
83                     10.898091                0.567508

    validation_test_improvement  validation_avg_train_test_improvement  \
29                     0.038449                               0.037478
88                     0.030811                               0.033382
20                     0.035837                               0.033052
16                     0.034076                               0.032032
25                     0.031252                               0.031903
23                     0.031439                               0.031784
26                     0.033466                               0.031265
30                     0.031923                               0.030820
48                     0.036411                               0.030940
18                     0.030084                               0.029981
21                     0.031543                               0.029660
43                     0.035003                               0.029897
42                     0.039034                               0.030473
24                     0.027262                               0.028964
36                     0.033194                               0.029086
41                     0.026959                               0.028442
12                     0.031544                               0.028173
77                     0.030779                               0.028002
28                     0.023094                               0.028133
83                     0.032820                               0.028004

   validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                            0.037453                              0.037465
88                            0.033184                              0.033283
20                            0.032817                              0.032934
16                            0.031902                              0.031967
25                            0.031890                              0.031897
23                            0.031780                              0.031782
26                            0.031110                              0.031187
30                            0.030781                              0.030800
48                            0.029972                              0.030452
18                            0.029981                              0.029981
21                            0.029540                              0.029600
43                            0.029025                              0.029458
42                            0.028068                              0.029246
24                            0.028864                              0.028914
36                            0.028506                              0.028795
41                            0.028365                              0.028403
12                            0.027769                              0.027970
77                            0.027726                              0.027864
28                            0.027230                              0.027678
83                            0.027176                              0.027587

    num_layers iteration_number
29           1               30
88           1               89
20           1               21
16           1               17
25           1               26
23           1               24
26           1               27
30           1               31
48           1               49
18           1               19
21           1               22
43           1               44
42           1               43
24           1               25
36           1               37
41           1               42
12           1               13
77           1               78
28           1               29
83           1               84

[20 rows x 52 columns]
1 112 640
[{'nodes': 256, 'activation': <function gelu at 0x000001F6C52FBA60>, 'l2_reg': 0.0001, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.02422167153793232, Original: 9.762922791515482, New: 9.5264484824092
Test: Improvement: 0.03467936714451241, Original: 10.2199936987652, New: 9.865570785071117
     learning_rate  batch_size  \
29           0.001         128
88           0.001         128
20           0.001         128
16           0.001         128
25           0.001         128
23           0.001         128
26           0.001         128
30           0.001         128
48           0.001         128
18           0.001         128
21           0.001         128
43           0.001         128
42           0.001         128
111          0.001         128
24           0.001         128
36           0.001         128
41           0.001         128
12           0.001         128
77           0.001         128
28           0.001         128

                                             optimizer  \
29   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
111  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                               optimizer_name  \
29   <class 'keras.src.optimizers.adam.Adam'>
88   <class 'keras.src.optimizers.adam.Adam'>
20   <class 'keras.src.optimizers.adam.Adam'>
16   <class 'keras.src.optimizers.adam.Adam'>
25   <class 'keras.src.optimizers.adam.Adam'>
23   <class 'keras.src.optimizers.adam.Adam'>
26   <class 'keras.src.optimizers.adam.Adam'>
30   <class 'keras.src.optimizers.adam.Adam'>
48   <class 'keras.src.optimizers.adam.Adam'>
18   <class 'keras.src.optimizers.adam.Adam'>
21   <class 'keras.src.optimizers.adam.Adam'>
43   <class 'keras.src.optimizers.adam.Adam'>
42   <class 'keras.src.optimizers.adam.Adam'>
111  <class 'keras.src.optimizers.adam.Adam'>
24   <class 'keras.src.optimizers.adam.Adam'>
36   <class 'keras.src.optimizers.adam.Adam'>
41   <class 'keras.src.optimizers.adam.Adam'>
12   <class 'keras.src.optimizers.adam.Adam'>
77   <class 'keras.src.optimizers.adam.Adam'>
28   <class 'keras.src.optimizers.adam.Adam'>

                                      optimizer_params  \
29   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
111  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                         loss_function  \
29   (<class 'keras.src.losses.Huber'>, {'reduction...
88   (<class 'keras.src.losses.Huber'>, {'reduction...
20   (<class 'keras.src.losses.Huber'>, {'reduction...
16   (<class 'keras.src.losses.Huber'>, {'reduction...
25   (<class 'keras.src.losses.Huber'>, {'reduction...
23   (<class 'keras.src.losses.Huber'>, {'reduction...
26   (<class 'keras.src.losses.Huber'>, {'reduction...
30   (<class 'keras.src.losses.Huber'>, {'reduction...
48   (<class 'keras.src.losses.Huber'>, {'reduction...
18   (<class 'keras.src.losses.Huber'>, {'reduction...
21   (<class 'keras.src.losses.Huber'>, {'reduction...
43   (<class 'keras.src.losses.Huber'>, {'reduction...
42   (<class 'keras.src.losses.Huber'>, {'reduction...
111  (<class 'keras.src.losses.Huber'>, {'reduction...
24   (<class 'keras.src.losses.Huber'>, {'reduction...
36   (<class 'keras.src.losses.Huber'>, {'reduction...
41   (<class 'keras.src.losses.Huber'>, {'reduction...
12   (<class 'keras.src.losses.Huber'>, {'reduction...
77   (<class 'keras.src.losses.Huber'>, {'reduction...
28   (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
29   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
111  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                               metrics  epochs  ...  \
29   [(<class 'keras.src.metrics.regression_metrics...     200  ...
88   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16   [(<class 'keras.src.metrics.regression_metrics...     200  ...
25   [(<class 'keras.src.metrics.regression_metrics...     200  ...
23   [(<class 'keras.src.metrics.regression_metrics...     200  ...
26   [(<class 'keras.src.metrics.regression_metrics...     200  ...
30   [(<class 'keras.src.metrics.regression_metrics...     200  ...
48   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18   [(<class 'keras.src.metrics.regression_metrics...     200  ...
21   [(<class 'keras.src.metrics.regression_metrics...     200  ...
43   [(<class 'keras.src.metrics.regression_metrics...     200  ...
42   [(<class 'keras.src.metrics.regression_metrics...     200  ...
111  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24   [(<class 'keras.src.metrics.regression_metrics...     200  ...
36   [(<class 'keras.src.metrics.regression_metrics...     200  ...
41   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12   [(<class 'keras.src.metrics.regression_metrics...     200  ...
77   [(<class 'keras.src.metrics.regression_metrics...     200  ...
28   [(<class 'keras.src.metrics.regression_metrics...     200  ...

    validation_test_abserror_mean  validation_test_abserror_median  \
29                      12.635708                         9.827050
88                      12.716035                         9.905105
20                      12.586595                         9.853741
16                      12.655114                         9.871741
25                      12.655870                         9.900599
23                      12.647896                         9.898682
26                      12.658295                         9.877973
30                      12.646721                         9.893741
48                      12.759424                         9.847878
18                      12.627546                         9.912533
21                      12.610680                         9.897622
43                      12.691234                         9.862266
42                      12.587036                         9.821062
111                     12.827723                         9.865571
24                      12.661850                         9.941372
36                      12.614977                         9.880752
41                      12.808724                         9.944474
12                      12.727644                         9.897619
77                      12.742423                         9.905432
28                      12.725132                         9.983974

     validation_test_abserror_std validation_test_success  \
29                      11.081309                0.567138
88                      11.188376                0.569969
20                      10.996522                0.566646
16                      11.069855                0.566646
25                      11.064878                0.566892
23                      11.021342                0.565169
26                      11.042697                0.561846
30                      11.061687                0.561846
48                      11.587685                0.566400
18                      11.057780                0.573169
21                      10.961830                0.559877
43                      11.139631                0.568123
42                      10.946263                0.565538
111                     11.528715                0.567754
24                      11.083350                0.564554
36                      10.948780                0.565169
41                      11.394268                0.566277
12                      11.311885                0.561846
77                      11.411437                0.566646
28                      11.188626                0.566523

     validation_test_improvement  validation_avg_train_test_improvement  \
29                      0.038449                               0.037478
88                      0.030811                               0.033382
20                      0.035837                               0.033052
16                      0.034076                               0.032032
25                      0.031252                               0.031903
23                      0.031439                               0.031784
26                      0.033466                               0.031265
30                      0.031923                               0.030820
48                      0.036411                               0.030940
18                      0.030084                               0.029981
21                      0.031543                               0.029660
43                      0.035003                               0.029897
42                      0.039034                               0.030473
111                     0.034679                               0.029451
24                      0.027262                               0.028964
36                      0.033194                               0.029086
41                      0.026959                               0.028442
12                      0.031544                               0.028173
77                      0.030779                               0.028002
28                      0.023094                               0.028133

    validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                             0.037453                              0.037465
88                             0.033184                              0.033283
20                             0.032817                              0.032934
16                             0.031902                              0.031967
25                             0.031890                              0.031897
23                             0.031780                              0.031782
26                             0.031110                              0.031187
30                             0.030781                              0.030800
48                             0.029972                              0.030452
18                             0.029981                              0.029981
21                             0.029540                              0.029600
43                             0.029025                              0.029458
42                             0.028068                              0.029246
111                            0.028522                              0.028983
24                             0.028864                              0.028914
36                             0.028506                              0.028795
41                             0.028365                              0.028403
12                             0.027769                              0.027970
77                             0.027726                              0.027864
28                             0.027230                              0.027678

     num_layers iteration_number
29            1               30
88            1               89
20            1               21
16            1               17
25            1               26
23            1               24
26            1               27
30            1               31
48            1               49
18            1               19
21            1               22
43            1               44
42            1               43
111           1              112
24            1               25
36            1               37
41            1               42
12            1               13
77            1               78
28            1               29

[20 rows x 52 columns]
1 113 640
[{'nodes': 256, 'activation': 'linear', 'l2_reg': 0.1, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.01997713883023031, Original: 9.762922791515482, New: 9.567887527520558
Test: Improvement: 0.02529787012404962, Original: 10.2199936987652, New: 9.961449625505232
     learning_rate  batch_size  \
29           0.001         128
88           0.001         128
20           0.001         128
16           0.001         128
25           0.001         128
23           0.001         128
26           0.001         128
30           0.001         128
48           0.001         128
18           0.001         128
21           0.001         128
43           0.001         128
42           0.001         128
111          0.001         128
24           0.001         128
36           0.001         128
41           0.001         128
12           0.001         128
77           0.001         128
28           0.001         128

                                             optimizer  \
29   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
111  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                               optimizer_name  \
29   <class 'keras.src.optimizers.adam.Adam'>
88   <class 'keras.src.optimizers.adam.Adam'>
20   <class 'keras.src.optimizers.adam.Adam'>
16   <class 'keras.src.optimizers.adam.Adam'>
25   <class 'keras.src.optimizers.adam.Adam'>
23   <class 'keras.src.optimizers.adam.Adam'>
26   <class 'keras.src.optimizers.adam.Adam'>
30   <class 'keras.src.optimizers.adam.Adam'>
48   <class 'keras.src.optimizers.adam.Adam'>
18   <class 'keras.src.optimizers.adam.Adam'>
21   <class 'keras.src.optimizers.adam.Adam'>
43   <class 'keras.src.optimizers.adam.Adam'>
42   <class 'keras.src.optimizers.adam.Adam'>
111  <class 'keras.src.optimizers.adam.Adam'>
24   <class 'keras.src.optimizers.adam.Adam'>
36   <class 'keras.src.optimizers.adam.Adam'>
41   <class 'keras.src.optimizers.adam.Adam'>
12   <class 'keras.src.optimizers.adam.Adam'>
77   <class 'keras.src.optimizers.adam.Adam'>
28   <class 'keras.src.optimizers.adam.Adam'>

                                      optimizer_params  \
29   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
111  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                         loss_function  \
29   (<class 'keras.src.losses.Huber'>, {'reduction...
88   (<class 'keras.src.losses.Huber'>, {'reduction...
20   (<class 'keras.src.losses.Huber'>, {'reduction...
16   (<class 'keras.src.losses.Huber'>, {'reduction...
25   (<class 'keras.src.losses.Huber'>, {'reduction...
23   (<class 'keras.src.losses.Huber'>, {'reduction...
26   (<class 'keras.src.losses.Huber'>, {'reduction...
30   (<class 'keras.src.losses.Huber'>, {'reduction...
48   (<class 'keras.src.losses.Huber'>, {'reduction...
18   (<class 'keras.src.losses.Huber'>, {'reduction...
21   (<class 'keras.src.losses.Huber'>, {'reduction...
43   (<class 'keras.src.losses.Huber'>, {'reduction...
42   (<class 'keras.src.losses.Huber'>, {'reduction...
111  (<class 'keras.src.losses.Huber'>, {'reduction...
24   (<class 'keras.src.losses.Huber'>, {'reduction...
36   (<class 'keras.src.losses.Huber'>, {'reduction...
41   (<class 'keras.src.losses.Huber'>, {'reduction...
12   (<class 'keras.src.losses.Huber'>, {'reduction...
77   (<class 'keras.src.losses.Huber'>, {'reduction...
28   (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
29   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
111  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                               metrics  epochs  ...  \
29   [(<class 'keras.src.metrics.regression_metrics...     200  ...
88   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16   [(<class 'keras.src.metrics.regression_metrics...     200  ...
25   [(<class 'keras.src.metrics.regression_metrics...     200  ...
23   [(<class 'keras.src.metrics.regression_metrics...     200  ...
26   [(<class 'keras.src.metrics.regression_metrics...     200  ...
30   [(<class 'keras.src.metrics.regression_metrics...     200  ...
48   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18   [(<class 'keras.src.metrics.regression_metrics...     200  ...
21   [(<class 'keras.src.metrics.regression_metrics...     200  ...
43   [(<class 'keras.src.metrics.regression_metrics...     200  ...
42   [(<class 'keras.src.metrics.regression_metrics...     200  ...
111  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24   [(<class 'keras.src.metrics.regression_metrics...     200  ...
36   [(<class 'keras.src.metrics.regression_metrics...     200  ...
41   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12   [(<class 'keras.src.metrics.regression_metrics...     200  ...
77   [(<class 'keras.src.metrics.regression_metrics...     200  ...
28   [(<class 'keras.src.metrics.regression_metrics...     200  ...

    validation_test_abserror_mean  validation_test_abserror_median  \
29                      12.635708                         9.827050
88                      12.716035                         9.905105
20                      12.586595                         9.853741
16                      12.655114                         9.871741
25                      12.655870                         9.900599
23                      12.647896                         9.898682
26                      12.658295                         9.877973
30                      12.646721                         9.893741
48                      12.759424                         9.847878
18                      12.627546                         9.912533
21                      12.610680                         9.897622
43                      12.691234                         9.862266
42                      12.587036                         9.821062
111                     12.827723                         9.865571
24                      12.661850                         9.941372
36                      12.614977                         9.880752
41                      12.808724                         9.944474
12                      12.727644                         9.897619
77                      12.742423                         9.905432
28                      12.725132                         9.983974

     validation_test_abserror_std validation_test_success  \
29                      11.081309                0.567138
88                      11.188376                0.569969
20                      10.996522                0.566646
16                      11.069855                0.566646
25                      11.064878                0.566892
23                      11.021342                0.565169
26                      11.042697                0.561846
30                      11.061687                0.561846
48                      11.587685                0.566400
18                      11.057780                0.573169
21                      10.961830                0.559877
43                      11.139631                0.568123
42                      10.946263                0.565538
111                     11.528715                0.567754
24                      11.083350                0.564554
36                      10.948780                0.565169
41                      11.394268                0.566277
12                      11.311885                0.561846
77                      11.411437                0.566646
28                      11.188626                0.566523

     validation_test_improvement  validation_avg_train_test_improvement  \
29                      0.038449                               0.037478
88                      0.030811                               0.033382
20                      0.035837                               0.033052
16                      0.034076                               0.032032
25                      0.031252                               0.031903
23                      0.031439                               0.031784
26                      0.033466                               0.031265
30                      0.031923                               0.030820
48                      0.036411                               0.030940
18                      0.030084                               0.029981
21                      0.031543                               0.029660
43                      0.035003                               0.029897
42                      0.039034                               0.030473
111                     0.034679                               0.029451
24                      0.027262                               0.028964
36                      0.033194                               0.029086
41                      0.026959                               0.028442
12                      0.031544                               0.028173
77                      0.030779                               0.028002
28                      0.023094                               0.028133

    validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                             0.037453                              0.037465
88                             0.033184                              0.033283
20                             0.032817                              0.032934
16                             0.031902                              0.031967
25                             0.031890                              0.031897
23                             0.031780                              0.031782
26                             0.031110                              0.031187
30                             0.030781                              0.030800
48                             0.029972                              0.030452
18                             0.029981                              0.029981
21                             0.029540                              0.029600
43                             0.029025                              0.029458
42                             0.028068                              0.029246
111                            0.028522                              0.028983
24                             0.028864                              0.028914
36                             0.028506                              0.028795
41                             0.028365                              0.028403
12                             0.027769                              0.027970
77                             0.027726                              0.027864
28                             0.027230                              0.027678

     num_layers iteration_number
29            1               30
88            1               89
20            1               21
16            1               17
25            1               26
23            1               24
26            1               27
30            1               31
48            1               49
18            1               19
21            1               22
43            1               44
42            1               43
111           1              112
24            1               25
36            1               37
41            1               42
12            1               13
77            1               78
28            1               29

[20 rows x 52 columns]
1 114 640
[{'nodes': 256, 'activation': 'linear', 'l2_reg': 0.1, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.02192475341984256, Original: 9.762922791515482, New: 9.548873116654544
Test: Improvement: 0.02355002233477097, Original: 10.2199936987652, New: 9.97931261889806
     learning_rate  batch_size  \
29           0.001         128
88           0.001         128
20           0.001         128
16           0.001         128
25           0.001         128
23           0.001         128
26           0.001         128
30           0.001         128
48           0.001         128
18           0.001         128
21           0.001         128
43           0.001         128
42           0.001         128
111          0.001         128
24           0.001         128
36           0.001         128
41           0.001         128
12           0.001         128
77           0.001         128
28           0.001         128

                                             optimizer  \
29   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
111  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                               optimizer_name  \
29   <class 'keras.src.optimizers.adam.Adam'>
88   <class 'keras.src.optimizers.adam.Adam'>
20   <class 'keras.src.optimizers.adam.Adam'>
16   <class 'keras.src.optimizers.adam.Adam'>
25   <class 'keras.src.optimizers.adam.Adam'>
23   <class 'keras.src.optimizers.adam.Adam'>
26   <class 'keras.src.optimizers.adam.Adam'>
30   <class 'keras.src.optimizers.adam.Adam'>
48   <class 'keras.src.optimizers.adam.Adam'>
18   <class 'keras.src.optimizers.adam.Adam'>
21   <class 'keras.src.optimizers.adam.Adam'>
43   <class 'keras.src.optimizers.adam.Adam'>
42   <class 'keras.src.optimizers.adam.Adam'>
111  <class 'keras.src.optimizers.adam.Adam'>
24   <class 'keras.src.optimizers.adam.Adam'>
36   <class 'keras.src.optimizers.adam.Adam'>
41   <class 'keras.src.optimizers.adam.Adam'>
12   <class 'keras.src.optimizers.adam.Adam'>
77   <class 'keras.src.optimizers.adam.Adam'>
28   <class 'keras.src.optimizers.adam.Adam'>

                                      optimizer_params  \
29   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
111  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                         loss_function  \
29   (<class 'keras.src.losses.Huber'>, {'reduction...
88   (<class 'keras.src.losses.Huber'>, {'reduction...
20   (<class 'keras.src.losses.Huber'>, {'reduction...
16   (<class 'keras.src.losses.Huber'>, {'reduction...
25   (<class 'keras.src.losses.Huber'>, {'reduction...
23   (<class 'keras.src.losses.Huber'>, {'reduction...
26   (<class 'keras.src.losses.Huber'>, {'reduction...
30   (<class 'keras.src.losses.Huber'>, {'reduction...
48   (<class 'keras.src.losses.Huber'>, {'reduction...
18   (<class 'keras.src.losses.Huber'>, {'reduction...
21   (<class 'keras.src.losses.Huber'>, {'reduction...
43   (<class 'keras.src.losses.Huber'>, {'reduction...
42   (<class 'keras.src.losses.Huber'>, {'reduction...
111  (<class 'keras.src.losses.Huber'>, {'reduction...
24   (<class 'keras.src.losses.Huber'>, {'reduction...
36   (<class 'keras.src.losses.Huber'>, {'reduction...
41   (<class 'keras.src.losses.Huber'>, {'reduction...
12   (<class 'keras.src.losses.Huber'>, {'reduction...
77   (<class 'keras.src.losses.Huber'>, {'reduction...
28   (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
29   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
111  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                               metrics  epochs  ...  \
29   [(<class 'keras.src.metrics.regression_metrics...     200  ...
88   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16   [(<class 'keras.src.metrics.regression_metrics...     200  ...
25   [(<class 'keras.src.metrics.regression_metrics...     200  ...
23   [(<class 'keras.src.metrics.regression_metrics...     200  ...
26   [(<class 'keras.src.metrics.regression_metrics...     200  ...
30   [(<class 'keras.src.metrics.regression_metrics...     200  ...
48   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18   [(<class 'keras.src.metrics.regression_metrics...     200  ...
21   [(<class 'keras.src.metrics.regression_metrics...     200  ...
43   [(<class 'keras.src.metrics.regression_metrics...     200  ...
42   [(<class 'keras.src.metrics.regression_metrics...     200  ...
111  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24   [(<class 'keras.src.metrics.regression_metrics...     200  ...
36   [(<class 'keras.src.metrics.regression_metrics...     200  ...
41   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12   [(<class 'keras.src.metrics.regression_metrics...     200  ...
77   [(<class 'keras.src.metrics.regression_metrics...     200  ...
28   [(<class 'keras.src.metrics.regression_metrics...     200  ...

    validation_test_abserror_mean  validation_test_abserror_median  \
29                      12.635708                         9.827050
88                      12.716035                         9.905105
20                      12.586595                         9.853741
16                      12.655114                         9.871741
25                      12.655870                         9.900599
23                      12.647896                         9.898682
26                      12.658295                         9.877973
30                      12.646721                         9.893741
48                      12.759424                         9.847878
18                      12.627546                         9.912533
21                      12.610680                         9.897622
43                      12.691234                         9.862266
42                      12.587036                         9.821062
111                     12.827723                         9.865571
24                      12.661850                         9.941372
36                      12.614977                         9.880752
41                      12.808724                         9.944474
12                      12.727644                         9.897619
77                      12.742423                         9.905432
28                      12.725132                         9.983974

     validation_test_abserror_std validation_test_success  \
29                      11.081309                0.567138
88                      11.188376                0.569969
20                      10.996522                0.566646
16                      11.069855                0.566646
25                      11.064878                0.566892
23                      11.021342                0.565169
26                      11.042697                0.561846
30                      11.061687                0.561846
48                      11.587685                0.566400
18                      11.057780                0.573169
21                      10.961830                0.559877
43                      11.139631                0.568123
42                      10.946263                0.565538
111                     11.528715                0.567754
24                      11.083350                0.564554
36                      10.948780                0.565169
41                      11.394268                0.566277
12                      11.311885                0.561846
77                      11.411437                0.566646
28                      11.188626                0.566523

     validation_test_improvement  validation_avg_train_test_improvement  \
29                      0.038449                               0.037478
88                      0.030811                               0.033382
20                      0.035837                               0.033052
16                      0.034076                               0.032032
25                      0.031252                               0.031903
23                      0.031439                               0.031784
26                      0.033466                               0.031265
30                      0.031923                               0.030820
48                      0.036411                               0.030940
18                      0.030084                               0.029981
21                      0.031543                               0.029660
43                      0.035003                               0.029897
42                      0.039034                               0.030473
111                     0.034679                               0.029451
24                      0.027262                               0.028964
36                      0.033194                               0.029086
41                      0.026959                               0.028442
12                      0.031544                               0.028173
77                      0.030779                               0.028002
28                      0.023094                               0.028133

    validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                             0.037453                              0.037465
88                             0.033184                              0.033283
20                             0.032817                              0.032934
16                             0.031902                              0.031967
25                             0.031890                              0.031897
23                             0.031780                              0.031782
26                             0.031110                              0.031187
30                             0.030781                              0.030800
48                             0.029972                              0.030452
18                             0.029981                              0.029981
21                             0.029540                              0.029600
43                             0.029025                              0.029458
42                             0.028068                              0.029246
111                            0.028522                              0.028983
24                             0.028864                              0.028914
36                             0.028506                              0.028795
41                             0.028365                              0.028403
12                             0.027769                              0.027970
77                             0.027726                              0.027864
28                             0.027230                              0.027678

     num_layers iteration_number
29            1               30
88            1               89
20            1               21
16            1               17
25            1               26
23            1               24
26            1               27
30            1               31
48            1               49
18            1               19
21            1               22
43            1               44
42            1               43
111           1              112
24            1               25
36            1               37
41            1               42
12            1               13
77            1               78
28            1               29

[20 rows x 52 columns]
1 115 640
[{'nodes': 256, 'activation': 'linear', 'l2_reg': 0.1, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 1s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.021173940315420834, Original: 9.762922791515482, New: 9.556203247023872
Test: Improvement: 0.019758964633107536, Original: 10.2199936987652, New: 10.018057204720716
     learning_rate  batch_size  \
29           0.001         128
88           0.001         128
20           0.001         128
16           0.001         128
25           0.001         128
23           0.001         128
26           0.001         128
30           0.001         128
48           0.001         128
18           0.001         128
21           0.001         128
43           0.001         128
42           0.001         128
111          0.001         128
24           0.001         128
36           0.001         128
41           0.001         128
12           0.001         128
77           0.001         128
28           0.001         128

                                             optimizer  \
29   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
111  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                               optimizer_name  \
29   <class 'keras.src.optimizers.adam.Adam'>
88   <class 'keras.src.optimizers.adam.Adam'>
20   <class 'keras.src.optimizers.adam.Adam'>
16   <class 'keras.src.optimizers.adam.Adam'>
25   <class 'keras.src.optimizers.adam.Adam'>
23   <class 'keras.src.optimizers.adam.Adam'>
26   <class 'keras.src.optimizers.adam.Adam'>
30   <class 'keras.src.optimizers.adam.Adam'>
48   <class 'keras.src.optimizers.adam.Adam'>
18   <class 'keras.src.optimizers.adam.Adam'>
21   <class 'keras.src.optimizers.adam.Adam'>
43   <class 'keras.src.optimizers.adam.Adam'>
42   <class 'keras.src.optimizers.adam.Adam'>
111  <class 'keras.src.optimizers.adam.Adam'>
24   <class 'keras.src.optimizers.adam.Adam'>
36   <class 'keras.src.optimizers.adam.Adam'>
41   <class 'keras.src.optimizers.adam.Adam'>
12   <class 'keras.src.optimizers.adam.Adam'>
77   <class 'keras.src.optimizers.adam.Adam'>
28   <class 'keras.src.optimizers.adam.Adam'>

                                      optimizer_params  \
29   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
111  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                         loss_function  \
29   (<class 'keras.src.losses.Huber'>, {'reduction...
88   (<class 'keras.src.losses.Huber'>, {'reduction...
20   (<class 'keras.src.losses.Huber'>, {'reduction...
16   (<class 'keras.src.losses.Huber'>, {'reduction...
25   (<class 'keras.src.losses.Huber'>, {'reduction...
23   (<class 'keras.src.losses.Huber'>, {'reduction...
26   (<class 'keras.src.losses.Huber'>, {'reduction...
30   (<class 'keras.src.losses.Huber'>, {'reduction...
48   (<class 'keras.src.losses.Huber'>, {'reduction...
18   (<class 'keras.src.losses.Huber'>, {'reduction...
21   (<class 'keras.src.losses.Huber'>, {'reduction...
43   (<class 'keras.src.losses.Huber'>, {'reduction...
42   (<class 'keras.src.losses.Huber'>, {'reduction...
111  (<class 'keras.src.losses.Huber'>, {'reduction...
24   (<class 'keras.src.losses.Huber'>, {'reduction...
36   (<class 'keras.src.losses.Huber'>, {'reduction...
41   (<class 'keras.src.losses.Huber'>, {'reduction...
12   (<class 'keras.src.losses.Huber'>, {'reduction...
77   (<class 'keras.src.losses.Huber'>, {'reduction...
28   (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
29   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
111  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                               metrics  epochs  ...  \
29   [(<class 'keras.src.metrics.regression_metrics...     200  ...
88   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16   [(<class 'keras.src.metrics.regression_metrics...     200  ...
25   [(<class 'keras.src.metrics.regression_metrics...     200  ...
23   [(<class 'keras.src.metrics.regression_metrics...     200  ...
26   [(<class 'keras.src.metrics.regression_metrics...     200  ...
30   [(<class 'keras.src.metrics.regression_metrics...     200  ...
48   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18   [(<class 'keras.src.metrics.regression_metrics...     200  ...
21   [(<class 'keras.src.metrics.regression_metrics...     200  ...
43   [(<class 'keras.src.metrics.regression_metrics...     200  ...
42   [(<class 'keras.src.metrics.regression_metrics...     200  ...
111  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24   [(<class 'keras.src.metrics.regression_metrics...     200  ...
36   [(<class 'keras.src.metrics.regression_metrics...     200  ...
41   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12   [(<class 'keras.src.metrics.regression_metrics...     200  ...
77   [(<class 'keras.src.metrics.regression_metrics...     200  ...
28   [(<class 'keras.src.metrics.regression_metrics...     200  ...

    validation_test_abserror_mean  validation_test_abserror_median  \
29                      12.635708                         9.827050
88                      12.716035                         9.905105
20                      12.586595                         9.853741
16                      12.655114                         9.871741
25                      12.655870                         9.900599
23                      12.647896                         9.898682
26                      12.658295                         9.877973
30                      12.646721                         9.893741
48                      12.759424                         9.847878
18                      12.627546                         9.912533
21                      12.610680                         9.897622
43                      12.691234                         9.862266
42                      12.587036                         9.821062
111                     12.827723                         9.865571
24                      12.661850                         9.941372
36                      12.614977                         9.880752
41                      12.808724                         9.944474
12                      12.727644                         9.897619
77                      12.742423                         9.905432
28                      12.725132                         9.983974

     validation_test_abserror_std validation_test_success  \
29                      11.081309                0.567138
88                      11.188376                0.569969
20                      10.996522                0.566646
16                      11.069855                0.566646
25                      11.064878                0.566892
23                      11.021342                0.565169
26                      11.042697                0.561846
30                      11.061687                0.561846
48                      11.587685                0.566400
18                      11.057780                0.573169
21                      10.961830                0.559877
43                      11.139631                0.568123
42                      10.946263                0.565538
111                     11.528715                0.567754
24                      11.083350                0.564554
36                      10.948780                0.565169
41                      11.394268                0.566277
12                      11.311885                0.561846
77                      11.411437                0.566646
28                      11.188626                0.566523

     validation_test_improvement  validation_avg_train_test_improvement  \
29                      0.038449                               0.037478
88                      0.030811                               0.033382
20                      0.035837                               0.033052
16                      0.034076                               0.032032
25                      0.031252                               0.031903
23                      0.031439                               0.031784
26                      0.033466                               0.031265
30                      0.031923                               0.030820
48                      0.036411                               0.030940
18                      0.030084                               0.029981
21                      0.031543                               0.029660
43                      0.035003                               0.029897
42                      0.039034                               0.030473
111                     0.034679                               0.029451
24                      0.027262                               0.028964
36                      0.033194                               0.029086
41                      0.026959                               0.028442
12                      0.031544                               0.028173
77                      0.030779                               0.028002
28                      0.023094                               0.028133

    validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                             0.037453                              0.037465
88                             0.033184                              0.033283
20                             0.032817                              0.032934
16                             0.031902                              0.031967
25                             0.031890                              0.031897
23                             0.031780                              0.031782
26                             0.031110                              0.031187
30                             0.030781                              0.030800
48                             0.029972                              0.030452
18                             0.029981                              0.029981
21                             0.029540                              0.029600
43                             0.029025                              0.029458
42                             0.028068                              0.029246
111                            0.028522                              0.028983
24                             0.028864                              0.028914
36                             0.028506                              0.028795
41                             0.028365                              0.028403
12                             0.027769                              0.027970
77                             0.027726                              0.027864
28                             0.027230                              0.027678

     num_layers iteration_number
29            1               30
88            1               89
20            1               21
16            1               17
25            1               26
23            1               24
26            1               27
30            1               31
48            1               49
18            1               19
21            1               22
43            1               44
42            1               43
111           1              112
24            1               25
36            1               37
41            1               42
12            1               13
77            1               78
28            1               29

[20 rows x 52 columns]
1 116 640
[{'nodes': 256, 'activation': 'linear', 'l2_reg': 0.1, 'l1_reg': 0.0001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.014154460534140496, Original: 9.762922791515482, New: 9.624733886165115
Test: Improvement: 0.02053592938607458, Original: 10.2199936987652, New: 10.01011662984123
     learning_rate  batch_size  \
29           0.001         128
88           0.001         128
20           0.001         128
16           0.001         128
25           0.001         128
23           0.001         128
26           0.001         128
30           0.001         128
48           0.001         128
18           0.001         128
21           0.001         128
43           0.001         128
42           0.001         128
111          0.001         128
24           0.001         128
36           0.001         128
41           0.001         128
12           0.001         128
77           0.001         128
28           0.001         128

                                             optimizer  \
29   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
111  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                               optimizer_name  \
29   <class 'keras.src.optimizers.adam.Adam'>
88   <class 'keras.src.optimizers.adam.Adam'>
20   <class 'keras.src.optimizers.adam.Adam'>
16   <class 'keras.src.optimizers.adam.Adam'>
25   <class 'keras.src.optimizers.adam.Adam'>
23   <class 'keras.src.optimizers.adam.Adam'>
26   <class 'keras.src.optimizers.adam.Adam'>
30   <class 'keras.src.optimizers.adam.Adam'>
48   <class 'keras.src.optimizers.adam.Adam'>
18   <class 'keras.src.optimizers.adam.Adam'>
21   <class 'keras.src.optimizers.adam.Adam'>
43   <class 'keras.src.optimizers.adam.Adam'>
42   <class 'keras.src.optimizers.adam.Adam'>
111  <class 'keras.src.optimizers.adam.Adam'>
24   <class 'keras.src.optimizers.adam.Adam'>
36   <class 'keras.src.optimizers.adam.Adam'>
41   <class 'keras.src.optimizers.adam.Adam'>
12   <class 'keras.src.optimizers.adam.Adam'>
77   <class 'keras.src.optimizers.adam.Adam'>
28   <class 'keras.src.optimizers.adam.Adam'>

                                      optimizer_params  \
29   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
111  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                         loss_function  \
29   (<class 'keras.src.losses.Huber'>, {'reduction...
88   (<class 'keras.src.losses.Huber'>, {'reduction...
20   (<class 'keras.src.losses.Huber'>, {'reduction...
16   (<class 'keras.src.losses.Huber'>, {'reduction...
25   (<class 'keras.src.losses.Huber'>, {'reduction...
23   (<class 'keras.src.losses.Huber'>, {'reduction...
26   (<class 'keras.src.losses.Huber'>, {'reduction...
30   (<class 'keras.src.losses.Huber'>, {'reduction...
48   (<class 'keras.src.losses.Huber'>, {'reduction...
18   (<class 'keras.src.losses.Huber'>, {'reduction...
21   (<class 'keras.src.losses.Huber'>, {'reduction...
43   (<class 'keras.src.losses.Huber'>, {'reduction...
42   (<class 'keras.src.losses.Huber'>, {'reduction...
111  (<class 'keras.src.losses.Huber'>, {'reduction...
24   (<class 'keras.src.losses.Huber'>, {'reduction...
36   (<class 'keras.src.losses.Huber'>, {'reduction...
41   (<class 'keras.src.losses.Huber'>, {'reduction...
12   (<class 'keras.src.losses.Huber'>, {'reduction...
77   (<class 'keras.src.losses.Huber'>, {'reduction...
28   (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
29   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
111  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                               metrics  epochs  ...  \
29   [(<class 'keras.src.metrics.regression_metrics...     200  ...
88   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16   [(<class 'keras.src.metrics.regression_metrics...     200  ...
25   [(<class 'keras.src.metrics.regression_metrics...     200  ...
23   [(<class 'keras.src.metrics.regression_metrics...     200  ...
26   [(<class 'keras.src.metrics.regression_metrics...     200  ...
30   [(<class 'keras.src.metrics.regression_metrics...     200  ...
48   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18   [(<class 'keras.src.metrics.regression_metrics...     200  ...
21   [(<class 'keras.src.metrics.regression_metrics...     200  ...
43   [(<class 'keras.src.metrics.regression_metrics...     200  ...
42   [(<class 'keras.src.metrics.regression_metrics...     200  ...
111  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24   [(<class 'keras.src.metrics.regression_metrics...     200  ...
36   [(<class 'keras.src.metrics.regression_metrics...     200  ...
41   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12   [(<class 'keras.src.metrics.regression_metrics...     200  ...
77   [(<class 'keras.src.metrics.regression_metrics...     200  ...
28   [(<class 'keras.src.metrics.regression_metrics...     200  ...

    validation_test_abserror_mean  validation_test_abserror_median  \
29                      12.635708                         9.827050
88                      12.716035                         9.905105
20                      12.586595                         9.853741
16                      12.655114                         9.871741
25                      12.655870                         9.900599
23                      12.647896                         9.898682
26                      12.658295                         9.877973
30                      12.646721                         9.893741
48                      12.759424                         9.847878
18                      12.627546                         9.912533
21                      12.610680                         9.897622
43                      12.691234                         9.862266
42                      12.587036                         9.821062
111                     12.827723                         9.865571
24                      12.661850                         9.941372
36                      12.614977                         9.880752
41                      12.808724                         9.944474
12                      12.727644                         9.897619
77                      12.742423                         9.905432
28                      12.725132                         9.983974

     validation_test_abserror_std validation_test_success  \
29                      11.081309                0.567138
88                      11.188376                0.569969
20                      10.996522                0.566646
16                      11.069855                0.566646
25                      11.064878                0.566892
23                      11.021342                0.565169
26                      11.042697                0.561846
30                      11.061687                0.561846
48                      11.587685                0.566400
18                      11.057780                0.573169
21                      10.961830                0.559877
43                      11.139631                0.568123
42                      10.946263                0.565538
111                     11.528715                0.567754
24                      11.083350                0.564554
36                      10.948780                0.565169
41                      11.394268                0.566277
12                      11.311885                0.561846
77                      11.411437                0.566646
28                      11.188626                0.566523

     validation_test_improvement  validation_avg_train_test_improvement  \
29                      0.038449                               0.037478
88                      0.030811                               0.033382
20                      0.035837                               0.033052
16                      0.034076                               0.032032
25                      0.031252                               0.031903
23                      0.031439                               0.031784
26                      0.033466                               0.031265
30                      0.031923                               0.030820
48                      0.036411                               0.030940
18                      0.030084                               0.029981
21                      0.031543                               0.029660
43                      0.035003                               0.029897
42                      0.039034                               0.030473
111                     0.034679                               0.029451
24                      0.027262                               0.028964
36                      0.033194                               0.029086
41                      0.026959                               0.028442
12                      0.031544                               0.028173
77                      0.030779                               0.028002
28                      0.023094                               0.028133

    validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                             0.037453                              0.037465
88                             0.033184                              0.033283
20                             0.032817                              0.032934
16                             0.031902                              0.031967
25                             0.031890                              0.031897
23                             0.031780                              0.031782
26                             0.031110                              0.031187
30                             0.030781                              0.030800
48                             0.029972                              0.030452
18                             0.029981                              0.029981
21                             0.029540                              0.029600
43                             0.029025                              0.029458
42                             0.028068                              0.029246
111                            0.028522                              0.028983
24                             0.028864                              0.028914
36                             0.028506                              0.028795
41                             0.028365                              0.028403
12                             0.027769                              0.027970
77                             0.027726                              0.027864
28                             0.027230                              0.027678

     num_layers iteration_number
29            1               30
88            1               89
20            1               21
16            1               17
25            1               26
23            1               24
26            1               27
30            1               31
48            1               49
18            1               19
21            1               22
43            1               44
42            1               43
111           1              112
24            1               25
36            1               37
41            1               42
12            1               13
77            1               78
28            1               29

[20 rows x 52 columns]
1 117 640
[{'nodes': 256, 'activation': 'linear', 'l2_reg': 0.01, 'l1_reg': 0.1}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 2ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 3s 2ms/step
Training: Improvement: 0.013880546332780056, Original: 9.762922791515482, New: 9.627408089364497
Test: Improvement: 0.024889378005863837, Original: 10.2199936987652, New: 9.965624412379086
     learning_rate  batch_size  \
29           0.001         128
88           0.001         128
20           0.001         128
16           0.001         128
25           0.001         128
23           0.001         128
26           0.001         128
30           0.001         128
48           0.001         128
18           0.001         128
21           0.001         128
43           0.001         128
42           0.001         128
111          0.001         128
24           0.001         128
36           0.001         128
41           0.001         128
12           0.001         128
77           0.001         128
28           0.001         128

                                             optimizer  \
29   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
111  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                               optimizer_name  \
29   <class 'keras.src.optimizers.adam.Adam'>
88   <class 'keras.src.optimizers.adam.Adam'>
20   <class 'keras.src.optimizers.adam.Adam'>
16   <class 'keras.src.optimizers.adam.Adam'>
25   <class 'keras.src.optimizers.adam.Adam'>
23   <class 'keras.src.optimizers.adam.Adam'>
26   <class 'keras.src.optimizers.adam.Adam'>
30   <class 'keras.src.optimizers.adam.Adam'>
48   <class 'keras.src.optimizers.adam.Adam'>
18   <class 'keras.src.optimizers.adam.Adam'>
21   <class 'keras.src.optimizers.adam.Adam'>
43   <class 'keras.src.optimizers.adam.Adam'>
42   <class 'keras.src.optimizers.adam.Adam'>
111  <class 'keras.src.optimizers.adam.Adam'>
24   <class 'keras.src.optimizers.adam.Adam'>
36   <class 'keras.src.optimizers.adam.Adam'>
41   <class 'keras.src.optimizers.adam.Adam'>
12   <class 'keras.src.optimizers.adam.Adam'>
77   <class 'keras.src.optimizers.adam.Adam'>
28   <class 'keras.src.optimizers.adam.Adam'>

                                      optimizer_params  \
29   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
111  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                         loss_function  \
29   (<class 'keras.src.losses.Huber'>, {'reduction...
88   (<class 'keras.src.losses.Huber'>, {'reduction...
20   (<class 'keras.src.losses.Huber'>, {'reduction...
16   (<class 'keras.src.losses.Huber'>, {'reduction...
25   (<class 'keras.src.losses.Huber'>, {'reduction...
23   (<class 'keras.src.losses.Huber'>, {'reduction...
26   (<class 'keras.src.losses.Huber'>, {'reduction...
30   (<class 'keras.src.losses.Huber'>, {'reduction...
48   (<class 'keras.src.losses.Huber'>, {'reduction...
18   (<class 'keras.src.losses.Huber'>, {'reduction...
21   (<class 'keras.src.losses.Huber'>, {'reduction...
43   (<class 'keras.src.losses.Huber'>, {'reduction...
42   (<class 'keras.src.losses.Huber'>, {'reduction...
111  (<class 'keras.src.losses.Huber'>, {'reduction...
24   (<class 'keras.src.losses.Huber'>, {'reduction...
36   (<class 'keras.src.losses.Huber'>, {'reduction...
41   (<class 'keras.src.losses.Huber'>, {'reduction...
12   (<class 'keras.src.losses.Huber'>, {'reduction...
77   (<class 'keras.src.losses.Huber'>, {'reduction...
28   (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
29   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
111  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                               metrics  epochs  ...  \
29   [(<class 'keras.src.metrics.regression_metrics...     200  ...
88   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16   [(<class 'keras.src.metrics.regression_metrics...     200  ...
25   [(<class 'keras.src.metrics.regression_metrics...     200  ...
23   [(<class 'keras.src.metrics.regression_metrics...     200  ...
26   [(<class 'keras.src.metrics.regression_metrics...     200  ...
30   [(<class 'keras.src.metrics.regression_metrics...     200  ...
48   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18   [(<class 'keras.src.metrics.regression_metrics...     200  ...
21   [(<class 'keras.src.metrics.regression_metrics...     200  ...
43   [(<class 'keras.src.metrics.regression_metrics...     200  ...
42   [(<class 'keras.src.metrics.regression_metrics...     200  ...
111  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24   [(<class 'keras.src.metrics.regression_metrics...     200  ...
36   [(<class 'keras.src.metrics.regression_metrics...     200  ...
41   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12   [(<class 'keras.src.metrics.regression_metrics...     200  ...
77   [(<class 'keras.src.metrics.regression_metrics...     200  ...
28   [(<class 'keras.src.metrics.regression_metrics...     200  ...

    validation_test_abserror_mean  validation_test_abserror_median  \
29                      12.635708                         9.827050
88                      12.716035                         9.905105
20                      12.586595                         9.853741
16                      12.655114                         9.871741
25                      12.655870                         9.900599
23                      12.647896                         9.898682
26                      12.658295                         9.877973
30                      12.646721                         9.893741
48                      12.759424                         9.847878
18                      12.627546                         9.912533
21                      12.610680                         9.897622
43                      12.691234                         9.862266
42                      12.587036                         9.821062
111                     12.827723                         9.865571
24                      12.661850                         9.941372
36                      12.614977                         9.880752
41                      12.808724                         9.944474
12                      12.727644                         9.897619
77                      12.742423                         9.905432
28                      12.725132                         9.983974

     validation_test_abserror_std validation_test_success  \
29                      11.081309                0.567138
88                      11.188376                0.569969
20                      10.996522                0.566646
16                      11.069855                0.566646
25                      11.064878                0.566892
23                      11.021342                0.565169
26                      11.042697                0.561846
30                      11.061687                0.561846
48                      11.587685                0.566400
18                      11.057780                0.573169
21                      10.961830                0.559877
43                      11.139631                0.568123
42                      10.946263                0.565538
111                     11.528715                0.567754
24                      11.083350                0.564554
36                      10.948780                0.565169
41                      11.394268                0.566277
12                      11.311885                0.561846
77                      11.411437                0.566646
28                      11.188626                0.566523

     validation_test_improvement  validation_avg_train_test_improvement  \
29                      0.038449                               0.037478
88                      0.030811                               0.033382
20                      0.035837                               0.033052
16                      0.034076                               0.032032
25                      0.031252                               0.031903
23                      0.031439                               0.031784
26                      0.033466                               0.031265
30                      0.031923                               0.030820
48                      0.036411                               0.030940
18                      0.030084                               0.029981
21                      0.031543                               0.029660
43                      0.035003                               0.029897
42                      0.039034                               0.030473
111                     0.034679                               0.029451
24                      0.027262                               0.028964
36                      0.033194                               0.029086
41                      0.026959                               0.028442
12                      0.031544                               0.028173
77                      0.030779                               0.028002
28                      0.023094                               0.028133

    validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                             0.037453                              0.037465
88                             0.033184                              0.033283
20                             0.032817                              0.032934
16                             0.031902                              0.031967
25                             0.031890                              0.031897
23                             0.031780                              0.031782
26                             0.031110                              0.031187
30                             0.030781                              0.030800
48                             0.029972                              0.030452
18                             0.029981                              0.029981
21                             0.029540                              0.029600
43                             0.029025                              0.029458
42                             0.028068                              0.029246
111                            0.028522                              0.028983
24                             0.028864                              0.028914
36                             0.028506                              0.028795
41                             0.028365                              0.028403
12                             0.027769                              0.027970
77                             0.027726                              0.027864
28                             0.027230                              0.027678

     num_layers iteration_number
29            1               30
88            1               89
20            1               21
16            1               17
25            1               26
23            1               24
26            1               27
30            1               31
48            1               49
18            1               19
21            1               22
43            1               44
42            1               43
111           1              112
24            1               25
36            1               37
41            1               42
12            1               13
77            1               78
28            1               29

[20 rows x 52 columns]
1 118 640
[{'nodes': 256, 'activation': 'linear', 'l2_reg': 0.01, 'l1_reg': 0.01}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step
Training: Improvement: 0.012254366092659938, Original: 9.762922791515482, New: 9.643284361493878
Test: Improvement: 0.022653990627945795, Original: 10.2199936987652, New: 9.988470057295707
     learning_rate  batch_size  \
29           0.001         128
88           0.001         128
20           0.001         128
16           0.001         128
25           0.001         128
23           0.001         128
26           0.001         128
30           0.001         128
48           0.001         128
18           0.001         128
21           0.001         128
43           0.001         128
42           0.001         128
111          0.001         128
24           0.001         128
36           0.001         128
41           0.001         128
12           0.001         128
77           0.001         128
28           0.001         128

                                             optimizer  \
29   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
88   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
20   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
16   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
25   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
23   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
26   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
30   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
48   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
18   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
21   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
43   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
42   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
111  (<class 'keras.src.optimizers.adam.Adam'>, {'b...
24   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
36   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
41   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
12   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
77   (<class 'keras.src.optimizers.adam.Adam'>, {'b...
28   (<class 'keras.src.optimizers.adam.Adam'>, {'b...

                               optimizer_name  \
29   <class 'keras.src.optimizers.adam.Adam'>
88   <class 'keras.src.optimizers.adam.Adam'>
20   <class 'keras.src.optimizers.adam.Adam'>
16   <class 'keras.src.optimizers.adam.Adam'>
25   <class 'keras.src.optimizers.adam.Adam'>
23   <class 'keras.src.optimizers.adam.Adam'>
26   <class 'keras.src.optimizers.adam.Adam'>
30   <class 'keras.src.optimizers.adam.Adam'>
48   <class 'keras.src.optimizers.adam.Adam'>
18   <class 'keras.src.optimizers.adam.Adam'>
21   <class 'keras.src.optimizers.adam.Adam'>
43   <class 'keras.src.optimizers.adam.Adam'>
42   <class 'keras.src.optimizers.adam.Adam'>
111  <class 'keras.src.optimizers.adam.Adam'>
24   <class 'keras.src.optimizers.adam.Adam'>
36   <class 'keras.src.optimizers.adam.Adam'>
41   <class 'keras.src.optimizers.adam.Adam'>
12   <class 'keras.src.optimizers.adam.Adam'>
77   <class 'keras.src.optimizers.adam.Adam'>
28   <class 'keras.src.optimizers.adam.Adam'>

                                      optimizer_params  \
29   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
88   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
20   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
16   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
25   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
23   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
26   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
30   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
48   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
18   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
21   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
43   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
42   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
111  {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
24   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
36   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
41   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
12   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
77   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...
28   {'beta_1': 0.99, 'beta_2': 0.9995, 'epsilon': ...

                                         loss_function  \
29   (<class 'keras.src.losses.Huber'>, {'reduction...
88   (<class 'keras.src.losses.Huber'>, {'reduction...
20   (<class 'keras.src.losses.Huber'>, {'reduction...
16   (<class 'keras.src.losses.Huber'>, {'reduction...
25   (<class 'keras.src.losses.Huber'>, {'reduction...
23   (<class 'keras.src.losses.Huber'>, {'reduction...
26   (<class 'keras.src.losses.Huber'>, {'reduction...
30   (<class 'keras.src.losses.Huber'>, {'reduction...
48   (<class 'keras.src.losses.Huber'>, {'reduction...
18   (<class 'keras.src.losses.Huber'>, {'reduction...
21   (<class 'keras.src.losses.Huber'>, {'reduction...
43   (<class 'keras.src.losses.Huber'>, {'reduction...
42   (<class 'keras.src.losses.Huber'>, {'reduction...
111  (<class 'keras.src.losses.Huber'>, {'reduction...
24   (<class 'keras.src.losses.Huber'>, {'reduction...
36   (<class 'keras.src.losses.Huber'>, {'reduction...
41   (<class 'keras.src.losses.Huber'>, {'reduction...
12   (<class 'keras.src.losses.Huber'>, {'reduction...
77   (<class 'keras.src.losses.Huber'>, {'reduction...
28   (<class 'keras.src.losses.Huber'>, {'reduction...

                  loss_function_class   loss_function_params  \
29   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
88   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
20   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
16   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
25   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
23   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
26   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
30   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
48   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
18   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
21   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
43   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
42   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
111  <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
24   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
36   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
41   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
12   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
77   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}
28   <class 'keras.src.losses.Huber'>  {'reduction': 'auto'}

                                               metrics  epochs  ...  \
29   [(<class 'keras.src.metrics.regression_metrics...     200  ...
88   [(<class 'keras.src.metrics.regression_metrics...     200  ...
20   [(<class 'keras.src.metrics.regression_metrics...     200  ...
16   [(<class 'keras.src.metrics.regression_metrics...     200  ...
25   [(<class 'keras.src.metrics.regression_metrics...     200  ...
23   [(<class 'keras.src.metrics.regression_metrics...     200  ...
26   [(<class 'keras.src.metrics.regression_metrics...     200  ...
30   [(<class 'keras.src.metrics.regression_metrics...     200  ...
48   [(<class 'keras.src.metrics.regression_metrics...     200  ...
18   [(<class 'keras.src.metrics.regression_metrics...     200  ...
21   [(<class 'keras.src.metrics.regression_metrics...     200  ...
43   [(<class 'keras.src.metrics.regression_metrics...     200  ...
42   [(<class 'keras.src.metrics.regression_metrics...     200  ...
111  [(<class 'keras.src.metrics.regression_metrics...     200  ...
24   [(<class 'keras.src.metrics.regression_metrics...     200  ...
36   [(<class 'keras.src.metrics.regression_metrics...     200  ...
41   [(<class 'keras.src.metrics.regression_metrics...     200  ...
12   [(<class 'keras.src.metrics.regression_metrics...     200  ...
77   [(<class 'keras.src.metrics.regression_metrics...     200  ...
28   [(<class 'keras.src.metrics.regression_metrics...     200  ...

    validation_test_abserror_mean  validation_test_abserror_median  \
29                      12.635708                         9.827050
88                      12.716035                         9.905105
20                      12.586595                         9.853741
16                      12.655114                         9.871741
25                      12.655870                         9.900599
23                      12.647896                         9.898682
26                      12.658295                         9.877973
30                      12.646721                         9.893741
48                      12.759424                         9.847878
18                      12.627546                         9.912533
21                      12.610680                         9.897622
43                      12.691234                         9.862266
42                      12.587036                         9.821062
111                     12.827723                         9.865571
24                      12.661850                         9.941372
36                      12.614977                         9.880752
41                      12.808724                         9.944474
12                      12.727644                         9.897619
77                      12.742423                         9.905432
28                      12.725132                         9.983974

     validation_test_abserror_std validation_test_success  \
29                      11.081309                0.567138
88                      11.188376                0.569969
20                      10.996522                0.566646
16                      11.069855                0.566646
25                      11.064878                0.566892
23                      11.021342                0.565169
26                      11.042697                0.561846
30                      11.061687                0.561846
48                      11.587685                0.566400
18                      11.057780                0.573169
21                      10.961830                0.559877
43                      11.139631                0.568123
42                      10.946263                0.565538
111                     11.528715                0.567754
24                      11.083350                0.564554
36                      10.948780                0.565169
41                      11.394268                0.566277
12                      11.311885                0.561846
77                      11.411437                0.566646
28                      11.188626                0.566523

     validation_test_improvement  validation_avg_train_test_improvement  \
29                      0.038449                               0.037478
88                      0.030811                               0.033382
20                      0.035837                               0.033052
16                      0.034076                               0.032032
25                      0.031252                               0.031903
23                      0.031439                               0.031784
26                      0.033466                               0.031265
30                      0.031923                               0.030820
48                      0.036411                               0.030940
18                      0.030084                               0.029981
21                      0.031543                               0.029660
43                      0.035003                               0.029897
42                      0.039034                               0.030473
111                     0.034679                               0.029451
24                      0.027262                               0.028964
36                      0.033194                               0.029086
41                      0.026959                               0.028442
12                      0.031544                               0.028173
77                      0.030779                               0.028002
28                      0.023094                               0.028133

    validation_train_test_harmonic_mean  validation_train_test_geometric_mean  \
29                             0.037453                              0.037465
88                             0.033184                              0.033283
20                             0.032817                              0.032934
16                             0.031902                              0.031967
25                             0.031890                              0.031897
23                             0.031780                              0.031782
26                             0.031110                              0.031187
30                             0.030781                              0.030800
48                             0.029972                              0.030452
18                             0.029981                              0.029981
21                             0.029540                              0.029600
43                             0.029025                              0.029458
42                             0.028068                              0.029246
111                            0.028522                              0.028983
24                             0.028864                              0.028914
36                             0.028506                              0.028795
41                             0.028365                              0.028403
12                             0.027769                              0.027970
77                             0.027726                              0.027864
28                             0.027230                              0.027678

     num_layers iteration_number
29            1               30
88            1               89
20            1               21
16            1               17
25            1               26
23            1               24
26            1               27
30            1               31
48            1               49
18            1               19
21            1               22
43            1               44
42            1               43
111           1              112
24            1               25
36            1               37
41            1               42
12            1               13
77            1               78
28            1               29

[20 rows x 52 columns]
1 119 640
[{'nodes': 256, 'activation': 'linear', 'l2_reg': 0.01, 'l1_reg': 0.001}]

X_pca shape: (28310, 15)
Outlier detection enabled. Outliers detected: 1416
Outlier detection enabled.
Total samples: 28310
Total outliers detected: 1416 (5.00%)
Training fold 1...
177/177 [==============================] - 0s 1ms/step

X has feature names, but PCA was fitted without feature names

1643/1643 [==============================] - 2s 1ms/step

KeyboardInterrupt:

In [ ]:
# 0.5760644418872267

In [ ]:
for best_num in [25, 10, 5]:
#     for best_num in [5]:


    # Get top 10
    top_models = top_models.iloc[0:best_num]

    results_dicts = []
    loop_num = 0

    for row in top_models.index:

        loop_num += 1
        print(loop_num, len(top_models))

        model_to_try = top_models.loc[row].to_dict()
#             model_to_try = replace_df_objects_with_functions(str(model_to_try))

        # If we have loaded the data from a csv then these dictionaries, tuples are stored as strings, convert back
        for key in ['optimizer', 'loss_function', 'activation_layers', 'outlier_dict', 'lr_schedule_strategy']:
            if key in model_to_try.keys():
                value = model_to_try[key]
                if isinstance(value, str):
                    model_to_try[key] = replace_df_objects_with_functions(str(model_to_try[key]))
                    model_to_try[key] = eval(model_to_try[key])

        results_dict, feature_importances_df, fold_metrics = run_experiment(model_type, model_to_try['pca'], model_to_try['pca_threshold'], X, y, model_to_try['learning_rate'], model_to_try['batch_size'], model_to_try['optimizer'], model_to_try['loss_function'], metrics, epochs[0], model_to_try['activation_layers'], n_splits, model_to_try['class_weights_enabled'], outlier_dict = model_to_try['outlier_dict'], stratification_enabled = model_to_try['stratification_enabled'], lr_schedule_enabled = model_to_try['lr_schedule_enabled'], lr_schedule_strategy = model_to_try['lr_schedule_strategy'], dropout_enabled = model_to_try['dropout_enabled'], dropout_rate = model_to_try['dropout_rate'], early_stopping_metric = model_to_try['early_stopping_metric'], validation_dict = validation_dict)
        results_dict['num_layers'] = model_layer
        results_dict['iteration_number'] = -1
        results_dicts.append(results_dict)


    # Reset what the top models are
    top_models = pd.DataFrame(results_dicts).sort_values(model_ass_val, ascending = model_ass_val_direction)

    # Add these top models to our global dataframe
    all_model_iterations = pd.concat([all_model_iterations, top_models], ignore_index = True)

    print("'''''''''''' Best Models ''''''''''''")
    print("''''''''''''",best_num)
    print(top_models)
    print('')

In [ ]:
# Specific training dataset results
# 0.6974981046247157 10.054136269215872 7.811145401631084
# Mean + STD of training -0.5548133024165735 13.141383103587481
# Home Accuracy 0.7444196428571429 10.215136869913763 7.989008184384796
# Away Accuracy 0.5981087470449172 9.713104263955088 7.67490416493068


# Train Results
# 0.6974981046247157 10.054136269215872 7.811145401631084
# Home Accuracy 0.7444196428571429
# Away Accuracy 0.5981087470449172
# Test Results
# 0.6832579185520362 11.688933087487388 9.0062714356169
# Home Accuracy 0.7142857142857143
# Away Accuracy 0.6170212765957447

In [ ]:
all_model_iterations = pd.concat([all_model_iterations, activation_layers_df], ignore_index = True)

In [ ]:
# Specify folder and file name
folder_name = "model_results/"
results_dicts = []
model_number = 0
n_splits = 3


# !!!!!!!!!!! Change
### See if we have any other models tried
top_models = all_model_iterations.sort_values(model_ass_val, ascending = model_ass_val_direction)[:15]


# Iterate through all files in the folder
for filename in os.listdir(folder_name):
    # Check if the file starts with the desired prefix and is a .pkl file
    if filename.startswith('model_' + model_name +'_test') and filename.endswith(".pkl"):
        file_path = os.path.join(folder_name, filename)
        # Load the .pkl file
        with open(file_path, 'rb') as f:
            data = pickle.load(f)
            if isinstance(data, dict):  # Ensure it's a dictionary
                results_dicts.append(data)
            else:
                print(f"File {filename} does not contain a dictionary.")

if len(results_dicts)>0:
    temp_df = pd.DataFrame(results_dicts)
    model_number = temp_df['model_number'].max()
    

# Now take the top 10 and iterate 10 times to see if we can produce any better models (starting weights are random so we might get something better)


for i in range(0, 10):
    
    print('Iteration: ', i, 10)

    for row in top_models.index:

        model_number += 1
        print(model_number, len(top_models))

        model_to_try = top_models.loc[row].to_dict()

        # If we have loaded the data from a csv then these dictionaries, tuples are stored as strings, convert back
        for key in ['optimizer', 'loss_function', 'activation_layers', 'outlier_dict', 'lr_schedule_strategy']:
            if key in model_to_try.keys():
                value = model_to_try[key]
                if isinstance(value, str):
                    model_to_try[key] = replace_df_objects_with_functions(str(model_to_try[key]))
                    model_to_try[key] = eval(model_to_try[key])

        results_dict, feature_importances_df, fold_metrics = run_experiment(model_type, model_to_try['pca'], model_to_try['pca_threshold'], X, y, model_to_try['learning_rate'], model_to_try['batch_size'], model_to_try['optimizer'], model_to_try['loss_function'], metrics, epochs[0], model_to_try['activation_layers'], n_splits, model_to_try['class_weights_enabled'], outlier_dict = model_to_try['outlier_dict'], stratification_enabled = model_to_try['stratification_enabled'], lr_schedule_enabled = model_to_try['lr_schedule_enabled'], lr_schedule_strategy = model_to_try['lr_schedule_strategy'], dropout_enabled = model_to_try['dropout_enabled'], dropout_rate = model_to_try['dropout_rate'], early_stopping_metric = model_to_try['early_stopping_metric'], validation_dict = validation_dict)
        results_dict['num_layers'] = model_layer
        results_dict['iteration_number'] = -1
        results_dict['model_number'] = model_number
        
        results_dicts.append(results_dict)
        
        temp_df = pd.DataFrame(results_dicts).sort_values(model_ass_val, ascending = model_ass_val_direction)
        print(temp_df[:20])


        # Full path to the file
        temp_model_name = model_name+'_test'+str(model_number)
        save_model_and_attributes(folder_name, temp_model_name, results_dict)

    
# Reset what the top models are
top_models = pd.DataFrame(results_dicts).sort_values(model_ass_val, ascending = model_ass_val_direction)

In [ ]:
top_models = pd.DataFrame(results_dicts).sort_values(model_ass_val, ascending = model_ass_val_direction)

In [ ]:
top_models[:10]

In [ ]:
top_models[:10]

In [ ]:
# Pick the best model we want to use
top_model = pd.DataFrame(top_models).iloc[0].to_dict()
save_model_and_attributes('', model_name, top_model)